// @vitest-environment node
/**
 * Pravāha B6.0 / Codex round 8 R8-10 — protected-window REHEARSAL harness: 26-class VOLUME, SEAL TIMING and CONTENTION on a
 * disposable database. It is a MEASUREMENT harness (opt-in: GOCHARA_REHEARSAL=1), not a CI gate: it invents no pass/fail
 * bound — it records timings so the steward can decide what is acceptable.
 *
 * Helpers are the 1232 suite's (generated by copying its helper section: the deployment-faithful role mirror — objects owned by
 * `amjis_app`, PUBLIC EXECUTE revoked, builder + separately granted sealer — then the window list gains 1233 and the Moon-specific
 * fixtures are dropped). Scale knobs (env): REHEARSAL_PINS (included pins per class, default 4), REHEARSAL_OB_PER_PIN (default 30),
 * REHEARSAL_INTERVALS_PER_OB (default 3), REHEARSAL_OUT (a JSON file for the result table).
 *
 * Classes: the registry's 27 minus `birth_anchor` (its epoch tautology — the 26-class search; CONFIRM with Stream A).
 * Measured phases: construct (builder INSERTs), finalise (digest functions + UPDATE), independent verification rows (builder
 * today — see the rehearsal plan: the builder holds INSERT on the verification table), partition rows, SEAL (as the sealer), the
 * completeness check alone, and CONTENTION: a builder transaction on a second generation while the sealer is sealing the first.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { Pool, type PoolClient } from 'pg'
import { createHash } from 'node:crypto'
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import path from 'node:path'
import { TRACKER_DDL, TRACKER_IDENTITY_DDL, runMigrations } from '../../scripts/migrate'
import { resolveDisposableA51Config } from './gochara_a5_1_disposable_url'

const TEST_DB_URL = process.env.GOCHARA_A51_TEST_DATABASE_URL
const REQUIRE_DB = process.env.GOCHARA_REQUIRE_DB === '1'
const RUN_REHEARSAL = process.env.GOCHARA_REHEARSAL === '1'      // opt-in: this harness is a measurement, not a CI gate

const MIGRATIONS_DIR = path.resolve(process.cwd(), 'migrations')
const PARENT_FILES = [
  '1081_nirmana_l3_gochara_ledger_coverage_publication.sql',
  '1087_nirmana_l3_gochara_contacts_inclusivity_completeness_tier_basis.sql',
  '1152_kala_gochara_contacts_t_exact_nullable_truncated.sql',
] as const
const CONTRACT_FILES = [
  '1153_gochara_sky_event_substrate.sql', '1154_gochara_rule_path_registry.sql',
  '1155_gochara_relationship_record.sql', '1156_gochara_eval_window.sql',
  '1157_gochara_av_polarity_declaration.sql',
] as const
const M1204 = '1204_gochara_av_qualifier_object_role.sql'
const M1206 = '1206_gochara_search_inventory_completeness.sql'
const M1216 = '1216_gochara_contract_builder_grants.sql'
const M1232 = '1232_gochara_search_moon_scope_domain.sql'
const M1233 = '1233_gochara_p1_period_anchor.sql'
const WINDOW_FILES = [...CONTRACT_FILES, M1204, M1206, M1232, M1233, M1216] as const

const BUILDER = 'data_plane_builder'
const SEALER = 'gochara_sealer'
// What migration 1206 §7 grants the builder EXECUTE on (12 own helpers + 5 contract functions its guards call).
const BUILDER_OWN_FUNCTIONS = [
  'ka_gochara_sha256_hex(text)', 'ka_gochara_uuidv8(text)', 'ka_gochara_canonical_json(jsonb)',
  'ka_gochara_utc_ts(timestamptz)', 'ka_gochara_uuid_set_ok(uuid[])',
  'ka_gochara_search_input_digest(text, jsonb, text, text, text[])', 'ka_gochara_search_l1_facts_digest(uuid, text[])',
  'ka_gochara_search_dasha_digest(uuid, uuid[])', 'ka_gochara_search_av_entry(text)',
  'ka_gochara_search_inventory_preimage(uuid, text, text)', 'ka_gochara_search_inventory_digest(uuid, text, text)',
  'ka_gochara_search_ledger_digest(uuid, text, text)',
] as const
const BUILDER_CONTRACT_FUNCTIONS = [
  'ka_gochara_lock_chart(uuid)', 'ka_gochara_lock_global_shared()', 'ka_gochara_generation_is_sealed(uuid, text)',
  'ka_gochara_generation_governed(text)', 'ka_gochara_horizon_finite_ok(tstzrange)',
] as const
// The seal principal's functions (names; unique in the schema).
const SEALER_FUNCTIONS = [
  'ka_gochara_lock_chart', 'ka_gochara_seal_generation', 'ka_gochara_generation_governed', 'ka_gochara_coverage_drift',
  'ka_gochara_horizon_finite_ok', 'ka_gochara_coverage_facts', 'ka_gochara_facts_horizon',
  'ka_gochara_membership_violations', 'ka_gochara_membership_violation', 'ka_gochara_lock_global_shared',
  'ka_gochara_search_completeness_violations', 'ka_gochara_search_l1_facts_digest', 'ka_gochara_sha256_hex',
  'ka_gochara_canonical_json', 'ka_gochara_search_dasha_digest', 'ka_gochara_search_av_entry',
  'ka_gochara_search_inventory_digest', 'ka_gochara_search_ledger_digest', 'ka_gochara_search_inventory_preimage',
  'ka_gochara_utc_ts', 'ka_gochara_search_replay_violations', 'ka_gochara_search_inventories_digest',
  'ka_gochara_search_moon_scope_violations', 'ka_gochara_search_moon_resolved_domain',
] as const
// The routine/protected migration principal: in production it OWNS every table and function, and the
// governed bootstrap revokes PUBLIC EXECUTE on whatever it creates (platform/scripts/
// nirmana-evidence-ownership-preflight.ts:259). The suite builds the same world so a missing
// function grant fails here, not in production (steward M20261001T224443-bfc4 R6).
const OWNER = 'amjis_app'

const CHART = '482012f1-710e-4a25-994a-93821f5871aa'
const CONV = 'sha256:eac922d4c3b0deb700112f2260cd250a0388ab159f4a1c4bca9451281a48e7a3'   // AM-1 vector digest
const CONV_OTHER = 'sha256:' + 'b'.repeat(64)                                               // a second sky convention
const LEGACY_CONV = 'legacy:c0'            // bridged to CONV
const LEGACY_OTHER = 'legacy:c1'           // bridged to CONV_OTHER (an INCOMPATIBLE bridge)
const LEGACY_NOBRIDGE = 'legacy:c2'        // registered, NEVER bridged
const AV_DECL = 'av-build:l1:482012f1:v1'
const LO = '2025-01-01T00:00:00Z'
const MID = '2025-02-01T00:00:00Z'
const HI = '2025-03-01T00:00:00Z'
const HORIZON_SQL = `tstzrange('${LO}','${HI}','[)')`
const VEC = { bg_transit_rules: 'd1', bg_transit_av_gates: 'd2' }
const VEC_SCOPE = { ...VEC, stored_scope: 'stored_non_moon' }   // AM-14: the scope bound to the manifest
const B_P6 = 'spec:GOCHARA_DESIGN_SPECS@1.4#§2.2/P6'
const B_EMPTY = 'oracle:O-RP-8'
const B_NA = 'spec:GOCHARA_DESIGN_SPECS@1.4#§2.2/na'
const CLS = 'marriage'

// the sealed registry the suite builds: every (path, version) must be ACCOUNTED for per class
const REGISTRY: Array<[string, string]> = [['p1', '1.0'], ['p5a', '1.0'], ['p7', '1.0'], ['p6', '1.0']]   // p1/p5a/p7 included, p6 on-demand

// ── independent reference implementation (node crypto) ─────────────────────────
const sha = (s: string): string => createHash('sha256').update(s, 'utf8').digest('hex')
function uuidv8(s: string): string {
  const b = createHash('sha256').update(s, 'utf8').digest().subarray(0, 16)
  b[6] = (b[6]! & 0x0f) | 0x80
  b[8] = (b[8]! & 0x3f) | 0x80
  const h = b.toString('hex')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`
}
function canonJson(v: unknown): string {
  if (v === null || typeof v !== 'object') return JSON.stringify(v)
  if (Array.isArray(v)) return '[' + v.map(canonJson).join(',') + ']'
  const o = v as Record<string, unknown>
  return '{' + Object.keys(o).sort().map(k => JSON.stringify(k) + ':' + canonJson(o[k])).join(',') + '}'
}
const inputDigest = (c: { conv: string; vec: unknown; l1: string; dasha: string; av: string[] }): string =>
  sha([`av_declarations=${[...c.av].sort().join(',')}`, `convention_id=${c.conv}`, `dasha_digest=${c.dasha}`,
       `input_generation_vector=${canonJson(c.vec)}`, `l1_facts_digest=${c.l1}`].join('\n'))

type Ob = readonly [agent: string, relation: string, role: string, target: string, frame: string, person: string]
const obBytes = (path_: string, ver: string, o: Ob, cls = CLS): string => [cls, path_, ver, ...o].join('|')
const obId = (path_: string, ver: string, o: Ob): string => uuidv8(obBytes(path_, ver, o))
const P1A: Ob = ['jupiter', 'residence', 'lord', 'lord_of:7', 'dasha_lord', 'self']
const P1B: Ob = ['jupiter', 'residence', 'occupant', 'occupant_of:7', 'dasha_lord', 'self']
const P5A: Ob = ['saturn', 'residence', 'av_qualifier', 'house_span:7', 'lagna', 'self']
const P5B: Ob = ['saturn', 'residence', 'av_qualifier', 'house_span:8', 'lagna', 'self']

interface PinRef { path: string; ver?: string; disp: 'included' | 'computed_empty' | 'excluded'; reason?: string; ruling?: string; basis?: string; ids: string[] }
const sortC = (xs: string[]): string[] => [...xs].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
function tsInventoryDigest(conv: string, input: string, pins: PinRef[], obs: string[]): string {
  const lines = [`convention=${conv}`, `horizon=[${LO},${HI})`, `input=${input}`]
  for (const p of [...pins].sort((a, b) => (`${a.path}|${a.ver ?? '1.0'}` < `${b.path}|${b.ver ?? '1.0'}` ? -1 : 1)))
    lines.push(`pin=${p.path}|${p.ver ?? '1.0'}|${p.disp}|${p.reason ?? ''}|${p.ruling ?? ''}|${p.basis ?? ''}|${sortC(p.ids).join(',')}`)
  for (const o of sortC(obs)) lines.push(`ob=${o}`)
  return sha(lines.join('\n'))
}
// ledger_digest preimage (v1.1): `input=<input_digest>` first, so an EMPTY ledger is input-bound too
const tsLedgerDigest = (rows: Array<[string, string, string, string]>, input: string): string =>
  sha(['input=' + input, ...sortC(rows.map(([id, lo, hi, st]) => `${id}|${lo}|${hi}|${st}|${input}`))].join('\n'))

// ── harness ────────────────────────────────────────────────────────────────────
let pool: Pool
type Q = Pick<PoolClient, 'query'>
let genSeq = 0
const nextGen = (): string => `5.${++genSeq + 20}`

function mig(name: string): string { return readFileSync(join(MIGRATIONS_DIR, name), 'utf8') }
async function tx<T>(fn: (c: PoolClient) => Promise<T>, opts: { tz?: string; role?: string } = {}): Promise<T> {
  const c = await pool.connect()
  try {
    await c.query('BEGIN')
    if (opts.tz) await c.query(`SET LOCAL TIME ZONE '${opts.tz}'`)
    if (opts.role) await c.query(`SET LOCAL ROLE ${opts.role}`)
    const r = await fn(c)
    await c.query('COMMIT')
    return r
  } catch (err) { await c.query('ROLLBACK').catch(() => undefined); throw err }
  finally { c.release() }
}
async function withTempDir<T>(files: readonly string[], fn: (dir: string) => Promise<T>): Promise<T> {
  const dir = mkdtempSync(join(tmpdir(), 'gochara-am5-'))
  try { for (const f of files) copyFileSync(join(MIGRATIONS_DIR, f), join(dir, f)); return await fn(dir) }
  finally { rmSync(dir, { recursive: true, force: true }) }
}
/** Run `fn` on one connection AS the migration principal (production: amjis_app owns everything). */
async function asOwner<T>(fn: (c: PoolClient) => Promise<T>): Promise<T> {
  const c = await pool.connect()
  try { await c.query(`SET ROLE ${OWNER}`); return await fn(c) }
  finally { await c.query('RESET ROLE').catch(() => undefined); c.release() }
}
async function window(files: readonly string[]): Promise<void> {
  await withTempDir(WINDOW_FILES, async dir => {
    await asOwner(c => runMigrations(c, [dir], { only: new Set(files), disclosures: new Map(), renumberDisclosures: new Map() }))
  })
}
// The REAL production column sets of the two L1 tables the input digests read (information_schema,
// read-only, 2026-10-02): audit column `computed_at`; float8 / numeric / timestamptz / date / array
// material columns. Constraints are reduced to the keys (PK fact_id / dasha_row_id).
const L1_STANDINS = `
  CREATE TABLE chart_facts (
    fact_id text PRIMARY KEY, chart_id uuid NOT NULL, ayanamsha_id text NOT NULL, build_id uuid NOT NULL,
    fact_category text NOT NULL, fact_subject text NOT NULL, fact_key text NOT NULL,
    fact_value_text text, fact_value_num numeric, fact_value_jsonb jsonb, unit text,
    citation_ref text NOT NULL DEFAULT '', citation_human text NOT NULL DEFAULT '',
    source_calculation text NOT NULL DEFAULT '', verification_pass_status text NOT NULL DEFAULT 'single_pass',
    engine_version text NOT NULL DEFAULT 'v', salience_formula_ver text,
    computed_at timestamptz NOT NULL DEFAULT now(), tolerance_arcsec double precision,
    near_sign_boundary_flag boolean DEFAULT false, near_nakshatra_boundary_flag boolean DEFAULT false,
    vargottama_flag_at_point boolean DEFAULT false, formula_provenance_text text,
    cross_ayanamsha_divergence_arcsec double precision DEFAULT 0.0, formula_id text);
  CREATE TABLE chart_dashas (
    dasha_row_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), chart_id uuid NOT NULL, ayanamsha_id text NOT NULL,
    build_id uuid NOT NULL, system_id text NOT NULL, level_n integer NOT NULL, parent_row_id uuid,
    lord_graha text NOT NULL, lord_sign text, start_date date NOT NULL, end_date date NOT NULL,
    start_iso timestamptz NOT NULL, end_iso timestamptz NOT NULL, duration_days numeric NOT NULL,
    sandhi_flag boolean NOT NULL DEFAULT false, karaka_role_at_period text,
    verification_pass_status text NOT NULL DEFAULT 'two_pass_verified', verification_method text NOT NULL DEFAULT '',
    citation_ref text NOT NULL DEFAULT '', citation_human text NOT NULL DEFAULT '',
    computed_at timestamptz NOT NULL DEFAULT now(), engine_version text NOT NULL DEFAULT '',
    lord_natal_shadbala_total numeric, next_dasha_start_iso timestamptz, concurrent_system_lords_jsonb jsonb,
    anchored_solar_return_iso timestamptz, karakas_active_during_period text[]);`
async function resetSchema(): Promise<void> {
  await ensureRoles()
  await pool.query(`DROP SCHEMA public CASCADE; CREATE SCHEMA public AUTHORIZATION ${OWNER};`)
  await asOwner(async c => {
    await c.query(`CREATE TABLE charts (id UUID PRIMARY KEY DEFAULT gen_random_uuid());
                   ${L1_STANDINS}`)
    for (const f of PARENT_FILES) await c.query(mig(f))
    await c.query(TRACKER_DDL)
    await c.query(TRACKER_IDENTITY_DDL)
  })
  await pool.query(`INSERT INTO charts (id) VALUES ($1)`, [CHART])
}
/** Roles are cluster-global: create each only if absent, and install the production default-privilege
 *  revocation (per database, idempotent). */
async function ensureRoles(): Promise<void> {
  for (const r of [OWNER, BUILDER, SEALER])
    await pool.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='${r}') THEN CREATE ROLE ${r} NOLOGIN; END IF; END $$`)
  await pool.query(`ALTER DEFAULT PRIVILEGES FOR ROLE ${OWNER} REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC`)
}
/** Leave a plain superuser-owned schema, then clear this database's role dependencies and drop what no
 *  other database on the cluster still needs. */
async function dropRoles(): Promise<void> {
  await pool.query(`DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;`)
  for (const r of [BUILDER, SEALER, OWNER]) {
    await pool.query(`DROP OWNED BY ${r} CASCADE`).catch(() => undefined)
    await pool.query(`DROP ROLE IF EXISTS ${r}`).catch(() => undefined)
  }
}
const chartCtx = (c: Q) => c.query(`SELECT ka_gochara_lock_chart($1)`, [CHART])

// fixtures that are generation-independent
const BUILD = '40000000-0000-4000-8000-000000000001'
const DASHA_IDS = ['30000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000002']
async function seedStatic(): Promise<void> {
  await tx(async c => {
    await chartCtx(c)
    for (const lc of [LEGACY_CONV, LEGACY_OTHER, LEGACY_NOBRIDGE])
      await c.query(`INSERT INTO kala_gochara_convention
         (convention_id, zodiac, ayanamsha, sidereal_method, node_model, node_source, epoch_convention, time_scale,
          house_system, ephemeris_mode, method_version)
         VALUES ($1,'sidereal','lahiri_chitrapaksha','true_chitra','mean','swiss','j2000','utc','whole_sign','swiss',$2)`,
        [lc, lc])
    for (const sc of [CONV, CONV_OTHER])
      await c.query(`INSERT INTO ka_gochara_sky_convention
         (convention_id, ephemeris_generation, ayanamsha, node_convention, grid, method_version, domain_start, domain_end)
         VALUES ($1,'de441','lahiri_chitrapaksha','mean','1s','m1','2025-01-01T00:00Z','2026-01-01T00:00Z')`, [sc])
    await c.query(`INSERT INTO ka_gochara_convention_bridge (kala_convention_id, sky_convention_id) VALUES ($1,$2),($3,$4)`,
      [LEGACY_CONV, CONV, LEGACY_OTHER, CONV_OTHER])           // LEGACY_NOBRIDGE deliberately unbridged
    await c.query(`INSERT INTO ka_gochara_av_polarity_declaration
       (convention, benefic_mark_name, malefic_mark_name, source_ref, applies_to_fact_categories)
       VALUES ($1,'rekhā','khaṇḍa','L1_ASHTAKAVARGA_EXTRACT_v1_1', ARRAY['ashtakavarga_bindu'])`, [AV_DECL])
  })
  await pool.query(`INSERT INTO chart_facts (fact_id, chart_id, ayanamsha_id, build_id, fact_category, fact_subject, fact_key,
                      fact_value_text, fact_value_num, unit, tolerance_arcsec)
                    VALUES ('F1',$1,'lahiri_chitrapaksha',$2,'graha_shadbala_total','SUN','rupa','a', 8.47,'rupa', 0.1),
                           ('F2',$1,'lahiri_chitrapaksha',$2,'graha_shadbala_total','MOON','rupa','b', 5.65,'rupa', 0.2)`, [CHART, BUILD])
  await pool.query(`INSERT INTO chart_dashas (dasha_row_id, chart_id, ayanamsha_id, build_id, system_id, level_n, lord_graha,
                      start_date, end_date, start_iso, end_iso, duration_days, lord_natal_shadbala_total, next_dasha_start_iso)
                    VALUES ($1,$3,'lahiri_chitrapaksha',$4,'vimshottari',1,'Mercury','2010-08-18','2027-08-18','2010-08-18T15:50:23Z','2027-08-18T21:50:23Z',6209,7.55,'2027-08-18T21:50:23Z'),
                           ($2,$3,'lahiri_chitrapaksha',$4,'vimshottari',2,'Ketu','2013-01-14','2014-01-11','2013-01-14T07:17:23Z','2014-01-11T12:14:23Z',362,0.625,'2014-01-11T12:14:23Z')`,
    [DASHA_IDS[0], DASHA_IDS[1], CHART, BUILD])
  await tx(async c => registry(c, REGISTRY))
  // the L1 read grants the builder principal holds in production (stand-ins carry none by default)
  await pool.query(`GRANT SELECT ON chart_facts, chart_dashas TO ${BUILDER}, ${SEALER}`)
}
async function registry(c: Q, ids: Array<[string, string]>): Promise<void> {
  const sel: Record<string, [string, string, string, string, string]> = {
    p1: ['dasha_lord', 'jupiter', 'residence', 'lord', 'verse_cited'],
    p5a: ['lagna', 'saturn', 'residence', 'av_qualifier', 'verse_cited'],
    p6: ['moon', 'moon', 'conjunction', 'karaka', 'uncited_extension'],
    p7: ['lagna', 'mars', 'residence', 'occupant', 'verse_cited'],
  }
  await c.query(`INSERT INTO ka_gochara_predicate (predicate_id, rule_version, operator, operands)
     VALUES ('q1','v1','within_orb','{"left":"chart_facts.graha_position:mars","right":"object.longitude","orb":3.0}')
     ON CONFLICT DO NOTHING`)
  for (const [id, ver] of ids) {
    const [frame, agent, rel, role, prov] = sel[id]!
    await c.query(
      `INSERT INTO ka_gochara_rule_path (path_id, rule_version, frame_kind, frame_arg, agent_set, relation_set, object_selector,
         provenance, operator_role, ruling_ref, score_rule)
       VALUES ($1,$9,$2,NULL,$3::jsonb,$4::jsonb,$5::jsonb,$6,$7,$8,'within_path_product')`,
      [id, frame, JSON.stringify([agent]), JSON.stringify([rel]),
       JSON.stringify([{ agent, relation: rel, object_role: role }]), prov,
       id === 'p6' ? 'testimony' : 'scored', prov === 'uncited_extension' ? 'R-9' : null, ver])
    await c.query(`INSERT INTO ka_gochara_rule_path_prerequisite (path_id, rule_version, ordinal, predicate_id, predicate_rule_version)
                   VALUES ($1,$2,1,'q1','v1')`, [id, ver])
    await c.query(`INSERT INTO ka_gochara_rule_path_seal (path_id, rule_version) VALUES ($1,$2)`, [id, ver])
  }
}

// ── per-generation builders (each step takes the chart key first, in ONE transaction by the caller) ──
interface Snap { conv: string; vec: unknown; l1: string; dasha: string; av: string[]; digest: string }
async function publication(c: Q, gen: string, vec: unknown = VEC, legacy = LEGACY_CONV): Promise<void> {
  await c.query(`INSERT INTO kala_gochara_publication
     (chart_id, generation, writer_asset_id, convention_id, input_generation_vector, ephemeris_backend, horizon, row_counts, content_digest, status)
     VALUES ($1,$2,'ka_gochara',$3,$4::jsonb,'{}',${HORIZON_SQL},'{}','digest','candidate')`, [CHART, gen, legacy, JSON.stringify(vec)])
}
async function snapshotLive(c: Q, gen: string, vec: unknown = VEC, conv = CONV): Promise<Snap> {
  const q = async (sqlText: string, args: unknown[]): Promise<string> => (await c.query<{ v: string }>(sqlText, args)).rows[0]!.v
  const l1 = await q(`SELECT ka_gochara_search_l1_facts_digest($1,$2::text[]) AS v`, [CHART, ['F1', 'F2']])
  const dasha = await q(`SELECT ka_gochara_search_dasha_digest($1,$2::uuid[]) AS v`, [CHART, DASHA_IDS])
  const av = [await q(`SELECT ka_gochara_search_av_entry($1) AS v`, [AV_DECL])]
  return snapshotWith(c, gen, { conv, vec, l1, dasha, av })
}
async function snapshotWith(c: Q, gen: string, s: Omit<Snap, 'digest'>): Promise<Snap> {
  const digest = inputDigest(s)
  await c.query(
    `INSERT INTO ka_gochara_search_input_snapshot
       (chart_id, generation, convention_id, input_generation_vector, consumed_fact_ids, consumed_dasha_row_ids,
        av_declarations, l1_facts_digest, dasha_digest, input_digest)
     VALUES ($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9,$10)`,
    [CHART, gen, s.conv, JSON.stringify(s.vec), ['F1', 'F2'], DASHA_IDS, s.av, s.l1, s.dasha, digest])
  return { ...s, digest }
}
async function header(c: Q, gen: string, input: string, cls = CLS, horizon = HORIZON_SQL): Promise<void> {
  await c.query(`INSERT INTO ka_gochara_search_inventory (chart_id, generation, event_class, horizon, input_digest)
                 VALUES ($1,$2,$3,${horizon},$4)`, [CHART, gen, cls, input])
}
async function pin(c: Q, gen: string, p: PinRef, cls = CLS): Promise<void> {
  await c.query(
    `INSERT INTO ka_gochara_search_path_pin
       (chart_id, generation, event_class, path_id, rule_version, disposition, exclusion_reason, ruling_ref, basis, committed_ob_ids)
     VALUES ($1,$2,$3,$4,$10,$5,$6,$7,$8,$9::uuid[])`,
    [CHART, gen, cls, p.path, p.disp, p.reason ?? null, p.ruling ?? null, p.basis ?? null, sortC(p.ids), p.ver ?? '1.0'])
}
/** Pin every registry version NOT in `handled` as an explicit exclusion (the total partition). */
async function pinRest(c: Q, gen: string, handled: Array<[string, string]>, cls = CLS): Promise<void> {
  for (const [path_, ver] of REGISTRY) {
    if (handled.some(([p, v]) => p === path_ && v === ver)) continue
    if (path_ === 'p6') await pin(c, gen, { path: 'p6', ver, disp: 'excluded', reason: 'on_demand_tier', basis: B_P6, ids: [] }, cls)
    else await pin(c, gen, { path: path_, ver, disp: 'excluded', reason: 'not_applicable_to_class', basis: B_NA, ids: [] }, cls)
  }
}
async function ob(c: Q, gen: string, path_: string, o: Ob, cls = CLS, ver = '1.0'): Promise<string> {
  const bytes = obBytes(path_, ver, o, cls); const id = uuidv8(bytes)
  await c.query(
    `INSERT INTO ka_gochara_search_obligation
       (chart_id, generation, event_class, ob_id, path_id, rule_version, agent, relation, object_role, target, frame, person, canonical_bytes)
     VALUES ($1,$2,$3,$4,$5,$13,$6,$7,$8,$9,$10,$11,$12)`, [CHART, gen, cls, id, path_, ...o, bytes, ver])
  return id
}
async function iv(c: Q, gen: string, id: string, lo: string, hi: string, input: string, state = 'searched_complete', cls = CLS): Promise<void> {
  await c.query(
    `INSERT INTO ka_gochara_search_interval (chart_id, generation, event_class, ob_id, search_range, state, input_digest)
     VALUES ($1,$2,$3,$4,tstzrange($5::timestamptz,$6::timestamptz,'[)'),$7,$8)`, [CHART, gen, cls, id, lo, hi, state, input])
}
async function finalize(c: Q, gen: string, cls = CLS): Promise<{ inv: string; led: string }> {
  const r = await c.query<{ inv: string; led: string }>(
    `SELECT ka_gochara_search_inventory_digest($1,$2,$3) AS inv, ka_gochara_search_ledger_digest($1,$2,$3) AS led`, [CHART, gen, cls])
  const d = r.rows[0]!
  await c.query(`UPDATE ka_gochara_search_inventory SET inventory_digest=$4, ledger_digest=$5
                 WHERE chart_id=$1 AND generation=$2 AND event_class=$3`, [CHART, gen, cls, d.inv, d.led])
  return d
}
async function partition(c: Q, gen: string, o: { cls?: string; relations?: string[]; horizon?: string; legacy?: string } = {}): Promise<void> {
  const h = o.horizon ?? HORIZON_SQL
  await c.query(
    `INSERT INTO kala_gochara_coverage
       (chart_id, generation, partition_kind, partition_key, convention_id, requested_horizon, completed_horizon, resolution,
        relations_searched, targets_requested, targets_resolved, targets_unresolved, target_resolution_state_counts, build_id)
     VALUES ($1,$2,'event_class',$3,$4,${h},${h},1.0,$5::text[],1,1,0,'{"resolved":1}','build-am5')`,
    [CHART, gen, o.cls ?? CLS, o.legacy ?? LEGACY_CONV, o.relations ?? ['residence']])
}
async function verify(c: Q, gen: string, digest: string, who = 'verifier-a', cls = CLS): Promise<void> {
  await c.query(`INSERT INTO ka_gochara_search_inventory_verification
     (chart_id, generation, event_class, verifier_id, verifier_version, rederived_inventory_digest) VALUES ($1,$2,$3,$4,'1',$5)`,
    [CHART, gen, cls, who, digest])
}
async function publishAndSeal(gen: string, opts: { role?: string; tz?: string } = {}): Promise<void> {
  if (!opts.role) opts = { ...opts, role: SEALER }   // every seal runs as the separately authorised principal
  await tx(async c => {
    await chartCtx(c)
    await c.query(`UPDATE kala_gochara_publication SET status='published', published_at=now() WHERE chart_id=$1 AND generation=$2`, [CHART, gen])
    await c.query(`SELECT ka_gochara_seal_generation($1,$2)`, [CHART, gen])
  }, opts)
}

/** A GOOD two-path build: p1@1.0 (A,B) + p5a@1.0 (A,B) included; every other registry version excluded;
 *  every obligation covered over the horizon; finalised; partition written; verified by a hash of the
 *  stored rows. `between` runs inside the build transaction before finalisation. */
interface Built { gen: string; snap: Snap; ids: { p1: string[]; p5a: string[] }; dig: { inv: string; led: string } }
async function goodBuild(gen: string, o: {
  vec?: unknown; skipP5aObligations?: boolean; p5a?: 'included' | 'computed_empty' | 'none'
  noVerify?: boolean; verifyDigest?: string; noPartition?: boolean; partitionRelations?: string[]
  tz?: string; role?: string
  between?: (c: PoolClient, b: { snap: Snap; ids: { p1: string[]; p5a: string[] } }) => Promise<void>
} = {}): Promise<Built> {
  return tx(async c => {
    await chartCtx(c)
    await publication(c, gen, o.vec)
    const snap = await snapshotLive(c, gen, o.vec ?? VEC)
    await header(c, gen, snap.digest)
    const p1 = [obId('p1', '1.0', P1A), obId('p1', '1.0', P1B)]
    const p5a = [obId('p5a', '1.0', P5A), obId('p5a', '1.0', P5B)]
    const mode = o.p5a ?? 'included'
    await pin(c, gen, { path: 'p1', disp: 'included', ids: p1 })
    if (mode === 'included') await pin(c, gen, { path: 'p5a', disp: 'included', ids: p5a })
    if (mode === 'computed_empty') await pin(c, gen, { path: 'p5a', disp: 'computed_empty', basis: B_EMPTY, ids: [] })
    await pinRest(c, gen, [['p1', '1.0'], ...(mode === 'none' ? [] : [['p5a', '1.0'] as [string, string]])])
    await ob(c, gen, 'p1', P1A); await ob(c, gen, 'p1', P1B)
    if (mode === 'included' && !o.skipP5aObligations) { await ob(c, gen, 'p5a', P5A); await ob(c, gen, 'p5a', P5B) }
    const covered = [...p1, ...(mode === 'included' && !o.skipP5aObligations ? p5a : [])]
    for (const id of covered) await iv(c, gen, id, LO, HI, snap.digest)
    if (o.between) await o.between(c, { snap, ids: { p1, p5a } })
    const dig = await finalize(c, gen)
    if (!o.noPartition) await partition(c, gen, { relations: o.partitionRelations })
    if (!o.noVerify) await verify(c, gen, o.verifyDigest ?? dig.inv)
    return { gen, snap, ids: { p1, p5a }, dig }
  }, { tz: o.tz, role: o.role })
}
const refused = async (p: Promise<unknown>, re: RegExp): Promise<void> => { await expect(p).rejects.toThrow(re) }

// ── the 26-class volume build ────────────────────────────────────────────────────────────────────────────────
const ALL_CLASSES = ['achievement_recognition', 'bereavement', 'business_launch', 'career_advancement', 'career_change', 'career_entry',
  'career_setback', 'childbirth', 'chronic_onset', 'education_milestone', 'exam_outcome', 'financial_deception', 'foreign_settlement',
  'illness_acute', 'major_gain', 'major_loss', 'marriage', 'parental_event', 'property_acquisition', 'psychological_arc', 'relocation',
  'romantic_start', 'separation', 'spiritual_turn', 'surgery', 'travel_event'] as const        // 26: the registry's 27 minus birth_anchor
const INCLUDED_PATHS = ['p1', 'p5a', 'p7'] as const
const PINS = Math.min(Number(process.env.REHEARSAL_PINS ?? 3), INCLUDED_PATHS.length)
const OB_PER_PIN = Number(process.env.REHEARSAL_OB_PER_PIN ?? 30)
const IV_PER_OB = Number(process.env.REHEARSAL_INTERVALS_PER_OB ?? 3)
const AGENTS = ['sun', 'moon', 'mars', 'mercury', 'jupiter', 'venus', 'saturn', 'rahu']
const obTuples = (n: number): Ob[] => {
  const out: Ob[] = []
  for (const t of Array.from({ length: 12 }, (_, i) => `house_span:${i + 1}`))
    for (const a of AGENTS) out.push([a, 'residence', 'occupant', t, 'lagna', 'self'])
  if (n > out.length) throw new Error(`REHEARSAL_OB_PER_PIN ${n} exceeds the ${out.length} distinct tuples this harness generates`)
  return out.slice(0, n)
}
const slices = (): Array<[string, string]> => {
  const lo = Date.parse(LO), hi = Date.parse(HI), step = Math.floor((hi - lo) / IV_PER_OB)
  return Array.from({ length: IV_PER_OB }, (_, i) => [new Date(lo + i * step).toISOString(), new Date(i === IV_PER_OB - 1 ? hi : lo + (i + 1) * step).toISOString()] as [string, string])
}
const ms = (t0: number): number => Math.round((performance.now() - t0) * 10) / 10

interface Phases { construct: number; finalise: number; verify: number; partition: number; rows: { obligations: number; intervals: number } }
/** One class, one transaction, as the BUILDER: header → pins → obligations → intervals → finalise → partition → verification. */
async function buildClass(gen: string, cls: string, snapDigest: string, ph: Phases): Promise<void> {
  await tx(async c => {
    await chartCtx(c)
    let t = performance.now()
    await header(c, gen, snapDigest, cls)
    const handled: Array<[string, string]> = []
    const pinned: Array<{ path: string; ids: string[]; obs: Ob[] }> = []
    for (const path_ of INCLUDED_PATHS.slice(0, PINS)) {
      const obs = obTuples(OB_PER_PIN)
      pinned.push({ path: path_, ids: obs.map(o => obId(path_, '1.0', o, )), obs })
      handled.push([path_, '1.0'])
    }
    // obligation ids are class-scoped (the class is part of the canonical bytes)
    for (const p of pinned) p.ids = p.obs.map(o => uuidv8(obBytes(p.path, '1.0', o, cls)))
    for (const p of pinned) await pin(c, gen, { path: p.path, disp: 'included', ids: p.ids }, cls)
    await pinRest(c, gen, handled, cls)
    for (const p of pinned) for (const o of p.obs) { await ob(c, gen, p.path, o, cls); ph.rows.obligations++ }
    for (const p of pinned) for (const id of p.ids) for (const [lo, hi] of slices()) { await iv(c, gen, id, lo, hi, snapDigest, 'searched_complete', cls); ph.rows.intervals++ }
    ph.construct += ms(t)
    t = performance.now(); const d = await finalize(c, gen, cls); ph.finalise += ms(t)
    t = performance.now(); await partition(c, gen, { cls }); ph.partition += ms(t)
    t = performance.now(); await verify(c, gen, d.inv, 'verifier-a', cls); ph.verify += ms(t)
  }, { role: BUILDER })
}

describe.runIf(RUN_REHEARSAL && !!TEST_DB_URL)('B6.0 R8-10 — 26-class volume, seal timing and contention (measurement; opt-in)', () => {
  const out: Record<string, unknown> = { scale: { classes: ALL_CLASSES.length, pins_per_class: PINS, ob_per_pin: OB_PER_PIN, intervals_per_ob: IV_PER_OB } }
  beforeAll(async () => {
    pool = new Pool({ ...resolveDisposableA51Config(TEST_DB_URL), max: 8 })
    await resetSchema()
    await window([...CONTRACT_FILES, M1204])
    await window([M1206])
    await window([M1216])
    await window([M1232])
    await window([M1233])
    await seedStatic()
    await pool.query(`GRANT USAGE ON SCHEMA public TO ${BUILDER}, ${SEALER}`)
    await pool.query(`
      GRANT SELECT, INSERT ON ka_gochara_generation_seal TO ${SEALER};
      GRANT SELECT, UPDATE ON kala_gochara_publication TO ${SEALER};
      GRANT SELECT ON kala_gochara_coverage, ka_gochara_rule_path_seal, ka_gochara_convention_bridge,
        ka_gochara_av_polarity_declaration, ka_gochara_relationship_record, ka_gochara_eval_window,
        ka_gochara_eval_window_record, ka_gochara_search_input_snapshot, ka_gochara_search_inventory,
        ka_gochara_search_path_pin, ka_gochara_search_obligation, ka_gochara_search_interval,
        ka_gochara_search_inventory_verification TO ${SEALER}`)
    await pool.query(`GRANT EXECUTE ON FUNCTION ${SEALER_FUNCTIONS.map(f => `public.${f}`).join(', ')} TO ${SEALER}`)
  }, 300_000)
  afterAll(async () => {
    if (process.env.REHEARSAL_OUT) writeFileSync(process.env.REHEARSAL_OUT, JSON.stringify(out, null, 2))
    console.log('REHEARSAL RESULT ' + JSON.stringify(out))
    if (!pool) return; await dropRoles(); await pool.end()
  })

  it('builds 26 classes as the builder, then seals as the sealer — timings recorded, replay clean', async () => {
    const GEN = '5.0'
    const ph: Phases = { construct: 0, finalise: 0, verify: 0, partition: 0, rows: { obligations: 0, intervals: 0 } }
    let snapDigest = ''
    const t0 = performance.now()
    await tx(async c => { await chartCtx(c); await publication(c, GEN, VEC_SCOPE); snapDigest = (await snapshotLive(c, GEN, VEC_SCOPE)).digest }, { role: BUILDER })
    for (const cls of ALL_CLASSES) await buildClass(GEN, cls, snapDigest, ph)
    out.build = { ...ph, total_ms: ms(t0) }
    const tSeal = performance.now()
    await publishAndSeal(GEN)                                   // flips to published, runs completeness + membership + replay checks, writes the seal row — as the sealer
    out.seal_ms = ms(tSeal)
    const tReplay = performance.now()
    const replay = await tx(async c => (await c.query(`SELECT count(*)::int AS n FROM ka_gochara_search_replay_violations($1,$2)`, [CHART, GEN])).rows[0]!.n, { role: SEALER })
    out.replay_check_ms = ms(tReplay)
    expect(replay).toBe(0)
    const sealed = await pool.query(`SELECT count(*)::int AS n FROM ka_gochara_generation_seal WHERE chart_id=$1 AND generation=$2`, [CHART, GEN])
    expect(sealed.rows[0].n).toBe(1)
  }, 900_000)

  it('CONTENTION: a builder transaction on a second generation WAITS for an in-flight seal — wait recorded', async () => {
    const G1 = '5.1', G2 = '5.2'
    const ph: Phases = { construct: 0, finalise: 0, verify: 0, partition: 0, rows: { obligations: 0, intervals: 0 } }
    let snap1 = ''
    await tx(async c => { await chartCtx(c); await publication(c, G1, VEC_SCOPE); snap1 = (await snapshotLive(c, G1, VEC_SCOPE)).digest }, { role: BUILDER })
    for (const cls of ALL_CLASSES) await buildClass(G1, cls, snap1, ph)
    const tSealStart = performance.now()
    const sealP = publishAndSeal(G1).then(() => ms(tSealStart))
    await new Promise(r => setTimeout(r, 30))                                // let the seal take its locks first
    const tB = performance.now()
    const bP = tx(async c => { await chartCtx(c); await publication(c, G2, VEC_SCOPE) }, { role: BUILDER }).then(() => ms(tB))
    const [sealMs, builderWaitMs] = await Promise.all([sealP, bP])
    out.contention = { seal_ms: sealMs, builder_other_generation_total_ms: builderWaitMs }
    expect(sealMs).toBeGreaterThan(0)
  }, 900_000)
})
