/**
 * r5_codegen_parity.test.ts — R5 W0b-codegen CI parity gate
 * =============================================================
 * Design §19 (single-source contract generation) + brief §6.2 (strangler — every
 * migrated instrument gets its own parity gate before/after promotion).
 *
 * Two independent parity claims are asserted here:
 *
 * 1. ENVELOPE PARITY (the §19 keystone fix): `src/generated/envelope.ts` (generated by
 *    `scripts/generate_envelope.ts`) must build byte-identical envelope objects to the
 *    canonical `platform/src/lib/retrieval/envelope.ts` for a recorded corpus of
 *    representative request/response shapes. This is the direct replacement for the
 *    hand-mirror the verifier ring flagged — this test is what makes "generated,
 *    not hand-mirrored" a checked fact instead of a comment.
 *
 * 2. REGISTRY-SHIM PARITY (pilot instruments): for the 3 STRANGLER pilots
 *    (ganita_strength_get, ganita_sade_sati_get, ganita_tajaka_get), the LIVE handwritten
 *    zod schema (exported from `register_p1_ganita.ts`) and the GENERATED schema
 *    (derived from the registry CapabilityDescriptor, `src/generated/registry_shims.ts`)
 *    must accept/reject the same corpus of args objects and, on acceptance, parse to the
 *    same structured content — on the INTERSECTING field set the live shim exposes today
 *    (chart_id/ayanamsha_id/limit/offset; see generate_registry_shims.ts's docstring for
 *    why the generated schema's superset fields are out of scope for this gate).
 *
 * Both suites replay a fixed, recorded corpus (not property-based/random) so failures are
 * reproducible and the corpus itself documents the contract being protected.
 */
import { describe, it, expect } from 'vitest'
import { z } from 'zod'
import {
  buildRetrievalEnvelope as generatedBuildEnvelope,
  type BuildRetrievalEnvelopeParams as GeneratedParams,
  type EnvelopeFormat as GeneratedFormat,
} from '../generated/envelope.js'
// Canonical, single-source module — imported directly here ONLY because this test process
// (vitest, run from platform-mcp/) can reach across the repo via a relative path for
// TEST-TIME comparison. This is NOT how register_p1_ganita.ts (the runtime shim) consumes
// it — that always goes through the generated module (the whole point of §19). If this
// relative import ever breaks (e.g. the canonical file moves), that is itself a useful
// signal that the generator's SOURCE_PATH needs updating too.
import {
  buildRetrievalEnvelope as canonicalBuildEnvelope,
  type BuildRetrievalEnvelopeParams as CanonicalParams,
  type EnvelopeFormat as CanonicalFormat,
} from '../../../platform/src/lib/retrieval/envelope.ts'

import {
  ganitaStrengthGetInputSchema,
  ganitaSadeSatiGetInputSchema,
  ganitaTajakaGetInputSchema,
} from '../tools/register_p1_ganita.js'
import {
  ganitaStrengthGetGeneratedInputSchema,
  ganitaSadeSatiGetGeneratedInputSchema,
  ganitaTajakaGetGeneratedInputSchema,
} from '../generated/registry_shims.js'

// ── 1. Envelope parity ────────────────────────────────────────────────────────

describe('R5 W0b-codegen parity gate — envelope (generated vs canonical)', () => {
  const FIXED_NOW = '2026-07-08T00:00:00.000Z'

  const corpus: Array<{ label: string; params: GeneratedParams & CanonicalParams; format: 'legacy' | 'v3' }> = [
    {
      label: 'legacy, minimal content',
      params: { tool: 'ganita_strength_get', content: { rows: [] } },
      format: 'legacy',
    },
    {
      label: 'legacy, with pagination',
      params: {
        tool: 'ganita_yogas_get',
        content: { rows: [{ a: 1 }] },
        pagination: { offset: 10, limit: 50, total: 82 },
      },
      format: 'legacy',
    },
    {
      label: 'v3, fully populated',
      params: {
        tool: 'ganita_yogas_get',
        content: { rows: [{ fact_id: 'f-1', citation_ref: 'c-1', verification_pass_status: 'pass' }] },
        pagination: { offset: 0, limit: 500, total: 82 },
        chart_header: {
          chart_id_short: '482012f1', name: 'native', lagna_sign: 'Aries', lagna_deg: 1.2,
          moon_sign: 'Purva Bhadrapada', sun_sign: 'Capricorn', ayanamsha: 'lahiri_chitrapaksha',
          current_maha_antar: 'Saturn/Mercury',
        },
        as_of_date: '2026-07-08',
        verdict: { yogas_fired: 3 },
        ranking_basis: { mode: 'catalog_order' },
        grounding: { fact_ids: ['f-1'], citations: ['c-1'], grounding_score: 1 },
        // SAMĀPTI A2: 'get_signals' is the live MCP tool name; the internal registry
        // capability name 'query_signals' that used to sit here is not a registered
        // tool and tripped sc_pointer_validation.ts (SC-18 class, quarantined since
        // 2026-07-10). Production emits 'get_signals' (register_d9_judgment.ts:1143,
        // registry_bridge.ts:3209); the fixture now matches production.
        drill_pointers: [{ instrument: 'bodha_signals_get', hint: 'x' }],
        judgment_flags: ['zero_rows_returned'],
      },
      format: 'v3',
    },
    {
      label: 'v3, no v3Extras supplied (falls back to defaults)',
      params: { tool: 'ganita_sade_sati_get', content: { rows: [] } },
      format: 'v3',
    },
  ]

  for (const { label, params, format } of corpus) {
    it(`generated and canonical produce identical output — ${label}`, () => {
      const generated = generatedBuildEnvelope(params, format as GeneratedFormat)
      const canonical = canonicalBuildEnvelope(params, format as CanonicalFormat)

      // 'timing.computed_at' is a live Date().toISOString() in both builders — strip it
      // (and confirm it's a valid ISO string on both sides) before the deep-equal, since
      // two independent `new Date()` calls a few microseconds apart are never byte-equal.
      const strip = (env: unknown): unknown => {
        if (env && typeof env === 'object' && 'timing' in env) {
          const e = env as { timing: { computed_at: string } }
          expect(() => new Date(e.timing.computed_at).toISOString()).not.toThrow()
          return { ...env, timing: { ...e.timing, computed_at: FIXED_NOW } }
        }
        return env
      }
      expect(strip(generated)).toEqual(strip(canonical))
    })
  }
})

// ── 2. Registry-shim parity (pilot instruments) ───────────────────────────────

describe('R5 W0b-codegen parity gate — registry shims (handwritten vs generated, pilot set)', () => {
  // Only the fields the LIVE handwritten shim actually exposes today (see
  // generate_registry_shims.ts docstring "PARITY NOTE").
  const INTERSECTING_FIELDS = ['chart_id', 'ayanamsha_id', 'limit', 'offset'] as const

  function pickIntersecting(shape: Record<string, z.ZodTypeAny>): z.ZodTypeAny {
    const picked: Record<string, z.ZodTypeAny> = {}
    for (const f of INTERSECTING_FIELDS) {
      if (shape[f]) picked[f] = shape[f]
    }
    return z.object(picked)
  }

  const pilots: Array<{
    mcpToolName: string
    handwritten: Record<string, z.ZodTypeAny>
    generated: Record<string, z.ZodTypeAny>
  }> = [
    { mcpToolName: 'ganita_strength_get', handwritten: ganitaStrengthGetInputSchema, generated: ganitaStrengthGetGeneratedInputSchema },
    { mcpToolName: 'ganita_sade_sati_get', handwritten: ganitaSadeSatiGetInputSchema, generated: ganitaSadeSatiGetGeneratedInputSchema },
    { mcpToolName: 'ganita_tajaka_get', handwritten: ganitaTajakaGetInputSchema, generated: ganitaTajakaGetGeneratedInputSchema },
  ]

  const validChartId = '482012f1-710e-4a25-994a-93821f5871aa'

  // NOTE: the registry CapabilityDescriptor's `input_schema` (the codegen source) carries
  // no numeric bounds metadata (min/max) for limit/offset — only the handwritten shim's
  // zod schema declares `.min(1).max(25000)`. Codegen deliberately does NOT invent bounds
  // that aren't in the descriptor (fabricating constraints would be worse than omitting
  // them), so out-of-range numeric values are NOT a fair parity comparison and are excluded
  // from this corpus. This is a real, flagged gap (see generate_registry_shims.ts's
  // paramSchemaToZodExpr) — not silently resolved.
  const argsCorpus: Array<{ label: string; args: Record<string, unknown> }> = [
    { label: 'minimal valid (chart_id only)', args: { chart_id: validChartId } },
    { label: 'full valid', args: { chart_id: validChartId, ayanamsha_id: 'lahiri_chitrapaksha', limit: 100, offset: 5 } },
    { label: 'missing chart_id (invalid)', args: { ayanamsha_id: 'lahiri_chitrapaksha' } },
    { label: 'chart_id not a uuid (invalid)', args: { chart_id: 'not-a-uuid' } },
  ]

  for (const { mcpToolName, handwritten, generated } of pilots) {
    describe(mcpToolName, () => {
      const handwrittenIntersecting = pickIntersecting(handwritten)
      const generatedIntersecting = pickIntersecting(generated)

      for (const { label, args } of argsCorpus) {
        it(`old handwritten shim and new generated shim agree — ${label}`, () => {
          const oldResult = handwrittenIntersecting.safeParse(args)
          const newResult = generatedIntersecting.safeParse(args)
          expect(newResult.success).toBe(oldResult.success)
          if (oldResult.success && newResult.success) {
            // Compare only the keys the CALLER actually supplied. The generated schema
            // additionally fills in zod `.default(...)` values (e.g. limit=500) for keys
            // the caller omitted, matching what the handwritten call sites do manually via
            // `limit ?? 500` AFTER parsing — same effective behavior, different layer. That
            // is not a parity violation; asserting on the full parsed object would be.
            for (const key of Object.keys(args)) {
              expect(newResult.data[key as keyof typeof newResult.data])
                .toEqual(oldResult.data[key as keyof typeof oldResult.data])
            }
          }
        })
      }
    })
  }
})
