/**
 * mcp_profile.ts — W5 L2: per-family MCP surface profiles, OAuth-scope-gated
 * ================================================================================
 * RETRIEVAL_PLANE_ELEVATION_PLAN_v1_0.md §R-4 item 1/2 (master brief §E W5): "Profile
 * selection = entitlement (OT-10 b+c): OAuth scope / connect URL selects the projection;
 * a plain guest cannot reach raw tools." Ruling RC-1: "≤20 umbrellas for non-Claude
 * families." Ruling RC-3: "DeepSeek posture — consult-profile-only." Plan §6.5: "Safe
 * by default: consultation profile default; raw tools scope-gated."
 *
 * THREE NAMED PROFILES (generated by `platform/scripts/manifest/mcp_surface_profile_builder.ts`,
 * mirrored here as `../generated/mcp_surface_profiles.generated.ts` — see that file's own
 * banner for why it's a TS data mirror, not a JSON import, across the platform/platform-mcp
 * process boundary):
 *   - full:    every mcp_full-tagged tool, uncapped — the served surface for a trusted
 *              first-party caller (this server's own Bearer API key) or an OAuth grant that
 *              explicitly carries the `mcp:profile:full` scope.
 *   - compact: ≤20 ranked umbrella tools (RC-1) — an OAuth grant carrying
 *              `mcp:profile:compact`.
 *   - consult: the small, restricted orienting-tool set — the SAFE DEFAULT for every OAuth
 *              grant that does not explicitly request a wider scope (unscoped, legacy
 *              `mcp:tools`-only grants, or any unrecognized scope string). This is the
 *              profile a "plain guest" gets, per the plan's own words.
 *
 * WHY THIS IS SAFE BY CONSTRUCTION, NOT JUST BY CONVENTION: `applyProfileGate()` does not
 * filter a tools/list RESPONSE after the fact (a filter that could be bypassed by a client
 * calling an unlisted tool name directly) — it monkeypatches the per-request `McpServer`
 * instance's own `.tool()` REGISTRATION method before any `register*Tools()` call site in
 * `server.ts` runs. A tool name outside the resolved profile's allowlist is never handed to
 * the SDK's tool registry at all for that request — there is no server-side dispatch path
 * to it, so a `tools/call` for it fails the same way calling an unregistered tool name
 * always fails (MCP protocol error, not a filtered/redacted success). This closes the
 * exact gap server.ts had before this lane: EVERY `register*Tools(server, ...)` call was
 * unconditional, so `tools/list` returned all ~150 tools to every caller regardless of
 * OAuth scope — the "profile selection = entitlement" ruling was not implemented at all
 * prior to this file.
 */
import { MCP_SURFACE_PROFILES, type McpProfileName } from '../generated/mcp_surface_profiles.generated.js'

export type { McpProfileName }

// ── Scope vocabulary ──────────────────────────────────────────────────────────
// New scopes, additive to the existing `mcp:tools`/`mcp:resources`/`mcp:prompts` grant
// scopes (`server.ts`'s dynamic-client-registration default, `oauth/authorize.ts`'s
// VALID_SCOPES). A client may carry BOTH a resource-shape scope (mcp:tools) AND a
// profile scope (mcp:profile:compact) — they answer different questions ("can this
// client call server.tool() style requests at all" vs. "which tool SET").
export const FULL_SCOPE = 'mcp:profile:full' as const
export const COMPACT_SCOPE = 'mcp:profile:compact' as const
export const CONSULT_SCOPE = 'mcp:profile:consult' as const
export const PROFILE_SCOPES = [FULL_SCOPE, COMPACT_SCOPE, CONSULT_SCOPE] as const

export type AuthKind = 'bearer_key' | 'oauth'

export interface ProfileAuthContext {
  /** 'bearer_key' = this server's own first-party Bearer API-key auth (validateMcpKeyFromHeader).
   *  'oauth' = a DB-backed OAuth 2.0 access token (validateAccessToken). */
  authKind: AuthKind
  /** OAuth scopes on the validated token, when authKind === 'oauth'. Ignored for bearer_key. */
  oauthScopes?: string[]
}

/**
 * Resolve a profile from an OAuth token's granted scopes. SAFE BY DEFAULT: any scope set
 * that does not explicitly carry `mcp:profile:full` or `mcp:profile:compact` resolves to
 * `consult` — including an empty/undefined scope list, a legacy grant that only carries
 * `mcp:tools`/`mcp:resources`/`mcp:prompts`, or an unrecognized scope string. This is a
 * closed decision (never "if in doubt, allow"), matching plan §6.5.
 */
export function resolveProfileFromScopes(scopes: string[] | undefined): McpProfileName {
  const set = new Set(scopes ?? [])
  if (set.has(FULL_SCOPE)) return 'full'
  if (set.has(COMPACT_SCOPE)) return 'compact'
  return 'consult'
}

/**
 * Resolve the effective profile for an authenticated MCP request. First-party Bearer-key
 * callers (this platform's own trusted credential — the OT-5 "keep self-issued OAuth for
 * this campaign" path, i.e. Cowork / the platform's own chat integration) always get
 * `full`: they are not the "plain guest" the plan's safe-by-default language targets.
 * OAuth callers (third-party MCP connectors — ChatGPT, Gemini, DeepSeek, generic clients)
 * resolve from their token's granted scopes.
 */
export function resolveMcpProfile(ctx: ProfileAuthContext): McpProfileName {
  if (ctx.authKind === 'bearer_key') return 'full'
  return resolveProfileFromScopes(ctx.oauthScopes)
}

/**
 * Allowed tool names for a profile. `null` for `full` means "no filter" — every tool this
 * codebase ever registers is within the `mcp_full` profile's remit by construction (the
 * registry's own projection_tags rule tags every LLM-facing tool at least `mcp_full`).
 */
export function getAllowedToolNames(profile: McpProfileName): Set<string> | null {
  if (profile === 'full') return null
  return new Set(MCP_SURFACE_PROFILES[profile].tool_names)
}

export interface ProfileGateResult {
  profile: McpProfileName
  /** null when profile === 'full' (no gate applied — every tool passes through). */
  allowed: Set<string> | null
  /**
   * Tool names whose registration was BLOCKED this request (mutated in place as
   * `register*Tools()` calls happen after this function returns — read after all
   * registrations complete, e.g. for the request-dispatch log line).
   */
  blockedAttempts: string[]
}

/* eslint-disable @typescript-eslint/no-explicit-any -- McpServer.tool() is a heavily
   overloaded SDK method (name+handler / name+description+handler / name+schema+handler /
   name+description+schema+handler / +annotations variants); this gate only needs to
   intercept the call by NAME, so it deliberately does not re-derive the SDK's full
   overload union here (the same `as any` pattern server.ts itself already uses at every
   `register*Tools(server as any, ...)` call site for the same underlying reason). */

/** Structural shape this gate needs — any object with a `.tool(name, ...)` registration method. */
export interface ToolRegisteringServer {
  tool: (name: string, ...rest: any[]) => any
}

/**
 * Monkeypatches `server.tool()` IN PLACE so any registration call for a tool name outside
 * the resolved profile's allowlist becomes a no-op (never reaches the real SDK registration
 * — the tool is simply never added to this request's `McpServer` instance). Call this ONCE,
 * immediately after constructing the per-request `McpServer`, before any `register*Tools()`
 * call site runs. A no-op for the `full` profile (server.tool left untouched).
 *
 * Safe to call on a fresh `McpServer` per request (this codebase is stateless per D10 — a
 * new `McpServer` is constructed for every `/mcp` POST, per `server.ts`), so patching the
 * instance method has no cross-request leakage risk.
 */
export function applyProfileGate(server: ToolRegisteringServer, profile: McpProfileName): ProfileGateResult {
  const allowed = getAllowedToolNames(profile)
  const blockedAttempts: string[] = []
  if (allowed === null) {
    return { profile, allowed, blockedAttempts }
  }
  const originalTool = server.tool.bind(server)
  server.tool = (name: string, ...rest: any[]) => {
    if (!allowed.has(name)) {
      blockedAttempts.push(name)
      return undefined
    }
    return originalTool(name, ...rest)
  }
  return { profile, allowed, blockedAttempts }
}
/* eslint-enable @typescript-eslint/no-explicit-any */
