'use client'

import { useEffect, useRef, useState } from 'react'
import dynamic from 'next/dynamic'

interface MermaidBlockProps {
  code: string
  /** Suppress render during streaming — show placeholder instead */
  isStreaming?: boolean
}

// Inner component that does the actual mermaid rendering.
// Loaded lazily by next/dynamic (ssr: false) to keep the main bundle lean.
function MermaidRenderer({ code }: { code: string }) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [error, setError] = useState<string | null>(null)
  const [svg, setSvg] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    async function render() {
      try {
        const mermaid = (await import('mermaid')).default
        mermaid.initialize({ startOnLoad: false, theme: 'dark', securityLevel: 'loose' })
        const id = `mermaid-${Math.random().toString(36).slice(2)}`
        const { svg: rendered } = await mermaid.render(id, code)
        if (!cancelled) setSvg(rendered)
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err))
      }
    }

    render()
    return () => { cancelled = true }
  }, [code])

  if (error) {
    return (
      <pre
        data-testid="v2-mermaid-error"
        className="my-4 overflow-x-auto rounded bg-muted px-4 py-3 text-sm font-mono text-muted-foreground"
      >
        {code}
      </pre>
    )
  }

  if (!svg) {
    return (
      <div
        data-testid="v2-mermaid-loading"
        className="my-4 flex items-center gap-2 text-sm text-muted-foreground"
      >
        <span className="animate-spin">⟳</span>
        <span>Rendering diagram…</span>
      </div>
    )
  }

  return (
    <div
      ref={containerRef}
      data-testid="v2-mermaid-diagram"
      className="my-4 overflow-x-auto"
      // SVG is generated by mermaid from the diagram definition string — not user input.
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

// Lazy-load MermaidRenderer so the ~1MB mermaid bundle stays out of the initial page bundle.
const LazyMermaidRenderer = dynamic(() => Promise.resolve(MermaidRenderer), { ssr: false })

export function MermaidBlock({ code, isStreaming = false }: MermaidBlockProps) {
  if (isStreaming) {
    return (
      <div
        data-testid="v2-mermaid-streaming-placeholder"
        className="my-4 flex items-center gap-2 text-sm text-muted-foreground"
      >
        <span className="animate-pulse">●</span>
        <span>Rendering diagram…</span>
      </div>
    )
  }

  return <LazyMermaidRenderer code={code} />
}
