/**
 * registry_data.ts — GENERATED, DO NOT HAND-EDIT.
 * ==================================================
 * Generated by `platform/scripts/generate_vidhi_registry_mirror.ts` from `platform/src/lib/vidhi/registry_data.ts`
 * (source sha256:6d119cebcc293840). Run `npm run codegen:vidhi` in platform/ to regenerate
 * after any change to the canonical source; run `npm run codegen:vidhi:check` in CI to
 * detect drift.
 *
 * Design §19 (single-source contract generation): this file exists so the platform /
 * platform-mcp vidhi-registry process-boundary copy has exactly ONE authored copy (the
 * canonical file above) and this copy is mechanically derived. It previously stood as a
 * hand-synced "vendored mirror" (see this directory's index.ts doc-comment) — the two
 * copies had already drifted on this exact import line (GT-56, W0 baseline probe) with no
 * gate to catch it. This generated module, plus its companion parity test
 * (platform-mcp/src/__tests__/vidhi_codegen_parity.test.ts), closes that gap for
 * registry_data.ts specifically — see the generator's own header for the two OTHER known
 * hand-synced copies (types.ts here, compiler.ts, and the migration-440 DB seed) this pass
 * does NOT cover.
 *
 * The only substantive edit versus the canonical source is the NodeNext-required `.js`
 * extension on the sibling type-only import (platform-mcp's moduleResolution: "NodeNext"
 * requires it; platform's moduleResolution: "bundler" does not).
 */

import type { FloorItem, IntentFloor, VidhiPrimitive } from './types.js';

export const VIDHI_PRIMITIVES: readonly VidhiPrimitive[] = [
  // ── Structural / worked-example core (design §3 floor(wealth_deepdive) atoms 1-4, 6-7) ──
  {
    primitive_id: 'bhava_condition',
    version: 1,
    definition: 'Full condition of a bhava (house): occupants, lord, aspects received, dignity of occupants.',
    category: 'structural',
    live_tool: 'ganita_structural_get',
    tool_args: { chart_id: '{chart_id}', house: '{house}' },
    fallback_face: 'ganita_chart_facts_get(category=bhava)',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'bhavesha_condition',
    version: 1,
    definition: 'Condition of a bhava’s lord (bhāveśa): placement, dignity, strength, aspects on/from it.',
    category: 'structural',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', house: '{house}', mode: 'lord' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'karaka_condition',
    version: 1,
    definition: 'Condition of a significator graha (naisargika or chāra kāraka) for the domain in question.',
    category: 'structural',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', karaka: '{karaka}', mode: 'karaka' },
    fallback_face: 'ganita_strength_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: ['CR-36'],
  },
  {
    primitive_id: 'from_moon_view',
    version: 1,
    definition: 'Chandra-lagna re-derivation of house/karaka reads (bhāva reckoned from Moon, not just Lagna).',
    category: 'structural',
    live_tool: 'ganita_chart_facts_get',
    tool_args: { chart_id: '{chart_id}', reference_point: 'moon' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'varga_ratification',
    version: 1,
    definition: 'Compares D1 promise against operative-varga delivery per bhāveśa/kāraka; fires when dignity flips.',
    category: 'signal',
    live_tool: 'bodha_signals_get',
    tool_args: { chart_id: '{chart_id}', signal_type_class: 'varga_ratification_divergence' },
    fallback_face: 'ganita_chart_facts_get(divisional_chart={varga})',
    known_gap: null, // CR-57 CLOSED_WITH_EVIDENCE (D-1.6 S-7) — live per §F0.
    mandatory_tags: ['varga_ratification_divergence'],
    cr27_prevents: ['CR-36'],
  },
  {
    primitive_id: 'special_lagna_read',
    version: 1,
    definition: 'Reads special lagnas (Indu, Sree, Ghati, Hora, Bhava, etc.) with domain salience.',
    category: 'structural',
    live_tool: 'ganita_special_lagnas_get',
    tool_args: { chart_id: '{chart_id}', lagnas: '{lagnas}' },
    fallback_face: 'ganita_special_lagnas_get',
    known_gap: null, // CR-16 STALE-CORRECTED (SARVA-SIDDHI, 2026-07-24): shipped PR #594/D-2 (20e2da8e) — ganita_special_lagnas_get (register_p1_aliases.ts) now accepts an optional chart_id and serves stored special-lagna facts from chart_facts (245 facts verified live for chart 482012f1). Was still tagged OPEN here — register drift, same precedent as CR-54/CR-56/CR-59.
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'chara_karaka_read',
    version: 1,
    definition: 'Reads a chāra kāraka (e.g. Ātmakāraka) placement and condition per Jaimini.',
    category: 'structural',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', mode: 'chara_karaka', karaka: '{chara_karaka}' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'dhana_yoga_scan',
    version: 1,
    definition: 'Scans the house-lord yoga family for the domain (dhana / raja / Budha-Āditya / Sarasvatī / Lakṣmī).',
    category: 'doctrine',
    live_tool: 'ganita_yoga_firings_get',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}', family: 'house_lord' },
    fallback_face: 'ganita_yogas_get',
    known_gap: null, // CR-56 CORRECTED (VIDHI-PŪRṆATĀ, 2026-07-23): the house-lord dhana/raja family IS confirmed firing live via ganita_yoga_firings_get (dhana_yoga_house_lords), verified by P-0's probe AND by yoga_firings_read (same underlying tool, known_gap:null) in this file. CR-56 CLOSED 2026-07-23 — the tag was stale register drift. Mirrors the CR-59/nbry_scan stale-correction precedent above.
    mandatory_tags: [],
    cr27_prevents: ['CR-27c'],
  },
  {
    // VIDHI-PŪRṆATĀ P-2 (2026-07-23): dedicated Jaimini spiritual/renunciate yoga scan for the
    // spirituality_deepdive floor. Kept SEPARATE from dhana_yoga_scan (rather than a family
    // override on it) precisely so its data-gap is honest and durable: dhana_yoga_scan's CR-56
    // has now been reconciled to null (VIDHI-PŪRṆATĀ, 2026-07-23: the house-lord family DOES fire
    // live), and had the spiritual-family gap been folded into CR-56, that CR-56 closure would have
    // silently un-flagged a gap that is genuinely still dark. The 'spiritual' family key is absent from
    // ganita_yoga_firings_get (P-0 probe) → known_gap CR-130 → surfaces in the completeness
    // receipt's `dark` bucket, never presented as served (brief §0 honesty line).
    primitive_id: 'spiritual_yoga_scan',
    version: 1,
    definition: 'Scans the Jaimini spiritual/renunciate yoga family (pravrajyā, sannyāsa, tāpasa — 4+ grahas in one bhāva, Ketu/Saturn/12th-lord involvement) for the mokṣa domain.',
    category: 'doctrine',
    live_tool: 'ganita_yoga_firings_get',
    tool_args: { chart_id: '{chart_id}', domain: 'spirituality', family: 'spiritual' },
    fallback_face: 'ganita_yogas_get',
    known_gap: 'CR-130', // Jaimini 'spiritual' yoga family not surfaced as a family key by the firings engine (P-0) — data gap, do NOT fake
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'nbry_scan',
    version: 1,
    definition: 'Nīcha-Bhaṅga (debility cancellation) scan, per-varga (not D1-only).',
    category: 'doctrine',
    // D-2 gate fix (2026-07-17): routed to the firings-authoritative surface. ganita_yoga_firings_get
    // serves neecha_bhanga_raja_yoga FIRED with bhanga_active + a per-varga grounds_jsonb ledger
    // (BPHS Ch.39 rule-by-rule) since D-1.6 S-3. The prior route (ganita_yogas_get) is the catalog
    // face that does NOT evaluate NBRY — following it left the reading blind to the D9 cancellations.
    live_tool: 'ganita_yoga_firings_get',
    tool_args: { chart_id: '{chart_id}', bhanga_active: true },
    fallback_face: 'ganita_condition_get',
    known_gap: null, // CR-59 CORRECTED (D-2, 2026-07-17): L1 NBRY detector is LIVE (D9-scoped, grounds-carried) since D-1.6 S-3. Residual is L2 ranking/surfacing, not detection.
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'wealth_loss_mechanism_scan',
    version: 1,
    definition: 'Scans functional-lordship links (dusthana/maraka/badhaka aspects) that constitute a loss mechanism.',
    category: 'signal',
    // D-2 gate fix (2026-07-17): dropped the dead signal_type_class 'functional_lordship_link'
    // (0 rows on live) — it left this floor item empty and the reading blind to the adverse
    // wealth signals. Now returns the composite-ranked wealth signals (adverse valence rows —
    // e.g. Ketu→H2 major-malefic, Saturn→H9 chart-defining — surface here); the derived
    // graha-bhava-affliction MECHANISM (Rahu-occupies-dhana) is served by the fallback_face
    // judgment_query's affliction_mechanisms layer (now budget-trimmed to be floor-model-digestible).
    live_tool: 'bodha_signals_get',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}' },
    fallback_face: 'judgment_query',
    known_gap: null, // CR-54 functional-lordship valence is LIVE (ga_vichara valence_pass, DR-9 doctrine) since D-2; residual taxonomy completeness tracked separately, not a route gap
    mandatory_tags: [],
    cr27_prevents: ['CR-27c'],
  },
  {
    primitive_id: 'dasha_spine_lord_capability',
    version: 1,
    definition: 'Full daśā spine enriched with per-lord capability (shadbala percentile, house class, functional lordship, ratification factor, warning tier).',
    category: 'temporal',
    live_tool: 'ganita_dasha_lord_capability_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'ganita_dashas_get',
    known_gap: null, // CR-60 CLOSED_WITH_EVIDENCE (D-1.6 S-7) — live per §F0.
    mandatory_tags: ['dasha_lord_capability'],
    // CR-27a ("4-call diff reading answered a fresh-reading question"): a compiled floor
    // that always includes the current daśā spine forces a fresh-state read regardless of
    // how the question was framed, closing the diff-vs-fresh ambiguity at the floor level.
    cr27_prevents: ['CR-36', 'CR-27a'],
  },
  {
    primitive_id: 'taranga_curve',
    version: 1,
    definition: 'Domain-scoped temporal window bundle (dasha × transit convolution) — full convergence convolution is D-3 (Kāla Taraṅga) scope; this primitive serves the pre-D-3 window bundle.',
    category: 'temporal',
    live_tool: 'kala_bundle_get',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}' },
    fallback_face: 'kala_windows_get',
    known_gap: 'CR-66', // Phala wealth/domain anchors still zero — timing spine hand-assembled — OPEN, UPDATE evidence
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'lel_retrodiction',
    version: 1,
    definition: 'Joins LEL events to the signal/mechanism they retrodictively confirm, served as confirmation only (never as prediction input).',
    category: 'temporal',
    // CR-68 STALE-CORRECTED (SARVA-SIDDHI, 2026-07-24): shipped PR #688 (5f27d9d2, 2026-07-21) —
    // mechanism_retrodiction_get is a dedicated, registered, live-wired tool that joins LEL events
    // to the classical house-lord/dasha activation mechanism per house (fired_count, fired_events,
    // not_confirmed_events, unmapped_events — CONFIRMATION-ONLY, sealed pre-2020 test split).
    // Verified live for chart 482012f1 (7 mechanisms fired, e.g. 10th-house/Saturn career mechanism
    // fired 2x). Repoints this primitive's live_tool from mimamsa_lel_query (the raw LEL surface,
    // kept as fallback_face) to the purpose-built retrodiction surface.
    live_tool: 'mechanism_retrodiction_get',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}' },
    fallback_face: 'mimamsa_lel_query',
    known_gap: null, // CR-68 CLOSED — see live_tool comment above.
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'intervention_synthesis',
    version: 1,
    definition: 'Leverage-ranked remedy synthesis: domain load-bearing weight ÷ capability, forward-weighted by daśā runway.',
    category: 'remedy',
    live_tool: 'bodha_remedies_get',
    tool_args: { chart_id: '{chart_id}', leverage_ranked: true },
    fallback_face: 'bodha_remedies_get',
    known_gap: null, // CR-69 CLOSED (SARVA-SIDDHI W-3): query_remedies now reads leverage_ranked and ranks by L1 chart_vichara.leverage_index composite
    mandatory_tags: [],
    cr27_prevents: ['CR-27b'],
  },

  // ── General-purpose primitives (non-wealth-specific; support other intent classes) ──
  {
    primitive_id: 'positions_snapshot',
    version: 1,
    definition: 'Full natal position snapshot (rasi + degree + nakshatra + retrograde flags, all grahas).',
    category: 'structural',
    live_tool: 'ganita_positions_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'ganita_positions_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'dignity_scan',
    version: 1,
    definition: 'Per-graha dignity (exaltation/own/friend/neutral/enemy/debility) across the chart.',
    category: 'strength',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', mode: 'dignity' },
    fallback_face: 'ganita_strength_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'shadbala_rank',
    version: 1,
    definition: 'Ranked shadbala (six-fold strength) across all grahas — authoritative strength ordering.',
    category: 'strength',
    live_tool: 'ganita_strength_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'bodha_chart_digest_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'nakshatra_semantics',
    version: 1,
    definition: 'Nakshatra-semantic layer per graha: own-star, dispositor chains, tara bala, end-degree flags.',
    category: 'signal',
    live_tool: 'ganita_nakshatra_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'bodha_signals_get(signal_type_class=nakshatra_semantic)',
    known_gap: null, // CR-64 STALE-CORRECTED (SARVA-SIDDHI, 2026-07-24): shipped via the V-5 emitter (PR #585) — bodha_signals_get(signal_type_class=nakshatra_semantic) returns 9 salience-ranked rows live for chart 482012f1 (computed_salience populated, verification_pass_status=documented_approximation). RESIDUAL (not a route gap, does not block this closure): constituent_facts_array carries a 16.7% orphan rate on this chart (DEFECT-001, live-reported by the tool itself) — tracked separately, see cr_status.ts CLOSED_CRS note.
    mandatory_tags: [],
    cr27_prevents: ['CR-27d'],
  },
  {
    primitive_id: 'sensitive_degree_check',
    version: 1,
    definition: 'Sensitive-degree checks (mrityu-bhaga, gandanta, pushkara, kartari, 22nd drekkana) per graha.',
    category: 'structural',
    live_tool: 'ganita_sensitive_degrees_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'ganita_chart_facts_get',
    known_gap: null, // R-47 CLOSED — live.
    mandatory_tags: ['sensitive_degree'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'divisional_facts',
    version: 1,
    definition: 'Divisional-chart (varga) fact set for a named varga, including D2 varga_hora_class (Surya/Chandra hora semantics).',
    category: 'structural',
    live_tool: 'ganita_chart_facts_get',
    tool_args: { chart_id: '{chart_id}', divisional_chart: '{varga}' },
    fallback_face: null,
    known_gap: null, // CR-58 CLOSED_WITH_EVIDENCE (D-1.6 S-7) — varga_hora_class live.
    mandatory_tags: ['varga_hora_class'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'dasha_window',
    version: 1,
    definition: 'Bounded daśā window query (level-scoped, natally enriched: lord house/dignity/shadbala).',
    category: 'temporal',
    live_tool: 'ganita_dasha_periods_get',
    tool_args: { chart_id: '{chart_id}', level: '{level}', start: '{start}', end: '{end}' },
    fallback_face: 'ganita_dashas_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'yoga_activation_scan',
    version: 1,
    definition: 'Yoga activation by daśā — which catalog yogas are dated/active for the query horizon.',
    category: 'temporal',
    live_tool: 'kala_yoga_activation_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'kala_yoga_activation_get',
    known_gap: null, // CR-37 CLOSED (SARVA-SIDDHI T-3, 2026-07-24): ka_yojaka/ka_kalasutra rebuilt
    // with real dasha-derived activation windows for both charts (native 482012f1 YOGA 12/74→161/207
    // dated, DOSHA 203/422→926/1059; control 1c826d5a YOGA 0/66→168/213, DOSHA 0/155→760/820).
    // Live-verified 2026-07-24: kala_yoga_activation_get returns real chart_dashas-derived windows
    // (Anapha/Sasa/Vasi) for non-structural yogas; correctly-undated distribution yogas (Gola/Kedara/
    // Shoola/Yuga) now carry an honest always_on_reason discriminator instead of a bare null.
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'transit_window_scan',
    version: 1,
    definition: 'Gochara (transit) window scan for a bounded horizon.',
    category: 'temporal',
    live_tool: 'kala_windows_get',
    tool_args: { chart_id: '{chart_id}', start: '{start}', end: '{end}' },
    fallback_face: 'ref_planet_transit_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'muhurta_scan',
    version: 1,
    definition: 'Muhurta window scan for an intervention/undertaking horizon.',
    category: 'temporal',
    live_tool: 'kala_muhurta_get',
    tool_args: { chart_id: '{chart_id}', start: '{start}', end: '{end}' },
    fallback_face: 'kala_muhurta_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'mechanism_read',
    version: 1,
    definition: 'Named, valenced CGM subgraph read — chain/circuit motifs (e.g. the 10→8→12→10 specimen).',
    category: 'signal',
    live_tool: 'bodha_mechanisms_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'bodha_graph_subgraph_get',
    // CR-24 CLOSED (SARVA-SIDDHI planner-wiring follow-up, 2026-07-24): repointed from the raw
    // bodha_graph_subgraph_get path to the dedicated bodha_mechanisms_get serving face
    // (§N.6-compliant chain/circuit-first ordering). registry_data.ts + cr_status.ts both updated.
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: ['CR-27c'],
  },
  {
    primitive_id: 'arudha_read',
    version: 1,
    definition: 'Arudha-semantic read: AL conjunctions, A2/A11 placement, AL–bhāva relationships, ranked.',
    category: 'signal',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', mode: 'arudha' },
    fallback_face: 'bodha_signals_get(frame=arudha)',
    known_gap: null, // CR-61 STALE-CORRECTED (SARVA-SIDDHI, 2026-07-24): shipped via the V-5 emitter (PR #585) — bodha_signals_get(signal_type_class=arudha) returns 5 salience-ranked rows live for chart 482012f1 (AL-conjunction, A2/A11 tenancy, AL-bhava relation, real computed_salience). See cr_status.ts CLOSED_CRS note.
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'dosha_scan',
    version: 1,
    definition: 'Per-chart bespoke dosha detection with cancellation/bhaṅga checks.',
    category: 'doctrine',
    live_tool: 'ref_doshas_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'bodha_signals_get(signal_type_class=dosha_label)',
    known_gap: 'CR-73', // bespoke detection + cancellation still narrowed-open post D-1.6 stub-half close
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'statistical_context',
    version: 1,
    definition: 'Within-chart statistical rarity / calibration context for a signal or verdict (L5 structural-mode).',
    category: 'utility',
    live_tool: 'mimamsa_calibration_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'bodha_quality_get',
    known_gap: null, // L5 sealed in STRUCTURAL mode by design — not a defect (CLAUDE.md §E).
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    primitive_id: 'remedy_scan',
    version: 1,
    definition: 'Domain-scoped remedy scan joined to (weakest load-bearing graha × existing sādhana history × daśā runway).',
    category: 'remedy',
    live_tool: 'bodha_remedies_get',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}' },
    fallback_face: 'ref_remedies_chart_get',
    known_gap: null, // CR-67 CLOSED (SARVA-SIDDHI W-3): bo_upaya now populates associated_cdlm_cells_array, so the domain join returns real domain-joined resonances
    mandatory_tags: [],
    cr27_prevents: ['CR-27b'],
  },
  {
    primitive_id: 'contradiction_scan',
    version: 1,
    definition: 'Cross-signal contradiction/discovery scan.',
    category: 'utility',
    live_tool: 'bodha_discoveries_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'bodha_signals_get',
    known_gap: null,
    mandatory_tags: [],
    cr27_prevents: [],
  },

  // ── §B0.4 mandatory-surface primitives (D-1.5b/D-1.6 substrate deltas per §F0) ──
  {
    primitive_id: 'chalit_cusp_read',
    version: 1,
    definition: 'Chalit (bhāva-cuspal) chart facts: bhava_cusps, house_chalit, sandhi_flag.',
    category: 'structural',
    live_tool: 'ganita_chart_facts_get',
    tool_args: { chart_id: '{chart_id}', category: 'chalit' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: ['chalit_cusp'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'sudarshana_agreement_check',
    version: 1,
    definition: 'Sudarśana-cakra tri-lagna (rasi/Chandra/Sūrya) agreement signal.',
    category: 'signal',
    live_tool: 'bodha_signals_get',
    tool_args: { chart_id: '{chart_id}', signal_type_class: 'sudarshana_agreement' },
    fallback_face: 'ganita_chart_facts_get',
    known_gap: null,
    mandatory_tags: ['sudarshana_agreement'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'bhavat_bhavam_check',
    version: 1,
    definition: 'Bhāvāt-bhāvam (house-from-house) amplifier signal.',
    category: 'signal',
    live_tool: 'bodha_signals_get',
    tool_args: { chart_id: '{chart_id}', signal_type_class: 'bhavat_bhavam_amplifier' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: ['bhavat_bhavam'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'bhava_bala_scan',
    version: 1,
    definition: 'Bhāva-bala (house-strength) atoms per house (house_bhava_bala_total).',
    category: 'strength',
    live_tool: 'ganita_strength_get',
    tool_args: { chart_id: '{chart_id}', mode: 'bhava_bala' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: ['bhava_bala'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'ashtakavarga_scan',
    version: 1,
    definition: 'Ashtakavarga bindu-sign scan (ashtakavarga_bindu_sign) per graha/house.',
    category: 'structural',
    live_tool: 'ganita_chart_facts_get',
    tool_args: { chart_id: '{chart_id}', category: 'ashtakavarga' },
    fallback_face: 'ganita_structural_get',
    known_gap: null,
    mandatory_tags: ['ashtakavarga_bindu'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'karakamsa_read',
    version: 1,
    definition: 'Karakāṃśa (Ātmakāraka-in-D9) position read.',
    category: 'structural',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', mode: 'karakamsa' },
    fallback_face: 'ganita_special_lagnas_get',
    known_gap: null,
    mandatory_tags: ['karakamsa'],
    cr27_prevents: [],
  },
  {
    primitive_id: 'kp_cusp_sublord_read',
    version: 1,
    definition: 'Real KP cusps + sub-lords (bhāva cuspal sub-lord chain per KP).',
    category: 'structural',
    // CR-30 CLOSED (SARVA-SIDDHI W-4 D-4): dedicated first-class KP cusp/sub-lord face shipped
    // — ganita_kp_cusps_get (→ marsys://tool/L1/get_kp_cusps). Serves the full per-cusp KP chain
    // (sign/star/sub/sub_sub/prana lords + significators + cusp degrees) + natal ruling planets
    // over the already-stored L1 facts (no new computation). Was previously reachable only via
    // the raw ganita_chart_facts_get category route; now a first-class primitive face.
    live_tool: 'ganita_kp_cusps_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'ganita_chart_facts_get',
    known_gap: null,
    mandatory_tags: ['kp_cusp_sublord'],
    cr27_prevents: ['CR-36'],
  },

  // ── VIDHI-PŪRṆATĀ P-3 (F2/F3/F4 floor-completeness, 2026-07-23) — three new primitives ──
  // All three re-probed LIVE at P-3 against chart 482012f1 and confirmed data-backed:
  //   ganita_ayurdaya_get → 26 rows (AMSAYU/PINDAYU/NISARGAYU totals, applicable_method=pindayu,
  //     maraka_grahas=Mars,Saturn,Venus); ganita_medical_get → per-graha dosha/organ/body watch
  //     (e.g. Saturn: vata; teeth/bones/joints/legs; BPHS Ch.18); ganita_condition_get facet=karakas
  //     → bhava_arudha.BHAVA_ARUDHA_UPA (house_d1=3, sign Cancer) + arudha_pada.ARUDHA_A12 present.
  {
    // F4 (health): the āyurdāya/longevity spine the audit found missing from health_deepdive.
    primitive_id: 'ayurdaya_read',
    version: 1,
    definition:
      'Classical longevity (Āyurdāya) computation: Piṇḍa/Aṃśa/Naisarga āyus totals + longevity band (alpāyu/madhyāyu/pūrṇāyu), applicable_method, and the maraka grahas — a longevity-band + maraka-load read, NOT a death prediction.',
    category: 'doctrine',
    live_tool: 'ganita_ayurdaya_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: null,
    known_gap: null, // data-backed live (P-3 probe: 26 rows, maraka_grahas served).
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // F4 (health): per-graha Vaidya-phala watch-indications, the medical layer the audit wanted.
    primitive_id: 'medical_read',
    version: 1,
    definition:
      'Vaidya-phala medical watch-indications per graha: dosha aggravated (vāta/pitta/kapha), organ_watch, body_part_watch, and indication tier, with BPHS Ch.18 / Aṣṭāṅga Hṛdayam citations. NOT a diagnosis — classical watch-indications only.',
    category: 'structural',
    live_tool: 'ganita_medical_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'ref_sign_medical_get',
    known_gap: null, // data-backed live (P-3 probe: per-graha dosha/organ/body watch + citations).
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // F3 (marriage): Upapada Lagna read. NOTE ON NAMING — the P-3 task called for "a new arudha_read
    // primitive scoped to UPA"; it is authored here as a DISTINCT primitive_id (`upapada_read`)
    // rather than overloading the existing generic `arudha_read` (which declares the mode:'arudha'
    // route) because (a) primitive_ids must be unique and (b) the P-0 ledger + P-3 live probe confirm
    // UPA data resolves specifically via `ganita_condition_get facet=karakas` (bhava_arudha.UPA /
    // arudha_pada.ARUDHA_A12), a different route than generic arudha_read declares. The 2nd-from-UL
    // is folded in as an ANSWERER-SIDE derivation off the UPA house (deterministic bhava-from-bhava
    // over the data-backed UPA position — like P-2's from-karakāṃśa-12th) — NOT a separate tool, so
    // no known_gap is minted for it. The raw arudha positions are data-backed; only their salience
    // RANKING is the outstanding gap (CR-61, OPEN), inherited from arudha_read.
    primitive_id: 'upapada_read',
    version: 1,
    definition:
      'Upapada Lagna (UL/UPA) read for the marriage/relationship domain: the UPA bhava-arudha position (sign + house) and Arudha A12 (ARUDHA_A12), plus the 2nd-from-UL bhāva as an answerer-side derivation off the UPA house (sustenance / longevity-of-union significator). Raw arudha positions are data-backed; salience ranking shipped (CR-61, see known_gap).',
    category: 'signal',
    live_tool: 'ganita_condition_get',
    tool_args: { chart_id: '{chart_id}', facet: 'karakas' },
    fallback_face: 'bodha_signals_get(frame=arudha)',
    known_gap: null, // CR-61 STALE-CORRECTED (SARVA-SIDDHI, 2026-07-24): arudha ranking now live via bodha_signals_get(signal_type_class=arudha) — see arudha_read's known_gap note above for the verified evidence.
    mandatory_tags: [],
    cr27_prevents: [],
  },

  // ── VIDHI-PŪRṆATĀ P-3b elevation primitives (E-0/E-1/E-2/E-7, 2026-07-23) — 7 new atoms ──
  // All re-probed LIVE at P-3b against chart 482012f1 (2026-07-23):
  //   bodha_chart_digest_get   → whole-chart UCD digest (signal/yoga/dosha counts, contradiction_count,
  //       weakest_graha=Venus via shadbala re-derivation, composite-ranked entity_profiles per graha +
  //       BHAVA_1..12, convergence_domains, top_signals) — data-backed, E-0 lead.
  //   ganita_yoga_firings_get  → 12 fired yogas incl. dhana_yoga_house_lords / raja_yoga_kendra_trikona /
  //       neecha_bhanga_raja_yoga (bhanga_active) — data-backed firings-authoritative surface, E-0.
  //   synth_tail_divergence_get→ bottom-decile dissent/tail signals w/ salience_pctl — data-backed, E-7.
  //   phala_predictive_anchors_get → 6 OPEN filed predictions (domain/window/falsifier/posterior) — E-2.
  //   gochara_{activation,forecast,election_avoidance}_get → REGISTERED + LIVE with a correct DR-16
  //       envelope, but backing_data_reachable:false (DATABASE_URL not set — require direct DB) on every
  //       P-0 + P-3b probe → known_gap CR-131 (reachability), surfaced dark, never faked (brief §0).
  {
    // E-0 (Pūrṇa-Ādhāra): the whole-chart digest/rollup that LEADS the foundational floor — the
    // densest, verdict-bearing layer served FIRST (§N.6), hard_floor-protected at the floor level.
    // Alias of get_chart_orientation (L2 UCD): rolls up all 12 bhāvas + graha strength + contradictions.
    primitive_id: 'chart_digest_read',
    version: 1,
    definition:
      'Whole-chart UCD digest (bodha_chart_digest_get): msr_signal/yoga/dosha counts, contradiction_count, weakest_graha (shadbala-derived), composite-ranked entity_profiles (one row per graha and per BHAVA_1..12), convergence_domains, and top signals — the layered digest/rollup that leads the Pūrṇa-Ādhāra foundational floor.',
    category: 'structural',
    live_tool: 'bodha_chart_digest_get',
    tool_args: { chart_id: '{chart_id}', mode: 'summary' },
    fallback_face: 'get_chart_orientation',
    known_gap: null, // data-backed live (P-3b probe: full digest + entity_profiles + convergence_domains).
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // E-0: the firings-AUTHORITATIVE yoga surface for the foundation — ALL fired yogas (not the
    // house-lord family filter dhana_yoga_scan applies, and NOT carrying dhana_yoga_scan's separate
    // CR-56 register question). Routes to ganita_yoga_firings_get, which P-0 + P-3b confirmed serves
    // 12 fired yogas (dhana_yoga_house_lords, raja_yoga_kendra_trikona, neecha_bhanga_raja_yoga w/
    // bhanga_active, budha_aditya, sarasvati, …) with per-varga BPHS grounds.
    primitive_id: 'yoga_firings_read',
    version: 1,
    definition:
      'Firings-authoritative yoga surface (ganita_yoga_firings_get): every FIRED yoga for the chart (dhana / raja / nīcha-bhaṅga / pañca-mahāpuruṣa / budha-āditya / sarasvatī …) with fire_reason, per-varga grounds and strength — the "confirmed firings" layer (never a catalog/label match) the whole-chart foundation reads.',
    category: 'doctrine',
    live_tool: 'ganita_yoga_firings_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'ganita_yogas_get',
    known_gap: null, // data-backed live (P-0/P-3b: 12 fired yogas, firings-authoritative surface).
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // E-1 (D-5 temporal engine): current-date activation of the signed λ_e gochara field.
    primitive_id: 'gochara_activation_read',
    version: 1,
    definition:
      'Gochara (D-5) activation view (gochara_activation_get): kala_gochara_windows rows ACTIVE on the current date — "is this event-class configuration firing right now?" over the signed λ_e intensity field, carrying the DR-16 honest-clarity + structural_prior envelope. Bind at horizon=current in every deepdive machine band.',
    category: 'temporal',
    live_tool: 'gochara_activation_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'kala_windows_get',
    known_gap: 'CR-131', // registered+live but backing_data_reachable:false via the MCP path (DATABASE_URL) — dark, not faked
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // E-1: forward-looking multi-year forecast over the gochara field. Bind where horizon=multi_year.
    primitive_id: 'gochara_forecast_read',
    version: 1,
    definition:
      'Gochara (D-5) forecast view (gochara_forecast_get): kala_gochara_windows overlapping a forward date range (point/interval/chain shapes, is_irreversibility_milestone flagged) over the signed λ_e field, DR-16-enveloped — the forward temporal spine. Bind where horizon=multi_year.',
    category: 'temporal',
    live_tool: 'gochara_forecast_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'kala_windows_get',
    known_gap: 'CR-131', // registered+live but backing_data_reachable:false via the MCP path — dark, not faked
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // E-1: election-avoidance (adverse-window) view — binds when the question is an undertaking/muhurta ask.
    primitive_id: 'election_read',
    version: 1,
    definition:
      'Gochara (D-5) election-avoidance view (gochara_election_avoidance_get): ADVERSE kala_gochara_windows to avoid for an undertaking, each carrying the full DR-16 payload (clarity_statement, probabilistic framing, falsifier, mitigation-paired BPHS remedy, confidence_disclosure). Bind when the question is an undertaking / timing / muhūrta ask.',
    category: 'temporal',
    live_tool: 'gochara_election_avoidance_get',
    tool_args: { chart_id: '{chart_id}' },
    fallback_face: 'kala_muhurta_get',
    known_gap: 'CR-131', // registered+live but backing_data_reachable:false via the MCP path — dark, not faked
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // E-2 (prospective ledger): the OPEN filed falsifiable predictions for the question's domain.
    // Confirmation / disclosure ONLY — this primitive NEVER writes calibration (mimamsa_outcome_record
    // and the retired record_outcome path are out of scope; CR-128).
    //
    // SARVA-SIDDHI W-2 P-1 (2026-07-24) — live_tool REPOINTED phala_predictive_anchors_get →
    // standing_predictions_read. The prior wiring was the exact PRE_DARPANA_READINESS B-2 FAIL:
    // this primitive is DEFINED as a "prospective-ledger read", but phala_predictive_anchors_get
    // reads L4 phala_anchors (deterministic ph_nimitta rows), NOT the LIVE prospective ledger
    // (brahma_prospective_ledger, migration 458). For a wealth plan phala_anchors is empty, so the
    // native's genuinely-filed standing predictions (Sat–Jupiter Apr–Aug 2027, Ketu-MD shape,
    // Venus-MD 2034 — all filed 2026-07-19, D-4a Lane A-4, provenance intact in the ledger) never
    // surfaced. standing_predictions_read → marsys://tool/L4/query_prospective_ledger reads the
    // table this primitive was always meant to read. phala_predictive_anchors_get is kept as the
    // fallback_face (still a valid, distinct L4 predictive-anchors surface).
    primitive_id: 'standing_predictions_read',
    version: 2,
    definition:
      'Standing prospective-ledger read (standing_predictions_read → brahma_prospective_ledger): the OPEN filed, falsifiable predictions for the domain — each with claim, event_class, temporal shape + window/milestones, confidence, a MANDATORY FALSIFIER, generator_class (reading_synthesis | engine | native_intuition | anchor_engine) and source_citation. Non-domain-matching open predictions are still returned (other_domain_predictions) — never silently dropped. Makes every reading falsifier-bearing by default. Confirmation/disclosure ONLY — never a calibration or filing write (§11: predictions exist by explicit filing only).',
    category: 'temporal',
    live_tool: 'standing_predictions_read',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}' },
    fallback_face: 'phala_predictive_anchors_get',
    known_gap: null, // data-backed live: reads brahma_prospective_ledger (migration 458) via query_prospective_ledger.
    mandatory_tags: [],
    cr27_prevents: [],
  },
  {
    // E-7 (insight band): rarity / where-THIS-chart-diverges-from-the-typical — the beyond-acharya carve.
    primitive_id: 'tail_divergence_read',
    version: 1,
    definition:
      'Tail-divergence read (synth_tail_divergence_get): the bottom-decile dissent/tail signals (BA-P4 70/20/10 attention budget) that contradict or diverge from the dominant synthesis — the rarity / "where THIS chart departs from the typical" surface the insight band mines for the non-obvious, beyond-acharya finding.',
    category: 'signal',
    live_tool: 'synth_tail_divergence_get',
    tool_args: { chart_id: '{chart_id}', domain: '{domain}' },
    fallback_face: 'bodha_discoveries_get',
    known_gap: null, // data-backed live (P-3b probe: tail_signals with salience_pctl + classical sources).
    mandatory_tags: [],
    cr27_prevents: [],
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────────────
// VIDHI-PŪRṆATĀ P-3b — shared deepdive elevation tail (E-1/E-2/E-5/E-6/E-7)
// ─────────────────────────────────────────────────────────────────────────────────────

/**
 * The elevation tail every `*_deepdive` machine band ends with (VIDHI-PŪRṆATĀ P-3b). Ordered
 * AFTER a floor's own domain-specific machine items (dasha spine, taraṅga curve,
 * intervention/remedy). `domain` scopes the domain-bearing primitives; `from` is the first
 * `order` value the caller passes (the next free order after its own machine items). Pure data —
 * the compiler / codegen mirror / registry-parity test all see the fully-expanded arrays.
 *
 *   E-1  gochara_activation_read (horizon=current) · gochara_forecast_read (horizon=multi_year) ·
 *        election_read (undertaking asks) — the D-5 temporal engine, all CR-131-dark (reachability).
 *   E-2  standing_predictions_read — the domain's OPEN filed falsifiable predictions (live).
 *   E-6  lel_retrodiction — domain-scoped personal retrodiction (confirmation-only).
 *   E-7  INSIGHT BAND (hard_floor-protected, §N.6 — never the rows a budget trim sacrifices first):
 *        contradiction_scan (also satisfies E-5 cross-domain awareness) · tail_divergence_read ·
 *        mechanism_read · statistical_context — the beyond-acharya insight carve that closes the plan.
 */
function elevationTail(domain: string, from: number): FloorItem[] {
  return [
    // E-1 — D-5 temporal engine (all dark, CR-131 reachability; asked-for, never faked).
    { primitive_id: 'gochara_activation_read', order: from, band: 'machine_band' },
    { primitive_id: 'gochara_forecast_read', order: from + 1, band: 'machine_band' },
    { primitive_id: 'election_read', order: from + 2, band: 'machine_band' },
    // E-1 (T-5 fix, A-6(b)): the daśā-driven yoga-activation surface (kala_yoga_activation_get).
    // Previously a REGISTERED primitive wired into NO floor, so CR-37 (yoga-activation dating)
    // could never reach a completeness receipt regardless of the tool's own honest
    // undated_activation_count. Binding it into the shared E-1 temporal band puts CR-37's
    // known_gap into every deepdive + foundation receipt (dark, disclosed, never faked).
    { primitive_id: 'yoga_activation_scan', order: from + 3, band: 'machine_band' },
    // E-2 — prospective ledger: OPEN filed predictions for the domain (confirmation-only, live).
    { primitive_id: 'standing_predictions_read', order: from + 4, band: 'machine_band', args_override: { domain } },
    // E-6 — personal retrodiction, domain-scoped (confirmation-only framing preserved).
    { primitive_id: 'lel_retrodiction', order: from + 5, band: 'machine_band', args_override: { domain } },
    // ── E-7 INSIGHT BAND (hard_floor: the beyond-acharya carve; §N.6-protected) ──
    { primitive_id: 'contradiction_scan', order: from + 6, band: 'machine_band', hard_floor: true }, // + E-5
    { primitive_id: 'tail_divergence_read', order: from + 7, band: 'machine_band', args_override: { domain }, hard_floor: true },
    { primitive_id: 'mechanism_read', order: from + 8, band: 'machine_band', hard_floor: true },
    { primitive_id: 'statistical_context', order: from + 9, band: 'machine_band', hard_floor: true },
  ];
}

// ─────────────────────────────────────────────────────────────────────────────────────
// Floors
// ─────────────────────────────────────────────────────────────────────────────────────

/**
 * floor(wealth_deepdive) — matches DOCTRINE_CAMPAIGN_DESIGN_v1_0.md §3's worked example
 * verbatim for its 14 named atoms (items 1-14 below map 1:1 to the design doc's
 * bhava_condition(2) · bhavesha_condition(2) · karaka_condition(Jupiter) · from_moon_view ·
 * varga_ratification(D2,D9,D11) · special_lagna_read(Indu,Sree) · chara_karaka_read(AmK) ·
 * dhana_yoga_scan · nbry_scan(per-varga) · wealth_loss_mechanism_scan ·
 * dasha_spine+lord_capability · taranga_curve(wealth) · lel_retrodiction(wealth) ·
 * intervention_synthesis(leverage_ranked)); items 15+ are this lane's §B0.4-mandatory and
 * CR-27-corpus additions, making this floor a superset that alone satisfies every §B0.4
 * tag and every CR-27 instance for the gate's flagship (wealth) domain.
 */
const WEALTH_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 2 } },
  { primitive_id: 'bhavesha_condition', order: 2, band: 'acharya_floor', args_override: { house: 2 } },
  { primitive_id: 'karaka_condition', order: 3, band: 'acharya_floor', args_override: { karaka: 'jupiter' } },
  { primitive_id: 'from_moon_view', order: 4, band: 'acharya_floor' },
  { primitive_id: 'chalit_cusp_read', order: 5, band: 'acharya_floor' },
  { primitive_id: 'bhava_bala_scan', order: 6, band: 'acharya_floor' },
  { primitive_id: 'ashtakavarga_scan', order: 7, band: 'acharya_floor' },
  { primitive_id: 'sensitive_degree_check', order: 8, band: 'acharya_floor' },
  { primitive_id: 'divisional_facts', order: 9, band: 'acharya_floor', args_override: { varga: 'D2' } },
  {
    primitive_id: 'varga_ratification',
    order: 10,
    band: 'acharya_floor',
    args_override: { vargas: ['D2', 'D9', 'D11'] },
  },
  { primitive_id: 'karakamsa_read', order: 11, band: 'acharya_floor' },
  { primitive_id: 'kp_cusp_sublord_read', order: 12, band: 'acharya_floor' },
  {
    primitive_id: 'special_lagna_read',
    order: 13,
    band: 'acharya_floor',
    args_override: { lagnas: ['indu', 'sree'] },
  },
  { primitive_id: 'chara_karaka_read', order: 14, band: 'acharya_floor', args_override: { chara_karaka: 'AmK' } },
  { primitive_id: 'dhana_yoga_scan', order: 15, band: 'acharya_floor', args_override: { domain: 'wealth' } },
  { primitive_id: 'nbry_scan', order: 16, band: 'acharya_floor' },
  { primitive_id: 'wealth_loss_mechanism_scan', order: 17, band: 'acharya_floor', args_override: { domain: 'wealth' } },
  { primitive_id: 'sudarshana_agreement_check', order: 18, band: 'acharya_floor' },
  { primitive_id: 'bhavat_bhavam_check', order: 19, band: 'acharya_floor' },
  { primitive_id: 'nakshatra_semantics', order: 20, band: 'acharya_floor' },
  // P-3b: mechanism_read + statistical_context relocated to the E-7 insight band (elevationTail);
  // lel_retrodiction likewise now arrives via the tail (still a design-§3 atom — present, just re-banded).
  { primitive_id: 'dasha_spine_lord_capability', order: 21, band: 'machine_band' },
  { primitive_id: 'taranga_curve', order: 22, band: 'machine_band', args_override: { domain: 'wealth' } },
  { primitive_id: 'intervention_synthesis', order: 23, band: 'machine_band', args_override: { domain: 'wealth' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=wealth; orders 24-32).
  ...elevationTail('wealth', 24),
];

const CAREER_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 10 } },
  { primitive_id: 'bhavesha_condition', order: 2, band: 'acharya_floor', args_override: { house: 10 } },
  { primitive_id: 'karaka_condition', order: 3, band: 'acharya_floor', args_override: { karaka: 'sun' } },
  { primitive_id: 'divisional_facts', order: 4, band: 'acharya_floor', args_override: { varga: 'D10' } },
  { primitive_id: 'divisional_facts', order: 5, band: 'acharya_floor', args_override: { varga: 'D9' } },
  { primitive_id: 'varga_ratification', order: 6, band: 'acharya_floor', args_override: { vargas: ['D1', 'D9', 'D10'] } },
  // §B0.4 mandatory-surface floor-completeness additions (RETRIEVAL_PLANE_ELEVATION_PLAN §R-3.3):
  // brings career to the full §B0.4 tag set held by the flagship wealth floor.
  { primitive_id: 'chalit_cusp_read', order: 7, band: 'acharya_floor' },
  { primitive_id: 'bhava_bala_scan', order: 8, band: 'acharya_floor' },
  { primitive_id: 'ashtakavarga_scan', order: 9, band: 'acharya_floor' },
  { primitive_id: 'sensitive_degree_check', order: 10, band: 'acharya_floor' },
  { primitive_id: 'karakamsa_read', order: 11, band: 'acharya_floor' },
  { primitive_id: 'kp_cusp_sublord_read', order: 12, band: 'acharya_floor' },
  { primitive_id: 'sudarshana_agreement_check', order: 13, band: 'acharya_floor' },
  { primitive_id: 'bhavat_bhavam_check', order: 14, band: 'acharya_floor' },
  { primitive_id: 'dhana_yoga_scan', order: 15, band: 'acharya_floor', args_override: { domain: 'career', family: 'raja' } },
  { primitive_id: 'nakshatra_semantics', order: 16, band: 'acharya_floor' },
  // VIDHI-PŪRṆATĀ P-3 (F7 career-completeness, 2026-07-23): the Amātyakāraka (AmK) — the Jaimini
  // significator of profession/minister — was absent from the career floor. Data-backed via
  // ganita_condition_get facet=karakas (chara-karaka category, two_pass_verified).
  { primitive_id: 'chara_karaka_read', order: 17, band: 'acharya_floor', args_override: { chara_karaka: 'AmK' } },
  // P-3b: mechanism_read relocated to the E-7 insight band (elevationTail) — present, re-banded.
  { primitive_id: 'dasha_spine_lord_capability', order: 18, band: 'machine_band' },
  { primitive_id: 'taranga_curve', order: 19, band: 'machine_band', args_override: { domain: 'career' } },
  { primitive_id: 'intervention_synthesis', order: 20, band: 'machine_band', args_override: { domain: 'career' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=career; orders 21-29).
  ...elevationTail('career', 21),
];

const HEALTH_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 6 } },
  { primitive_id: 'bhavesha_condition', order: 2, band: 'acharya_floor', args_override: { house: 6 } },
  { primitive_id: 'karaka_condition', order: 3, band: 'acharya_floor', args_override: { karaka: 'mars' } },
  { primitive_id: 'dignity_scan', order: 4, band: 'acharya_floor' },
  { primitive_id: 'sensitive_degree_check', order: 5, band: 'acharya_floor' },
  { primitive_id: 'divisional_facts', order: 6, band: 'acharya_floor', args_override: { varga: 'D6' } },
  { primitive_id: 'dosha_scan', order: 7, band: 'acharya_floor' },
  // §B0.4 mandatory-surface floor-completeness additions (RETRIEVAL_PLANE_ELEVATION_PLAN §R-3.3):
  // brings health to the full §B0.4 tag set held by the flagship wealth floor.
  // varga_ratification carries the varga_ratification_divergence tag; D1/D6/D9 for roga vs. stamina delivery.
  { primitive_id: 'varga_ratification', order: 8, band: 'acharya_floor', args_override: { vargas: ['D1', 'D6', 'D9'] } },
  { primitive_id: 'chalit_cusp_read', order: 9, band: 'acharya_floor' },
  { primitive_id: 'bhava_bala_scan', order: 10, band: 'acharya_floor' },
  { primitive_id: 'ashtakavarga_scan', order: 11, band: 'acharya_floor' },
  { primitive_id: 'karakamsa_read', order: 12, band: 'acharya_floor' },
  { primitive_id: 'kp_cusp_sublord_read', order: 13, band: 'acharya_floor' },
  { primitive_id: 'sudarshana_agreement_check', order: 14, band: 'acharya_floor' },
  { primitive_id: 'bhavat_bhavam_check', order: 15, band: 'acharya_floor' },
  // ── VIDHI-PŪRṆATĀ P-3 (F4 health-completeness, 2026-07-23) ──
  // F4 (longevity + medical + 8th + Saturn): the āyurdāya longevity spine, the per-graha Vaidya
  // medical watch, the 8th (āyuṣ / longevity) bhāva, and Saturn as the chronic/longevity kāraka.
  { primitive_id: 'ayurdaya_read', order: 16, band: 'acharya_floor' },
  { primitive_id: 'medical_read', order: 17, band: 'acharya_floor' },
  { primitive_id: 'bhava_condition', order: 18, band: 'acharya_floor', args_override: { house: 8 } },
  { primitive_id: 'karaka_condition', order: 19, band: 'acharya_floor', args_override: { karaka: 'saturn' } },
  // VIDHI-PŪRṆATĀ (F4 health-floor completeness, 2026-07-23): the Moon as mind/mental-health kāraka —
  // required by STATIC_VIDHI_AUDIT_v1_0.md F4 + brief §2 P-3's health floor. Data-backed live via the
  // same karaka_condition primitive that already routes mars/saturn/jupiter here (known_gap NULL).
  { primitive_id: 'karaka_condition', order: 20, band: 'acharya_floor', args_override: { karaka: 'moon' } },
  { primitive_id: 'dasha_spine_lord_capability', order: 21, band: 'machine_band' },
  { primitive_id: 'taranga_curve', order: 22, band: 'machine_band', args_override: { domain: 'health' } },
  { primitive_id: 'remedy_scan', order: 23, band: 'machine_band', args_override: { domain: 'health' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=health; orders 24-32).
  ...elevationTail('health', 24),
];

const MARRIAGE_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 7 } },
  { primitive_id: 'bhavesha_condition', order: 2, band: 'acharya_floor', args_override: { house: 7 } },
  { primitive_id: 'karaka_condition', order: 3, band: 'acharya_floor', args_override: { karaka: 'venus' } },
  { primitive_id: 'divisional_facts', order: 4, band: 'acharya_floor', args_override: { varga: 'D9' } },
  { primitive_id: 'varga_ratification', order: 5, band: 'acharya_floor', args_override: { vargas: ['D1', 'D9'] } },
  { primitive_id: 'dosha_scan', order: 6, band: 'acharya_floor' },
  { primitive_id: 'karakamsa_read', order: 7, band: 'acharya_floor' },
  // §B0.4 mandatory-surface floor-completeness additions (RETRIEVAL_PLANE_ELEVATION_PLAN §R-3.3):
  // brings marriage to the full §B0.4 tag set held by the flagship wealth floor.
  { primitive_id: 'chalit_cusp_read', order: 8, band: 'acharya_floor' },
  { primitive_id: 'bhava_bala_scan', order: 9, band: 'acharya_floor' },
  { primitive_id: 'ashtakavarga_scan', order: 10, band: 'acharya_floor' },
  { primitive_id: 'sensitive_degree_check', order: 11, band: 'acharya_floor' },
  { primitive_id: 'kp_cusp_sublord_read', order: 12, band: 'acharya_floor' },
  { primitive_id: 'sudarshana_agreement_check', order: 13, band: 'acharya_floor' },
  { primitive_id: 'bhavat_bhavam_check', order: 14, band: 'acharya_floor' },
  // ── VIDHI-PŪRṆATĀ P-3 (F2/F3 marriage-completeness, 2026-07-23) ──
  // F3 (Jaimini spouse tools + kuṭumba/māṅgalya bhāvas): 2nd (kuṭumba — family into which one
  // marries), 8th (māṅgalya / longevity-of-union), Dārā-kāraka (DK — the Jaimini significator of
  // spouse), and the Upapada Lagna read (UL + 2nd-from-UL derived answerer-side).
  { primitive_id: 'bhava_condition', order: 15, band: 'acharya_floor', args_override: { house: 2 } },
  { primitive_id: 'bhava_condition', order: 16, band: 'acharya_floor', args_override: { house: 8 } },
  { primitive_id: 'chara_karaka_read', order: 17, band: 'acharya_floor', args_override: { chara_karaka: 'DK' } },
  { primitive_id: 'upapada_read', order: 18, band: 'acharya_floor' },
  { primitive_id: 'dasha_spine_lord_capability', order: 19, band: 'machine_band' },
  // F2 (timing spine): marriage previously had NO domain-scoped temporal window bundle. taranga_curve
  // carries CR-66 (phala domain anchors still zero) — dark, surfaced in the receipt, never faked.
  { primitive_id: 'taranga_curve', order: 20, band: 'machine_band', args_override: { domain: 'marriage' } },
  { primitive_id: 'remedy_scan', order: 21, band: 'machine_band', args_override: { domain: 'marriage' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=marriage; orders 22-30).
  ...elevationTail('marriage', 22),
];

/** Narrow, structure-depth — "show me my D1" canonical example (design §3 §8). */
const STRUCTURE_READ_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'positions_snapshot', order: 1, band: 'acharya_floor' },
  { primitive_id: 'dignity_scan', order: 2, band: 'acharya_floor' },
  { primitive_id: 'shadbala_rank', order: 3, band: 'acharya_floor' },
  { primitive_id: 'chalit_cusp_read', order: 4, band: 'acharya_floor' },
  { primitive_id: 'bhava_bala_scan', order: 5, band: 'acharya_floor' },
];

/** Panoramic-breadth — "unleash my financial potential"-shaped wide sweep, domain-agnostic. */
const PANORAMIC_BREADTH_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'positions_snapshot', order: 1, band: 'acharya_floor' },
  { primitive_id: 'shadbala_rank', order: 2, band: 'acharya_floor' },
  { primitive_id: 'nakshatra_semantics', order: 3, band: 'acharya_floor' },
  { primitive_id: 'arudha_read', order: 4, band: 'acharya_floor' },
  { primitive_id: 'mechanism_read', order: 5, band: 'acharya_floor' },
  { primitive_id: 'contradiction_scan', order: 6, band: 'machine_band' },
  { primitive_id: 'statistical_context', order: 7, band: 'machine_band' },
  { primitive_id: 'dasha_spine_lord_capability', order: 8, band: 'machine_band' },
];

/** Retrieval-only — minimal, single-fact-shaped question (design §3 §8 canonical example). */
const RETRIEVAL_ONLY_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'positions_snapshot', order: 1, band: 'acharya_floor' },
];

/**
 * E-0 (Pūrṇa-Ādhāra foundational floor, VIDHI-PŪRṆATĀ P-3b). "When the planner does not recognize
 * the territory, it lays the entire foundation on the table and lets the intelligence judge."
 * Replaces the thin pre-P-3b 6-item general_synthesis fallback with a comprehensive, LAYERED
 * whole-chart foundation (BRIEF_VIDHI_PURNATA_v1_0 §B E-0). Served digest-FIRST per §N.6: the
 * chart_digest_read lead (hard_floor) is the densest verdict-bearing rollup — it carries the
 * all-12-bhāva + per-graha-strength + contradiction rollup (entity_profiles BHAVA_1..12), so the
 * foundation LEADS with that layer and provides drill pointers (the full per-bhāva reads) rather
 * than dumping 24 raw bhava/bhavesha rows (the "undifferentiated dump" §N.6 forbids). Everything
 * an acharya lays out for an unknown chart is PRESENT and prioritized: positions+degrees,
 * dignity/shadbala/bhava-bala, the lagna anchor + bhāvat-bhāvam (aspects/argala structure), all
 * chara-karakas + arudhas incl. Upapada, sensitive degrees, the core cross-domain vargas
 * (D9+D2/D10/D7/D20), the firings-authoritative yoga surface, the full dasha spine, and the
 * E-1..E-7 elevation tail (gochara activation/forecast/election, standing predictions, LEL
 * retrodiction, and the hard_floor-protected E-7 insight band — contradiction/tail-divergence/
 * mechanism/statistical).
 *
 * REUSABLE BAND (E-0): exported so any intent's floor can splice `...FOUNDATION_BAND_ITEMS` as a
 * foundation layer ("expose the same set as a foundation band any intent can request").
 *
 * DUAL GATE (E-0, held both directions): this floor is the UNCLASSIFIABLE-question path
 * (general_synthesis) — a safety net, NEVER the default for a CLASSIFIED question (a wealth
 * question routes to wealth_deepdive, etc., via scope_resolver + compiler DOMAIN_TO_INTENT). It
 * is deliberately NOT a domain deepdive, so the E-4 union never replaces a classified floor with
 * it and never treats it as a union base.
 */
export const FOUNDATION_BAND_ITEMS: readonly FloorItem[] = [
  // ── Layer 1 (densest, hard_floor): the whole-chart digest / rollup / verdict lead (§N.6) ──
  { primitive_id: 'chart_digest_read', order: 1, band: 'acharya_floor', hard_floor: true },
  // ── Layer 2: whole-chart structural + strength foundation ──
  { primitive_id: 'positions_snapshot', order: 2, band: 'acharya_floor' },
  { primitive_id: 'dignity_scan', order: 3, band: 'acharya_floor' },
  { primitive_id: 'shadbala_rank', order: 4, band: 'acharya_floor' },
  { primitive_id: 'bhava_bala_scan', order: 5, band: 'acharya_floor' },
  // Lagna anchor + house-from-house. Aspects/parivartana/argala structure is carried by
  // bhava_condition's aspects-received + bhavat_bhavam + the tail's CGM mechanism_read (no
  // fabricated argala primitive is minted); the other 11 bhāvas roll up in chart_digest_read
  // with drill pointers, per §N.6 digest-first layering.
  { primitive_id: 'bhava_condition', order: 6, band: 'acharya_floor', args_override: { house: 1 } },
  { primitive_id: 'bhavat_bhavam_check', order: 7, band: 'acharya_floor' },
  { primitive_id: 'sensitive_degree_check', order: 8, band: 'acharya_floor' },
  // ── Layer 3: Jaimini kārakas + arudhas (incl. Upapada Lagna) ──
  { primitive_id: 'chara_karaka_read', order: 9, band: 'acharya_floor', args_override: { chara_karaka: 'AK' } },
  { primitive_id: 'karakamsa_read', order: 10, band: 'acharya_floor' },
  { primitive_id: 'arudha_read', order: 11, band: 'acharya_floor' },
  { primitive_id: 'upapada_read', order: 12, band: 'acharya_floor' },
  // ── Layer 4: firings-authoritative yogas + core cross-domain vargas (D9+D2/D10/D7/D20 digest) ──
  { primitive_id: 'yoga_firings_read', order: 13, band: 'acharya_floor' },
  { primitive_id: 'divisional_facts', order: 14, band: 'acharya_floor', args_override: { varga: 'D9' } },
  { primitive_id: 'divisional_facts', order: 15, band: 'acharya_floor', args_override: { varga: 'D2' } },
  { primitive_id: 'divisional_facts', order: 16, band: 'acharya_floor', args_override: { varga: 'D10' } },
  { primitive_id: 'divisional_facts', order: 17, band: 'acharya_floor', args_override: { varga: 'D7' } },
  { primitive_id: 'divisional_facts', order: 18, band: 'acharya_floor', args_override: { varga: 'D20' } },
  // ── Machine band: the full dasha spine + the E-1..E-7 elevation tail (domain=general; 20-28) ──
  { primitive_id: 'dasha_spine_lord_capability', order: 19, band: 'machine_band' },
  ...elevationTail('general', 20),
];

/** General fallback = the Pūrṇa-Ādhāra foundation (E-0). The unclassifiable-question path now
 *  compiles the deepest floor of all, per the depth-default doctrine (ambiguity → MORE depth,
 *  never less). Aliased (not re-listed) so the two never drift. */
const GENERAL_SYNTHESIS_ITEMS: readonly FloorItem[] = FOUNDATION_BAND_ITEMS;

// ── VIDHI-PŪRṆATĀ P-2 (F1 taxonomy completeness, 2026-07-23) — three new life-domain floors ──
// Every item below resolves to a live tool (per P-0's data-support ledger, chart 482012f1) OR
// carries a truthful primitive-level known_gap surfaced in the completeness receipt's `dark`
// bucket. NONE is faked (brief §0 honesty line). Depth defaults to `deepdive` for these intents
// via scope_resolver.defaultDepthForIntent, so a naive "will I attain moksha?" compiles the full
// floor + machine band.

/**
 * floor(spirituality_deepdive) [MANDATORY — brief §2 P-2 / §A]. Mokṣa-domain acharya floor:
 * 9th (dharma) + 12th (mokṣa) bhāvas & lords · Jupiter (guru-kāraka) + Ketu (mokṣa-kāraka) ·
 * Ātmakāraka + Karakāṃśa (the from-karakāṃśa 12th/4th mokṣa-trikoṇa is an answerer-side
 * derivation off the karakāṃśa position) · D20 Vimśāṃśa + its D1/D9/D20 varga-ratification ·
 * nakshatra semantics (Ketu/Jupiter focus, answerer-side) · the Jaimini spiritual-yoga scan
 * (dark, CR-130) · CGM mechanism read · sudarśana tri-lagna agreement. Machine band: dasha spine
 * + leverage-ranked intervention synthesis.
 */
const SPIRITUALITY_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 9 } },
  { primitive_id: 'bhava_condition', order: 2, band: 'acharya_floor', args_override: { house: 12 } },
  { primitive_id: 'bhavesha_condition', order: 3, band: 'acharya_floor', args_override: { house: 9 } },
  { primitive_id: 'bhavesha_condition', order: 4, band: 'acharya_floor', args_override: { house: 12 } },
  { primitive_id: 'karaka_condition', order: 5, band: 'acharya_floor', args_override: { karaka: 'jupiter' } },
  { primitive_id: 'karaka_condition', order: 6, band: 'acharya_floor', args_override: { karaka: 'ketu' } },
  { primitive_id: 'chara_karaka_read', order: 7, band: 'acharya_floor', args_override: { chara_karaka: 'AK' } },
  { primitive_id: 'karakamsa_read', order: 8, band: 'acharya_floor' },
  { primitive_id: 'divisional_facts', order: 9, band: 'acharya_floor', args_override: { varga: 'D20' } },
  { primitive_id: 'varga_ratification', order: 10, band: 'acharya_floor', args_override: { vargas: ['D1', 'D9', 'D20'] } },
  { primitive_id: 'nakshatra_semantics', order: 11, band: 'acharya_floor' },
  { primitive_id: 'spiritual_yoga_scan', order: 12, band: 'acharya_floor' },
  // P-3b: mechanism_read relocated to the E-7 insight band (elevationTail) — present, re-banded.
  { primitive_id: 'sudarshana_agreement_check', order: 13, band: 'acharya_floor' },
  { primitive_id: 'dasha_spine_lord_capability', order: 14, band: 'machine_band' },
  { primitive_id: 'intervention_synthesis', order: 15, band: 'machine_band', args_override: { domain: 'spirituality' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=spirituality; orders 16-24).
  ...elevationTail('spirituality', 16),
];

/**
 * floor(education_deepdive) [CANDIDATE — full worked floor; D24 confirmed data-backed at P-0].
 * 4th (formal schooling) + 5th (buddhi/pūrva-puṇya) + 9th (higher learning/guru) bhāvas & the
 * 4th/5th lords · Mercury (buddhi) + Jupiter (jñāna) kārakas · D24 Chaturviṃśāṃśa + D1/D9/D24
 * ratification · nakshatra semantics (Mercury focus) · dignity + sensitive-degree checks. Machine
 * band: dasha spine + education-scoped taraṅga curve (its phala anchors are the CR-66 dark gap —
 * flagged, not faked).
 */
const EDUCATION_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 4 } },
  { primitive_id: 'bhava_condition', order: 2, band: 'acharya_floor', args_override: { house: 5 } },
  { primitive_id: 'bhava_condition', order: 3, band: 'acharya_floor', args_override: { house: 9 } },
  { primitive_id: 'bhavesha_condition', order: 4, band: 'acharya_floor', args_override: { house: 4 } },
  { primitive_id: 'bhavesha_condition', order: 5, band: 'acharya_floor', args_override: { house: 5 } },
  { primitive_id: 'karaka_condition', order: 6, band: 'acharya_floor', args_override: { karaka: 'mercury' } },
  { primitive_id: 'karaka_condition', order: 7, band: 'acharya_floor', args_override: { karaka: 'jupiter' } },
  { primitive_id: 'divisional_facts', order: 8, band: 'acharya_floor', args_override: { varga: 'D24' } },
  { primitive_id: 'varga_ratification', order: 9, band: 'acharya_floor', args_override: { vargas: ['D1', 'D9', 'D24'] } },
  { primitive_id: 'nakshatra_semantics', order: 10, band: 'acharya_floor' },
  { primitive_id: 'dignity_scan', order: 11, band: 'acharya_floor' },
  { primitive_id: 'sensitive_degree_check', order: 12, band: 'acharya_floor' },
  { primitive_id: 'dasha_spine_lord_capability', order: 13, band: 'machine_band' },
  { primitive_id: 'taranga_curve', order: 14, band: 'machine_band', args_override: { domain: 'education' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=education; orders 15-23).
  ...elevationTail('education', 15),
];

/**
 * floor(progeny_deepdive) [CANDIDATE — full worked floor; D7 confirmed data-backed at P-0].
 * SPINE KEYED OFF H5 + Jupiter (putra-kāraka) + PuK REGARDLESS of the D7 karya-label quirk
 * (P-0 (e): the D7 `varga_karya_bhava` row mislabels as `spouse_karya`; that is an L1
 * `chart_divisionals` writer bug — must_not_touch — so this floor never reads the karya label;
 * D7 `divisional_facts` is corroboration only). 5th (santāna) + its lord · 9th read as the
 * 5th-from-5th derivation · Jupiter putra-kāraka + Jaimini PuK · D7 Saptāṃśa + D1/D9/D7
 * ratification · dosha scan. Machine band: dasha spine + progeny-scoped remedy scan.
 */
const PROGENY_DEEPDIVE_ITEMS: readonly FloorItem[] = [
  { primitive_id: 'bhava_condition', order: 1, band: 'acharya_floor', args_override: { house: 5 } },
  { primitive_id: 'bhava_condition', order: 2, band: 'acharya_floor', args_override: { house: 9 } },
  { primitive_id: 'bhavesha_condition', order: 3, band: 'acharya_floor', args_override: { house: 5 } },
  { primitive_id: 'karaka_condition', order: 4, band: 'acharya_floor', args_override: { karaka: 'jupiter' } },
  { primitive_id: 'chara_karaka_read', order: 5, band: 'acharya_floor', args_override: { chara_karaka: 'PuK' } },
  { primitive_id: 'divisional_facts', order: 6, band: 'acharya_floor', args_override: { varga: 'D7' } },
  { primitive_id: 'varga_ratification', order: 7, band: 'acharya_floor', args_override: { vargas: ['D1', 'D9', 'D7'] } },
  { primitive_id: 'dosha_scan', order: 8, band: 'acharya_floor' },
  { primitive_id: 'dasha_spine_lord_capability', order: 9, band: 'machine_band' },
  { primitive_id: 'remedy_scan', order: 10, band: 'machine_band', args_override: { domain: 'progeny' } },
  // E-1/E-2/E-5/E-6/E-7 shared elevation tail (domain=progeny; orders 11-19).
  ...elevationTail('progeny', 11),
];

export const VIDHI_INTENT_FLOORS: readonly IntentFloor[] = [
  {
    intent: 'wealth_deepdive',
    version: 1,
    floor_items: WEALTH_DEEPDIVE_ITEMS,
    cr27_coverage: ['CR-27a', 'CR-27b', 'CR-27c', 'CR-27d', 'CR-36'],
    notes: 'Flagship floor — worked example per DOCTRINE_CAMPAIGN_DESIGN_v1_0.md §3; §G master acceptance target.',
  },
  {
    intent: 'career_deepdive',
    version: 1,
    floor_items: CAREER_DEEPDIVE_ITEMS,
    cr27_coverage: ['CR-27c', 'CR-27d'],
    notes: 'D10/D9 multi-varga per CR-62’s wealth {D1,D2,D9,D11} / career {D1,D9,D10} map (design §12 lord-placement join).',
  },
  {
    intent: 'health_deepdive',
    version: 1,
    floor_items: HEALTH_DEEPDIVE_ITEMS,
    cr27_coverage: ['CR-27b'],
  },
  {
    intent: 'marriage_deepdive',
    version: 1,
    floor_items: MARRIAGE_DEEPDIVE_ITEMS,
    cr27_coverage: ['CR-27b'],
  },
  {
    intent: 'spirituality_deepdive',
    version: 1,
    floor_items: SPIRITUALITY_DEEPDIVE_ITEMS,
    cr27_coverage: [],
    notes:
      'VIDHI-PŪRṆATĀ P-2 [MANDATORY] — mokṣa-domain floor (brief §2 P-2 / §A). H9+H12 + lords, ' +
      'Jupiter(guru)+Ketu(mokṣa) kārakas, AK+karakāṃśa (from-karakāṃśa 12th derived answerer-side), ' +
      'D20, D1/D9/D20 ratification. Jaimini spiritual-yoga scan is DARK (CR-130 — family key absent).',
  },
  {
    intent: 'education_deepdive',
    version: 1,
    floor_items: EDUCATION_DEEPDIVE_ITEMS,
    cr27_coverage: [],
    notes:
      'VIDHI-PŪRṆATĀ P-2 [CANDIDATE] — D24-backed education floor (brief §A). H4+H5+H9 + 4th/5th ' +
      'lords, Mercury(buddhi)+Jupiter(jñāna) kārakas, D24 + D1/D9/D24 ratification. education-scoped ' +
      'taraṅga_curve inherits CR-66 (phala domain anchors zero) — dark, not faked.',
  },
  {
    intent: 'progeny_deepdive',
    version: 1,
    floor_items: PROGENY_DEEPDIVE_ITEMS,
    cr27_coverage: [],
    notes:
      'VIDHI-PŪRṆATĀ P-2 [CANDIDATE] — D7-backed progeny floor (brief §A). Spine off H5 + Jupiter ' +
      '(putra-kāraka) + PuK REGARDLESS of the D7 spouse_karya label quirk (P-0 (e): L1 chart_divisionals ' +
      'writer mislabel, must_not_touch; D7 is corroboration only). H5(+H9 5th-from-5th), D7, D1/D9/D7 ratification.',
  },
  {
    intent: 'structure_read',
    version: 1,
    floor_items: STRUCTURE_READ_ITEMS,
    cr27_coverage: [],
    notes: 'Narrow/structure depth — the "show me my D1" canonical example; no machine band (deliberate).',
  },
  {
    intent: 'panoramic_breadth',
    version: 1,
    floor_items: PANORAMIC_BREADTH_ITEMS,
    cr27_coverage: ['CR-27a', 'CR-27c', 'CR-27d'],
    notes: 'The "unleash my financial potential"-shaped wide sweep — domain-agnostic breadth, not depth.',
  },
  {
    intent: 'retrieval_only',
    version: 1,
    floor_items: RETRIEVAL_ONLY_ITEMS,
    cr27_coverage: [],
  },
  {
    intent: 'general_synthesis',
    version: 1,
    floor_items: GENERAL_SYNTHESIS_ITEMS,
    cr27_coverage: ['CR-27a'],
  },
];
