import json, collections
from lib import q
def c(t,ch,pg,sl,qt): return dict(text_id=t,chunk_id=ch,page=pg,sloka_printed=sl,quote=qt)
MC93=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0093_c01','PG93',sl,qt)
MC94=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0094_c01','PG94',sl,qt)
MC94b=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0094_c02','PG94',sl,qt)
MC95=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0095_c01','PG95',sl,qt)
MC96a=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0096_c01','PG96',sl,qt)
MC96b=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0096_c02','PG96',sl,qt)
MC97=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0097_c01','PG97',sl,qt)
MC106=lambda qt,sl: c('muhurta_chintamani','muhurta_chintamani_pg0106_c01','PG106',sl,qt)
MAXQ=MC93("(१) गुण, वश्यमे (२), तारामे (३), योनिमे (४) ... नाडीमे गुण (८) ... योग (३६)","21")
T="reference_nakshatra_matrix"
TRANS="(Mahidhara bhasha tika, Khemraj ed.)"
CIT=lambda sl,ch,extra='': f"Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka {sl} as printed — {ch} {TRANS}{extra}"
F=[]
def fam(key,mt,where,claim,state,sc,corpus,inf,cite,action,qn,note=None):
    F.append(dict(key=key,mt=mt,where=where,claim=claim,state=state,sc=sc,corpus=corpus,inf=inf,cite=cite,action=action,qn=qn,note=note))
# ---- gana
fam('gana_same','gana_kuta',"matrix_type='gana_kuta' and from_key=to_key","Same-gana pairs (Deva-Deva, Manushya-Manushya, Rakshasa-Rakshasa) score 6/6","sourced_fact","FACT",[MC95("इस कूटमे गणसाम्यमे ६ गुण","29-30")],None,CIT('29-30','muhurta_chintamani:PG95:C1'),'recite',None)
fam('gana_dm','gana_kuta',"matrix_type='gana_kuta' and from_key<>to_key and 'Rakshasa' not in (from_key,to_key)","Deva-Manushya pair (both directions) scores 5/6","sourced_inference","INFERENCE",[MC95("देव मनुष्य में ५ ... कन्या देव वर मनुष्य में ४ गुण","30")],"Chunk states 5 for Deva-Manushya but its tail also gives direction-specific values (bride deva/groom manushya = 4); DB uses the symmetric 5 in both directions and does not document which of from/to is the groom. OCR-damaged sentence.",CIT('30','muhurta_chintamani:PG95:C1'),'acharya',"Gana kuta Deva-Manushya: Muhurta-Cintamani PG95 (Sloka 30 tika) gives 5 but also a direction-specific 4 (bride Deva, groom Manushya). Should the matrix be asymmetric, and which of from_key/to_key is groom vs bride?")
fam('gana_rak','gana_kuta',"matrix_type='gana_kuta' and from_key<>to_key and 'Rakshasa' in (from_key,to_key)","Deva-Rakshasa and Manushya-Rakshasa pairs (both directions) score 0/6","sourced_inference","INFERENCE",[MC95("राक्षस मनुष्यका मृत्यु, देव राक्षसका हो तो कलह","30"),MC95("देव राक्षस एवं मनुष्य राक्षसम गुण (०) है, कन्या राक्षसी वर देवमें २","30")],"Chunk states 0 for Deva-Rakshasa / Manushya-Rakshasa but also a direction-specific 2 (bride Rakshasi, groom Deva), which the DB (0 both ways) does not carry; orientation of from/to undocumented. OCR-damaged sentence.",CIT('30','muhurta_chintamani:PG95:C1'),'acharya',"Gana kuta Rakshasa pairs: Muhurta-Cintamani PG95 (Sloka 30 tika) gives 0 but a direction-specific 2 for (bride Rakshasi, groom Deva). Should the Deva<->Rakshasa cell for that direction be 2 rather than 0?")
# ---- nadi
fam('nadi_same','nadi_kuta',"matrix_type='nadi_kuta' and from_key=to_key","Same-nadi pairs score 0/8 (nadi dosha)","sourced_inference","INFERENCE",[MC97("Marriage of a couple falling within one and the same nāḍī is not good","34")],"Chunk says same-nadi marriage is not good (middle nadi: death of both); 0 points is the platform's numeric reading. MC also lists exceptions (south of the Godavari, Kshatriyas) and parihara not modelled in DB.",CIT('34','muhurta_chintamani:PG97:C1'),'recite',None)
fam('nadi_diff','nadi_kuta',"matrix_type='nadi_kuta' and from_key<>to_key","Different-nadi pairs score 8/8","sourced_inference","INFERENCE",[MC93("(८) ... इन सबका योग (३६) गुण","21"),MC97("Marriage of a couple falling within one and the same nāḍī is not good","34")],"Max 8 for nadi is stated (verse 21); full 8 for differing nadis follows from the dosha being defined only for the same nadi (absence-based).",CIT('21, 34','muhurta_chintamani:PG93:C1, muhurta_chintamani:PG97:C1'),'recite',None)
# ---- yoni
fam('yoni_same','yoni_kuta',"matrix_type='yoni_kuta' and relation_value='same_yoni'","Same-yoni pairs score 4/4","sourced_inference","INFERENCE",[MC94("एक योनिके वर कन्या उत्तम मित्र ... योनिमेत्री होनेमे (४) गुण","25-26")],"MC: same yoni = best ('uttam mitra'), yoni-maitri scores up to 4 (verse 21); mapping best->4 is inference.",CIT('25-26','muhurta_chintamani:PG94:C1'),'recite',None)
fam('yoni_enemy','yoni_kuta',"matrix_type='yoni_kuta' and relation_value='enemy'","Natural-enemy yoni pairs (cow-tiger, elephant-lion, horse-buffalo, dog-hare, mongoose-serpent, monkey-goat, cat-rat) score 0/4","sourced_inference","INFERENCE",[MC94("इनका वैर-गौ व्याघका । गज सिंह । घोड़ा भैंसा। कुत्ता मृग। नेवला सर्प । वानर मेंढा । बिल्ली चूहा","25-26")],"Pair set is stated (7 pairs; MC has dog-mriga/deer and monkey-mendha/ram where DB has Hare and Goat: naming variants); 'inauspicious' -> 0 points is inference.",CIT('25-26','muhurta_chintamani:PG94:C1'),'recite',None)
fam('yoni_friendly','yoni_kuta',"matrix_type='yoni_kuta' and relation_value='friendly'","Distinct non-enemy yoni pairs score 2/4","unsourced_marked","NONE",[MC94("समयोनिकं सामान्य ओर परस्पर योनिवैरमे अशुभ","25-26")],"MC distinguishes same (best), 'sama' (ordinary), enemy (inauspicious) but gives no intermediate point value; the 2-point tier (and flat 2 for every non-enemy pair) is not in the held text.",None,'mark_unsourced',None)
# ---- tara
TP="substring(notes from 'pos=([0-9]+)')::int"
fam('tara_bad','tara_kuta',f"matrix_type='tara_kuta' and {TP} in (3,5,7)","Tara positions Vipat(3), Pratyari(5), Vadha(7) score 0/3","sourced_inference","INFERENCE",[MC93("तारा ... ९ से भाग दे शेषको तारा जाननी, ३।५।७ ... अशुभ अन्य शुभ","24")],"Chunk (partly garbled) names remainders 3,5,7 as inauspicious ('3|5|7 ... ashubh, anya shubh'); 0 points for them is the platform reading. DB position = ((dist-1) mod 9)+1 with dist=(to-from) mod 27 (a 0-based difference; same star -> dist 27 -> position 9, next star -> position 1 'Janma'). If MC's count is the usual inclusive one (not stated in the damaged chunk) every DB position label is shifted by one; DB also counts one direction only (MC counts both ways).",CIT('24 (tika mark; verse-line OCR reads 27)','muhurta_chintamani:PG93:C1'),'recite',None)
fam('tara_good','tara_kuta',f"matrix_type='tara_kuta' and {TP} in (2,4,6,8,9)","Tara positions Sampat(2), Kshema(4), Sadhaka(6), Mitra(8), Atimitra(9) score 2 (Sadhaka 1.5) of 3","sourced_inference","INFERENCE",[MC93("३।५।७ ... अशुभ अन्य शुभ होते है, शुभसे (३) गुण मिलते है","24")],"Classification (non-3/5/7 = auspicious) is stated; the cell values 2 and 1.5 are NOT in the held text (MC says auspicious tara = 3 gunas; per-direction halves/graded values are the platform's scheme). So the class is supported, the point values are not.",CIT('24 (tika mark)','muhurta_chintamani:PG93:C1',' — classification only; points unsourced'),'acharya',"Tara kuta: Muhurta-Cintamani PG93 (Sloka 24 tika) says only remainders 3/5/7 are inauspicious and all others yield the full 3 gunas. The rows give 2 (Sampat, Kshema, Mitra, Atimitra) and 1.5 (Sadhaka) per direction. Also: DB 'dist' is the 0-based difference (same star = position 9, next star = position 1 'Janma'); is tara counted inclusively (same star = 1) as is usual? What scale and what combination rule (sum of both directions? halves?) does the platform adopt, and from which source?")
fam('tara_janma','tara_kuta',f"matrix_type='tara_kuta' and {TP}=1","Tara position Janma(1) scores 0/3","contradicted","CONTRADICTS",[MC93("३।५।७ ... अशुभ अन्य शुभ होते है","24")],"Held chunk marks only remainders 3,5,7 as inauspicious ('others auspicious'), so remainder 1 (Janma) is auspicious by the text; DB scores it 0. Chunk partly garbled.",None,'acharya',"Tara kuta Janma (remainder 1): Muhurta-Cintamani PG93 (Sloka 24 tika) says only remainders 3/5/7 are inauspicious ('anya shubh'), yet the rows score Janma 0. Is Janma tara to be scored 0 (another tradition), and from what authority?")
# ---- rajju etc
fam('rajju','rajju',"matrix_type='rajju'","Nakshatra -> rajju group membership (Pada/Kati/Nabhi/Kantha/Shira with aroha/avaroha direction)","unsourced_marked","NONE",[],"Searched the whole corpus (Roman 'rajju', Devanagari रज्जु/राजु, MC IAST): the only 'Rajju' hits are the Rajju asraya-yoga in Brihat Jataka (unrelated). Muhurta-Cintamani's Vivaha chapter has no rajju koota.",None,'mark_unsourced',"Rajju grouping: not in the held corpus. The platform's groups (e.g. Padha = nakshatra 2,6,11,16,21,27) look unlike the commonly taught five-group scheme of 6/6/6/6/3 nakshatras; please confirm against the acharya's table and name the authority. (Outside-corpus remark, not a citation.)")
fam('mahendra','mahendra',"matrix_type='mahendra'","Mahendra pairs: distance 4,7,10,13,16,19,22,25 from the from-nakshatra","unsourced_marked","NONE",[],"(DB dist is the 0-based difference, so an inclusive-count rule would be offset by one - see tara.) Searched 'mahendra' in all texts and Devanagari महेन्द्र in MC: only place names / Mahendra-system mentions (Brihat Samhita, Jataka Parijata); no koota statement.",None,'mark_unsourced',None)
fam('stree_deergha','stree_deergha',"matrix_type='stree_deergha'","Stree-deergha: dosha when min(forward, reverse distance) < 9","unsourced_marked","NONE",[],"No held text states a stree-deergha rule. MC PG99-100 gives a different pūrva/madhya/apara-bhāga (6/12/9) rule for husband/wife affection, which is not this construct and not the 9-nakshatra threshold.",None,'mark_unsourced',None)
fam('vedha','vedha',"matrix_type='vedha'","13 symmetric nakshatra pairs as vedha (1-16,2-15,...,8-9,17-27,...,21-23)","unsourced_marked","NONE",[MC106("पञ्चशलाका ... परस्पर वेध ... सप्तशलाका-ज्येष्ठा पुष्य । शतभिषा स्वाती","56-57")],"MC's vedha tables are the pancha-/sapta-shalaka (planet-pierced Moon-star) pairs for marriage muhurta: a different construct and a different pair set (no DB pair reproduces them except possibly 7-10). The DB pairs follow i+j=17 / i+j=44 arithmetic. Not supported.",None,'mark_unsourced',"Vedha pairs: the rows follow a pure arithmetic pattern (1-16, 2-15, ... 8-9 and 17-27, 18-26, ... 21-23); Muhurta-Cintamani PG105-106 (Sloka 56-57) lists different pancha-/sapta-shalaka pairs. Which vedha scheme is intended (ashtakoota vedha vs shalaka-vedha) and what is its authority?")
# ---- varna / vashya
fam('varna_core','varna_kuta',"matrix_type='varna_kuta' and from_key in ('Brahmin','Kshatriya','Vaishya','Shudra') and to_key in ('Brahmin','Kshatriya','Vaishya','Shudra')","Varna kuta among the 4 classical varnas: 1/1 when from-varna >= to-varna, else 0","sourced_inference","INFERENCE",[MC93("वर्णाधिक वर होनेमे (१) गुण मिलता है, कन्या अधिकमे नहीं","22")],"MC: groom of equal/higher varna scores 1, bride higher scores 0 (max 1). Inference: from_key = groom, to_key = bride (DB does not document orientation). MC assigns varna to RASHIS (Pisces/Scorpio/Cancer Brahmin, ...), DB assigns varna to NAKSHATRAS - the nakshatra-level assignment is unsourced.",CIT('22','muhurta_chintamani:PG93:C1'),'recite',None)
fam('varna_ext','varna_kuta',"matrix_type='varna_kuta' and not (from_key in ('Brahmin','Kshatriya','Vaishya','Shudra') and to_key in ('Brahmin','Kshatriya','Vaishya','Shudra'))","Varna kuta cells involving the extra classes Farmer, Butcher, Mleccha (ranked equal to Shudra)","unsourced_marked","NONE",[],"Held text knows only four varnas; Farmer/Butcher/Mleccha and their rank equality with Shudra are not in the corpus.",None,'mark_unsourced',None)
fam('vashya','vashya_kuta',"matrix_type='vashya_kuta'","5x5 vashya matrix (Dwipada/Chaturpada/Jalasheela/Keeta/Vanachara) scoring 2/1/0","unsourced_marked","NONE",[MC93("(२) ... वश्यक्ट-मनुष्यराशि ३।६। ७ ... सिह विना सभी राशि","23")],"Only the max (2) is stated. MC's vashya is a rashi-based rule (humans' vashya = all signs except Leo, aquatic signs as food, ...), not the 5-class animal-group matrix; the cell values are not in the held text.",None,'mark_unsourced',None)
# ---- graha maitri
GM="matrix_type='graha_maitri_kuta'"
fam('gm_same','graha_maitri_kuta',f"{GM} and from_key=to_key","Same-planet cells (same sign lord) score 3 (neutral_neutral) of 5","contradicted","CONTRADICTS",[MC94b("वरकन्याकं राशीश मित्र तथा एकाधिपत्यवे हो तो ५ गुण","27-28")],"MC: if the two sign lords are friends OR the same planet (ekadhipatya) the score is 5; DB scores a planet against itself 3 because it classifies self as neutral_neutral.",None,'acharya',"Graha maitri, same lord: Muhurta-Cintamani PG94 (Sloka 27-28 tika) gives 5 gunas when the two rashi-lords are friends or one and the same planet (ekadhipatya). The 7 diagonal rows (sun-sun ... saturn-saturn) are scored 3. Should they be 5?")
fam('gm_ff','graha_maitri_kuta',f"{GM} and from_key<>to_key and relation_value='friend_friend'","Mutual friends score 5/5","sourced_inference","INFERENCE",[MC94("ग्रहकूट-सूयेके म॑° बृ° च॑° मित ... चन्द्रमाके सू० बु० मित्र","27-28"),MC94b("५ गुण, एवं सममित्रमे ४ ... सम सममं ३","27-28")],"Planet friend/neutral/enemy relations read from the MC list (OCR-damaged: Sun's and Jupiter's enemy lists, sh. = Shani/Shukra abbreviations); all 42 off-diagonal DB relations agree with that reading (script-checked). Score 5 for friend-friend is stated.",CIT('27-28','muhurta_chintamani:PG94:C1, muhurta_chintamani:PG94:C2'),'recite',None)
fam('gm_fn','graha_maitri_kuta',f"{GM} and from_key<>to_key and relation_value in ('friend_neutral','neutral_friend')","Friend/neutral pairs score 4/5","sourced_inference","INFERENCE",[MC94b("सममित्रमे ४? सम सममं ३","27-28")],"As gm_ff; 'sam-mitra' = 4 is read from a damaged sentence ('4?').",CIT('27-28','muhurta_chintamani:PG94:C1, muhurta_chintamani:PG94:C2'),'recite',None)
fam('gm_nn','graha_maitri_kuta',f"{GM} and from_key<>to_key and relation_value='neutral_neutral'","Mutually neutral planets score 3/5","sourced_inference","INFERENCE",[MC94b("सम सममं ३","27-28")],"As gm_ff; 'sam-sam' = 3 stated.",CIT('27-28','muhurta_chintamani:PG94:C1, muhurta_chintamani:PG94:C2'),'recite',None)
fam('gm_ee','graha_maitri_kuta',f"{GM} and from_key<>to_key and relation_value='enemy_enemy'","Mutual enemies score 0/5","sourced_inference","INFERENCE",[MC94b("शत्रु शत्रुका मेल कहीं नहीं होता, मत्युषट्काष्टक होता है","27-28")],"Chunk says enemy-enemy union is not made anywhere (0 gunas stated '(०) मिलता है').",CIT('27-28','muhurta_chintamani:PG94:C2'),'recite',None)
fam('gm_fe','graha_maitri_kuta',f"{GM} and from_key<>to_key and relation_value in ('friend_enemy','enemy_friend')","Friend/enemy pairs score 1/5","contradicted","CONTRADICTS",[MC94b("मित्र शवूमे २, सम शते १","27-28")],"MC scale (read from damaged text) gives mitra-shatru 2 and sama-shatru 1; DB gives friend-enemy 1 and neutral-enemy 0 (a half-step lower).",None,'acharya',"Graha maitri scale: Muhurta-Cintamani PG94 (Sloka 27-28 tika, OCR-damaged) reads friend-enemy = 2 and neutral-enemy = 1, but the rows score friend-enemy 1 and neutral-enemy 0. Please read the printed table and say which scale the platform follows.")
fam('gm_ne','graha_maitri_kuta',f"{GM} and from_key<>to_key and relation_value in ('neutral_enemy','enemy_neutral')","Neutral/enemy pairs score 0/5","contradicted","CONTRADICTS",[MC94b("सम शते १","27-28")],"See gm_fe: MC reads neutral-enemy = 1; DB 0.",None,'acharya',"Graha maitri neutral-enemy (12 rows scored 0): Muhurta-Cintamani PG94 (Sloka 27-28 tika) appears to read 'sama-shatru 1'. Confirm 1 versus 0 from the printed text.")
# ---- bhakoot  (DB relation_value = "d_fwd/d_rev" where d = (sign2-sign1) mod 12, a 0-based DIFFERENCE; inclusive position = d+1)
BK="matrix_type='bhakoot_kuta'"
BKNOTE=" DB defect: the writer compares the 0-based differences (d_fwd,d_rev) against inclusive-position tuples {(2,12),(5,9),(6,8)} (l0_nakshatra.py:1237-1242), so no pair can ever match and all 144 rows carry 7/7."
fam('bk_212','bhakoot_kuta',f"{BK} and relation_value in ('1/11','11/1')","Bhakoot 2/12 pairs (inclusive positions; DB relation_value 1/11 and 11/1) are scored 7/7 although classed inauspicious","contradicted","CONTRADICTS",[MC96a("if 2–12, poverty. In the remaining positions they are auspicious","31")],"MC (Sloka 31 tika; translator flags the verse as an interpolation) calls 2-12 inauspicious (poverty) while all 24 rows score 7."+BKNOTE,None,'acharya',"Bhakoot dosha pairs: every one of the 144 bhakoot rows is scored 7/7, because the writer's inauspicious set {(2,12),(5,9),(6,8)} is compared against 0-based sign differences and never matches. Muhurta-Cintamani PG96 (Sloka 31 tika) calls 2-12 (poverty) and 5-9 (loss of sons) inauspicious and shatru-shadashtaka 6-8 (death) inauspicious. Please confirm the intended scoring (0 for these three families, with the parihara of Sloka 32 applied or not) so the rows can be regenerated.")
fam('bk_59','bhakoot_kuta',f"{BK} and relation_value in ('4/8','8/4')","Bhakoot 5/9 pairs (inclusive positions; DB relation_value 4/8 and 8/4) are scored 7/7 although classed inauspicious","contradicted","CONTRADICTS",[MC96a("If the signs of groom and bride stand 5–9 to one another there is loss of sons","31")],"MC calls 5-9 inauspicious (loss of sons); all 24 rows score 7."+BKNOTE,None,'acharya',"Bhakoot 5/9 (24 rows, relation_value 4/8 and 8/4, all scored 7): Muhurta-Cintamani PG96 (Sloka 31 tika) calls 5-9 inauspicious (loss of sons). Should these rows score 0?")
SHATRU="((relation_value='5/7' and from_key::int%2=1) or (relation_value='7/5' and from_key::int%2=0))"
MITRA="((relation_value='5/7' and from_key::int%2=0) or (relation_value='7/5' and from_key::int%2=1))"
fam('bk_68_shatru','bhakoot_kuta',f"{BK} and {SHATRU}","Bhakoot 6/8 pairs where the sixth is counted from an odd sign (shatru-shadashtaka) are scored 7/7 although classed inauspicious (death)","contradicted","CONTRADICTS",[MC95("विषमात्कन्यकाराशेः षष्ठे षष्ठाष्टकं न सत्‌ ।","31"),MC96a("The śatru-ṣaḍaṣṭaka brings death.","31")],"MC: sixth from an odd sign (= eighth from an even sign) is shatru-shadashtaka, death; 12 rows score 7. Class derived by sign parity (script)."+BKNOTE,None,'acharya',"Bhakoot shatru-shadashtaka (12 rows: relation 5/7 from an odd sign and 7/5 from an even sign, all scored 7): Muhurta-Cintamani PG95-96 (Sloka 31) calls it inauspicious (death). Should these rows score 0, with or without the Sloka 32 parihara for friendly/same lords?")
fam('bk_68_mitra','bhakoot_kuta',f"{BK} and {MITRA}","Bhakoot 6/8 pairs where the sixth is counted from an even sign (mitra-shadashtaka) score 7/7","sourced_inference","INFERENCE",[MC96a("the sixth from an even sign and the eighth from an odd one form the mitra-ṣaḍaṣṭaka ... this is auspicious","31")],"MC calls mitra-shadashtaka auspicious (lords friends: Taurus-Libra, Cancer-Sagittarius, Capricorn-Gemini, Pisces-Leo, Virgo-Aquarius, Scorpio-Aries); DB 7 agrees, but only by the same defect that scores everything 7. Full 7 for 'auspicious' is inference.",CIT('31','muhurta_chintamani:PG96:C1'),'recite',None)
fam('bk_rest','bhakoot_kuta',f"{BK} and relation_value not in ('1/11','11/1','4/8','8/4','5/7','7/5')","Bhakoot other positions (same sign, 3/11, 4/10, 7/7) score 7/7","sourced_inference","INFERENCE",[MC96a("In the remaining positions they are auspicious","31"),MC93("भकूटमैत्री ... (७)","21")],"Max 7 stated (verse 21); 'remaining positions auspicious' -> full 7 is inference.",CIT('21, 31','muhurta_chintamani:PG93:C1, muhurta_chintamani:PG96:C1'),'recite',None)
# --- resolve ids + verify partition
allids=set(int(r['id']) for r in q("select id from reference_nakshatra_matrix"))
seen={}; out=[]
for f in F:
    sql=f"select id from reference_nakshatra_matrix where {f['where']} order by id"
    ids=[int(r['id']) for r in q(sql)]
    for i in ids:
        assert i not in seen,(i,f['key'],seen[i]); seen[i]=f['key']
    f['ids']=ids
    out.append(dict(asset='bg_nakshatra',table=T,row_key=dict(family=f['key'],matrix_type=f['mt'],id_min=min(ids),id_max=max(ids)),row_key_query=sql,row_count=len(ids),
      claim=f['claim'],current_citation='bphs:ch73',state=f['state'],support_class=f['sc'],corpus=f['corpus'],inference_step=f['inf'],
      proposed_citation=f['cite'],proposed_action=f['action'],acharya_question=f['qn'],
      citation_resolution_note="bphs:ch73 is not resolvable: bphs PG73 is the Dvadasamsa notes/speculum; no BPHS chunk holds ashtakuta rules (searched kuta/koota/ashtakoot/bhakoot/vashya/yoni/gana/nadi stems over all 15 texts). The only held ashtakuta source is Muhurta-Cintamani (Devanagari OCR, MEDIUM, native decision pending) PG93-97.",
      max_points_check=None))
assert set(seen)==allids,(len(set(seen)),len(allids))
MX_MAX={'varna_kuta':(1,'1'),'vashya_kuta':(2,'2'),'tara_kuta':(3,'3'),'yoni_kuta':(4,'4'),'graha_maitri_kuta':(5,'5'),'gana_kuta':(6,'6'),'bhakoot_kuta':(7,'7'),'nadi_kuta':(8,'8')}
for o in out:
    mt=o['row_key']['matrix_type']
    if mt in MX_MAX:
        dbm=set(r['max_points'] for r in q(f"select distinct max_points from reference_nakshatra_matrix where matrix_type='{mt}'"))
        o['max_points_check']=dict(db_max=sorted(dbm),mc_max=MX_MAX[mt][0],state='sourced_fact' if dbm=={'%d.00'%MX_MAX[mt][0]} else 'MISMATCH',chunk='muhurta_chintamani_pg0093_c01',sloka_printed='21',quote='योग (३६) गुण (varna 1 ... nadi 8)')
    else: o['max_points_check']=None
json.dump(out,open('ledger_mx.json','w'),ensure_ascii=False,indent=1)
cnt=collections.Counter(); 
for o in out: cnt[o['state']]+=o['row_count']
print(cnt,sum(cnt.values()))
for o in out: print(o['row_key']['family'],o['row_count'],o['state'])
