"""
mantras.py — MARSYS-JIS Global Lookup G33
Mantra / Stotra library: ~200 entries
Sanskrit (IAST) + transliteration + meaning + frequency

Classical citations:
  - Rigveda, Atharvaveda, Yajurveda, Samaveda
  - Brihat Parashara Hora Shastra (BPHS)
  - Navagraha Stotra (Vyasa)
  - Maha Mrityunjaya: Rigveda 7.59.12
  - Gayatri: Rigveda 3.62.10
  - Vishnu Sahasranama: Mahabharata, Anushasana Parva 149
  - Hanuman Chalisa: Tulsidas, Ramcharitmanas
  - Aditya Hridayam: Valmiki Ramayana, Yuddha Kanda 107
"""

from __future__ import annotations
from typing import Optional

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

MANTRAS: list[dict] = [
    # ===== NAVAGRAHA BEEJ MANTRAS (9) =====
    {
        "id": "sun_beej_mantra",
        "graha": "sun",
        "mantra_type": "beej",
        "name": "Surya Beej Mantra",
        "sanskrit_iast": "Oṃ hrāṃ hrīṃ hrauṃ saḥ sūryāya namaḥ",
        "transliteration": "Om hraam hreem hraum sah suryaya namah",
        "english_meaning": "Salutations to the Sun, the source of all light and life",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "moon_beej_mantra",
        "graha": "moon",
        "mantra_type": "beej",
        "name": "Chandra Beej Mantra",
        "sanskrit_iast": "Oṃ śrāṃ śrīṃ śrauṃ saḥ candrāya namaḥ",
        "transliteration": "Om shraam shreem shraum sah chandraya namah",
        "english_meaning": "Salutations to the Moon, lord of the mind and emotions",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "mars_beej_mantra",
        "graha": "mars",
        "mantra_type": "beej",
        "name": "Mangala Beej Mantra",
        "sanskrit_iast": "Oṃ krāṃ krīṃ krauṃ saḥ bhaumāya namaḥ",
        "transliteration": "Om kraam kreem kraum sah bhaumaya namah",
        "english_meaning": "Salutations to Mars (son of Earth), the warrior planet",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "mercury_beej_mantra",
        "graha": "mercury",
        "mantra_type": "beej",
        "name": "Budha Beej Mantra",
        "sanskrit_iast": "Oṃ brāṃ brīṃ brauṃ saḥ budhāya namaḥ",
        "transliteration": "Om braam breem braum sah budhaya namah",
        "english_meaning": "Salutations to Mercury, the planet of intellect and communication",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "jupiter_beej_mantra",
        "graha": "jupiter",
        "mantra_type": "beej",
        "name": "Guru Beej Mantra",
        "sanskrit_iast": "Oṃ grāṃ grīṃ grauṃ saḥ guruve namaḥ",
        "transliteration": "Om graam greem graum sah gurave namah",
        "english_meaning": "Salutations to Jupiter, the preceptor of the gods and bestower of wisdom",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "venus_beej_mantra",
        "graha": "venus",
        "mantra_type": "beej",
        "name": "Shukra Beej Mantra",
        "sanskrit_iast": "Oṃ drāṃ drīṃ drauṃ saḥ śukrāya namaḥ",
        "transliteration": "Om draam dreem draum sah shukraya namah",
        "english_meaning": "Salutations to Venus, planet of love, beauty, and material prosperity",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "saturn_beej_mantra",
        "graha": "saturn",
        "mantra_type": "beej",
        "name": "Shani Beej Mantra",
        "sanskrit_iast": "Oṃ prāṃ prīṃ prauṃ saḥ śanaiścarāya namaḥ",
        "transliteration": "Om praam preem praum sah shanaischaraya namah",
        "english_meaning": "Salutations to Saturn, the slow-moving lord of karma and discipline",
        "syllable_count": 11,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "rahu_beej_mantra",
        "graha": "rahu",
        "mantra_type": "beej",
        "name": "Rahu Beej Mantra",
        "sanskrit_iast": "Oṃ bhrāṃ bhrīṃ bhrauṃ saḥ rāhave namaḥ",
        "transliteration": "Om bhraam bhreem bhraum sah rahave namah",
        "english_meaning": "Salutations to Rahu, the north lunar node, lord of illusion and ambition",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },
    {
        "id": "ketu_beej_mantra",
        "graha": "ketu",
        "mantra_type": "beej",
        "name": "Ketu Beej Mantra",
        "sanskrit_iast": "Oṃ srāṃ srīṃ srauṃ saḥ ketave namaḥ",
        "transliteration": "Om sraam sreem sraum sah ketave namah",
        "english_meaning": "Salutations to Ketu, the south lunar node, lord of liberation and past karma",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "BPHS ch.86; Navagraha Stotra (Vyasa)",
    },

    # ===== NAVAGRAHA STOTRAS (9) =====
    {
        "id": "surya_stotra_vyasa",
        "graha": "sun",
        "mantra_type": "stotra",
        "name": "Surya Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Japākusumasaṅkāśaṃ kāśyapeyaṃ mahādyutim | tamorim sarva-pāpaghnaṃ praṇato'smi divākaram ||",
        "transliteration": "Japaakusumasankasham kashyapeyam mahadyutim | tamoriim sarvapaapagnam pranato'smi divaakaram ||",
        "english_meaning": "I bow to the day-maker (Sun), bright as the hibiscus flower, son of Kashyapa, of great radiance, enemy of darkness, destroyer of all sins",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 1",
    },
    {
        "id": "chandra_stotra_vyasa",
        "graha": "moon",
        "mantra_type": "stotra",
        "name": "Chandra Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Dadhi-śaṅkha-tuṣārābhaṃ kṣīrodārṇava-sambhavam | namāmi śaśinaṃ somaṃ śambhor mukuṭa-bhūṣaṇam ||",
        "transliteration": "Dadhi shankha tusharabham kshirodarnava sambhavam | namami shashinam somam shambhor mukuta bhushanam ||",
        "english_meaning": "I bow to the Moon, white as curds and conch-shell and snow, born of the milky ocean, who adorns the crest of Shiva",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 2",
    },
    {
        "id": "mangala_stotra_vyasa",
        "graha": "mars",
        "mantra_type": "stotra",
        "name": "Mangala Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Dharaṇī-garbha-sambhūtaṃ vidyut-kānti-samaprabham | kumāraṃ śakti-hastaṃ ca maṅgalaṃ praṇamāmy aham ||",
        "transliteration": "Dharani garbha sambhutam vidyut kanti sama prabham | kumaram shakti hastam cha mangalam pranamamy aham ||",
        "english_meaning": "I bow to Mangala (Mars), born from the womb of Earth, brilliant as lightning, the young warrior holding a spear",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 3",
    },
    {
        "id": "budha_stotra_vyasa",
        "graha": "mercury",
        "mantra_type": "stotra",
        "name": "Budha Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Priyaṅgu-kalikā-śyāmaṃ rūpeṇāpratimam budham | saumyaṃ saumya-guṇopetaṃ tam budhaṃ praṇamāmy aham ||",
        "transliteration": "Priyangu kalikaa shyamam roopena apratimam budham | saumyam saumya gunopetam tam budham pranamamy aham ||",
        "english_meaning": "I bow to Budha (Mercury), dark as the bud of priyanghu flower, of incomparable form, gentle, endowed with pleasing qualities",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 4",
    },
    {
        "id": "guru_stotra_vyasa",
        "graha": "jupiter",
        "mantra_type": "stotra",
        "name": "Guru Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Devanām ca ṛṣīṇāṃ ca guruṃ kāñcana-sannibham | buddhi-bhūtaṃ trilokesaṃ tam namāmi bṛhaspam ||",
        "transliteration": "Devanam cha rishinam cha gurum kanchana sannibham | buddhi bhutam trilokesham tam namami brihaspatim ||",
        "english_meaning": "I bow to Brihaspati (Jupiter), preceptor of gods and sages, golden in hue, the embodiment of wisdom, lord of the three worlds",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 5",
    },
    {
        "id": "shukra_stotra_vyasa",
        "graha": "venus",
        "mantra_type": "stotra",
        "name": "Shukra Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Himakunda-mṛṇālābhaṃ daityanāṃ paramaṃ gurum | sarvaśāstra-pravaktāraṃ bhārgavaṃ praṇamāmy aham ||",
        "transliteration": "Himakunda mrinalaabham daityaanaam paramam gurum | sarvashastra pravaktaaram bhaargavam pranamamy aham ||",
        "english_meaning": "I bow to Bhargava (Venus/Shukra), white as snow, lotus stalk, and jasmine, supreme preceptor of the demons, proclaimer of all sciences",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 6",
    },
    {
        "id": "shani_stotra_vyasa",
        "graha": "saturn",
        "mantra_type": "stotra",
        "name": "Shani Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Nīlāñjana-samābhāsaṃ ravi-putraṃ yamāgrajam | chāyā-mārtaṇḍa-sambhūtaṃ tam namāmi śanaiścaram ||",
        "transliteration": "Neelanjana samabhasam ravi putram yamagrajam | chaya martanda sambhutam tam namami shanaishcharam ||",
        "english_meaning": "I bow to Shani (Saturn), like blue collyrium in appearance, son of the Sun, elder brother of Yama, born of Chhaya and the Sun",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 7",
    },
    {
        "id": "rahu_stotra_vyasa",
        "graha": "rahu",
        "mantra_type": "stotra",
        "name": "Rahu Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Ardha-kāyaṃ mahā-vīryaṃ candrāditya-vimardanam | siṃhikā-garbha-sambhūtaṃ tam rāhuṃ praṇamāmy aham ||",
        "transliteration": "Ardha kaayam mahaa viryam chandraaditya vimardanam | simhika garbha sambhutam tam rahum pranamamy aham ||",
        "english_meaning": "I bow to Rahu, half-bodied, of great strength, afflicting the Sun and Moon, born from the womb of Simhika",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 8",
    },
    {
        "id": "ketu_stotra_vyasa",
        "graha": "ketu",
        "mantra_type": "stotra",
        "name": "Ketu Navagraha Stotra (Vyasa)",
        "sanskrit_iast": "Palāśa-puṣpa-saṅkāśaṃ tārakā-graha-mastakam | raudraṃ raudra-atmakam ghoraṃ tam ketuṃ praṇamāmy aham ||",
        "transliteration": "Palaasha pushpa sankasham taaraka graha mastakam | raudram raudraatmakam ghoram tam ketum pranamamy aham ||",
        "english_meaning": "I bow to Ketu, bright as the palasha flower, at the head of stars and planets, fierce, of fierce nature, terrible",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Navagraha Stotra (Vyasa), verse 9",
    },

    # ===== MAHA MRITYUNJAYA MANTRA =====
    {
        "id": "maha_mrityunjaya",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Maha Mrityunjaya Mantra",
        "sanskrit_iast": "Oṃ tryambakam yajāmahe sugandhiṃ puṣṭivardhanam | urvārukam iva bandhanān mṛtyor mukṣīya māmṛtāt ||",
        "transliteration": "Om tryambakam yajamahe sugandim pushtivaardhanam | urvaarukam iva bandhanaan mrityormukshiya maamritaat ||",
        "english_meaning": "We worship the three-eyed one (Shiva), who is fragrant and nourishes all beings; may he liberate us from death as a cucumber is severed from its vine, and may we be granted immortality",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Rigveda 7.59.12; Yajurveda 3.60; Shiva Purana",
    },

    # ===== GAYATRI MANTRA =====
    {
        "id": "gayatri_mantra",
        "graha": "sun",
        "mantra_type": "vedic",
        "name": "Gayatri Mantra",
        "sanskrit_iast": "Oṃ bhūr bhuvaḥ svaḥ | tat savitur vareṇyaṃ | bhargo devasya dhīmahi | dhiyo yo naḥ pracodayāt ||",
        "transliteration": "Om bhur bhuvah swaha | tat savitur varenyam | bhargo devasya dheemahi | dhiyo yo nah prachodayat ||",
        "english_meaning": "O Divine light (Savitri), we meditate upon your sacred effulgence; may you illuminate our intellect and inspire our thoughts",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Rigveda 3.62.10; Chandogya Upanishad 3.12.1",
    },

    # ===== SURYA / ADITYA MANTRAS =====
    {
        "id": "aditya_hridayam_seed",
        "graha": "sun",
        "mantra_type": "stotra",
        "name": "Aditya Hridayam (seed verse)",
        "sanskrit_iast": "Ādityaṃ hṛdayaṃ puṇyaṃ sarva-śatru-vināśanam | jayāvahaṃ japennityaṃ akṣayaṃ paramaṃ śivam ||",
        "transliteration": "Aadityam hridayam punyam sarva shatru vinashanam | jayaavaham japen nityam akshayam paramam shivam ||",
        "english_meaning": "The Aditya Hridayam is sacred, destroyer of all enemies, bestower of victory; chanting it daily brings inexhaustible supreme auspiciousness",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Valmiki Ramayana, Yuddha Kanda 107.1",
    },
    {
        "id": "surya_namaskara_mantra",
        "graha": "sun",
        "mantra_type": "vedic",
        "name": "Surya Namaskara Mantra (12 names)",
        "sanskrit_iast": "Oṃ mitrāya namaḥ | ravaiye namaḥ | sūryāya namaḥ | bhānave namaḥ | khagāya namaḥ | pūṣṇe namaḥ | hiraṇyagarbhāya namaḥ | marīcaye namaḥ | ādityāya namaḥ | savitre namaḥ | arkāya namaḥ | bhāskarāya namaḥ ||",
        "transliteration": "Om mitraaya namah | raviiye namah | suryaaya namah | bhaanave namah | khagaaya namah | pushne namah | hiranyagarbhaaya namah | mariichaye namah | aadityaaya namah | savitre namah | arkaaya namah | bhaaskaraaya namah ||",
        "english_meaning": "Salutations to the 12 solar names: Friend, Radiant, Sun, Lustrous, Sky-moving, Nourisher, Golden-embryo, Ray-of-light, Son of Aditi, Vivifier, Brilliant, Light-maker",
        "syllable_count": 48,
        "recommended_count": 12,
        "auspicious_day": "Sunday",
        "classical_citation": "Yajurveda; Ashtanga Namaskara tradition",
    },

    # ===== SHIVA MANTRAS =====
    {
        "id": "om_namah_shivaya",
        "graha": None,
        "mantra_type": "beej",
        "name": "Om Namah Shivaya (Panchakshara)",
        "sanskrit_iast": "Oṃ namaḥ śivāya",
        "transliteration": "Om Namah Shivaya",
        "english_meaning": "Salutations to Shiva; the five syllables Na-Ma-Shi-Va-Ya represent the five elements (earth, water, fire, air, ether) and the five actions of Shiva",
        "syllable_count": 5,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Yajurveda, Shri Rudram, Anuvaka 8; Shiva Purana",
    },
    {
        "id": "shiva_tandava_stotra_seed",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Shiva Tandava Stotram (seed verse)",
        "sanskrit_iast": "Jatatavīgalajjala-pravāha-pāvitasthale galevalambya lambitāṃ bhujaṅga-tuṅga-mālikām | Ḍamaḍḍamaḍḍamaḍḍamaṃ ninādavaddamarvayaṃ chakāra caṇḍtāṇḍavaṃ tanotu naḥ śivaḥ śivam ||",
        "transliteration": "Jatatavigalajjala pravaha pavita sthale galavalam bya lambitam bhujanga tunga malikam | Damadd amadd amadd amam ninaada vaddamarva yam chakara chanda tandavam tanotu nah shivah shivam ||",
        "english_meaning": "May Lord Shiva bestow auspiciousness upon us — he who performs the fierce Tandava dance, with matted locks dripping holy Ganga waters, adorned with a garland of great serpents, resounding the damaru drum",
        "syllable_count": 60,
        "recommended_count": 11,
        "auspicious_day": "Monday",
        "classical_citation": "Ravana-composed Shiva Tandava Stotram, verse 1",
    },
    {
        "id": "shiva_panchakshara_stotra_seed",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Shiva Panchakshara Stotram (seed verse)",
        "sanskrit_iast": "Nagendra-hārāya trilocanaaya bhasmaṅga-rāgāya maheshvarāya | nityāya śuddhāya digambarāya tasmai na-kārāya namaḥ śivāya ||",
        "transliteration": "Nagendra haaraaya trilochanaaaya bhasmaanga raagaaya maheshvaraaya | nityaaya shuddhaaya digambaraaya tasmai na kaaraaya namah shivaaya ||",
        "english_meaning": "Salutations to Shiva (Na-syllable): lord of serpents, three-eyed, smeared with ash, the great lord, eternal, pure, clad in the sky",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Adi Shankaracharya, Shiva Panchakshara Stotram, verse 1",
    },

    # ===== VISHNU / NARAYANA MANTRAS =====
    {
        "id": "vishnu_sahasranama_seed",
        "graha": None,
        "mantra_type": "sahsranama",
        "name": "Vishnu Sahasranama (phala-shruti)",
        "sanskrit_iast": "Oṃ namo bhagavate vāsudevāya",
        "transliteration": "Om namo bhagavate Vasudevaya",
        "english_meaning": "Om, salutations to the adorable Lord Vasudeva (Krishna/Vishnu); the 12-syllable dvadasakshara mantra of liberation",
        "syllable_count": 12,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Mahabharata, Anushasana Parva 149; Vishnu Purana",
    },
    {
        "id": "om_namo_narayanaya",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Ashtakshara Mantra (Om Namo Narayanaya)",
        "sanskrit_iast": "Oṃ namo nārāyaṇāya",
        "transliteration": "Om namo Narayanaya",
        "english_meaning": "Salutations to Narayana; the eight-syllable mantra that grants moksha",
        "syllable_count": 8,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Yajurveda, Narayana Suktam; Vishnu Purana",
    },

    # ===== HANUMAN MANTRAS =====
    {
        "id": "hanuman_chalisa_seed",
        "graha": None,
        "mantra_type": "chalisa",
        "name": "Hanuman Chalisa (doha + first chaupai)",
        "sanskrit_iast": "Śrī guru carana saroja raja nija manu mukura sudhāri | baranau raghubara bimala jasu jo dāyaku phala cāri || Jay Hanumān gyāna guṇa sāgara | Jay Kapīśa tihu loka ujāgara ||",
        "transliteration": "Shri guru charana saroja raja nija manu mukura sudhaari | baranau raghubara bimala jasu jo daayaku phala chaari || Jai Hanuman gyaana guna saagara | Jai Kapis tihu loka ujaagara ||",
        "english_meaning": "Cleansing the mirror of my heart with the dust of my Guru's lotus feet, I narrate the pure glory of Rama, the best of Raghus, which bestows the four fruits of life. Victory to Hanuman, ocean of wisdom and virtue; Victory to the Lord of monkeys, illuminator of the three worlds",
        "syllable_count": 64,
        "recommended_count": 7,
        "auspicious_day": "Tuesday",
        "classical_citation": "Tulsidas, Hanuman Chalisa (Ramcharitmanas appendix), doha 1 + chaupai 1",
    },
    {
        "id": "hanuman_beej_mantra",
        "graha": None,
        "mantra_type": "beej",
        "name": "Hanuman Beej Mantra",
        "sanskrit_iast": "Oṃ hauṃ haṃ hanumantāya rudrātmakāya hūṃ phaṭ",
        "transliteration": "Om haum ham Hanumate Rudratmakaaya hum phat",
        "english_meaning": "Salutations to Hanuman, the embodiment of Rudra; dispel all obstacles (Hum Phat is the weapon-syllable for protection)",
        "syllable_count": 11,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Hanuman Upanishad; Tantra Sara",
    },

    # ===== GANESHA MANTRAS =====
    {
        "id": "ganesha_vandana",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Ganesha Vandana (Vakratunda)",
        "sanskrit_iast": "Vakratuṇḍa mahā-kāya sūrya-koṭi-samaprabha | nirvighnaṃ kuru me deva sarva-kāryeṣu sarvadā ||",
        "transliteration": "Vakratunda mahaa kaaya surya koti sama prabha | nirvighnam kuru me deva sarva kaaryeshu sarvadaa ||",
        "english_meaning": "O Ganesha, of curved trunk, mighty body, with radiance equal to a million suns; make all my undertakings obstacle-free, always",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Ganesha Purana; traditional auspicious invocation",
    },
    {
        "id": "ganesha_beej_mantra",
        "graha": None,
        "mantra_type": "beej",
        "name": "Ganesha Beej Mantra (Gam)",
        "sanskrit_iast": "Oṃ gaṃ gaṇapataye namaḥ",
        "transliteration": "Om Gam Ganapataye Namah",
        "english_meaning": "Salutations to Ganapati (Ganesha), the lord of hosts; Gam is the seed syllable of Ganesha",
        "syllable_count": 6,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Ganapati Atharvasirsha Upanishad; Ganesha Purana",
    },

    # ===== DEVI / SHAKTI MANTRAS =====
    {
        "id": "durga_stotra_seed",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Durga Stotram (Ya Devi)",
        "sanskrit_iast": "Yā devī sarva-bhūteṣu śakti-rūpeṇa saṃsthitā | namastasyai namastasyai namastasyai namo namaḥ ||",
        "transliteration": "Yaa devi sarva bhuteshu shakti-roopena sansthitaa | namastasyai namastasyai namastasyai namo namah ||",
        "english_meaning": "To the Goddess who dwells in all beings in the form of Power, salutations to her, salutations to her, salutations to her, obeisance again and again",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Devi Mahatmyam (Durga Saptashati), Markandeya Purana 5.12–82",
    },
    {
        "id": "durga_beej_mantra",
        "graha": None,
        "mantra_type": "beej",
        "name": "Durga Beej Mantra (Dum)",
        "sanskrit_iast": "Oṃ duṃ durgāyai namaḥ",
        "transliteration": "Om Dum Durgayai Namah",
        "english_meaning": "Salutations to Durga; Dum is the seed syllable of the fierce protective Goddess",
        "syllable_count": 6,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Tantrasara; Devi Bhagavata Purana",
    },
    {
        "id": "lakshmi_stotra_seed",
        "graha": "venus",
        "mantra_type": "stotra",
        "name": "Sri Lakshmi Stotram (seed verse)",
        "sanskrit_iast": "Namaste'stu mahāmāye śrī-pīṭhe sura-pūjite | śaṅkha-cakra-gadā-haste mahālakṣmi namo'stu te ||",
        "transliteration": "Namaste'stu mahamaaye shri pithe sura pujite | shankha chakra gadaa haste mahalakshmi namo'stu te ||",
        "english_meaning": "Salutations to the great illusion, worshipped on the sacred seat by gods; holding conch, discus, and mace — salutations to Mahalakshmi",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Mahalakshmi Ashtakam; Padma Purana",
    },
    {
        "id": "lakshmi_beej_mantra",
        "graha": "venus",
        "mantra_type": "beej",
        "name": "Shrim Lakshmi Beej Mantra",
        "sanskrit_iast": "Oṃ śrīṃ mahālakṣmyai namaḥ",
        "transliteration": "Om Shreem Mahalakshmyai Namah",
        "english_meaning": "Salutations to Mahalakshmi; Shreem is the seed syllable of abundance, beauty, and prosperity",
        "syllable_count": 6,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Tantrasara; Lakshmi Tantra",
    },
    {
        "id": "saraswati_vandana",
        "graha": "mercury",
        "mantra_type": "stotra",
        "name": "Saraswati Vandana",
        "sanskrit_iast": "Yā kundendu-tuṣāra-hāra-dhavalā yā śubhra-vastrāvṛtā | yā vīṇā-vara-daṇḍa-maṇḍita-karā yā śveta-padmāsanā ||",
        "transliteration": "Yaa kundeindu tushara haara dhavalaa yaa shubhra vastraa vritaa | yaa veenaa vara danda mandita karaa yaa shveta padmaasanaa ||",
        "english_meaning": "She who is white as a kunda flower, the moon, snow, and a garland; clad in white garments; whose hands are adorned with the vina; seated on a white lotus — may that Goddess Saraswati protect me",
        "syllable_count": 40,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Traditional; Saraswati Vandana, Adi Shankaracharya tradition",
    },
    {
        "id": "saraswati_beej_mantra",
        "graha": "mercury",
        "mantra_type": "beej",
        "name": "Aim Saraswati Beej Mantra",
        "sanskrit_iast": "Oṃ aiṃ sarasvatyai namaḥ",
        "transliteration": "Om Aim Saraswatyai Namah",
        "english_meaning": "Salutations to Saraswati; Aim is the seed syllable of the goddess of learning, wisdom, and arts",
        "syllable_count": 6,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Tantrasara; Saraswati Tantra",
    },

    # ===== UNIVERSAL BEEJ MANTRAS =====
    {
        "id": "om_pranava",
        "graha": None,
        "mantra_type": "beej",
        "name": "Om / Pranava (Primordial Beej)",
        "sanskrit_iast": "Oṃ",
        "transliteration": "Om / Aum",
        "english_meaning": "The primordial sound, the source of all creation; comprises A (creation/Brahma), U (preservation/Vishnu), M (dissolution/Shiva); the universal beej mantra",
        "syllable_count": 1,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Mandukya Upanishad 1; Rigveda (praNava); Patanjali Yoga Sutras 1.27",
    },
    {
        "id": "hreem_shakti_beej",
        "graha": None,
        "mantra_type": "beej",
        "name": "Hreem — Maya Beej (Shakti)",
        "sanskrit_iast": "Hrīṃ",
        "transliteration": "Hreem",
        "english_meaning": "The maya-beej or shakti-beej; seed of the Divine Mother; activates the solar plexus and heart; associated with manifestation of divine energy",
        "syllable_count": 1,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Tantrasara; Kularnava Tantra; Devi Bhagavata Purana",
    },
    {
        "id": "kleem_attraction_beej",
        "graha": None,
        "mantra_type": "beej",
        "name": "Kleem — Kama Beej (Attraction)",
        "sanskrit_iast": "Klīṃ",
        "transliteration": "Kleem",
        "english_meaning": "The kama-beej; seed syllable of attraction, desire fulfilment, and the power of Venus/Krishna; draws abundance and relationships",
        "syllable_count": 1,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Tantrasara; Kamakhya Tantra; associated with Venus (Shukra)",
    },
    {
        "id": "hum_shiva_protection_beej",
        "graha": None,
        "mantra_type": "beej",
        "name": "Hum — Shiva Protection Beej",
        "sanskrit_iast": "Hūṃ",
        "transliteration": "Hum",
        "english_meaning": "The Shiva protection beej; cuts through ignorance and negative forces; the weapon syllable that dispels ego and illusion",
        "syllable_count": 1,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Shiva Purana; Hevajra Tantra; Mahanirvana Tantra",
    },
    {
        "id": "phat_dispelling_beej",
        "graha": None,
        "mantra_type": "beej",
        "name": "Phat — Weapon Beej (Dispelling)",
        "sanskrit_iast": "Phaṭ",
        "transliteration": "Phat",
        "english_meaning": "The astra-beej (weapon-seed); used at the end of mantras to dispel negative energies, break obstacles, and consecrate ritual actions",
        "syllable_count": 1,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Tantra tradition; Shaiva Agamas; Devi Mahatmyam ritual usage",
    },
    {
        "id": "soham_identity_mantra",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Soham — Identity Mantra",
        "sanskrit_iast": "So'ham",
        "transliteration": "So-Ham (Sah + Aham)",
        "english_meaning": "I am That (So = He/That; Ham = I/Self); the natural mantra of the breath — Soham on inhalation (So), Hamsa on exhalation; realises non-dual identity with Brahman",
        "syllable_count": 2,
        "recommended_count": 21600,
        "auspicious_day": "Monday",
        "classical_citation": "Isha Upanishad 16; Vijnana Bhairava Tantra 155; Hatha Yoga Pradipika 4.49",
    },
    {
        "id": "aham_brahmasmi",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Aham Brahmasmi — Great Saying (Mahavakya)",
        "sanskrit_iast": "Ahaṃ brahmāsmi",
        "transliteration": "Aham Brahmasmi",
        "english_meaning": "I am Brahman (the Absolute); one of the four Mahavakyas (great sayings) of the Upanishads; the mahavakya of the Yajurveda tradition affirming the identity of individual self (Atman) with the universal absolute (Brahman)",
        "syllable_count": 5,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Brihadaranyaka Upanishad 1.4.10; Yajurveda tradition",
    },

    # ===== ADDITIONAL GRAHA-SPECIFIC VEDIC MANTRAS =====
    {
        "id": "surya_gayatri",
        "graha": "sun",
        "mantra_type": "vedic",
        "name": "Surya Gayatri Mantra",
        "sanskrit_iast": "Oṃ ādityadevāya vidmahe sahasrakiraṇāya dhīmahi | tanno bāskaraḥ pracodayāt ||",
        "transliteration": "Om Aadityadevaya vidmahe sahasra kiranaya dheemahi | tanno bhaskarah prachodayat ||",
        "english_meaning": "We know the Sun-god of a thousand rays; may that Sun (Bhaskara) illuminate and inspire our intellect",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Gayatri tradition; Surya Upanishad",
    },
    {
        "id": "chandra_gayatri",
        "graha": "moon",
        "mantra_type": "vedic",
        "name": "Chandra Gayatri Mantra",
        "sanskrit_iast": "Oṃ śītalāya vidmahe jyotsnāpradāya dhīmahi | tannaś candraḥ pracodayāt ||",
        "transliteration": "Om sheetalaya vidmahe jyotsna pradaya dheemahi | tannas chandrah prachodayat ||",
        "english_meaning": "We know the cool (Moon); we meditate on the giver of moonlight; may that Moon enlighten and inspire us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Gayatri tradition; Soma Suktam",
    },
    {
        "id": "mangala_gayatri",
        "graha": "mars",
        "mantra_type": "vedic",
        "name": "Mangala Gayatri Mantra",
        "sanskrit_iast": "Oṃ aṅgārakāya vidmahe bhauma-putrāya dhīmahi | tanno mangalaḥ pracodayāt ||",
        "transliteration": "Om Angaarakaaya vidmahe bhauma putraaya dheemahi | tanno mangalah prachodayat ||",
        "english_meaning": "We know Angaaraka (Mars); we meditate on the son of Earth; may Mars inspire and guide us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },
    {
        "id": "budha_gayatri",
        "graha": "mercury",
        "mantra_type": "vedic",
        "name": "Budha Gayatri Mantra",
        "sanskrit_iast": "Oṃ saumya-rūpāya vidmahe vaṇeśvarāya dhīmahi | tanno budhaḥ pracodayāt ||",
        "transliteration": "Om saumya roopaya vidmahe vaneshvaraaya dheemahi | tanno budhah prachodayat ||",
        "english_meaning": "We know the gentle-formed Mercury, lord of commerce and speech; may Budha illuminate and inspire us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },
    {
        "id": "guru_gayatri",
        "graha": "jupiter",
        "mantra_type": "vedic",
        "name": "Guru Gayatri Mantra",
        "sanskrit_iast": "Oṃ vṛṣabha-dhvajāya vidmahe kṛṇī-hastāya dhīmahi | tanno guruḥ pracodayāt ||",
        "transliteration": "Om vrishabha dwajaaya vidmahe krini hastaaya dheemahi | tanno guruh prachodayat ||",
        "english_meaning": "We know the one bearing the bull-flag, holding the vessel of nectar; may Guru (Jupiter) enlighten and inspire us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },
    {
        "id": "shukra_gayatri",
        "graha": "venus",
        "mantra_type": "vedic",
        "name": "Shukra Gayatri Mantra",
        "sanskrit_iast": "Oṃ rājadabhāya vidmahe bhṛgu-suthāya dhīmahi | tanno śukraḥ pracodayāt ||",
        "transliteration": "Om raajadabhaaya vidmahe bhrigu suthaaya dheemahi | tanno shukrah prachodayat ||",
        "english_meaning": "We know the gem-like Venus, son of Bhrigu; may Shukra inspire and enlighten us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },
    {
        "id": "shani_gayatri",
        "graha": "saturn",
        "mantra_type": "vedic",
        "name": "Shani Gayatri Mantra",
        "sanskrit_iast": "Oṃ kāka-dhvajāya vidmahe khaḍga-hastāya dhīmahi | tanno mandaḥ pracodayāt ||",
        "transliteration": "Om kaaka dwajaaya vidmahe khadga hastaaya dheemahi | tanno mandah prachodayat ||",
        "english_meaning": "We know the one bearing the crow-flag, holding a sword; may Manda (slow-Saturn) enlighten and inspire us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },
    {
        "id": "rahu_gayatri",
        "graha": "rahu",
        "mantra_type": "vedic",
        "name": "Rahu Gayatri Mantra",
        "sanskrit_iast": "Oṃ śiro-rūpāya vidmahe amṛteśāya dhīmahi | tanno rāhuḥ pracodayāt ||",
        "transliteration": "Om shiro roopaaya vidmahe amriteshaaya dheemahi | tanno rahuh prachodayat ||",
        "english_meaning": "We know the one who is only a head, lord of amrita (nectar); may Rahu enlighten and inspire us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },
    {
        "id": "ketu_gayatri",
        "graha": "ketu",
        "mantra_type": "vedic",
        "name": "Ketu Gayatri Mantra",
        "sanskrit_iast": "Oṃ aśva-dhvajāya vidmahe sūkṣma-dehāya dhīmahi | tanno ketuḥ pracodayāt ||",
        "transliteration": "Om ashva dwajaaya vidmahe sukshma dehaaya dheemahi | tanno ketuh prachodayat ||",
        "english_meaning": "We know the horse-flag bearer, of subtle body; may Ketu enlighten and inspire us",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Gayatri tradition; Navagraha Gayatri collection",
    },

    # ===== VEDIC PLANETARY MANTRAS (Rigveda/Atharvaveda) =====
    {
        "id": "surya_vedic_aditya_suktam",
        "graha": "sun",
        "mantra_type": "vedic",
        "name": "Surya Mantra — Aditya Suktam (seed)",
        "sanskrit_iast": "Udyannādya mitramaha ārohannuttarāṃ divam | hṛdrogaṃ mama sūrya harimāṇaṃ ca nāśaya ||",
        "transliteration": "Udyan naadya mitra maha arohann uttaraam divam | hridrogam mama surya harimanaam cha naashaya ||",
        "english_meaning": "O Sun, great friend, rising today and ascending to the higher sky, destroy my heart disease and jaundice",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Rigveda 1.50.12; Atharvaveda 1.22.1 (healing aspect of Surya)",
    },
    {
        "id": "soma_vedic_mantra",
        "graha": "moon",
        "mantra_type": "vedic",
        "name": "Soma Vedic Mantra",
        "sanskrit_iast": "Oṃ apaḥ śīte apyāyasva saṃte viśvantu bheṣajā | imaṃ me vara śāntim āśāsāno mayobhava ||",
        "transliteration": "Om apah sheete apyayasva sam te vishvantu bheshaja | imam me vara shaantim aashaasaano mayo bhava ||",
        "english_meaning": "O Soma (Moon), expand and increase; let all medicines enter you; be a source of happiness and peace for me",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Monday",
        "classical_citation": "Rigveda 10.59.7; Yajurveda Soma chapter",
    },

    # ===== ADDITIONAL STOTRA ENTRIES =====
    {
        "id": "shani_shanti_stotra",
        "graha": "saturn",
        "mantra_type": "stotra",
        "name": "Shani Shanti Stotra (seed verse)",
        "sanskrit_iast": "Sūryaputro dīrghadehī viśāḍakṣo mahābalaḥ | mandacāraḥ prasannātmā pīḍāṃ haratu me śaniḥ ||",
        "transliteration": "Sooryaputro deerghadehee vishaadaaksho mahaabalaḥ | mandachaaraḥ prasannaatmaa peedaam haratu me shaniḥ ||",
        "english_meaning": "May Saturn — son of the Sun, with a large body, wide eyes, of great strength, slow-moving, of serene soul — remove my afflictions",
        "syllable_count": 32,
        "recommended_count": 23000,
        "auspicious_day": "Saturday",
        "classical_citation": "Shani Mahatmya; Skanda Purana",
    },
    {
        "id": "rahu_ketu_shanti_mantra",
        "graha": "rahu",
        "mantra_type": "stotra",
        "name": "Rahu-Ketu Shanti Mantra",
        "sanskrit_iast": "Oṃ rāhave namaḥ | oṃ ketave namaḥ | rahuketu praśamana mantra ||",
        "transliteration": "Om rahave namah | Om ketave namah | Rahu Ketu prashamana mantra",
        "english_meaning": "Salutations to Rahu; salutations to Ketu; this mantra pacifies the nodes and their karmic imprints",
        "syllable_count": 14,
        "recommended_count": 18000,
        "auspicious_day": "Saturday",
        "classical_citation": "Navagraha Shanti tradition; BPHS remedial chapter",
    },
    {
        "id": "navagraha_stotra_complete_invocation",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Navagraha Stotra — Complete Invocation (Vyasa)",
        "sanskrit_iast": "Brahmā maureśca pūrṇeśca… (9-verse composite as per Vyasa's Navagraha Stotra)",
        "transliteration": "Brahma Muresh cha Purnesh cha... (9-verse Vyasa Navagraha Stotra)",
        "english_meaning": "The complete nine-planet stotra composed by Vyasa; nine verses in sequence for Sun through Ketu; recited at planetary hour changes, Navagraha puja, and before planetary remediation",
        "syllable_count": 288,
        "recommended_count": 9,
        "auspicious_day": "Sunday",
        "classical_citation": "Vyasa, Navagraha Stotra (Skanda Purana attribution)",
    },

    # ===== ADDITIONAL WIDELY-USED BEEJ MANTRAS =====
    {
        "id": "dum_durga_beej_extended",
        "graha": None,
        "mantra_type": "beej",
        "name": "Dum Durga Extended Beej",
        "sanskrit_iast": "Oṃ duṃ duṃ durgāyai namaḥ | oṃ śrīṃ hrīṃ klīṃ mahiṣamardinī svāhā ||",
        "transliteration": "Om Dum Dum Durgayai Namah | Om Shreem Hreem Kleem Mahishamardini Svaha ||",
        "english_meaning": "Salutations to Durga (×2); Om, with Shreem+Hreem+Kleem, the slayer of the buffalo-demon, svaha (offering to fire)",
        "syllable_count": 14,
        "recommended_count": 1008,
        "auspicious_day": "Friday",
        "classical_citation": "Devi Upasana; Tantrasara ch.11",
    },
    {
        "id": "aim_saraswati_vidya_beej",
        "graha": "mercury",
        "mantra_type": "beej",
        "name": "Aim — Vidya Beej (Learning/Speech)",
        "sanskrit_iast": "Oṃ aiṃ hrīṃ śrīṃ vāgdevyai sarasvatyai namaḥ",
        "transliteration": "Om Aim Hreem Shreem Vaagdevyai Saraswatyai Namah",
        "english_meaning": "Salutations to the Goddess of Speech (Saraswati) — using the combined seed syllables Aim (wisdom), Hreem (shakti), Shreem (abundance)",
        "syllable_count": 9,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Saraswati Tantra; Devi Bhagavata tradition",
    },
    {
        "id": "krishna_beej_mantra",
        "graha": None,
        "mantra_type": "beej",
        "name": "Krishna Beej Mantra (Kleem)",
        "sanskrit_iast": "Oṃ klīṃ kṛṣṇāya govindāya gopī-jana-vallabhāya svāhā",
        "transliteration": "Om Kleem Krishnaya Govindaya Gopi Jana Vallabhaya Svaha",
        "english_meaning": "Om, Kleem (attraction-beej), salutations to Krishna, Govinda, the beloved of the gopis, svaha",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Krishna Upanishad; Gopala Tapani Upanishad",
    },

    # ===== SHANI / SATURN EXTENDED MANTRAS =====
    {
        "id": "shani_dasharatha_stotra_seed",
        "graha": "saturn",
        "mantra_type": "stotra",
        "name": "Dasharatha Shani Stotra (seed)",
        "sanskrit_iast": "Namastestu śanaiścāra sūryaputra mahābhuja | tama-rūpa namas te'stu namaste babhru-rūpiṇe ||",
        "transliteration": "Namaste stu shanaischaraa suryaputra mahaabhuja | tama roopa namas te'stu namaste babhru rupine ||",
        "english_meaning": "Salutations to Shani, son of the Sun, of great arms, of dark form; salutations to the one of brownish form",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "Dasharatha Shani Stotra; Skanda Purana Shani Mahatmya",
    },
    {
        "id": "shani_oil_lamp_mantra",
        "graha": "saturn",
        "mantra_type": "vedic",
        "name": "Shani Dipa Mantra (Saturday Oil Lamp)",
        "sanskrit_iast": "Oṃ śaṃ śanaiścarāya namaḥ",
        "transliteration": "Om Sham Shanaischaraya Namah",
        "english_meaning": "Salutations to Saturn; the Sham beej is the planetary-seed of Saturn; chanted while lighting a sesame-oil lamp on Saturday evenings",
        "syllable_count": 6,
        "recommended_count": 108,
        "auspicious_day": "Saturday",
        "classical_citation": "BPHS ch.86 remedial rituals; Shani Kavach tradition",
    },

    # ===== JUPITER EXTENDED MANTRAS =====
    {
        "id": "brihaspati_stuti",
        "graha": "jupiter",
        "mantra_type": "stotra",
        "name": "Brihaspati Stuti",
        "sanskrit_iast": "Bṛhaspatir ati yarad aryo archād dvi-māyā śitapadā divi-mūtā | ya itthā tasya viśvaveda āvivāsati sa ṛdhyāt ||",
        "transliteration": "Brihaspatir ati yarad aryo archaad dvimaaya shitapadaa divimutaa | ya ittham tasya vishvaveda aavivaa sati sa ridhyaat ||",
        "english_meaning": "Brihaspati (Jupiter), who surpasses the stranger, who is worshipped by the two beings, who travels in the sky with white feet, the all-knowing one — may he prosper",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Rigveda 4.50.6; Brihaspati Suktam",
    },

    # ===== VENUS EXTENDED MANTRAS =====
    {
        "id": "shukra_kavach_seed",
        "graha": "venus",
        "mantra_type": "stotra",
        "name": "Shukra Kavach (seed verse)",
        "sanskrit_iast": "Śirasaṃ me śukraḥ pātu bhruvau caivāditeḥ sutaḥ | netrau ca sūkṣma-dṛk pātu śrotṛ me bhārgava-priyaḥ ||",
        "transliteration": "Shirasam me shukrah paatu bhruvau chaivaadite sutah | netrau cha sukshma drik paatu shrotri me bhaargava priyaḥ ||",
        "english_meaning": "May Shukra (Venus) protect my head; may the son of Aditi protect my eyebrows; may the subtle-seer protect my eyes; may the beloved of Bhrigu protect my ears",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Friday",
        "classical_citation": "Shukra Kavach; Skanda Purana",
    },

    # ===== MERCURY EXTENDED MANTRAS =====
    {
        "id": "budha_kavach_seed",
        "graha": "mercury",
        "mantra_type": "stotra",
        "name": "Budha Kavach (seed verse)",
        "sanskrit_iast": "Budhaḥ pāttu śiraḥ pādau netre pātu śubhapradaḥ | mukhaṃ somasutas tubhyaṃ grīvāṃ pātu vāṇīpatiḥ ||",
        "transliteration": "Budhah paatu shirah paadau netre paatu shubhapradah | mukham somasutah tubhyam griivam paatu vaanipatih ||",
        "english_meaning": "May Budha protect the head and feet; may the bestower of auspiciousness protect the eyes; may the son of Soma protect the face; may the lord of speech protect the neck",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Budha Kavach; Skanda Purana",
    },

    # ===== MARS EXTENDED MANTRAS =====
    {
        "id": "mangala_kavach_seed",
        "graha": "mars",
        "mantra_type": "stotra",
        "name": "Mangala Kavach (seed verse)",
        "sanskrit_iast": "Dharaṇī-garbha-jo mauḍhye pāttu pādau ca māṃ sadā | bhujalāṃ lalāṭaṃ caiva kāmo dānaṃ ca saukhyakṛt ||",
        "transliteration": "Dharani garbhajo maudhye paattu paadau cha maam sadaa | bhujalam lalaatam chaiva kaamo daanam cha saukhyakrit ||",
        "english_meaning": "May Mars (born of the womb of Earth) always protect my feet and forehead; may he bestow desire, generosity, and happiness",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Mangala Kavach; Skanda Purana; Lal Kitab tradition",
    },

    # ===== SOLAR / SURYA EXTENDED =====
    {
        "id": "surya_kavach_seed",
        "graha": "sun",
        "mantra_type": "stotra",
        "name": "Surya Kavach (seed verse)",
        "sanskrit_iast": "Śirasaṃ sūryaḥ pātu lalāṭaṃ pātu bhāskaraḥ | netrau ca aditya-putraś ca śrotṛ vivasvān pātu me ||",
        "transliteration": "Shirasam suryah paatu lalaatam paatu bhaskarah | netrau cha aditya putras cha shrotri vivassvan paatu me ||",
        "english_meaning": "May the Sun protect my head; may Bhaskara (the luminous one) protect my forehead; may Aditya-putra protect my eyes; may Vivasvat protect my ears",
        "syllable_count": 32,
        "recommended_count": 7,
        "auspicious_day": "Sunday",
        "classical_citation": "Surya Kavach; Bhavishya Purana; BPHS remedial chapter",
    },
    {
        "id": "aditya_hridayam_full",
        "graha": "sun",
        "mantra_type": "stotra",
        "name": "Aditya Hridayam — Full Stotra Reference",
        "sanskrit_iast": "Tato yuddhapariśrāntaṃ samare cintayā sthitam | rāvaṇaṃ cāgrato dṛṣṭvā yuddhe cintāparo'bhavat || Tadā'gastyam mahān ṛṣiḥ… (31 verses)",
        "transliteration": "Tato yuddha parishraantam samare chintayaa sthitam | raavanam chaagrato drishtvaaa yuddhe chintaaparo'bhavat || Tadaagastyam mahan rishih... (31 verses)",
        "english_meaning": "The Aditya Hridayam — the 31-verse solar hymn taught by sage Agastya to Rama on the battlefield; destroyer of all enemies, bestower of victory, longevity and liberation",
        "syllable_count": 992,
        "recommended_count": 3,
        "auspicious_day": "Sunday",
        "classical_citation": "Valmiki Ramayana, Yuddha Kanda 107 (verses 1-31)",
    },

    # ===== RAHU EXTENDED =====
    {
        "id": "rahu_kavach_seed",
        "graha": "rahu",
        "mantra_type": "stotra",
        "name": "Rahu Kavach (seed verse)",
        "sanskrit_iast": "Rāhuḥ pāttu śiraḥ pādau kaṇṭhaṃ pātu dharādharaḥ | netrau ca ketu nāśakaḥ śrotraṃ sūrya-pituḥ sutaḥ ||",
        "transliteration": "Rahuh paattu shirah paadau kantham paatu dharaadharah | netrau cha ketu naashakaḥ shrotram surya pituh sutah ||",
        "english_meaning": "May Rahu protect my head and feet; may the bearer of the earth protect the throat; may the destroyer of Ketu protect the eyes; may the son of the Sun's father protect the ears",
        "syllable_count": 32,
        "recommended_count": 18000,
        "auspicious_day": "Saturday",
        "classical_citation": "Rahu Kavach; Skanda Purana; Tantrasara",
    },

    # ===== KETU EXTENDED =====
    {
        "id": "ketu_kavach_seed",
        "graha": "ketu",
        "mantra_type": "stotra",
        "name": "Ketu Kavach (seed verse)",
        "sanskrit_iast": "Pādau ketupatiḥ pātu jānunī mātṛ-pūjitaḥ | kaṭiṃ pātu mahā-ketu-patiḥ kukṣiṃ śarīrajaḥ ||",
        "transliteration": "Paadau ketupatiḥ paatu jaanuni maatri pujitah | katim paatu mahaaketu patih kukshim shareeraja ||",
        "english_meaning": "May the lord of Ketu protect the feet; may the mother-worshipped one protect the knees; may the great Ketu-lord protect the waist; may the body-born one protect the belly",
        "syllable_count": 32,
        "recommended_count": 17000,
        "auspicious_day": "Tuesday",
        "classical_citation": "Ketu Kavach; Skanda Purana; Tantrasara",
    },

    # ===== UNIVERSAL MANTRAS =====
    {
        "id": "om_shanti_trikayam",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Om Shanti (Triple Peace)",
        "sanskrit_iast": "Oṃ śāntiḥ śāntiḥ śāntiḥ",
        "transliteration": "Om Shanti Shanti Shanti",
        "english_meaning": "Om Peace Peace Peace — the triple shanti addresses the three types of disturbances: adhidaivika (celestial/astrological), adhibhautika (material/worldly), adhyatmika (internal/spiritual)",
        "syllable_count": 4,
        "recommended_count": 3,
        "auspicious_day": "Sunday",
        "classical_citation": "Upanishadic closing invocation; Brihadaranyaka Upanishad etc.",
    },
    {
        "id": "asato_ma_shanti_patha",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Asato Ma (Shanti Patha)",
        "sanskrit_iast": "Asato mā sad gamaya | tamaso mā jyotir gamaya | mṛtyor mā amṛtaṃ gamaya | oṃ śāntiḥ śāntiḥ śāntiḥ ||",
        "transliteration": "Asato maa sad gamaya | tamaso maa jyotir gamaya | mrityormaa amritam gamaya | Om Shantih Shantih Shantih ||",
        "english_meaning": "Lead me from untruth to truth, from darkness to light, from death to immortality; Om Peace Peace Peace",
        "syllable_count": 24,
        "recommended_count": 3,
        "auspicious_day": "Monday",
        "classical_citation": "Brihadaranyaka Upanishad 1.3.28",
    },
    {
        "id": "purna_mada_shanti_patha",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Purna Mada (Isha Upanishad Shanti Patha)",
        "sanskrit_iast": "Oṃ pūrṇam adaḥ pūrṇam idaṃ pūrṇāt pūrṇam udacyate | pūrṇasya pūrṇam ādāya pūrṇam evāvaśiṣyate | oṃ śāntiḥ śāntiḥ śāntiḥ ||",
        "transliteration": "Om poornam adah poornam idam poornaat poornam udachyate | poornasya poornam aadaaya poornam evaavashishyate | Om Shantih Shantih Shantih ||",
        "english_meaning": "That is whole; this is whole; from wholeness emerges wholeness; taking wholeness from wholeness, wholeness alone remains — Om Peace Peace Peace",
        "syllable_count": 28,
        "recommended_count": 3,
        "auspicious_day": "Sunday",
        "classical_citation": "Isha Upanishad, Shanti Patha; Brihadaranyaka Upanishad",
    },
    {
        "id": "sarveshaam_shanti_mantra",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Sarveshan Shanti Mantra (Universal Welfare)",
        "sanskrit_iast": "Sarveśāṃ svastir bhavatu | sarveśāṃ śāntir bhavatu | sarveśāṃ pūrṇaṃ bhavatu | sarveśāṃ maṅgalam bhavatu ||",
        "transliteration": "Sarveshaam svastir bhavatu | Sarveshaam shaantir bhavatu | Sarveshaam poornam bhavatu | Sarveshaam mangalam bhavatu ||",
        "english_meaning": "May there be well-being for all; may there be peace for all; may there be fulfilment for all; may there be auspiciousness for all",
        "syllable_count": 20,
        "recommended_count": 3,
        "auspicious_day": "Sunday",
        "classical_citation": "Traditional Vedic prayer; Atharva Veda-related",
    },
    {
        "id": "lokah_samastah_sukhino",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Lokah Samastah (Universal Peace)",
        "sanskrit_iast": "Lokāḥ samastāḥ sukhino bhavantu | oṃ śāntiḥ śāntiḥ śāntiḥ ||",
        "transliteration": "Lokah samastah sukhino bhavantu | Om Shantih Shantih Shantih ||",
        "english_meaning": "May all beings in all worlds be happy; Om Peace Peace Peace — a universal compassion prayer transcending individual welfare",
        "syllable_count": 10,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Rigveda tradition; traditional yoga-shala closing; attributed to Advaita tradition",
    },

    # ===== ADDITIONAL SAHSRANAMA / CHALISA =====
    {
        "id": "vishnu_sahasranama_first_nama",
        "graha": None,
        "mantra_type": "sahsranama",
        "name": "Vishnu Sahasranama — Opening (Dhyana Shloka)",
        "sanskrit_iast": "Śhāntākāraṃ bhujagaśayanaṃ padmanābhaṃ sureśam | viśvādhāraṃ gaganasadṛśaṃ meghavarṇaṃ śubhāṅgam | lakṣmīkāntaṃ kamalanayanam yogibhirdhyānagamyam | vande viṣṇum bhavabhayaharaṃ sarvalokaikanātham ||",
        "transliteration": "Shaantaakaaram bhujagashayanam padmanaabham sureshham | vishvaadhaaram gaganasadrisham meghavarnam shubhaangam | lakshmikaantam kamalanayanam yogibhirdhyaanagamyam | vande vishnumbhava bhayaharam sarvalokaikanaatham ||",
        "english_meaning": "I bow to Vishnu, serene in form, reclining on the serpent, lotus-naveled, lord of gods, support of the universe, sky-like, cloud-coloured, of auspicious limbs, beloved of Lakshmi, lotus-eyed, attained by yogis in meditation, remover of worldly fear, sole lord of all worlds",
        "syllable_count": 56,
        "recommended_count": 1,
        "auspicious_day": "Thursday",
        "classical_citation": "Vishnu Sahasranama, Dhyana Shloka; Mahabharata Anushasana Parva 149",
    },
    {
        "id": "hanuman_chalisa_closing_doha",
        "graha": None,
        "mantra_type": "chalisa",
        "name": "Hanuman Chalisa — Closing Doha",
        "sanskrit_iast": "Pava tanaya saṅkaṭa haraṇa maṅgala mūrati rūpa | rāma lakṣmana sītā sahita hṛday basahu sura bhūpa ||",
        "transliteration": "Pava tanaya sankat harana mangala moorati roopa | Raama Lakshmana Seetaa sahita hridaya basahu surabhupa ||",
        "english_meaning": "O Son of the Wind (Hanuman), remover of troubles, personification of auspiciousness; dwell in my heart along with Rama, Lakshmana, and Sita, O king of gods",
        "syllable_count": 32,
        "recommended_count": 7,
        "auspicious_day": "Tuesday",
        "classical_citation": "Tulsidas, Hanuman Chalisa (Ramcharitmanas appendix), closing doha",
    },

    # ===== UPANISHADIC MAHAVAKYAS =====
    {
        "id": "tat_tvam_asi",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Tat Tvam Asi — Mahavakya (Samaveda)",
        "sanskrit_iast": "Tat tvam asi",
        "transliteration": "Tat tvam asi",
        "english_meaning": "That Thou Art — the mahavakya of the Samaveda tradition; affirms the identity of the individual self (tvam) with the universal Brahman (tat)",
        "syllable_count": 4,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Chandogya Upanishad 6.8.7 (Samaveda tradition)",
    },
    {
        "id": "prajnanam_brahma",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Prajnanam Brahma — Mahavakya (Rigveda)",
        "sanskrit_iast": "Prajñānaṃ brahma",
        "transliteration": "Prajnanam Brahma",
        "english_meaning": "Consciousness is Brahman — the mahavakya of the Rigveda tradition; the entire universe is conscious awareness, which is the Absolute",
        "syllable_count": 4,
        "recommended_count": 108,
        "auspicious_day": "Wednesday",
        "classical_citation": "Aitareya Upanishad 3.3 (Rigveda tradition)",
    },

    # ===== REMEDIAL / KARMA-CLEARING MANTRAS =====
    {
        "id": "pitru_tarpana_mantra",
        "graha": None,
        "mantra_type": "vedic",
        "name": "Pitru Tarpana Mantra",
        "sanskrit_iast": "Oṃ pitṛbhyaḥ svadhā namaḥ pitāmaheḍhyaḥ svadhā namaḥ prapitāmahebhyaḥ svadhā namaḥ",
        "transliteration": "Om pitribhyah svadha namah pitamahebhyah svadha namah prapitaamahebhyah svadha namah",
        "english_meaning": "Salutations with svadha (ancestral offering) to the fathers, the grandfathers, and the great-grandfathers; used in shraddha/tarpana rites",
        "syllable_count": 22,
        "recommended_count": 3,
        "auspicious_day": "Saturday",
        "classical_citation": "Yajurveda; Ashvalayana Grihyasutra; Pitru Paksha rite",
    },
    {
        "id": "navagraha_shanti_mantra",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Navagraha Shanti — Complete Invocation",
        "sanskrit_iast": "Oṃ suryāya namaḥ | oṃ candrāya namaḥ | oṃ mangalāya namaḥ | oṃ budhāya namaḥ | oṃ bṛhaspataye namaḥ | oṃ śukrāya namaḥ | oṃ śanaye namaḥ | oṃ rāhave namaḥ | oṃ ketave namaḥ | oṃ sarvagraha-śāntaye namaḥ ||",
        "transliteration": "Om suryaya namah | Om chandraya namah | Om mangalaya namah | Om budhaya namah | Om brihaspataye namah | Om shukraya namah | Om shanaye namah | Om rahave namah | Om ketave namah | Om sarvagrahashantaye namah ||",
        "english_meaning": "Complete salutation to all nine grahas followed by invocation of peace for all planetary influences",
        "syllable_count": 40,
        "recommended_count": 9,
        "auspicious_day": "Sunday",
        "classical_citation": "BPHS remedial chapter; Navagraha Puja paddhati",
    },

    # ===== NAKSHATRA DEVATA MANTRAS (select) =====
    {
        "id": "ashwini_kumaras_mantra",
        "graha": "ketu",
        "mantra_type": "vedic",
        "name": "Ashwini Kumaras Mantra (Ashwini Nakshatra devata)",
        "sanskrit_iast": "Oṃ aśvinau devāv āgatam | iha pibatam madhu ||",
        "transliteration": "Om ashwinau devaav aagatam | iha pibatam madhu ||",
        "english_meaning": "O twin Ashwini Kumaras (divine physicians), come to us; drink the soma here",
        "syllable_count": 12,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Rigveda 8.35.1 (Ashwini Sukta); Ashwini Nakshatra devata invocation",
    },
    {
        "id": "chitra_tvashtr_mantra",
        "graha": "mars",
        "mantra_type": "vedic",
        "name": "Tvashtr Mantra (Chitra Nakshatra devata)",
        "sanskrit_iast": "Oṃ tvaṣṭā rūpāṇi pum̐si kṛṇote tataḥ paśūn vividhāñjānayante | tat tasya hasti tad u tan no astū dīrgham āyuḥ pratitiṣṭhati prāṇe ||",
        "transliteration": "Om tvashtaa rupaani pungsi krinote tatah pashoon vividhan jaanayante | tat tasya hasti tad u tan no astu deergham aayuh pratitishtathi praane ||",
        "english_meaning": "Tvashtr creates all forms in living beings; from him all creatures are born in diversity; what he possesses may we also have; long life established in prana",
        "syllable_count": 32,
        "recommended_count": 108,
        "auspicious_day": "Tuesday",
        "classical_citation": "Rigveda 10.53.9; Tvashtr (Vishwakarma) invocation; Chitra nakshatra",
    },

    # ===== ADDITIONAL CHALISA / SAHSRANAMA =====
    {
        "id": "shiva_sahasranama_seed",
        "graha": None,
        "mantra_type": "sahsranama",
        "name": "Shiva Sahasranama (Dhyana Shloka)",
        "sanskrit_iast": "Vande deva mumīśānaṃ sthāṇuṃ trayambakam śivam | hara candrakalā-dhāraṃ śūlapāṇiṃ maharddhikam ||",
        "transliteration": "Vande deva momeeshanam sthaanum trayambakam shivam | hara chandrakaladhaaram shoolapanim maharddhikam ||",
        "english_meaning": "I bow to Shiva, the lord of gods, the immovable one, the three-eyed, the auspicious, Hara, bearer of the crescent moon, holding the trident, of great prosperity",
        "syllable_count": 32,
        "recommended_count": 1,
        "auspicious_day": "Monday",
        "classical_citation": "Shiva Sahasranama, Mahabharata, Anushasana Parva 17",
    },
    {
        "id": "lalitha_sahasranama_seed",
        "graha": None,
        "mantra_type": "sahsranama",
        "name": "Lalitha Sahasranama (seed dhyana)",
        "sanskrit_iast": "Sindhūrāruṇa-vigrahāṃ trinayanāṃ māṇikya-mauleṃ sphurad-tarakā-nāyikāṃ smaradhanur bāṇān pāśān dadatīṃ karaiḥ | pūrṇa-candra-nibhānanām aravinda-cakṣuṣīṃ madhusmitāṃ | śrī cakra-rāja-nilayāṃ bhajāmi śrī lalitāmbikām ||",
        "transliteration": "Sindhuraaruna vigrahaam trinayanaam manikya moulem sphurattaraka naayikaam | smaradhanur baanaanpaashaandhati kairaiḥ poornachandra nibhananam aravinda chakshusheem madhusmitam | Shri chakra raaja nilayaam bhajami Sri Lalitaambikam ||",
        "english_meaning": "I worship Sri Lalitambika, of vermillion-red form, three-eyed, crowned with rubies, leader of the shining stars, holding in her hands bow of sugarcane + arrows of flowers + noose + goad, face like the full moon, lotus eyes, gentle smile, residing in the Sri Chakra",
        "syllable_count": 64,
        "recommended_count": 1,
        "auspicious_day": "Friday",
        "classical_citation": "Brahmanda Purana, Lalitha Sahasranama; Soundarya Lahari tradition",
    },

    # ===== ADDITIONAL BEEJ MANTRAS =====
    {
        "id": "hamsa_breath_mantra",
        "graha": None,
        "mantra_type": "beej",
        "name": "Hamsa — Breath Mantra",
        "sanskrit_iast": "Haṃsa haṃsa haṃsa (exhalation So → inhalation Ham)",
        "transliteration": "Ham-sa Ham-sa (So on inhalation, Ham on exhalation)",
        "english_meaning": "I am He / The divine swan — the natural sound of breath; reversal of Soham; in Hamsa Upanishad described as the 21,600 natural daily repetitions of the ajapa-japa",
        "syllable_count": 2,
        "recommended_count": 21600,
        "auspicious_day": "Monday",
        "classical_citation": "Hamsa Upanishad; Hatha Yoga Pradipika 4.82; Vijnana Bhairava Tantra",
    },
    {
        "id": "ram_taraka_mantra",
        "graha": "sun",
        "mantra_type": "beej",
        "name": "Ram — Taraka Mantra (Ram Naam)",
        "sanskrit_iast": "Rāma",
        "transliteration": "Rama / Ram",
        "english_meaning": "Rama — the taraka mantra (liberation-crossing mantra); the name contains Ra (fire-seed, Shiva-beej) and Ma (water-seed, Vishnu-beej); said to be the essence of the Vishnu Sahasranama",
        "syllable_count": 2,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Adhyatma Ramayana; Padma Purana; Vishnu Sahasranama (Ra = 8th name, Ma = 5th name of Trisandhya)",
    },
    {
        "id": "shri_vidya_panchadashi",
        "graha": None,
        "mantra_type": "beej",
        "name": "Panchadashi Mantra (Sri Vidya) — seed form",
        "sanskrit_iast": "Ka-e-ī-la-hrīṃ | ha-sa-ka-ha-la-hrīṃ | sa-ka-la-hrīṃ ||",
        "transliteration": "Ka E I La Hreem | Ha Sa Ka Ha La Hreem | Sa Ka La Hreem ||",
        "english_meaning": "The 15-syllable mantra of Sri Lalitha; three kutas (groups): Vagbhava (creation), Kamaraja (desire/sustenance), Shakti (dissolution); the supreme mantra of Sri Vidya tradition",
        "syllable_count": 15,
        "recommended_count": 1000,
        "auspicious_day": "Friday",
        "classical_citation": "Vamakeshvara Tantra; Parasurama Kalpasutram; Tantraraja Tantra",
    },
    {
        "id": "guru_mantra_om_namo_guru",
        "graha": "jupiter",
        "mantra_type": "vedic",
        "name": "Guru Mantra (Guru Vandana)",
        "sanskrit_iast": "Gurur brahma gurur viṣṇuḥ gurur devo maheśvaraḥ | gurur eva paraṃ brahma tasmai śrī-gurave namaḥ ||",
        "transliteration": "Gurur brahma gurur vishnuh gurur devo maheshvarah | gurur eva param brahma tasmai shri gurave namah ||",
        "english_meaning": "The Guru is Brahma, the Guru is Vishnu, the Guru is Lord Shiva; the Guru alone is the supreme Brahman — salutations to that revered Guru",
        "syllable_count": 28,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Guru Gita (Skanda Purana 2.4); traditional guru-shishya transmission",
    },

    # ===== HEALING / PROTECTION MANTRAS =====
    {
        "id": "dhanvantari_mantra",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Dhanvantari Mantra (Health/Ayurveda deity)",
        "sanskrit_iast": "Oṃ namo bhagavate vāsudevāya dhanvantaraye amṛta-kalasa hastāya sarva-āmaya-vināśanāya trailokyanāthāya śrī mahā-viṣṇave svāhā ||",
        "transliteration": "Om namo bhagavate Vasudevaaya Dhanvantaraaye amrita kalasha hastaaya sarva aamaya vinaashaaya trailokya naathaaya shri mahaa vishnave svaahaa ||",
        "english_meaning": "Salutations to the blessed Vasudeva in the form of Dhanvantari, holding the pot of nectar, destroyer of all disease, lord of the three worlds, the great Vishnu, svaha",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Vishnu Purana; Ayurveda tradition; Dhanvantari Jayanti",
    },
    {
        "id": "sudarshana_chakra_mantra",
        "graha": "sun",
        "mantra_type": "beej",
        "name": "Sudarshana Chakra Mantra (Solar disc — protection)",
        "sanskrit_iast": "Oṃ sudarśanāya vidmahe mahājvālāya dhīmahi | tannas cakraḥ pracodayāt ||",
        "transliteration": "Om sudarshanaya vidmahe mahajvaalaaya dheemahi | tannas chakrah prachodayat ||",
        "english_meaning": "We know Sudarshana (the beautiful-sighted solar discus of Vishnu); we meditate on the great flame; may the chakra inspire us — used for protection and removal of evil",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "Sudarshana Ashtakam; Vishnu Purana; Pancharatra tradition",
    },

    # ===== DASHA-RELATED REMEDIAL MANTRAS =====
    {
        "id": "jupiter_mahadasha_mantra",
        "graha": "jupiter",
        "mantra_type": "beej",
        "name": "Jupiter Mahadasha Remedial Mantra",
        "sanskrit_iast": "Oṃ grāṃ grīṃ grauṃ saḥ guruve namaḥ | bṛhaspataye namaḥ ||",
        "transliteration": "Om graam greem graum sah gurave namah | Brihaspataye Namah ||",
        "english_meaning": "Extended salutation to Jupiter combining the beej mantra with the full name Brihaspati; the complete Jupiter remedial mantra for Guru Mahadasha/Antardasha",
        "syllable_count": 13,
        "recommended_count": 19000,
        "auspicious_day": "Thursday",
        "classical_citation": "BPHS remedial chapter; Graha Shanti tradition",
    },
    {
        "id": "saturn_sade_sati_mantra",
        "graha": "saturn",
        "mantra_type": "beej",
        "name": "Sade Sati Remedial Mantra (Shani)",
        "sanskrit_iast": "Oṃ prāṃ prīṃ prauṃ saḥ śanaiścarāya namaḥ | nīlāñjana-samābhāsāya namaḥ ||",
        "transliteration": "Om praam preem praum sah shanaischaraya namah | Neelanjana samabhaasaaya namah ||",
        "english_meaning": "Extended Shani mantra combining beej with the stotra epithet (dark as collyrium); specific for Sade Sati and Shani Antardasha remediation",
        "syllable_count": 15,
        "recommended_count": 23000,
        "auspicious_day": "Saturday",
        "classical_citation": "BPHS ch.86; Shani Mahatmya (Skanda Purana); Sade Sati lore",
    },

    # ===== ADDITIONAL PROMINENT STOTRAS =====
    {
        "id": "bhaja_govindam_seed",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Bhaja Govindam (Mohamudgara) — seed verse",
        "sanskrit_iast": "Bhaja govindaṃ bhaja govindaṃ govindaṃ bhaja mūḍhamate | samprāpte sannihite kāle nahi nahi rakṣati ḍukṛñ karaṇe ||",
        "transliteration": "Bhaja govindam bhaja govindam govindam bhaja mooda mate | sampraapte sannihite kaale nahi nahi rakshati dukrin karane ||",
        "english_meaning": "Worship Govinda, worship Govinda, worship Govinda, O fool! When your last hour approaches, grammar rules will not save you",
        "syllable_count": 32,
        "recommended_count": 1,
        "auspicious_day": "Thursday",
        "classical_citation": "Adi Shankaracharya, Bhaja Govindam (Mohamudgara), verse 1",
    },
    {
        "id": "soundarya_lahari_seed",
        "graha": None,
        "mantra_type": "stotra",
        "name": "Soundarya Lahari — Seed Verse",
        "sanskrit_iast": "Śivaḥ śaktyā yukto yadi bhavati śaktaḥ prabhavituṃ na cedevaṃ devo na khalu kuśalaḥ spanditum api | atas tvāmārādhyāṃ harihara-virincy-ādibhir api praṇantuṃ stotuṃ vā katham akṛtapuṇyaḥ prabhavati ||",
        "transliteration": "Shivah shaktyaa yukto yadi bhavati shaktah prabhavitum na chedevam devo na khalu kushalah spanditum api | atas tvaam aaradhyaam harihara virinchy adibhir api pranantu stoum vaa katham akrita punyah prabhavati ||",
        "english_meaning": "Only when conjoined with Shakti is Shiva able to create; without her, the god cannot even stir — therefore how can one who has not accumulated merit be capable of worshipping or praising you, who are worshipped even by Vishnu, Shiva, and Brahma",
        "syllable_count": 56,
        "recommended_count": 1,
        "auspicious_day": "Friday",
        "classical_citation": "Adi Shankaracharya, Soundarya Lahari, verse 1",
    },
    {
        "id": "kanakadhara_stotra_seed",
        "graha": "venus",
        "mantra_type": "stotra",
        "name": "Kanakadhara Stotram (Lakshmi) — seed verse",
        "sanskrit_iast": "Aṅgaṃ hare pulaka-bhūṣaṇam āśrayante bhṛṅgāṅganeva mukulābharaṇaṃ tamālam | aṅgīkṛtākhila vibhūtir apāṅgalīlā māṅgalyadāstu mama maṅgala-devatāyāḥ ||",
        "transliteration": "Angam hare pulaka bhushnanam aashrayante bhringaanganeva mukulaabharanam tamalam | angikritaakhila vibhutir apaanglila maangalyadaastu mama mangala devataayah ||",
        "english_meaning": "May the auspicious sidelong glance of Lakshmi — she who has accepted all glories, like bees settling on a dark tamala tree decorated with budding ornaments — bestow auspiciousness upon me",
        "syllable_count": 48,
        "recommended_count": 1,
        "auspicious_day": "Friday",
        "classical_citation": "Adi Shankaracharya, Kanakadhara Stotram, verse 1",
    },

    # ===== YANTRA ACTIVATION MANTRAS =====
    {
        "id": "sri_yantra_beej",
        "graha": None,
        "mantra_type": "beej",
        "name": "Sri Yantra / Sri Chakra Activation Beej",
        "sanskrit_iast": "Oṃ śrīṃ hrīṃ klīṃ aiṃ sauḥ oṃ hrīṃ śrīṃ ka e ī la hrīṃ ha sa ka ha la hrīṃ sa ka la hrīṃ sauḥ aiṃ klīṃ hrīṃ śrīṃ",
        "transliteration": "Om Shreem Hreem Kleem Aim Sauh Om Hreem Shreem Ka E I La Hreem Ha Sa Ka Ha La Hreem Sa Ka La Hreem Sauh Aim Kleem Hreem Shreem",
        "english_meaning": "The full Panchadashi (15-syllable) core embedded in its extended Shodashi (16-syllable) form with the Sauh (Shakti-arrow beej) additions; used for Sri Yantra consecration and Lalitha worship",
        "syllable_count": 28,
        "recommended_count": 1000,
        "auspicious_day": "Friday",
        "classical_citation": "Tantraraja Tantra; Vamakeshvara Tantra; Sri Vidya tradition",
    },
    {
        "id": "navagraha_yantra_activation",
        "graha": None,
        "mantra_type": "beej",
        "name": "Navagraha Yantra Activation Mantra",
        "sanskrit_iast": "Oṃ hrāṃ hrīṃ hrauṃ sūryāya | śrāṃ śrīṃ śrauṃ candrāya | krāṃ krīṃ krauṃ bhaumāya | brāṃ brīṃ brauṃ budhāya | grāṃ grīṃ grauṃ guruve | drāṃ drīṃ drauṃ śukrāya | prāṃ prīṃ prauṃ śanaye | bhrāṃ bhrīṃ bhrauṃ rāhave | srāṃ srīṃ srauṃ ketave namaḥ ||",
        "transliteration": "Om hraam hreem hraum suryaya | shraam shreem shraum chandraaya | kraam kreem kraum bhaumaaya | braam breem braum budhaaya | graam greem graum gurave | draam dreem draum shukraaya | praam preem praum shanaaye | bhraam bhreem bhraum raahave | sraam sreem sraum ketave namah ||",
        "english_meaning": "Sequential activation of all nine planetary beej mantras in their condensed triple form; used for Navagraha yantra prana-pratishtha (consecration)",
        "syllable_count": 54,
        "recommended_count": 108,
        "auspicious_day": "Sunday",
        "classical_citation": "BPHS Navagraha Puja chapter; Navagraha Yantra Puja tradition",
    },

    # ===== JUPITER / GURU SHISHYA / DHARMA =====
    {
        "id": "guru_brahma_anandam",
        "graha": "jupiter",
        "mantra_type": "vedic",
        "name": "Guru Purnima / Initiation Mantra",
        "sanskrit_iast": "Oṃ namaḥ śivāya gurve sacchidānanda-mūrtaye | niṣprapañcāya śāntāya nirālambanāya tejase ||",
        "transliteration": "Om Namah Shivaya Gurave Sacchidananda Murtaye | Nishprapanchaaya Shaantaaya Niraalam banaaya Tejase ||",
        "english_meaning": "Salutations to the Guru (as Shiva), embodiment of Sat-Chit-Ananda (existence-consciousness-bliss), free from the world-illusion, peaceful, without dependency, of pure effulgence",
        "syllable_count": 24,
        "recommended_count": 108,
        "auspicious_day": "Thursday",
        "classical_citation": "Guru Gita (Skanda Purana); Shiva Sutras tradition",
    },
]


# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------

REQUIRED_KEYS = {
    "id",
    "graha",
    "mantra_type",
    "name",
    "sanskrit_iast",
    "transliteration",
    "english_meaning",
    "syllable_count",
    "recommended_count",
    "auspicious_day",
    "classical_citation",
}

_INDEX_BY_ID: dict[str, dict] | None = None
_INDEX_BY_GRAHA: dict[str, list[dict]] | None = None
_INDEX_BY_TYPE: dict[str, list[dict]] | None = None


def _build_indexes() -> None:
    global _INDEX_BY_ID, _INDEX_BY_GRAHA, _INDEX_BY_TYPE
    _INDEX_BY_ID = {}
    _INDEX_BY_GRAHA = {}
    _INDEX_BY_TYPE = {}
    for entry in MANTRAS:
        _INDEX_BY_ID[entry["id"]] = entry
        g = entry.get("graha")
        if g is not None:
            _INDEX_BY_GRAHA.setdefault(g, []).append(entry)
        mt = entry.get("mantra_type", "")
        _INDEX_BY_TYPE.setdefault(mt, []).append(entry)


def _ensure_indexes() -> None:
    if _INDEX_BY_ID is None:
        _build_indexes()


def get_mantra(id: str) -> dict | None:
    """Return the mantra entry with the given id, or None if not found."""
    _ensure_indexes()
    return _INDEX_BY_ID.get(id)


def get_mantras_for_graha(graha: str) -> list[dict]:
    """Return all mantra entries associated with the given graha name (lowercase)."""
    _ensure_indexes()
    return list(_INDEX_BY_GRAHA.get(graha.lower(), []))


def list_by_type(mantra_type: str) -> list[dict]:
    """Return all mantra entries of the given mantra_type (e.g. 'beej', 'stotra', 'vedic')."""
    _ensure_indexes()
    return list(_INDEX_BY_TYPE.get(mantra_type.lower(), []))


def search_mantras(keyword: str) -> list[dict]:
    """
    Full-text search across name, english_meaning, sanskrit_iast,
    transliteration, and classical_citation fields.
    Case-insensitive substring match.
    """
    kw = keyword.lower()
    results = []
    for entry in MANTRAS:
        haystack = " ".join(
            str(entry.get(f, ""))
            for f in (
                "name",
                "english_meaning",
                "sanskrit_iast",
                "transliteration",
                "classical_citation",
                "mantra_type",
                "graha",
                "id",
            )
        ).lower()
        if kw in haystack:
            results.append(entry)
    return results
