# KĀLA-YANTRA — FLEET environment (NO SECRETS). Copy to ~/.config/kalayantra/fleet.env and `source` it in the shell that runs
# fleet/kalayantra_fleet.sh. The supervisor refuses to start if DATABASE_URL / KY_*_DATABASE_URL / PGPASSWORD are set in that shell.
# Pool size is NOT set here: the conductor writes $KY_ROOT/run/KY_WORKERS (0 until launch acceptance, then 1, up to 6).
export KY_ROOT=/Users/Dev/kalayantra
export KY_MAX_CYCLES_PER_DAY=600            # BUILDER cycle starts per day (the six k lanes)
export KY_MAX_CONTROL_CYCLES_PER_DAY=300    # conductor, surrogate and verifiers per day, counted apart
export KY_CONTROL_SLEEP=300                 # control lanes wait five minutes between cycles
export KY_QUOTA_BACKOFF_S=1800       # fleet-wide pause after a rate-limit or usage-limit marker
export KY_IDLE_SLEEP=600             # a lane that reported IDLE-OK waits this long before its next cycle
export KY_CODEX_PROFILE=kalayantra   # generated by fleet/make_codex_profile.sh: approvals never, full access, every personal MCP server and plugin off
export KY_MODEL_WORKER=gpt-6-sol;        export KY_EFFORT_WORKER=high
export KY_MODEL_SUTRADHARA=gpt-6-sol;    export KY_EFFORT_SUTRADHARA=high
# export KY_NODE_BIN=/Users/Dev/.nvm/versions/node/v24.14.0/bin   # only if node is not found by itself
export KY_MODEL_ADHIKARIN=gpt-6-astra;   export KY_EFFORT_ADHIKARIN=xhigh
export KY_MODEL_PARIKSAKA=gpt-6-astra;   export KY_EFFORT_PARIKSAKA=xhigh
export SE_EPHE_PATH=$KY_ROOT/ephe
