#!/usr/bin/env bash
# KĀLA-YANTRA fleet supervisor v1.1 — the Codex port of the Nirmāṇa v2.3 supervised-cycle loop, corrected per
# reviews/ASTRA_REVIEW_KALAYANTRA_CHARTER_v1_0.md (KY-04, KY-12, KY-13, KY-21, KY-27).
#
#   kalayantra_fleet.sh up               snapshot this folder to $KY_ROOT/fleet_live and start every lane loop from the snapshot,
#                                        fully detached (idempotent: lane locks prevent duplicates)
#   kalayantra_fleet.sh lane <name>      supervise ONE lane in this terminal (sutradhara adhikarin v1 v2 v3 k1..k8)
#   kalayantra_fleet.sh smoke            REAL start of the worker and reviewer models under the exact lane environment: proves the
#                                        Codex profile loads, the login works, the models answer, the tools resolve, and no
#                                        credential-like variable reaches a command an agent runs (run by preflight)
#   kalayantra_fleet.sh status           one-screen fleet status (log timestamps + tracker; not proof of progress — use `ky audit`)
#   kalayantra_fleet.sh down             write STOP files for every lane; active cycles finish inside their cap
#   kalayantra_fleet.sh resume           remove HOLD and STOP files and start loops
#
# Pool size is a FILE the conductor writes, never an environment default: run/KY_WORKERS (absent = 0 — no implementation worker
# runs before launch acceptance B-7) and run/KY_VERIFIERS (absent = 1 — one verifier until atomic claims land at B-2).
# Secrets: this process MUST NOT hold a production credential. It refuses to start if one is in its environment.
# Agents get an allow-listed environment (env -i), a generated Codex profile with every personal MCP server and plugin off,
# and a shell start-up that does not source the user's profile. Production operations go through fleet/executor.py.
set -u

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
PY=/opt/homebrew/bin/python3
KY_ROOT="${KY_ROOT:-/Users/Dev/kalayantra}"
KY_REPO_MAIN="${KY_REPO_MAIN:-/Users/Dev/Vibe-Coding/Apps/Madhav}"   # object store for `git worktree add`; its files are never written
CAMP="$KY_ROOT/wt/campaign"
BRIEF="$CAMP/00_ARCHITECTURE/briefs/kalayantra"
RUN="$KY_ROOT/run"; LOGD="$KY_ROOT/logs"; WT="$KY_ROOT/wt"
HOLD="$KY_ROOT/HOLD"

CYCLE_SLEEP="${KY_CYCLE_SLEEP:-60}"                      # builders: next cycle a minute after the last
CONTROL_SLEEP="${KY_CONTROL_SLEEP:-300}"                 # conductor, surrogate, verifiers: five minutes — their work is reacting, not building
CRASH_SLEEP="${KY_CRASH_SLEEP:-120}"
IDLE_SLEEP="${KY_IDLE_SLEEP:-600}"                       # after a cycle that printed IDLE-OK: no paid minute-by-minute polling
MAX_CYCLE_SECS="${KY_MAX_CYCLE_SECS:-5400}"
KY_QUOTA_BACKOFF_S="${KY_QUOTA_BACKOFF_S:-1800}"
KY_MAX_CYCLES_PER_DAY="${KY_MAX_CYCLES_PER_DAY:-600}"             # BUILDER cycle starts per day (k1…k8)
KY_MAX_CONTROL_CYCLES_PER_DAY="${KY_MAX_CONTROL_CYCLES_PER_DAY:-300}"   # conductor + surrogate + verifiers per day — never charged to the builders
WORKER_CEILING=8   # k7/k8 added 2026-10-08: with one claim per builder, waiting builders starved eight READY items
CODEX_PROFILE="${KY_CODEX_PROFILE:-kalayantra}"             # generated by make_codex_profile.sh: the madhav-parity posture (approvals never,
                                                            # full access) with every personal MCP server and plugin switched off
HERE="$(dirname "$SELF")"; SHELL_HOME="$KY_ROOT/zdotdir"

MODEL_WORKER="${KY_MODEL_WORKER:-gpt-6-sol}";           EFFORT_WORKER="${KY_EFFORT_WORKER:-high}"
MODEL_SUTRADHARA="${KY_MODEL_SUTRADHARA:-gpt-6-sol}";   EFFORT_SUTRADHARA="${KY_EFFORT_SUTRADHARA:-high}"
MODEL_ADHIKARIN="${KY_MODEL_ADHIKARIN:-gpt-6-astra}";   EFFORT_ADHIKARIN="${KY_EFFORT_ADHIKARIN:-xhigh}"
MODEL_PARIKSAKA="${KY_MODEL_PARIKSAKA:-gpt-6-astra}";   EFFORT_PARIKSAKA="${KY_EFFORT_PARIKSAKA:-xhigh}"
SE_EPHE_PATH="${SE_EPHE_PATH:-$KY_ROOT/ephe}"

ALL_LANES=(sutradhara adhikarin v1 v2 v3 k1 k2 k3 k4 k5 k6 k7 k8)
mkdir -p "$RUN" "$LOGD" "$WT" "$RUN/claims" "$RUN/verdicts" "$RUN/reviews" "$RUN/ops/requests" "$RUN/ops/receipts" "$RUN/ops/acceptance" "$RUN/ops/sql" "$RUN/ops/drafts" "$RUN/bootstrap" "$RUN/tests"

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
log() { echo "$(ts) [sup:$1] $2" >> "$LOGD/supervisor.log"; }

refuse_secrets() {
  local v
  for v in DATABASE_URL KY_BUILDER_DATABASE_URL KY_OWNER_DATABASE_URL PGPASSWORD; do
    if [ -n "${!v:-}" ]; then echo "REFUSED: $v is set in the supervisor's environment. Secrets belong only to the executor's shell (charter §7)." >&2; exit 78; fi
  done
}

valid_lane() { case "$1" in sutradhara|adhikarin|v1|v2|v3|k1|k2|k3|k4|k5|k6|k7|k8) return 0 ;; *) echo "invalid lane: $1" >&2; return 2 ;; esac; }
role_of()   { case "$1" in sutradhara) echo SUTRADHARA;; adhikarin) echo ADHIKARIN;; v*) echo PARIKSAKA;; k*) echo KARAKA;; esac; }
stream_of() { case "$1" in sutradhara) echo S;; adhikarin) echo N;; v*) echo V;; k*) echo K;; esac; }
model_of()  { case "$1" in sutradhara) echo "$MODEL_SUTRADHARA";; adhikarin) echo "$MODEL_ADHIKARIN";; v*) echo "$MODEL_PARIKSAKA";; k*) echo "$MODEL_WORKER";; esac; }
effort_of() { case "$1" in sutradhara) echo "$EFFORT_SUTRADHARA";; adhikarin) echo "$EFFORT_ADHIKARIN";; v*) echo "$EFFORT_PARIKSAKA";; k*) echo "$EFFORT_WORKER";; esac; }

wanted() {   # wanted <file> <default-when-absent> <ceiling>  → an integer in [0, ceiling]; malformed → the default
  "$PY" - "$1" "$2" "$3" <<'PYEOF'
import pathlib, sys
p = pathlib.Path(sys.argv[1]); default = int(sys.argv[2]); ceiling = int(sys.argv[3])
try:
    n = int(p.read_text().strip(), 10) if p.exists() else default
except (OSError, ValueError):
    n = default
print(max(0, min(ceiling, n)))
PYEOF
}
workers_wanted()   { wanted "$RUN/KY_WORKERS" 0 "$WORKER_CEILING"; }
verifiers_wanted() { wanted "$RUN/KY_VERIFIERS" 1 3; }

# ---- the lane environment: an allow-list, a clean shell start-up, and an explicit tool path ------------------------
node_bin() {   # node comes from nvm on this machine; without the user's shell profile the lane needs its folder named
  if [ -s "$RUN/NODE_BIN" ] && [ -x "$(cat "$RUN/NODE_BIN")/node" ]; then cat "$RUN/NODE_BIN"; return 0; fi
  local d=""
  if [ -n "${KY_NODE_BIN:-}" ] && [ -x "$KY_NODE_BIN/node" ]; then d="$KY_NODE_BIN"
  elif command -v node >/dev/null 2>&1; then d="$(dirname "$(command -v node)")"
  else d="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1)"; fi
  [ -n "$d" ] && [ -x "$d/node" ] || return 1
  printf '%s\n' "$d" > "$RUN/NODE_BIN"; echo "$d"
}
lane_path() { local nb; nb="$(node_bin)" || nb=""; echo "$KY_ROOT/bin${nb:+:$nb}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"; }
no_wrappers() {   # $KY_ROOT/bin holds the campaign CLI only; a wrapper around git, gh, npm, psql or codex there is refused (the LOCAL_ONLY incident of 2026-10-07)
  local f bad=""
  for f in "$KY_ROOT"/bin/*; do case "$(basename "$f")" in ky|kybrief) ;; *) bad="$bad $(basename "$f")";; esac; done
  [ -z "$bad" ] || { echo "REFUSED: $KY_ROOT/bin carries tool wrappers ($bad); only ky and kybrief belong there" >&2; return 78; }
}
ensure_shell_home() {   # the agent's shell must not source the user's ~/.zshrc (it exports personal keys): ZDOTDIR points here
  mkdir -p "$SHELL_HOME" || return 1
  printf '# KĀLA-YANTRA lane shell start-up (generated). Nothing personal is sourced.\nexport PATH="%s"\n' "$(lane_path)" > "$SHELL_HOME/.zshenv"
  printf '# generated; intentionally empty apart from the path\nexport PATH="%s"\n' "$(lane_path)" > "$SHELL_HOME/.zprofile"
  : > "$SHELL_HOME/.zshrc"; : > "$SHELL_HOME/.zlogin"
}
lane_env() {   # lane_env <lane> <stream> → fills the array LANE_ENV (the ONLY variables a lane's Codex process starts with)
  LANE_ENV=( "HOME=$HOME" "PATH=$(lane_path)" "LANG=en_US.UTF-8" "LC_ALL=en_US.UTF-8" "TERM=dumb" "USER=$(id -un)" "LOGNAME=$(id -un)" "SHELL=/bin/zsh"
             "TMPDIR=${TMPDIR:-/tmp}" "ZDOTDIR=$SHELL_HOME" "BASH_ENV=" "ENV="
             "KY_STREAM=$2" "KY_LANE=$1" "KY_ROOT=$KY_ROOT" "KY_PY=$KY_ROOT/venv/bin/python"
             "SE_EPHE_PATH=$SE_EPHE_PATH" "SWE_EPHE_PATH=$SE_EPHE_PATH" "CODEX_HOME=$HOME/.codex" )
}

ensure_worktree() {
  local wt="$WT/$1"
  if [ ! -e "$wt/.git" ]; then
    git -C "$KY_REPO_MAIN" fetch origin main -q || { log "$1" "FATAL: git fetch failed"; return 1; }
    git -C "$KY_REPO_MAIN" worktree add "$wt" --detach origin/main >/dev/null 2>&1 || { log "$1" "FATAL: cannot create worktree $wt"; return 1; }
    log "$1" "worktree created at $wt"
  fi
  [ -d "$wt/platform" ] || { log "$1" "FATAL: $wt is not a Madhav checkout"; return 1; }
  return 0
}

# ---- fleet-wide backoff and reservations (locked, fail-closed on malformed state) --------------------------------
quota_backoff_active() {
  "$PY" - "$RUN" <<'PYEOF'
import fcntl, pathlib, sys, time
root = pathlib.Path(sys.argv[1]); f = root / "KY_QUOTA_BACKOFF"
with (root / "backoff.lock").open("a+") as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    if not f.exists(): sys.exit(1)
    try: until = int(f.read_text().strip())
    except ValueError: sys.exit(0)          # malformed → treat as active (fail closed); the supervisor logs it
    if time.time() < until: sys.exit(0)
    f.unlink(); sys.exit(1)
PYEOF
}
mark_quota_backoff() {
  "$PY" - "$RUN" "$KY_QUOTA_BACKOFF_S" <<'PYEOF'
import fcntl, pathlib, sys, time
root = pathlib.Path(sys.argv[1]); f = root / "KY_QUOTA_BACKOFF"; new = int(time.time()) + int(sys.argv[2])
with (root / "backoff.lock").open("a+") as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    try: cur = int(f.read_text().strip()) if f.exists() else 0
    except ValueError: cur = 0
    f.write_text(str(max(cur, new)))
PYEOF
  log "$1" "quota/rate-limit marker in the current cycle log — fleet backs off ${KY_QUOTA_BACKOFF_S}s"
}
quota_error_in() {   # true when one of the last 40 lines is a Codex ERROR line naming a usage/rate limit
  tail -n 40 "$1" 2>/dev/null | grep -qiE "^(ERROR|error)[: ].*(\"status\": ?429|status 429|usage limit|usage_limit|rate.?limit|quota|too many requests)|^.{0,40}you.?ve hit your usage limit"
}
reserve_cycle() {   # prints the cycle number; exit 75 when this lane group's daily cap is reached (builders and control lanes are counted apart)
  "$PY" - "$RUN" "$1" "$KY_MAX_CYCLES_PER_DAY" "$KY_MAX_CONTROL_CYCLES_PER_DAY" <<'PYEOF'
import datetime, fcntl, json, os, pathlib, sys
root = pathlib.Path(sys.argv[1]); lane = sys.argv[2]; cap_workers = int(sys.argv[3]); cap_control = int(sys.argv[4])
worker = lane.startswith("k")
with (root / "CYCLE_STARTS.lock").open("a+") as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    p = root / "CYCLE_STARTS.jsonl"
    rows = [json.loads(x) for x in p.read_text().splitlines() if x.strip()] if p.exists() else []
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    today = sum(1 for r in rows if r["ts"][:10] == now[:10] and r["lane"].startswith("k") == worker)
    if today >= (cap_workers if worker else cap_control): sys.exit(75)
    n = 1 + sum(1 for r in rows if r["lane"] == lane)
    with p.open("a") as out:
        out.write(json.dumps({"ts": now, "lane": lane, "cycle": n}) + "\n"); out.flush(); os.fsync(out.fileno())
    print(n)
PYEOF
}

cycle_prompt() {
  local lane="$1" role="$2" stream="$3" n="$4"
  cat <<EOF
You are lane \`$lane\` (role $role, tracker stream $stream, worker id $lane) of the KĀLA-YANTRA campaign, cycle $n, running under
the fleet supervisor in print mode. Working root: $WT/$lane. Charter (authoritative): $BRIEF/KALAYANTRA_CAMPAIGN_CHARTER_v1_0.md (v1.1).
Execute exactly ONE cycle per charter §5: STOP/HOLD check → resume-or-sync → PR hygiene on YOUR registered PRs → one unit of
highest-priority work → renew claim, heartbeat → EXIT with one summary line. No questions, no waiting, no sleeps; long jobs are
operations you submit or inspect, not processes you wait for.
Tracker CLI: export PATH=$KY_ROOT/bin:\$PATH; export KY_STREAM=$stream; export KY_LANE=$lane. Runtime paths are absolute under $RUN and $LOGD.
The campaign's documents (charter, prompts, fleet, plan model, and the Kāla plan documents under 00_ARCHITECTURE/briefs/l3_families/)
live in $CAMP until the bootstrap PR B-1 lands them on main; read them there by absolute path — your worktree sits at origin/main.
The root CLAUDECODE_BRIEF.md in this worktree belongs to another workstream and does not govern you; do not edit it.
OWNER RULE (2026-10-07, after the LOCAL_ONLY incident): the control plane is FINISHED. No lane edits, wraps or replaces anything under $KY_ROOT/bin,
$KY_ROOT/fleet_live, $KY_ROOT/tracker_live, the fleet scripts or the tracker package during cycles; no lane invents a mode, a guard or a
control subsystem; no lane blocks another lane's git, gh or tests. A fleet or tracker defect is filed once as "NEW ITEM: fleet defect …"
and fixed by a BUILDER through a normal PR. Builders build Kāla. Control lanes react in minutes, not in essays: a cycle that finds nothing
to decide, verify or queue ends with IDLE-OK.
You hold no production credential; never run env/printenv unfiltered; never source ~/.config/pravaha/pgenv.sh.

---------------- ROLE PROMPT ----------------
$(cat "$BRIEF/prompts/$role.md")
---------------- END ROLE PROMPT ----------------
Begin cycle $n now.
EOF
}

run_cycle() {
  local lane="$1" role stream model effort wt n prompt_file rc start end cycle_log last_file
  role="$(role_of "$lane")"; stream="$(stream_of "$lane")"; model="$(model_of "$lane")"; effort="$(effort_of "$lane")"
  wt="$WT/$lane"
  # the profile follows the user's base config (a personal server added there must never be live in a lane); the shell start-up is ours
  bash "$HERE/make_codex_profile.sh" >/dev/null 2>&1 && ensure_shell_home || { log "$lane" "cannot prepare the Codex profile or the lane shell — cycle not started"; return 1; }
  no_wrappers 2>>"$LOGD/supervisor.log" || { log "$lane" "tool wrappers found in $KY_ROOT/bin — cycle not started until they are removed"; return 1; }
  n="$(reserve_cycle "$lane")" || { rc=$?; [ $rc -eq 75 ] && log "$lane" "daily cycle cap reached — lane waits"; return 75; }
  prompt_file="$(mktemp "$RUN/.prompt.$lane.XXXXXX")" || { log "$lane" "mktemp failed"; return 1; }
  cycle_prompt "$lane" "$role" "$stream" "$n" > "$prompt_file" || { log "$lane" "prompt generation failed"; rm -f "$prompt_file"; return 1; }
  cycle_log="$LOGD/$lane.$n.log"; last_file="$LOGD/$lane.$n.last.md"; LAST_FILE="$last_file"
  lane_env "$lane" "$stream"
  start=$(date +%s)
  log "$lane" "cycle $n start (profile $CODEX_PROFILE, model $model / $effort)$([ "${KY_DRY_RUN:-0}" = 1 ] && echo ' — DRY RUN')"
  local -a cmd=( codex exec -p "$CODEX_PROFILE" -C "$wt" --skip-git-repo-check -m "$model" -c "model_reasoning_effort=\"$effort\"" -o "$last_file" - )
  # KY_DRY_RUN=1 rehearses the supervisor (reservation, prompt, controller, locks, spacing, stop) without calling a model
  [ "${KY_DRY_RUN:-0}" = 1 ] && cmd=( bash -c 'cat > /dev/null; echo "IDLE-OK (dry run: no model was called)" > "$0"; echo "dry-run cycle: prompt read, nothing executed"' "$last_file" )
  env -i "${LANE_ENV[@]}" "$PY" - "$MAX_CYCLE_SECS" "$cycle_log" "$prompt_file" "${cmd[@]}" <<'PYEOF' &
import os, signal, subprocess, sys
limit = int(sys.argv[1]); logpath = sys.argv[2]; prompt = sys.argv[3]; argv = sys.argv[4:]
with open(logpath, "ab") as logf, open(prompt, "rb") as pin:
    p = subprocess.Popen(argv, stdin=pin, stdout=logf, stderr=subprocess.STDOUT, start_new_session=True)
    def terminate():
        for sig in (signal.SIGTERM, signal.SIGKILL):
            try: os.killpg(p.pid, sig)
            except ProcessLookupError: return
            try: p.wait(timeout=10); return
            except subprocess.TimeoutExpired: continue
    def interrupted(signum, frame):
        terminate(); raise SystemExit(128 + signum)
    signal.signal(signal.SIGTERM, interrupted); signal.signal(signal.SIGINT, interrupted)
    try:
        rc = p.wait(timeout=limit)
    except subprocess.TimeoutExpired:
        terminate(); rc = 124
    finally:
        try: os.killpg(p.pid, signal.SIGKILL)   # reap any tool descendant that outlived codex
        except ProcessLookupError: pass
raise SystemExit(rc)
PYEOF
  local pid=$!
  trap 'kill -TERM "$pid" 2>/dev/null; wait "$pid" 2>/dev/null; exit 143' TERM INT
  wait "$pid"; rc=$?
  trap - TERM INT
  end=$(date +%s)
  rm -f "$prompt_file"
  printf '{"ts":"%s","lane":"%s","cycle":%d,"rc":%d,"secs":%d,"model":"%s"}\n' "$(ts)" "$lane" "$n" "$rc" "$((end-start))" "$model" >> "$RUN/CYCLES.jsonl"
  [ $rc -eq 124 ] && log "$lane" "cycle $n exceeded ${MAX_CYCLE_SECS}s and was terminated; the claim record resumes it next cycle"
  log "$lane" "cycle $n end rc=$rc ($((end-start))s)"
  # A usage or rate limit is read ONLY from Codex's own error lines at the end of a cycle that FAILED — never from the body of the
  # log, which holds everything the agent read (a file listing has a line 429; this script contains the words "rate limit").
  if [ $rc -ne 0 ] && [ $rc -ne 124 ] && quota_error_in "$cycle_log"; then
    mark_quota_backoff "$lane"
  fi
  return $rc
}

supervise_lane() {
  local lane="$1" rc idx
  ensure_worktree "$lane" || { log "$lane" "worktree unavailable — retry in ${CRASH_SLEEP}s"; sleep "$CRASH_SLEEP"; exec bash "$SELF" lane-locked "$lane"; }
  while true; do
    if [ -f "$RUN/STOP_$lane" ]; then log "$lane" "STOP_$lane present — lane stopped"; exit 0; fi
    if [ -f "$HOLD" ]; then sleep 60; continue; fi
    if quota_backoff_active; then sleep 60; continue; fi
    case "$lane" in
      k*) idx="${lane#k}"; if (( idx > $(workers_wanted) )); then sleep 60; continue; fi ;;
      v*) idx="${lane#v}"; if (( idx > $(verifiers_wanted) )); then sleep 60; continue; fi ;;
    esac
    LAST_FILE=""; run_cycle "$lane"; rc=$?
    case $rc in
      0) if [ -n "$LAST_FILE" ] && grep -q 'IDLE-OK' "$LAST_FILE" 2>/dev/null; then sleep "$IDLE_SLEEP"
         else case "$lane" in k*) sleep "$CYCLE_SLEEP" ;; *) sleep "$CONTROL_SLEEP" ;; esac; fi ;;
      75) sleep 300 ;;
      *) sleep "$CRASH_SLEEP" ;;
    esac
  done
}

locked_lane() {   # one loop per lane, enforced by an exclusive non-blocking lock
  valid_lane "$1" || return 2
  "$PY" - "$RUN/$1.lock" "$SELF" "$1" <<'PYEOF'
import fcntl, subprocess, sys
lock = open(sys.argv[1], "a+")
try: fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
except BlockingIOError: raise SystemExit(0)      # already supervised
raise SystemExit(subprocess.call(["bash", sys.argv[2], "lane-locked", sys.argv[3]], pass_fds=(lock.fileno(),)))
PYEOF
}

status() {
  echo "── KĀLA-YANTRA fleet ── $(ts) ── HOLD: $([ -f "$HOLD" ] && echo YES || echo no) ── workers: $(workers_wanted) ── verifiers: $(verifiers_wanted) ── backoff: $(quota_backoff_active && echo ACTIVE || echo no)"
  local lane last n
  for lane in "${ALL_LANES[@]}"; do
    last="$(ls -t "$LOGD"/"$lane".*.last.md 2>/dev/null | head -1)"
    n="$( [ -n "$last" ] && basename "$last" | cut -d. -f2 )"
    printf "%-11s %s  cycle %-4s %s  %s\n" "$lane" "$( [ -f "$RUN/STOP_$lane" ] && echo STOP || echo run )" "${n:-—}" "$( [ -n "$last" ] && date -r "$last" +%H:%M || echo '--:--' )" "$( [ -n "$last" ] && tail -n 1 "$last" | cut -c1-100 )"
  done
  local today; today="$(grep -c "\"ts\": \"$(date -u +%Y-%m-%d)" "$RUN/CYCLE_STARTS.jsonl" 2>/dev/null || true)"
  local tw tc; tw="$(grep -E "\"ts\": \"$(date -u +%Y-%m-%d)" "$RUN/CYCLE_STARTS.jsonl" 2>/dev/null | grep -c '"lane": "k' || true)"; tc=$(( ${today:-0} - ${tw:-0} ))
  echo "── cycle starts today: builders ${tw:-0} / $KY_MAX_CYCLES_PER_DAY · control lanes $tc / $KY_MAX_CONTROL_CYCLES_PER_DAY ── queued PRs: $(cd "$CAMP" && gh pr list --search 'is:queued' --json number --jq 'length' 2>/dev/null || echo '?')"
  [ -x "$KY_ROOT/bin/ky" ] && KY_STREAM=S "$KY_ROOT/bin/ky" status 2>/dev/null | head -6
  echo "(liveness and earned progress: KY_STREAM=S ky audit --since <ts>)"
}

smoke() {
  refuse_secrets
  bash "$HERE/make_codex_profile.sh" && ensure_shell_home || { echo "✗ cannot prepare the Codex profile or the lane shell"; return 1; }
  local out="$RUN/smoke" rc=0 bad missing; mkdir -p "$out"; [ -d "$WT/k1" ] || { echo "✗ lane worktree k1 missing"; return 1; }
  lane_env k1 K
  cat > "$out/worker.prompt" <<'EOP'
Run exactly this one shell command and reply with its output only, nothing else:
env | cut -d= -f1 | sort | tr "\n" " "; echo; for t in node npm gh docker psql git python3; do command -v $t >/dev/null 2>&1 && echo "tool:$t:ok" || echo "tool:$t:MISSING"; done
EOP
  : > "$out/worker.last"
  if env -i "${LANE_ENV[@]}" codex exec -p "$CODEX_PROFILE" -s read-only -C "$WT/k1" --skip-git-repo-check -m "$MODEL_WORKER" -c 'model_reasoning_effort="low"' -o "$out/worker.last" - < "$out/worker.prompt" > "$out/worker.log" 2>&1; then
    echo "✓ worker model $MODEL_WORKER starts under profile $CODEX_PROFILE"
  else echo "✗ worker model $MODEL_WORKER did not start: $(grep -E '^ERROR|^Error' "$out/worker.log" | head -1 | cut -c1-200)"; rc=1; fi
  bad="$(tr ' ' '\n' < "$out/worker.last" | grep -iE 'KEY|TOKEN|SECRET|COOKIE|PASSW|CREDENTIAL|DATABASE_URL|^PG(PASSWORD|USER|HOST|DATABASE|SERVICE)$' | tr '\n' ' ')"
  if [ -n "$bad" ]; then echo "✗ a command run by a lane can see credential-like variables: $bad"; rc=1; else echo "✓ no credential-like variable reaches a lane's commands"; fi
  missing="$(grep -oE 'tool:[a-z0-9]+:MISSING' "$out/worker.last" | tr '\n' ' ')"
  if [ -n "$missing" ] || ! grep -q 'tool:node:ok' "$out/worker.last"; then echo "✗ tools not found on the lane path: ${missing:-the tool report is missing}"; rc=1; else echo "✓ node, npm, gh, docker, psql, git, python3 resolve on the lane path"; fi
  printf 'Reply with exactly the single word READY and stop. Do not run any command.\n' > "$out/reviewer.prompt"; : > "$out/reviewer.last"
  lane_env v1 V
  if env -i "${LANE_ENV[@]}" codex exec -p "$CODEX_PROFILE" -s read-only -C "$WT/v1" --skip-git-repo-check -m "$MODEL_PARIKSAKA" -c 'model_reasoning_effort="low"' -o "$out/reviewer.last" - < "$out/reviewer.prompt" > "$out/reviewer.log" 2>&1 && grep -q READY "$out/reviewer.last"; then
    echo "✓ reviewer model $MODEL_PARIKSAKA starts under profile $CODEX_PROFILE"
  else echo "✗ reviewer model $MODEL_PARIKSAKA did not start: $(grep -E '^ERROR|^Error' "$out/reviewer.log" | head -1 | cut -c1-200)"; rc=1; fi
  printf '{"ts":"%s","result":"%s","profile":"%s","worker_model":"%s","reviewer_model":"%s"}\n' "$(ts)" "$([ $rc -eq 0 ] && echo PASS || echo FAIL)" "$CODEX_PROFILE" "$MODEL_WORKER" "$MODEL_PARIKSAKA" > "$RUN/LANE_SMOKE.json"
  [ $rc -eq 0 ] && echo "LANE SMOKE PASS" || echo "LANE SMOKE FAIL"; return $rc
}

snapshot_self() {   # supervisors run from a snapshot, so an edit in the working tree can never change a running loop
  local live="$KY_ROOT/fleet_live"
  mkdir -p "$live" && rsync -a --delete "$BRIEF/fleet/" "$live/" || return 1
  echo "$live/kalayantra_fleet.sh"
}
up() {
  refuse_secrets
  [ -f "$HOLD" ] && { echo "HOLD exists at $HOLD; use: $0 resume"; return 1; }
  local lane runner
  no_wrappers || return 78
  runner="$(snapshot_self)" || { echo "cannot snapshot the fleet folder to $KY_ROOT/fleet_live"; return 1; }
  rm -f "$RUN/NODE_BIN"; node_bin >/dev/null || { echo "node was not found (set KY_NODE_BIN in fleet.env)"; return 1; }
  bash "$HERE/make_codex_profile.sh" && ensure_shell_home || { echo "cannot prepare the Codex profile or the lane shell"; return 1; }
  for lane in "${ALL_LANES[@]}"; do
    rm -f "$RUN/STOP_$lane"
    # double-fork into a new session: the loop survives the shell (or the Codex session) that started it
    "$PY" -c 'import os, sys
if os.fork(): os._exit(0)
os.setsid()
if os.fork(): os._exit(0)
log = os.open(sys.argv[3], os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600); null = os.open(os.devnull, os.O_RDONLY)
os.dup2(null, 0); os.dup2(log, 1); os.dup2(log, 2)
os.execvp("bash", ["bash", sys.argv[1], "lane", sys.argv[2]])' "$runner" "$lane" "$LOGD/supervisor.$lane.out"
  done
  sleep 2; log fleet "up requested for ${#ALL_LANES[@]} lanes from $runner (locks dedupe)"; status
}
down() {
  local lane
  for lane in "${ALL_LANES[@]}"; do touch "$RUN/STOP_$lane"; done
  log fleet "down: STOP files written; active cycles finish within the cap"
  echo "Stop requested. Active cycles keep their watchdog and finish within ${MAX_CYCLE_SECS}s; loops then exit."
}

case "${1:-status}" in
  up) up ;;
  down) down ;;
  resume) rm -f "$HOLD"; for lane in "${ALL_LANES[@]}"; do rm -f "$RUN/STOP_$lane"; done; up ;;
  status) status ;;
  smoke) smoke ;;
  lane) refuse_secrets; locked_lane "${2:?lane name required}" ;;
  lane-locked) valid_lane "${2:?}" || exit 2; supervise_lane "$2" ;;
  *) echo "usage: $0 up|down|resume|status|smoke|lane <name>"; exit 2 ;;
esac
