#!/usr/bin/env bash
# Generate the campaign's Codex profile: $CODEX_HOME/kalayantra.config.toml, layered by `codex -p kalayantra` on the user's
# base config. It gives a lane the autonomy posture of `madhav-parity` (approvals never, full access) and NOTHING ELSE of the
# user's personal setup: every MCP server and every plugin of the base config is switched off (the base config carries a
# database connector with an embedded connection — a lane must not have it), the turn-end notifier is silenced, and the shell
# environment is reduced to an allow-list. Regenerated at every `up` and before every cycle, because the base config changes
# (a server added there after generation would otherwise be live in a lane — the way `madhav-parity` itself broke).
# Reads section NAMES only; never prints or copies a value. Idempotent; atomic replace. Exit 1 if the base config is unreadable.
set -euo pipefail
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
/opt/homebrew/bin/python3 - "$CODEX_HOME" <<'PYEOF'
import os, pathlib, sys, tomllib
home = pathlib.Path(sys.argv[1]); base = home / "config.toml"; out = home / "kalayantra.config.toml"
try:
    cfg = tomllib.loads(base.read_text())
except Exception as e:
    print(f"cannot read the base Codex config: {type(e).__name__}", file=sys.stderr); sys.exit(1)
q = lambda k: '"' + k.replace('\\', '\\\\').replace('"', '\\"') + '"'
servers = sorted((cfg.get("mcp_servers") or {}).keys()); plugins = sorted((cfg.get("plugins") or {}).keys())
lines = [
    "# GENERATED by 00_ARCHITECTURE/briefs/kalayantra/fleet/make_codex_profile.sh — do not edit; regenerated before every cycle.",
    "# KĀLA-YANTRA lane profile: the madhav-parity posture, with every personal MCP server and plugin switched off.",
    'approval_policy = "never"', 'sandbox_mode = "danger-full-access"', "project_doc_fallback_filenames = []", "notify = []", "",
    "[shell_environment_policy]", 'inherit = "all"',
    'include_only = ["HOME", "PATH", "LANG", "LC_*", "TERM", "TMPDIR", "USER", "LOGNAME", "SHELL", "PWD", "ZDOTDIR", "BASH_ENV", "ENV", "KY_*", "SE_EPHE_PATH", "SWE_EPHE_PATH", "CODEX_HOME"]',
    "experimental_use_profile = false", "",
]
for s in servers: lines += [f"[mcp_servers.{q(s)}]", "enabled = false", ""]
for p in plugins: lines += [f"[plugins.{q(p)}]", "enabled = false", ""]
text = "\n".join(lines)
if not out.exists() or out.read_text() != text:
    tmp = out.with_suffix(".toml.tmp"); tmp.write_text(text); os.chmod(tmp, 0o600); tmp.replace(out)
print(f"profile kalayantra: {len(servers)} MCP servers off, {len(plugins)} plugins off → {out}")
PYEOF
