/**
 * Tool 25: classical_text_search
 *
 * Semantic + full-text search over classical_text_chunks.
 * Combines pgvector cosine similarity with tsvector FTS.
 * Embeddings generated by Vertex AI text-multilingual-embedding-002 (768-dim).
 *
 * L0FR Stream C implementation — 2026-06-07
 */

import 'server-only'
import { query } from '@/lib/db/client'

export interface ClassicalTextSearchInput {
  query: string
  schools?: string[]
  tier_max?: number
  limit?: number
}

export interface ClassicalTextSearchResult {
  chunk_id: string
  text_key: string
  chapter: string | null
  verse_range: string | null
  text: string
  confidence_baseline: number
  tier: number
  school: string | null
}

export interface ClassicalTextSearchOutput {
  results: ClassicalTextSearchResult[]
  total: number
  query_used: string
}

/** Fetch embedding from sidecar or fallback to FTS-only */
async function getEmbeddingForQuery(queryText: string): Promise<number[] | null> {
  const sidecarUrl = process.env['PYTHON_SIDECAR_URL']
  if (!sidecarUrl) return null
  try {
    const res = await fetch(`${sidecarUrl}/embed`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text: queryText }),
      signal: AbortSignal.timeout(8000),
    })
    if (!res.ok) return null
    const data = await res.json() as { embedding?: number[] }
    return data.embedding ?? null
  } catch {
    return null
  }
}

export async function classical_text_search(
  input: ClassicalTextSearchInput
): Promise<ClassicalTextSearchOutput> {
  const { query: queryText, schools, limit = 5 } = input
  if (!queryText || queryText.trim().length < 3) {
    return { results: [], total: 0, query_used: queryText }
  }

  const cap = Math.min(limit, 20)

  // Try vector search first
  const embedding = await getEmbeddingForQuery(queryText)

  let rows: Array<{
    chunk_id: string
    text_id: string
    chapter: number | null
    verse_ref: string | null
    content_en: string
    tradition_school: string | null
    rank: number
  }> = []

  if (embedding) {
    // Vector similarity search
    const embeddingStr = '[' + embedding.join(',') + ']'
    let sql = `
      SELECT
        c.chunk_id,
        c.text_id,
        c.chapter,
        c.verse_ref,
        c.content_en,
        c.tradition_school,
        (1 - (c.embedding <=> $1::vector))::float AS rank
      FROM classical_text_chunks c
      WHERE c.embedding IS NOT NULL
    `
    const params: unknown[] = [embeddingStr]

    if (schools && schools.length > 0) {
      sql += ` AND c.tradition_school = ANY($${params.length + 1}::text[])`
      params.push(schools)
    }

    sql += ` ORDER BY c.embedding <=> $1::vector LIMIT $${params.length + 1}`
    params.push(cap)

    const result = await query<{
      chunk_id: string
      text_id: string
      chapter: number | null
      verse_ref: string | null
      content_en: string
      tradition_school: string | null
      rank: number
    }>(sql, params)
    rows = result.rows
  }

  // If no embedding or no results, fall back to full-text search
  if (rows.length === 0) {
    const tsQuery = queryText
      .trim()
      .split(/\s+/)
      .filter(w => w.length > 2)
      .map(w => `${w}:*`)
      .join(' & ')

    let sql = `
      SELECT
        c.chunk_id,
        c.text_id,
        c.chapter,
        c.verse_ref,
        c.content_en,
        c.tradition_school,
        ts_rank(to_tsvector('english', c.content_en), to_tsquery('english', $1))::float AS rank
      FROM classical_text_chunks c
      WHERE to_tsvector('english', c.content_en) @@ to_tsquery('english', $1)
    `
    const params: unknown[] = [tsQuery]

    if (schools && schools.length > 0) {
      sql += ` AND c.tradition_school = ANY($${params.length + 1}::text[])`
      params.push(schools)
    }

    sql += ` ORDER BY rank DESC LIMIT $${params.length + 1}`
    params.push(cap)

    try {
      const result = await query<{
        chunk_id: string
        text_id: string
        chapter: number | null
        verse_ref: string | null
        content_en: string
        tradition_school: string | null
        rank: number
      }>(sql, params)
      rows = result.rows
    } catch {
      // FTS query parse error — fallback to ILIKE
      let sql2 = `
        SELECT
          c.chunk_id,
          c.text_id,
          c.chapter,
          c.verse_ref,
          c.content_en,
          c.tradition_school,
          0.5::float AS rank
        FROM classical_text_chunks c
        WHERE c.content_en ILIKE $1
      `
      const params2: unknown[] = [`%${queryText.substring(0, 50)}%`]

      if (schools && schools.length > 0) {
        sql2 += ` AND c.tradition_school = ANY($${params2.length + 1}::text[])`
        params2.push(schools)
      }
      sql2 += ` ORDER BY rank DESC LIMIT $${params2.length + 1}`
      params2.push(cap)

      const result2 = await query<{
        chunk_id: string
        text_id: string
        chapter: number | null
        verse_ref: string | null
        content_en: string
        tradition_school: string | null
        rank: number
      }>(sql2, params2)
      rows = result2.rows
    }
  }

  const results: ClassicalTextSearchResult[] = rows.map(r => ({
    chunk_id: r.chunk_id,
    text_key: r.text_id,
    chapter: r.chapter !== null ? String(r.chapter) : null,
    verse_range: r.verse_ref ?? null,
    text: r.content_en ?? '',
    confidence_baseline: Math.max(0, Math.min(1, Number(r.rank) || 0.5)),
    tier: 1,
    school: r.tradition_school ?? null,
  }))

  return { results, total: results.length, query_used: queryText }
}
