/**
 * C-2 fixture corpus → REAL `PariprashnaEvent` wire bridge — SAMĀPTI lane
 * B-PB8-BYTEEQ, deliverable (a) of
 * `FOLLOWUP_PB-2_BYTE_EQUALITY_FIXTURE_COVERAGE.md`.
 *
 * WHY THIS EXISTS
 * ───────────────
 * `canonical_serialization_golden.test.ts` (PB-2 lane M-2) asserts byte-equality
 * between a client-reducer simulation and the real production writer mapping —
 * but only over ONE hand-authored inline fixture. The 12-fixture corpus at
 * `platform/tests/pariprashna/fixtures/*.json` (generated by
 * `platform/scripts/replay/build_fixtures.ts`) is in lane C-2's PRE-LOCK harness
 * shape and cannot be pointed at that gate without a real semantic bridge.
 *
 * WHAT THIS IS NOT
 * ────────────────
 * This is NOT `src/components/pariprashna/state/c2ProtocolAdapter.ts`. That
 * adapter converts the same 12-fixture shape into a THIRD, UI-renderer-internal
 * shape (`ScheduledEvent`/`WireEvent`) for driving the React component tree —
 * it never produces a `PariprashnaEvent`, and so cannot feed the canonical
 * store's byte-equality gate at all. This module targets the real, Zod-validated
 * `@/lib/pariprashna/protocol/events` union and nothing else.
 *
 * THE HONESTY CONTRACT (why every event carries a recorded decision)
 * ──────────────────────────────────────────────────────────────────
 * The follow-up's §4 warns explicitly that "a half-built bridge that silently
 * drops the two no-equivalent event types without a documented decision would
 * itself become a new instance of the exact problem this follow-up exists to
 * fix." So: EVERY source event produces exactly one `BridgeDecision` row naming
 * its disposition and the reason. Nothing is silently dropped, nothing is
 * silently invented. The corpus test asserts the decision ledger's shape, so a
 * future change to the mapping cannot slide through unnoticed.
 *
 * PER-TYPE MAPPING DECISIONS (the authored part — not a mechanical rename)
 * ───────────────────────────────────────────────────────────────────────
 *   turn.open           MAPPED+SYNTH. `reading_depth: 'standard'` is not in the
 *                       real `ReadingDepthSchema` enum (`auto | deep_dive`).
 *                       Reinterpreted as `'auto'` — C-2's "standard" means
 *                       "engine-chosen, not forced deep", which is precisely
 *                       what `auto` means on the real wire. `deep_dive` passes
 *                       through unchanged.
 *   phase               MAPPED+SYNTH. C-2 phase names (`planning`,
 *                       `synthesizing`) → real enum (`plan`, `synthesize`).
 *                       C-2 carries NO `status`; the real event requires one.
 *                       Synthesized as `'start'` (a C-2 phase event marks entry
 *                       into a phase — there is no C-2 end marker to lose).
 *                       C-2's free-text `label` has no target field and is
 *                       dropped (the real wire resolves labels client-side).
 *   activity.upsert     MAPPED. `pass_id: 'pass-N'` (string) → first-seen
 *                       ordinal int, matching `c2ProtocolAdapter.ts`'s own
 *                       precedent for the same corpus. `status`
 *                       `pending`/`active` → `running`; `done` → `done`.
 *   block.open          MAPPED+SYNTH. C-2's `kind`
 *                       (`paragraph`/`heading`/`table`) is a RENDER kind; the
 *                       real wire's `role` (`prose`/`thinking`) is an
 *                       orthogonal visibility axis. Every C-2 kind in the
 *                       corpus is reader-visible prose → `role: 'prose'`. The
 *                       render kind and `index` have no target field and are
 *                       dropped. `pass_id` (required int on the real event) is
 *                       taken from the most recent activity pass ordinal, or 1.
 *   block.delta         MAPPED. `text` → `delta`.
 *   block.commit        MAPPED. `final_text` → `text`.
 *   citation.define     MAPPED+SYNTH. `citation_id` (string) → `index`
 *                       (first-seen ordinal int); `source_ref` → `signal_id`;
 *                       `label` → `snippet`; `verification` → `grade`
 *                       VERBATIM (C-2's vocabulary is `confirmed`/
 *                       `catalog_only`; the real `grade` is a free string, and
 *                       re-coding it into S-3's `primary|supporting|contextual|
 *                       unverified` would be an invented semantic — B.10).
 *                       `layer` is REQUIRED by the real schema and C-2 carries
 *                       no equivalent: filled with the explicit sentinel
 *                       `UNKNOWN_LAYER_SENTINEL` rather than a plausible-looking
 *                       real layer id. Consequence, stated plainly: this corpus
 *                       does NOT exercise real `layer` values.
 *   citation_anchor.*   DROPPED — NO TARGET. C-2's
 *                       `citation_anchor.open{anchor_offset}` +
 *                       `citation_anchor.set{citation_id}` pair encodes a
 *                       CHARACTER-OFFSET anchor placement inside a block's
 *                       text. The real wire has no such event, AND the
 *                       canonical `message_parts` model has no offset/anchor
 *                       concept at any layer (a `citation` part body is
 *                       index/signal_id/layer/snippet/reader_label/grade — see
 *                       `store/schema.ts`). Dropping therefore loses NO
 *                       canonical-part information. It does lose the
 *                       `citation_id: null` "no source found" signal in
 *                       `honest-gap.json` — which that same fixture carries
 *                       independently as a `flag{flag_key:'honest_gap.*'}`,
 *                       so the fixture's intent survives the drop.
 *   flag                MAPPED. `flag_key` → `code`, `severity` → `level`
 *                       (`notice` → `info`). NOTE: the follow-up's §2 states
 *                       "the real protocol has no corresponding flag code" —
 *                       that is REFUTED as worded: `FlagEventSchema.code` is
 *                       `z.string()`, a free label_key, so `honest_gap.*` rides
 *                       it unchanged. What IS true is that no `honest_gap` flag
 *                       produces a canonical part (only
 *                       `code === 'prediction_candidate'` does), so it is a
 *                       byte-equality no-op either way.
 *   turn.commit         MAPPED+SYNTH. The real event requires
 *                       `conversation_id`, `message_id`, `status`,
 *                       `assistant_chars`; C-2 carries `block_count` /
 *                       `citation_count` instead. `conversation_id` comes from
 *                       the fixture's own `turn.open`; `message_id` is a
 *                       DETERMINISTIC synthetic derived from the turn id;
 *                       `status: 'ok'`; `assistant_chars` is DERIVED (sum of
 *                       committed block text lengths), not invented.
 *                       `block_count`/`citation_count` have no target field and
 *                       are dropped. Load-bearing honesty note: `turn.commit`
 *                       drives NO canonical part in EITHER path, so none of
 *                       this synthesis can influence the byte-equality result —
 *                       the corpus test's "turn.commit synthesis cannot
 *                       influence the gate" case asserts exactly that.
 *   turn.close          MAPPED. `reason` → `status` (`complete` → `ok`,
 *                       `stopped`/`aborted`/`disconnect` → `aborted`, `error` →
 *                       `error`); `ms` derived from the event's own `t`.
 *   <anything else>     DROPPED — MALFORMED. `malformed-sentinel-variants.json`
 *                       deliberately contains a `blck.open` typo and an event
 *                       with no `type` field at all. Those are recorded as
 *                       dropped-malformed with a reason, never silently skipped.
 *
 * SEQ / T
 * ───────
 * `seq` is renumbered densely (0..n-1) over EMITTED events, because drops leave
 * holes in C-2's numbering and the real protocol's contract is a monotonic
 * per-turn sequence. `t` is carried over from the source event when it is a
 * non-negative integer, else clamped to 0.
 *
 * Every emitted event is `PariprashnaEventSchema.parse`d before it leaves this
 * module, so a bridge bug is a throw here, never a silently-malformed event
 * laundered through two paths that happen to agree on garbage.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import {
  PariprashnaEventSchema,
  type PariprashnaEvent,
  type PariprashnaEventType,
} from '@/lib/pariprashna/protocol/events'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type BridgeDisposition =
  /** 1:1 field rename, no authored decision required. */
  | 'mapped'
  /** Mapped, but at least one required target field had to be reinterpreted or derived. */
  | 'mapped_with_synthesis'
  /** The real protocol + canonical model have no target for this concept. */
  | 'dropped_no_target'
  /** The source event is deliberately malformed corpus content. */
  | 'dropped_malformed'

export interface BridgeDecision {
  /** Index of the source event within the fixture's `events` array. */
  source_index: number
  source_type: string
  disposition: BridgeDisposition
  target_type: PariprashnaEventType | null
  reason: string
}

export interface BridgedFixture {
  name: string
  description: string
  /** Real, Zod-validated wire events, densely re-sequenced. */
  events: PariprashnaEvent[]
  /** One row per SOURCE event — total, exhaustive, never partial. */
  decisions: BridgeDecision[]
}

export interface C2RawScheduledEvent {
  delay_ms: number
  event: Record<string, unknown>
}

export interface C2Fixture {
  name: string
  description?: string
  events: C2RawScheduledEvent[]
}

/**
 * Explicit sentinel for the required-but-absent `citation.define.layer`.
 * Deliberately NOT a plausible real layer id ('L1'/'L2.5'/…) — a reader
 * inspecting bridged output must be able to tell at a glance that no real
 * layer value was available.
 */
export const UNKNOWN_LAYER_SENTINEL = 'bridge:unknown-layer'

/** `Omit` distributed over a discriminated union (plain `Omit` collapses it). */
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never

// ---------------------------------------------------------------------------
// Small mapping helpers (each one is an authored decision, documented above)
// ---------------------------------------------------------------------------

function mapReadingDepth(raw: unknown): 'auto' | 'deep_dive' {
  return raw === 'deep_dive' ? 'deep_dive' : 'auto'
}

function mapLengthTier(raw: unknown): 'brief' | 'standard' | 'exhaustive' {
  return raw === 'brief' || raw === 'exhaustive' ? raw : 'standard'
}

function mapPhaseName(raw: unknown): 'plan' | 'retrieve' | 'synthesize' | 'finalize' | null {
  switch (raw) {
    case 'planning':
    case 'plan':
      return 'plan'
    case 'retrieval':
    case 'retrieve':
      return 'retrieve'
    case 'synthesizing':
    case 'synthesize':
      return 'synthesize'
    case 'finalizing':
    case 'finalize':
      return 'finalize'
    default:
      return null
  }
}

function mapActivityStatus(raw: unknown): 'running' | 'done' | 'error' {
  if (raw === 'done') return 'done'
  if (raw === 'error') return 'error'
  return 'running' // 'pending' | 'active' | anything else
}

function mapFlagLevel(raw: unknown): 'info' | 'warn' | 'error' {
  if (raw === 'error' || raw === 'critical') return 'error'
  if (raw === 'warn' || raw === 'warning') return 'warn'
  return 'info' // 'notice' | undefined | anything else
}

function mapCloseStatus(raw: unknown): 'ok' | 'error' | 'aborted' {
  if (raw === 'error') return 'error'
  if (raw === 'stopped' || raw === 'aborted' || raw === 'disconnect' || raw === 'interrupted') return 'aborted'
  return 'ok' // 'complete'
}

function nonNegInt(raw: unknown): number {
  const n = typeof raw === 'number' ? Math.trunc(raw) : 0
  return Number.isFinite(n) && n >= 0 ? n : 0
}

function str(raw: unknown, fallback = ''): string {
  return typeof raw === 'string' ? raw : fallback
}

/** Deterministic synthetic message id for `turn.commit` (no randomness — the
 *  bridge must be pure so the corpus test is reproducible). */
function syntheticMessageId(turnId: string): string {
  return `bridge-message-${turnId}`
}

// ---------------------------------------------------------------------------
// The bridge
// ---------------------------------------------------------------------------

export function bridgeC2Fixture(raw: C2Fixture): BridgedFixture {
  const events: PariprashnaEvent[] = []
  const decisions: BridgeDecision[] = []

  let seq = 0
  const push = (event: DistributiveOmit<PariprashnaEvent, 'seq'>): void => {
    const withSeq = { ...event, seq: seq++ } as PariprashnaEvent
    // Fail-fast: a bridge bug must throw here, never reach the gate.
    events.push(PariprashnaEventSchema.parse(withSeq) as PariprashnaEvent)
  }

  const passOrdinalByPassId = new Map<string, number>()
  const citationIndexByCitationId = new Map<string, number>()
  let currentPassOrdinal = 1
  let turnId = raw.name
  let conversationId = `conv-${raw.name}`
  /** Running sum of committed block text lengths — the DERIVED `assistant_chars`. */
  let committedChars = 0

  raw.events.forEach((scheduled, sourceIndex) => {
    const e = scheduled.event ?? {}
    const type = typeof e.type === 'string' ? e.type : null
    const t = nonNegInt(e.t)

    const record = (
      disposition: BridgeDisposition,
      target: PariprashnaEventType | null,
      reason: string,
    ): void => {
      decisions.push({ source_index: sourceIndex, source_type: type ?? '<no type field>', disposition, target_type: target, reason })
    }

    switch (type) {
      case 'turn.open': {
        turnId = str(e.turn_id, raw.name)
        conversationId = str(e.conversation_id, `conv-${raw.name}`)
        push({
          type: 'turn.open',
          t,
          turn_id: turnId,
          conversation_id: conversationId,
          chart_id: str(e.chart_id),
          model_id: str(e.model_id),
          reading_depth: mapReadingDepth(e.reading_depth),
          length_tier: mapLengthTier(e.length_tier),
        })
        record(
          'mapped_with_synthesis',
          'turn.open',
          `reading_depth ${JSON.stringify(e.reading_depth)} -> ${mapReadingDepth(e.reading_depth)} (C-2 'standard' is not in ReadingDepthSchema; 'auto' carries the same "engine-chosen" meaning)`,
        )
        break
      }

      case 'phase': {
        const phase = mapPhaseName(e.phase)
        if (phase === null) {
          record('dropped_malformed', null, `phase name ${JSON.stringify(e.phase)} has no target in PhaseNameSchema`)
          break
        }
        push({ type: 'phase', t, phase, status: 'start' })
        record(
          'mapped_with_synthesis',
          'phase',
          `phase ${JSON.stringify(e.phase)} -> '${phase}'; status synthesized as 'start' (C-2 carries no status and no end marker); C-2 free-text label dropped (no target field)`,
        )
        break
      }

      case 'activity.upsert': {
        const passKey = str(e.pass_id, 'pass-1')
        if (!passOrdinalByPassId.has(passKey)) passOrdinalByPassId.set(passKey, passOrdinalByPassId.size + 1)
        currentPassOrdinal = passOrdinalByPassId.get(passKey)!
        push({
          type: 'activity.upsert',
          t,
          key: str(e.key, `activity-${sourceIndex}`),
          label_key: str(e.label_key),
          pass_id: currentPassOrdinal,
          status: mapActivityStatus(e.status),
          ...(typeof e.detail === 'string' ? { detail: e.detail } : {}),
        })
        record(
          'mapped',
          'activity.upsert',
          `pass_id '${passKey}' -> ordinal ${currentPassOrdinal}; status ${JSON.stringify(e.status)} -> ${mapActivityStatus(e.status)}`,
        )
        break
      }

      case 'block.open': {
        push({
          type: 'block.open',
          t,
          block_id: str(e.block_id, `blk-${sourceIndex}`),
          pass_id: currentPassOrdinal,
          role: 'prose',
        })
        record(
          'mapped_with_synthesis',
          'block.open',
          `render kind ${JSON.stringify(e.kind)} + index ${JSON.stringify(e.index)} dropped (no target field; 'kind' is a render axis, 'role' a visibility axis); role synthesized 'prose'; pass_id from current pass ordinal ${currentPassOrdinal}`,
        )
        break
      }

      case 'block.delta': {
        push({ type: 'block.delta', t, block_id: str(e.block_id), delta: str(e.text) })
        record('mapped', 'block.delta', "field rename text -> delta")
        break
      }

      case 'block.commit': {
        const text = str(e.final_text)
        committedChars += text.length
        push({ type: 'block.commit', t, block_id: str(e.block_id), text })
        record('mapped', 'block.commit', 'field rename final_text -> text')
        break
      }

      case 'citation.define': {
        const cid = str(e.citation_id, `c-${sourceIndex}`)
        if (!citationIndexByCitationId.has(cid)) citationIndexByCitationId.set(cid, citationIndexByCitationId.size + 1)
        const index = citationIndexByCitationId.get(cid)!
        push({
          type: 'citation.define',
          t,
          index,
          signal_id: str(e.source_ref),
          layer: UNKNOWN_LAYER_SENTINEL,
          snippet: str(e.label),
          ...(typeof e.verification === 'string' ? { grade: e.verification } : {}),
        })
        record(
          'mapped_with_synthesis',
          'citation.define',
          `citation_id '${cid}' -> index ${index}; source_ref -> signal_id; label -> snippet; verification -> grade VERBATIM (re-coding into S-3's vocabulary would invent a semantic); layer REQUIRED but absent in C-2 -> sentinel '${UNKNOWN_LAYER_SENTINEL}' (this corpus does not exercise real layer values)`,
        )
        break
      }

      case 'citation_anchor.open':
      case 'citation_anchor.set': {
        record(
          'dropped_no_target',
          null,
          'character-offset citation anchoring has no event on the real wire AND no field anywhere in the canonical message_parts model, so the drop loses no canonical-part information; honest-gap.json carries its "no source found" intent independently via flag{honest_gap.*}',
        )
        break
      }

      case 'flag': {
        push({
          type: 'flag',
          t,
          code: str(e.flag_key, 'unknown'),
          level: mapFlagLevel(e.severity),
          ...(typeof e.detail === 'string' ? { detail: e.detail } : {}),
        })
        record(
          'mapped',
          'flag',
          `flag_key -> code (FlagEventSchema.code is z.string(), so honest_gap.* rides unchanged); severity ${JSON.stringify(e.severity)} -> level ${mapFlagLevel(e.severity)}`,
        )
        break
      }

      case 'turn.commit': {
        push({
          type: 'turn.commit',
          t,
          turn_id: str(e.turn_id, turnId),
          conversation_id: conversationId,
          message_id: syntheticMessageId(str(e.turn_id, turnId)),
          status: 'ok',
          assistant_chars: committedChars,
        })
        record(
          'mapped_with_synthesis',
          'turn.commit',
          `conversation_id from this fixture's turn.open; message_id deterministic synthetic; status 'ok'; assistant_chars DERIVED (${committedChars} = sum of committed block text lengths); block_count/citation_count dropped (no target field). Drives no canonical part in either path — asserted by the corpus test.`,
        )
        break
      }

      case 'turn.close': {
        push({
          type: 'turn.close',
          t,
          turn_id: str(e.turn_id, turnId),
          status: mapCloseStatus(e.reason),
          ms: t,
        })
        record('mapped', 'turn.close', `reason ${JSON.stringify(e.reason)} -> status ${mapCloseStatus(e.reason)}; ms derived from t`)
        break
      }

      default: {
        record(
          'dropped_malformed',
          null,
          type === null
            ? 'source event has no `type` field (deliberate malformed-corpus content)'
            : `unknown source event type '${type}' (deliberate malformed-corpus content, e.g. the 'blck.open' typo)`,
        )
        break
      }
    }
  })

  return {
    name: raw.name,
    description: raw.description ?? '',
    events,
    decisions,
  }
}

// ---------------------------------------------------------------------------
// Corpus loading
// ---------------------------------------------------------------------------

export const C2_CORPUS_DIR = join(__dirname, '..', 'fixtures')

/** Load + bridge every fixture in the corpus, sorted by name for determinism. */
export function loadBridgedCorpus(dir: string = C2_CORPUS_DIR): BridgedFixture[] {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
  return files.map((f) => bridgeC2Fixture(JSON.parse(readFileSync(join(dir, f), 'utf8')) as C2Fixture))
}
