/**
 * Paripraśna replay harness — fixture wire format.
 *
 * A "fixture" is a recorded SSE event stream simulating one assistant turn,
 * plus timing/transport directives that tell the replay server HOW to send
 * it (delays, byte-trickling, abrupt disconnects). This is harness-only
 * plumbing — it has no bearing on S-1's real route implementation, which
 * will presumably generate these events live rather than replay them from
 * disk.
 *
 * Fixtures are generated by `build_fixtures.ts` into
 * `platform/tests/pariprashna/fixtures/<name>.json` and served by
 * `server.ts`.
 */
import type { PariprashnaEventT } from '../../src/lib/pariprashna/protocol/events'

/** One entry in a fixture's event list. `delay_ms` is the pause BEFORE this
 *  event is sent, measured from when the previous event finished sending. */
export interface FixtureEventEntry {
  delay_ms: number
  /** The event payload. Typed loosely (not strictly PariprashnaEventT) so
   *  fixtures can deliberately encode protocol-invalid payloads (the
   *  malformed-sentinel-variants fixture depends on this escape hatch). */
  event: PariprashnaEventT | Record<string, unknown>
}

export interface FixtureSpec {
  name: string
  description: string
  events: FixtureEventEntry[]
  /** If set, every event's serialized SSE frame is written to the socket in
   *  chunks of at most this many bytes (with a tiny inter-chunk delay),
   *  instead of in one write() call. Simulates a slow/fragmenting transport. */
  chunk_bytes?: number
  /** If set, the server closes the TCP connection immediately after sending
   *  the event whose `seq` equals this value, WITHOUT sending any further
   *  events (even if more are defined) — simulates a mid-stream disconnect
   *  or an abrupt EOF with no turn.close. */
  abrupt_end_after_seq?: number
}

/** On-disk shape written by build_fixtures.ts / read by server.ts. Identical
 *  to FixtureSpec — kept as a separate alias in case the on-disk format ever
 *  needs to diverge from the in-memory builder shape. */
export type FixtureFile = FixtureSpec
