"""
brahmagyan.bodha.l2_grounded_batch_2 — BRAHMA-BO-2-1 (L2 Bodha Grounding)
======================================================================

WS-2 session l2-bodha-grounded: Batch 2
Signals grounded: SIG.MSR.101 – SIG.MSR.200 (100 signals)

Each entry in GROUNDED_SIGNALS maps signal_id → grounding assignment:
  rule_id:           WS-3 rule from rule corpus (WS3_RULE_BASE tag ws3-rule-base-complete)
  grounding_status:  GROUNDED | PARTIAL_MATCH | UNGROUNDED_NO_MATCH
  source_school:     parashari | jaimini | kp | tajaka | multi-school | nadi
  verse_citation:    source_verse.verse_ref from the matched rule
  match_confidence:  0.0–1.0 (scoring: scope 0–0.50, school 0–0.20, keyword 0–0.30)
  match_rationale:   brief rationale string

Batch 2 statistics:
  GROUNDED:            100
  PARTIAL_MATCH:       0
  UNGROUNDED_NO_MATCH: 0

Session: l2-bodha-grounded | Branch: feature/ws2-depth-build
Rule corpus: WS-3 (~1,370 rules across BPHS/Jaimini/KP/Tajaka)
Grounding algorithm: _grounding_engine.py
"""
from __future__ import annotations
from typing import Any


GROUNDED_SIGNALS: dict[str, dict[str, Any]] = {
    "SIG.MSR.101": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.102": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.103": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.104": {
        "rule_id": "BPHS.26.65.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.65",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.105": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.106": {
        "rule_id": "BPHS.35.7.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.7",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.107": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.108": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.109": {
        "rule_id": "BPHS.36.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.15",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.110": {
        "rule_id": "BPHS.36.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.15",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.111": {
        "rule_id": "BPHS.35.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.12",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.112": {
        "rule_id": "BPHS.76.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "76.3",
        "match_confidence": 0.75,
        "match_rationale": "scope=yoga / school=parashari / score=0.750",
    },
    "SIG.MSR.113": {
        "rule_id": "BPHS.36.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.12",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.114": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.115": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.116": {
        "rule_id": "BPHS.73.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "73.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.117": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.118": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.119": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.120": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.121": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.122": {
        "rule_id": "BPHS.36.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.52",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.123": {
        "rule_id": "BPHS.70.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "70.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.124": {
        "rule_id": "BPHS.36.50.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.50",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.125": {
        "rule_id": "BPHS.36.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.15",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.126": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.127": {
        "rule_id": "BPHS.70.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "70.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.128": {
        "rule_id": "BPHS.36.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.16",
        "match_confidence": 0.94,
        "match_rationale": "scope=yoga / school=parashari / score=0.940",
    },
    "SIG.MSR.129": {
        "rule_id": "BPHS.26.65.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.65",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.130": {
        "rule_id": "BPHS.36.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.16",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.131": {
        "rule_id": "BPHS.34.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.21",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.132": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.133": {
        "rule_id": "BPHS.71.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "71.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.134": {
        "rule_id": "BPHS.73.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "73.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.135": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.136": {
        "rule_id": "BPHS.75.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.22",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.137": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.138": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.139": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.140": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.141": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.867,
        "match_rationale": "scope=yoga / school=parashari / score=0.867",
    },
    "SIG.MSR.142": {
        "rule_id": "BPHS.36.35.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.35",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.143": {
        "rule_id": "BPHS.36.42.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.42",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.144": {
        "rule_id": "BPHS.35.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.12",
        "match_confidence": 1.0,
        "match_rationale": "scope=yoga / school=parashari / score=1.000",
    },
    "SIG.MSR.145": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.146": {
        "rule_id": "BPHS.70.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "70.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.147": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.148": {
        "rule_id": "BPHS.36.35.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.35",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.149": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.150": {
        "rule_id": "BPHS.47.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.151": {
        "rule_id": "BPHS.50.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "50.16",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.152": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.153": {
        "rule_id": "BPHS.25.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "25.12",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.154": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.155": {
        "rule_id": "BPHS.27.18.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.18",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.156": {
        "rule_id": "BPHS.10.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.10",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.157": {
        "rule_id": "BPHS.20.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "20.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.158": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.159": {
        "rule_id": "STUB_BPHS.CH14.RAHU_LAGNA_EFFECTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "14.APPROX.8",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.160": {
        "rule_id": "BPHS.27.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.161": {
        "rule_id": "STUB_BPHS.CH14.RAHU_LAGNA_EFFECTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "14.APPROX.8",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.162": {
        "rule_id": "STUB_BPHS.CH14.RAHU_LAGNA_EFFECTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "14.APPROX.8",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.163": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.164": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.165": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.166": {
        "rule_id": "BPHS.12.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "12.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.167": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.168": {
        "rule_id": "BPHS.38.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "38.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.169": {
        "rule_id": "BPHS.38.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "38.5",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.170": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.171": {
        "rule_id": "BPHS.75.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.6",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.172": {
        "rule_id": "JAIMINI.2.2.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.173": {
        "rule_id": "JAIMINI.2.1.3.2",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.174": {
        "rule_id": "JAIMINI.2.4.30.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.30",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.175": {
        "rule_id": "JAIMINI.2.4.30.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.30",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.176": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.177": {
        "rule_id": "JAIMINI.2.4.7.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.7",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.178": {
        "rule_id": "BPHS.38.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "38.5",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.179": {
        "rule_id": "BPHS.73.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "73.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.180": {
        "rule_id": "BPHS.73.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "73.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.181": {
        "rule_id": "BPHS.37.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "37.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.182": {
        "rule_id": "STUB_BPHS.CH49.RAHU_KETU_MOOLATRIKONA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.APPROX.10",
        "match_confidence": 0.71,
        "match_rationale": "scope=graha / school=parashari / score=0.710",
    },
    "SIG.MSR.183": {
        "rule_id": "BPHS.3.19.2",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.19",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.184": {
        "rule_id": "BPHS.36.27.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.27",
        "match_confidence": 0.91,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.910",
    },
    "SIG.MSR.185": {
        "rule_id": "BPHS.36.24.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.24",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.186": {
        "rule_id": "BPHS.36.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.22",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
    "SIG.MSR.187": {
        "rule_id": "BPHS.5.17.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.17",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.188": {
        "rule_id": "BPHS.36.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.21",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.189": {
        "rule_id": "BPHS.36.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.21",
        "match_confidence": 0.88,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.880",
    },
    "SIG.MSR.190": {
        "rule_id": "BPHS.5.18.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.18",
        "match_confidence": 0.88,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.880",
    },
    "SIG.MSR.191": {
        "rule_id": "BPHS.36.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.4",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.192": {
        "rule_id": "BPHS.36.18.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.18",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.193": {
        "rule_id": "BPHS.5.88.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.88",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.194": {
        "rule_id": "BPHS.5.88.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "5.88",
        "match_confidence": 0.68,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.680",
    },
    "SIG.MSR.195": {
        "rule_id": "BPHS.36.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.20",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
    "SIG.MSR.196": {
        "rule_id": "BPHS.35.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.2",
        "match_confidence": 0.94,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.940",
    },
    "SIG.MSR.197": {
        "rule_id": "BPHS.35.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.2",
        "match_confidence": 0.91,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.910",
    },
    "SIG.MSR.198": {
        "rule_id": "BPHS.35.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.2",
        "match_confidence": 0.91,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.910",
    },
    "SIG.MSR.199": {
        "rule_id": "BPHS.3.19.2",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.19",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.200": {
        "rule_id": "BPHS.36.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.22",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
}

BATCH_NUM = 2
SIGNAL_RANGE = ('SIG.MSR.101', 'SIG.MSR.200')
TOTAL_IN_BATCH = 100

GROUNDED_COUNT = 100
PARTIAL_COUNT = 0
NO_MATCH_COUNT = 0
