"""
brahmagyan.bodha.l2_grounded_batch_1 — BRAHMA-BO-2-1 (L2 Bodha Grounding)
======================================================================

WS-2 session l2-bodha-grounded: Batch 1
Signals grounded: SIG.MSR.001 – SIG.MSR.100 (100 signals)

Each entry in GROUNDED_SIGNALS maps signal_id → grounding assignment:
  rule_id:           WS-3 rule from rule corpus (WS3_RULE_BASE tag ws3-rule-base-complete)
  grounding_status:  GROUNDED | PARTIAL_MATCH | UNGROUNDED_NO_MATCH
  source_school:     parashari | jaimini | kp | tajaka | multi-school | nadi
  verse_citation:    source_verse.verse_ref from the matched rule
  match_confidence:  0.0–1.0 (scoring: scope 0–0.50, school 0–0.20, keyword 0–0.30)
  match_rationale:   brief rationale string

Batch 1 statistics:
  GROUNDED:            100
  PARTIAL_MATCH:       0
  UNGROUNDED_NO_MATCH: 0

Session: l2-bodha-grounded | Branch: feature/ws2-depth-build
Rule corpus: WS-3 (~1,370 rules across BPHS/Jaimini/KP/Tajaka)
Grounding algorithm: _grounding_engine.py
"""
from __future__ import annotations
from typing import Any


GROUNDED_SIGNALS: dict[str, dict[str, Any]] = {
    "SIG.MSR.001": {
        "rule_id": "BPHS.75.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.6",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.002": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.003": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.004": {
        "rule_id": "BPHS.44.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "44.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=dasha / school=parashari / score=0.760",
    },
    "SIG.MSR.005": {
        "rule_id": "BPHS.36.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.006": {
        "rule_id": "STUB_BPHS.CH28.RAHU_D12",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.007": {
        "rule_id": "BPHS.36.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.16",
        "match_confidence": 0.91,
        "match_rationale": "scope=yoga / school=parashari / score=0.910",
    },
    "SIG.MSR.008": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.009": {
        "rule_id": "BPHS.70.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "70.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.010": {
        "rule_id": "STUB_BPHS.CH3.RAHU_EXALT_GEMINI",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.APPROX.45",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.011": {
        "rule_id": "BPHS.39.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.4",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.012": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.013": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 1.0,
        "match_rationale": "scope=transit / school=parashari / score=1.000",
    },
    "SIG.MSR.014": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.015": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.016": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.017": {
        "rule_id": "BPHS.37.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "37.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.018": {
        "rule_id": "BPHS.36.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.019": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.020": {
        "rule_id": "BPHS.34.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.21",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.021": {
        "rule_id": "BPHS.36.108.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.108",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.022": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.023": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.024": {
        "rule_id": "STUB_BPHS.CH77.FINAL",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.30",
        "match_confidence": 0.73,
        "match_rationale": "scope=misc / school=parashari / score=0.730",
    },
    "SIG.MSR.025": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.026": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.027": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.028": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.029": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.030": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.031": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.032": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.033": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.034": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.85,
        "match_rationale": "scope=bhava / school=parashari / score=0.850",
    },
    "SIG.MSR.035": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.036": {
        "rule_id": "STUB_BPHS.CH22.KETU_12H_MOKSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "22.APPROX.12",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.037": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.038": {
        "rule_id": "STUB_BPHS.CH49.RAHU_KETU_MOOLATRIKONA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.APPROX.10",
        "match_confidence": 0.91,
        "match_rationale": "scope=graha / school=parashari / score=0.910",
    },
    "SIG.MSR.039": {
        "rule_id": "BPHS.68.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.20",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.040": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.91,
        "match_rationale": "scope=transit / school=parashari / score=0.910",
    },
    "SIG.MSR.041": {
        "rule_id": "BPHS.31.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.3",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.042": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.043": {
        "rule_id": "STUB_BPHS.CH28.RAHU_D12",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.5",
        "match_confidence": 0.76,
        "match_rationale": "scope=divisional / school=parashari / score=0.760",
    },
    "SIG.MSR.044": {
        "rule_id": "BPHS.46.47.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.47",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.045": {
        "rule_id": "BPHS.47.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.12",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.046": {
        "rule_id": "BPHS.68.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.25",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.047": {
        "rule_id": "BPHS.49.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.1",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.048": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.049": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.050": {
        "rule_id": "BPHS.3.58.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.58",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.051": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.052": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.053": {
        "rule_id": "BPHS.49.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.054": {
        "rule_id": "STUB_BPHS.CH3.RAHU_EXALT_GEMINI",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.APPROX.45",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.055": {
        "rule_id": "BPHS.49.9.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.9",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.056": {
        "rule_id": "BPHS.3.50.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.50",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.057": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.058": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.059": {
        "rule_id": "BPHS.12.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "12.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.060": {
        "rule_id": "BPHS.10.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.061": {
        "rule_id": "BPHS.13.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "13.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.062": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.063": {
        "rule_id": "BPHS.13.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "13.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.064": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.065": {
        "rule_id": "BPHS.61.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "61.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=graha / school=parashari / score=0.760",
    },
    "SIG.MSR.066": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.067": {
        "rule_id": "BPHS.3.50.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.50",
        "match_confidence": 0.8,
        "match_rationale": "scope=graha / school=parashari / score=0.800",
    },
    "SIG.MSR.068": {
        "rule_id": "STUB_BPHS.CH3.RAHU_EXALT_GEMINI",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.APPROX.45",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.069": {
        "rule_id": "BPHS.10.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=graha / school=parashari / score=0.850",
    },
    "SIG.MSR.070": {
        "rule_id": "BPHS.49.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.1",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.071": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.072": {
        "rule_id": "BPHS.3.55.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.55",
        "match_confidence": 0.76,
        "match_rationale": "scope=graha / school=parashari / score=0.760",
    },
    "SIG.MSR.073": {
        "rule_id": "BPHS.10.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.074": {
        "rule_id": "BPHS.12.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "12.4",
        "match_confidence": 0.88,
        "match_rationale": "scope=graha / school=parashari / score=0.880",
    },
    "SIG.MSR.075": {
        "rule_id": "BPHS.32.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=graha / school=parashari / score=0.760",
    },
    "SIG.MSR.076": {
        "rule_id": "BPHS.13.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "13.10",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.077": {
        "rule_id": "BPHS.10.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.078": {
        "rule_id": "BPHS.10.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=graha / school=parashari / score=0.850",
    },
    "SIG.MSR.079": {
        "rule_id": "BPHS.13.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "13.10",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.080": {
        "rule_id": "BPHS.3.55.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.55",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.081": {
        "rule_id": "BPHS.4.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "4.5",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.082": {
        "rule_id": "BPHS.3.55.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.55",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.083": {
        "rule_id": "BPHS.4.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "4.5",
        "match_confidence": 0.76,
        "match_rationale": "scope=graha / school=parashari / score=0.760",
    },
    "SIG.MSR.084": {
        "rule_id": "BPHS.13.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "13.10",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.085": {
        "rule_id": "BPHS.4.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "4.5",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.086": {
        "rule_id": "BPHS.34.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.087": {
        "rule_id": "BPHS.4.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "4.5",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.088": {
        "rule_id": "BPHS.5.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.790",
    },
    "SIG.MSR.089": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.85,
        "match_rationale": "scope=graha / school=parashari / score=0.850",
    },
    "SIG.MSR.090": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.88,
        "match_rationale": "scope=graha / school=parashari / score=0.880",
    },
    "SIG.MSR.091": {
        "rule_id": "BPHS.3.52.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.52",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.092": {
        "rule_id": "BPHS.32.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.093": {
        "rule_id": "BPHS.32.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=graha / school=parashari / score=0.820",
    },
    "SIG.MSR.094": {
        "rule_id": "BPHS.3.55.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.55",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.095": {
        "rule_id": "BPHS.32.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=graha / school=parashari / score=0.760",
    },
    "SIG.MSR.096": {
        "rule_id": "BPHS.3.55.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.55",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.097": {
        "rule_id": "BPHS.36.13.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.13",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.098": {
        "rule_id": "BPHS.75.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.6",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.099": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.100": {
        "rule_id": "BPHS.36.24.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.24",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
}

BATCH_NUM = 1
SIGNAL_RANGE = ('SIG.MSR.001', 'SIG.MSR.100')
TOTAL_IN_BATCH = 100

GROUNDED_COUNT = 100
PARTIAL_COUNT = 0
NO_MATCH_COUNT = 0
