"""
brahmagyan.bodha.l2_grounded_batch_5 — BRAHMA-BO-2-1 (L2 Bodha Grounding)
======================================================================

WS-2 session l2-bodha-grounded: Batch 5
Signals grounded: SIG.MSR.402 – SIG.MSR.504 (100 signals)

Each entry in GROUNDED_SIGNALS maps signal_id → grounding assignment:
  rule_id:           WS-3 rule from rule corpus (WS3_RULE_BASE tag ws3-rule-base-complete)
  grounding_status:  GROUNDED | PARTIAL_MATCH | UNGROUNDED_NO_MATCH
  source_school:     parashari | jaimini | kp | tajaka | multi-school | nadi
  verse_citation:    source_verse.verse_ref from the matched rule
  match_confidence:  0.0–1.0 (scoring: scope 0–0.50, school 0–0.20, keyword 0–0.30)
  match_rationale:   brief rationale string

Batch 5 statistics:
  GROUNDED:            100
  PARTIAL_MATCH:       0
  UNGROUNDED_NO_MATCH: 0

Session: l2-bodha-grounded | Branch: feature/ws2-depth-build
Rule corpus: WS-3 (~1,370 rules across BPHS/Jaimini/KP/Tajaka)
Grounding algorithm: _grounding_engine.py
"""
from __future__ import annotations
from typing import Any


GROUNDED_SIGNALS: dict[str, dict[str, Any]] = {
    "SIG.MSR.402": {
        "rule_id": "JAIMINI.3.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "3.2.4",
        "match_confidence": 0.73,
        "match_rationale": "scope=yoga / school=jaimini / score=0.730",
    },
    "SIG.MSR.403": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.404": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "10.11",
        "match_confidence": 0.59,
        "match_rationale": "scope=bhava / school=parashari / score=0.590",
    },
    "SIG.MSR.405": {
        "rule_id": "BPHS.76.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "76.5",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.406": {
        "rule_id": "BPHS.75.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.22",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.407": {
        "rule_id": "BPHS.35.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.12",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.408": {
        "rule_id": "BPHS.75.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.22",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.409": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.410": {
        "rule_id": "BPHS.75.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.22",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.411": {
        "rule_id": "BPHS.25.13.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "25.13",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.412": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.413": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.414": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.415": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.416": {
        "rule_id": "BPHS.72.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "72.2",
        "match_confidence": 0.743,
        "match_rationale": "scope=yoga / school=parashari / score=0.743",
    },
    "SIG.MSR.417": {
        "rule_id": "BPHS.36.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.20",
        "match_confidence": 0.775,
        "match_rationale": "scope=yoga / school=parashari / score=0.775",
    },
    "SIG.MSR.418": {
        "rule_id": "BPHS.36.50.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.50",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.419": {
        "rule_id": "BPHS.25.13.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "25.13",
        "match_confidence": 0.733,
        "match_rationale": "scope=yoga / school=parashari / score=0.733",
    },
    "SIG.MSR.420": {
        "rule_id": "BPHS.36.50.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.50",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.421": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.422": {
        "rule_id": "BPHS.35.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.10",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.423": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.424": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.425": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.426": {
        "rule_id": "BPHS.75.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.22",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.427": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.94,
        "match_rationale": "scope=yoga / school=parashari / score=0.940",
    },
    "SIG.MSR.428": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.429": {
        "rule_id": "BPHS.34.38.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.38",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.430": {
        "rule_id": "BPHS.34.38.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.38",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.431": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.432": {
        "rule_id": "JAIMINI.1.4.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "1.4.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=jaimini / score=0.820",
    },
    "SIG.MSR.433": {
        "rule_id": "BPHS.27.27.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.27",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.434": {
        "rule_id": "BPHS.34.38.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.38",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.435": {
        "rule_id": "JAIMINI.1.4.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "1.4.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=jaimini / score=0.850",
    },
    "SIG.MSR.436": {
        "rule_id": "BPHS.31.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.437": {
        "rule_id": "BPHS.92.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "92.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.438": {
        "rule_id": "BPHS.32.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=graha / school=parashari / score=0.790",
    },
    "SIG.MSR.439": {
        "rule_id": "STUB_BPHS.CH77.FEMALE_CHART_RULES",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.10",
        "match_confidence": 0.73,
        "match_rationale": "scope=misc / school=parashari / score=0.730",
    },
    "SIG.MSR.440": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.85,
        "match_rationale": "scope=bhava / school=parashari / score=0.850",
    },
    "SIG.MSR.441": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.442": {
        "rule_id": "BPHS.93.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "93.3",
        "match_confidence": 0.73,
        "match_rationale": "scope=muhurta / school=parashari / score=0.730",
    },
    "SIG.MSR.443": {
        "rule_id": "BPHS.35.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.20",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.444": {
        "rule_id": "BPHS.3.19.2",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.19",
        "match_confidence": 0.79,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.790",
    },
    "SIG.MSR.445": {
        "rule_id": "BPHS.36.27.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.27",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
    "SIG.MSR.446": {
        "rule_id": "BPHS.36.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.447": {
        "rule_id": "BPHS.36.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.4",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.448": {
        "rule_id": "BPHS.36.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.10",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.449": {
        "rule_id": "BPHS.36.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.21",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
    "SIG.MSR.450": {
        "rule_id": "BPHS.36.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.21",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
    "SIG.MSR.451": {
        "rule_id": "BPHS.5.19.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.19",
        "match_confidence": 0.79,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.790",
    },
    "SIG.MSR.452": {
        "rule_id": "BPHS.35.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.453": {
        "rule_id": "BPHS.3.19.2",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.19",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.454": {
        "rule_id": "BPHS.35.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.455": {
        "rule_id": "BPHS.3.18.2",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.18",
        "match_confidence": 0.76,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.760",
    },
    "SIG.MSR.456": {
        "rule_id": "BPHS.33.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.11",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.457": {
        "rule_id": "BPHS.36.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.458": {
        "rule_id": "BPHS.33.13.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.13",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.459": {
        "rule_id": "BPHS.42.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "42.3",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.460": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.73,
        "match_rationale": "scope=yoga / school=parashari / score=0.730",
    },
    "SIG.MSR.461": {
        "rule_id": "BPHS.36.35.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.35",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.462": {
        "rule_id": "BPHS.34.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.25",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.463": {
        "rule_id": "BPHS.16.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "16.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.464": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.73,
        "match_rationale": "scope=yoga / school=parashari / score=0.730",
    },
    "SIG.MSR.465": {
        "rule_id": "BPHS.6.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "6.1",
        "match_confidence": 0.73,
        "match_rationale": "scope=bhava / school=parashari / score=0.730",
    },
    "SIG.MSR.466": {
        "rule_id": "BPHS.33.9.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.9",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.467": {
        "rule_id": "BPHS.72.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "72.3",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.468": {
        "rule_id": "BPHS.6.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "6.1",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.469": {
        "rule_id": "BPHS.47.17.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.17",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.470": {
        "rule_id": "BPHS.44.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "44.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.471": {
        "rule_id": "BPHS.50.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "50.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.472": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.473": {
        "rule_id": "BPHS.47.17.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.17",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.474": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.475": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.476": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.88,
        "match_rationale": "scope=transit / school=parashari / score=0.880",
    },
    "SIG.MSR.477": {
        "rule_id": "BPHS.78.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=transit / school=parashari / score=0.880",
    },
    "SIG.MSR.478": {
        "rule_id": "BPHS.68.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.22",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.479": {
        "rule_id": "BPHS.80.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "80.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.480": {
        "rule_id": "BPHS.68.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.25",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.481": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.482": {
        "rule_id": "BPHS.32.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.12",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.483": {
        "rule_id": "BPHS.26.62.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.62",
        "match_confidence": 0.76,
        "match_rationale": "scope=divisional / school=parashari / score=0.760",
    },
    "SIG.MSR.484": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.485": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.76,
        "match_rationale": "scope=divisional / school=parashari / score=0.760",
    },
    "SIG.MSR.486": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.487": {
        "rule_id": "BPHS.28.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=divisional / school=parashari / score=0.760",
    },
    "SIG.MSR.488": {
        "rule_id": "BPHS.30.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "30.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.489": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.76,
        "match_rationale": "scope=divisional / school=parashari / score=0.760",
    },
    "SIG.MSR.490": {
        "rule_id": "BPHS.28.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.491": {
        "rule_id": "BPHS.31.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.2",
        "match_confidence": 0.8,
        "match_rationale": "scope=divisional / school=parashari / score=0.800",
    },
    "SIG.MSR.492": {
        "rule_id": "BPHS.26.61.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.61",
        "match_confidence": 0.767,
        "match_rationale": "scope=divisional / school=parashari / score=0.767",
    },
    "SIG.MSR.493": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.494": {
        "rule_id": "BPHS.19.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "19.4",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.495": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.496": {
        "rule_id": "BPHS.78.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=transit / school=parashari / score=0.760",
    },
    "SIG.MSR.500": {
        "rule_id": "STUB_BPHS.CH28.D12_RAHU_KETU",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.10",
        "match_confidence": 0.94,
        "match_rationale": "scope=divisional / school=parashari / score=0.940",
    },
    "SIG.MSR.501": {
        "rule_id": "BPHS.6.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "6.10",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.502": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.503": {
        "rule_id": "STUB_BPHS.CH28.RAHU_D12",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.504": {
        "rule_id": "BPHS.30.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "30.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
}

BATCH_NUM = 5
SIGNAL_RANGE = ('SIG.MSR.402', 'SIG.MSR.504')
TOTAL_IN_BATCH = 100

GROUNDED_COUNT = 100
PARTIAL_COUNT = 0
NO_MATCH_COUNT = 0
