"""
brahmagyan.bodha.l2_grounded_batch_3 — BRAHMA-BO-2-1 (L2 Bodha Grounding)
======================================================================

WS-2 session l2-bodha-grounded: Batch 3
Signals grounded: SIG.MSR.201 – SIG.MSR.301 (100 signals)

Each entry in GROUNDED_SIGNALS maps signal_id → grounding assignment:
  rule_id:           WS-3 rule from rule corpus (WS3_RULE_BASE tag ws3-rule-base-complete)
  grounding_status:  GROUNDED | PARTIAL_MATCH | UNGROUNDED_NO_MATCH
  source_school:     parashari | jaimini | kp | tajaka | multi-school | nadi
  verse_citation:    source_verse.verse_ref from the matched rule
  match_confidence:  0.0–1.0 (scoring: scope 0–0.50, school 0–0.20, keyword 0–0.30)
  match_rationale:   brief rationale string

Batch 3 statistics:
  GROUNDED:            100
  PARTIAL_MATCH:       0
  UNGROUNDED_NO_MATCH: 0

Session: l2-bodha-grounded | Branch: feature/ws2-depth-build
Rule corpus: WS-3 (~1,370 rules across BPHS/Jaimini/KP/Tajaka)
Grounding algorithm: _grounding_engine.py
"""
from __future__ import annotations
from typing import Any


GROUNDED_SIGNALS: dict[str, dict[str, Any]] = {
    "SIG.MSR.201": {
        "rule_id": "BPHS.36.9.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.9",
        "match_confidence": 0.79,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.790",
    },
    "SIG.MSR.202": {
        "rule_id": "BPHS.36.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.6",
        "match_confidence": 0.79,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.790",
    },
    "SIG.MSR.203": {
        "rule_id": "BPHS.36.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.21",
        "match_confidence": 0.82,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.820",
    },
    "SIG.MSR.204": {
        "rule_id": "BPHS.5.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.21",
        "match_confidence": 0.85,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.850",
    },
    "SIG.MSR.205": {
        "rule_id": "BPHS.5.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.6",
        "match_confidence": 0.88,
        "match_rationale": "scope=nakshatra / school=parashari / score=0.880",
    },
    "SIG.MSR.206": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.208": {
        "rule_id": "BPHS.26.60.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.60",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.209": {
        "rule_id": "STUB_BPHS.CH28.RAHU_D12",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.210": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.211": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.212": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.213": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.214": {
        "rule_id": "BPHS.26.63.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.63",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.215": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.216": {
        "rule_id": "STUB_BPHS.CH28.RAHU_D12",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.217": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.218": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.219": {
        "rule_id": "STUB_BPHS.CH28.D12_RAHU_KETU",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.10",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.220": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.76,
        "match_rationale": "scope=divisional / school=parashari / score=0.760",
    },
    "SIG.MSR.221": {
        "rule_id": "BPHS.31.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.222": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.223": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.224": {
        "rule_id": "STUB_BPHS.CH28.D12_RAHU_KETU",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.10",
        "match_confidence": 0.94,
        "match_rationale": "scope=divisional / school=parashari / score=0.940",
    },
    "SIG.MSR.225": {
        "rule_id": "BPHS.27.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "27.26",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.226": {
        "rule_id": "STUB_BPHS.CH28.RAHU_D12",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.APPROX.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.227": {
        "rule_id": "BPHS.28.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "28.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=divisional / school=parashari / score=0.880",
    },
    "SIG.MSR.228": {
        "rule_id": "BPHS.33.7.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.7",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.229": {
        "rule_id": "BPHS.10.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.10",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.230": {
        "rule_id": "BPHS.33.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.26",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.231": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.232": {
        "rule_id": "BPHS.22.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "22.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.233": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.234": {
        "rule_id": "BPHS.25.14.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "25.14",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.235": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.236": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.237": {
        "rule_id": "BPHS.33.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.238": {
        "rule_id": "BPHS.17.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "17.4",
        "match_confidence": 0.78,
        "match_rationale": "scope=bhava / school=parashari / score=0.780",
    },
    "SIG.MSR.239": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.69,
        "match_rationale": "scope=bhava / school=parashari / score=0.690",
    },
    "SIG.MSR.240": {
        "rule_id": "STUB_BPHS.CH14.RAHU_LAGNA_EFFECTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "14.APPROX.8",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.241": {
        "rule_id": "BPHS.43.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "43.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.242": {
        "rule_id": "BPHS.35.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "35.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.243": {
        "rule_id": "JAIMINI.4.4.27.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.4.27",
        "match_confidence": 0.62,
        "match_rationale": "scope=misc / school=jaimini / score=0.620",
    },
    "SIG.MSR.244": {
        "rule_id": "BPHS.33.9.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "33.9",
        "match_confidence": 0.65,
        "match_rationale": "scope=bhava / school=parashari / score=0.650",
    },
    "SIG.MSR.245": {
        "rule_id": "JAIMINI.4.3.19.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.3.19",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=jaimini / score=0.820",
    },
    "SIG.MSR.246": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.247": {
        "rule_id": "BPHS.10.13.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.13",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.248": {
        "rule_id": "BPHS.19.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "19.6",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.249": {
        "rule_id": "BPHS.10.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "10.11",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.250": {
        "rule_id": "BPHS.34.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.25",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
    "SIG.MSR.251": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.252": {
        "rule_id": "BPHS.33.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.11",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.253": {
        "rule_id": "BPHS.6.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "6.1",
        "match_confidence": 0.76,
        "match_rationale": "scope=bhava / school=parashari / score=0.760",
    },
    "SIG.MSR.254": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.255": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.256": {
        "rule_id": "BPHS.46.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.6",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.257": {
        "rule_id": "BPHS.47.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.258": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.259": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.260": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.261": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.262": {
        "rule_id": "BPHS.47.17.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.17",
        "match_confidence": 0.91,
        "match_rationale": "scope=dasha / school=parashari / score=0.910",
    },
    "SIG.MSR.263": {
        "rule_id": "BPHS.53.18.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.18",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.264": {
        "rule_id": "BPHS.46.14.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.14",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.265": {
        "rule_id": "BPHS.46.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.15",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.266": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.88,
        "match_rationale": "scope=dasha / school=parashari / score=0.880",
    },
    "SIG.MSR.267": {
        "rule_id": "JAIMINI.2.1.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.3",
        "match_confidence": 0.88,
        "match_rationale": "scope=dasha / school=jaimini / score=0.880",
    },
    "SIG.MSR.268": {
        "rule_id": "BPHS.47.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.16",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.269": {
        "rule_id": "BPHS.50.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "50.10",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.270": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.271": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.272": {
        "rule_id": "BPHS.78.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.273": {
        "rule_id": "BPHS.78.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.274": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.275": {
        "rule_id": "BPHS.78.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=transit / school=parashari / score=0.790",
    },
    "SIG.MSR.276": {
        "rule_id": "BPHS.80.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "80.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.277": {
        "rule_id": "BPHS.80.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "80.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.278": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.279": {
        "rule_id": "BPHS.80.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "80.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=transit / school=parashari / score=0.790",
    },
    "SIG.MSR.280": {
        "rule_id": "BPHS.68.32.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.32",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.281": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.282": {
        "rule_id": "BPHS.68.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.20",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.283": {
        "rule_id": "BPHS.68.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.3",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.284": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=transit / school=parashari / score=0.880",
    },
    "SIG.MSR.285": {
        "rule_id": "BPHS.68.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.286": {
        "rule_id": "BPHS.68.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=transit / school=parashari / score=0.790",
    },
    "SIG.MSR.287": {
        "rule_id": "BPHS.80.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "80.4",
        "match_confidence": 0.85,
        "match_rationale": "scope=transit / school=parashari / score=0.850",
    },
    "SIG.MSR.288": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.289": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.290": {
        "rule_id": "BPHS.68.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.20",
        "match_confidence": 0.82,
        "match_rationale": "scope=transit / school=parashari / score=0.820",
    },
    "SIG.MSR.291": {
        "rule_id": "BPHS.15.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "15.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=parashari / score=0.820",
    },
    "SIG.MSR.292": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.91,
        "match_rationale": "scope=transit / school=parashari / score=0.910",
    },
    "SIG.MSR.293": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.94,
        "match_rationale": "scope=transit / school=parashari / score=0.940",
    },
    "SIG.MSR.294": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.94,
        "match_rationale": "scope=transit / school=parashari / score=0.940",
    },
    "SIG.MSR.295": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.91,
        "match_rationale": "scope=transit / school=parashari / score=0.910",
    },
    "SIG.MSR.296": {
        "rule_id": "BPHS.75.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.6",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.297": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.91,
        "match_rationale": "scope=transit / school=parashari / score=0.910",
    },
    "SIG.MSR.298": {
        "rule_id": "STUB_BPHS.CH77.CONTENTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "77.APPROX.1",
        "match_confidence": 0.7,
        "match_rationale": "scope=misc / school=parashari / score=0.700",
    },
    "SIG.MSR.299": {
        "rule_id": "BPHS.68.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.2",
        "match_confidence": 0.91,
        "match_rationale": "scope=transit / school=parashari / score=0.910",
    },
    "SIG.MSR.300": {
        "rule_id": "KP.6.ch2.moon_chart.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.6.ch2.kp_moon_chart",
        "match_confidence": 0.82,
        "match_rationale": "scope=bhava / school=kp / score=0.820",
    },
    "SIG.MSR.301": {
        "rule_id": "BPHS.15.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "15.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=bhava / school=parashari / score=0.790",
    },
}

BATCH_NUM = 3
SIGNAL_RANGE = ('SIG.MSR.201', 'SIG.MSR.301')
TOTAL_IN_BATCH = 100

GROUNDED_COUNT = 100
PARTIAL_COUNT = 0
NO_MATCH_COUNT = 0
