"""
brahmagyan.bodha.l2_grounded_batch_4 — BRAHMA-BO-2-1 (L2 Bodha Grounding)
======================================================================

WS-2 session l2-bodha-grounded: Batch 4
Signals grounded: SIG.MSR.302 – SIG.MSR.401 (100 signals)

Each entry in GROUNDED_SIGNALS maps signal_id → grounding assignment:
  rule_id:           WS-3 rule from rule corpus (WS3_RULE_BASE tag ws3-rule-base-complete)
  grounding_status:  GROUNDED | PARTIAL_MATCH | UNGROUNDED_NO_MATCH
  source_school:     parashari | jaimini | kp | tajaka | multi-school | nadi
  verse_citation:    source_verse.verse_ref from the matched rule
  match_confidence:  0.0–1.0 (scoring: scope 0–0.50, school 0–0.20, keyword 0–0.30)
  match_rationale:   brief rationale string

Batch 4 statistics:
  GROUNDED:            100
  PARTIAL_MATCH:       0
  UNGROUNDED_NO_MATCH: 0

Session: l2-bodha-grounded | Branch: feature/ws2-depth-build
Rule corpus: WS-3 (~1,370 rules across BPHS/Jaimini/KP/Tajaka)
Grounding algorithm: _grounding_engine.py
"""
from __future__ import annotations
from typing import Any


GROUNDED_SIGNALS: dict[str, dict[str, Any]] = {
    "SIG.MSR.302": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.94,
        "match_rationale": "scope=transit / school=parashari / score=0.940",
    },
    "SIG.MSR.303": {
        "rule_id": "KP.1.ch15.saturn_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch15.saturn_rules_in_kp",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.304": {
        "rule_id": "KP.1.ch14.mercury_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch14.mercury_rules_in_kp",
        "match_confidence": 0.91,
        "match_rationale": "scope=sub_lord / school=kp / score=0.910",
    },
    "SIG.MSR.305": {
        "rule_id": "KP.1.ch15.saturn_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch15.saturn_rules_in_kp",
        "match_confidence": 0.85,
        "match_rationale": "scope=sub_lord / school=kp / score=0.850",
    },
    "SIG.MSR.306": {
        "rule_id": "KP.1.ch20.rahu_ketu_occupation.2",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch20.rahu_ketu_house_occupation",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.307": {
        "rule_id": "KP.1.ch14.mercury_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch14.mercury_rules_in_kp",
        "match_confidence": 0.91,
        "match_rationale": "scope=sub_lord / school=kp / score=0.910",
    },
    "SIG.MSR.308": {
        "rule_id": "KP.5.ch12.legal_career.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.5.ch12.legal_profession",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.309": {
        "rule_id": "KP.5.ch4.finance.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.5.ch4.finance_wealth",
        "match_confidence": 0.85,
        "match_rationale": "scope=sub_lord / school=kp / score=0.850",
    },
    "SIG.MSR.310": {
        "rule_id": "KP.1.ch15.saturn_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch15.saturn_rules_in_kp",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.311": {
        "rule_id": "KP.1.ch20.rahu_ketu_occupation.2",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch20.rahu_ketu_house_occupation",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.312": {
        "rule_id": "KP.1.ch14.mercury_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch14.mercury_rules_in_kp",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.313": {
        "rule_id": "KP.5.ch11.medical_career.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.5.ch11.medical_profession",
        "match_confidence": 0.94,
        "match_rationale": "scope=sub_lord / school=kp / score=0.940",
    },
    "SIG.MSR.314": {
        "rule_id": "KP.1.ch12.sun_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch12.sun_rules_in_kp",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.315": {
        "rule_id": "KP.1.ch15.saturn_in_kp.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.1.ch15.saturn_rules_in_kp",
        "match_confidence": 0.88,
        "match_rationale": "scope=sub_lord / school=kp / score=0.880",
    },
    "SIG.MSR.316": {
        "rule_id": "KP.5.ch12.legal_career.1",
        "grounding_status": "GROUNDED",
        "source_school": "kp",
        "verse_citation": "Vol.5.ch12.legal_profession",
        "match_confidence": 0.85,
        "match_rationale": "scope=sub_lord / school=kp / score=0.850",
    },
    "SIG.MSR.317": {
        "rule_id": "JAIMINI.2.2.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.318": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.319": {
        "rule_id": "JAIMINI.2.4.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.26",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.320": {
        "rule_id": "JAIMINI.2.2.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.21",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.321": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.322": {
        "rule_id": "JAIMINI.2.4.14.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.14",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.323": {
        "rule_id": "JAIMINI.2.4.14.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.14",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.324": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.325": {
        "rule_id": "JAIMINI.2.4.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.326": {
        "rule_id": "JAIMINI.4.4.53.STUB.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.4.53",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.327": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.328": {
        "rule_id": "JAIMINI.2.1.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.329": {
        "rule_id": "JAIMINI.4.3.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.3.11",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.330": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.331": {
        "rule_id": "JAIMINI.2.3.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.3.3",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.332": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.333": {
        "rule_id": "JAIMINI.4.3.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.3.12",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.334": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.335": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.336": {
        "rule_id": "JAIMINI.2.1.1.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.1",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.337": {
        "rule_id": "JAIMINI.4.3.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.3.11",
        "match_confidence": 0.88,
        "match_rationale": "scope=dasha / school=jaimini / score=0.880",
    },
    "SIG.MSR.338": {
        "rule_id": "JAIMINI.2.4.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.15",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.339": {
        "rule_id": "JAIMINI.4.3.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.3.10",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.340": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.341": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.342": {
        "rule_id": "JAIMINI.4.4.44.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.4.44",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.343": {
        "rule_id": "JAIMINI.4.4.44.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "4.4.44",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=jaimini / score=0.850",
    },
    "SIG.MSR.344": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.345": {
        "rule_id": "JAIMINI.2.1.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.3",
        "match_confidence": 0.88,
        "match_rationale": "scope=dasha / school=jaimini / score=0.880",
    },
    "SIG.MSR.346": {
        "rule_id": "JAIMINI.2.2.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.347": {
        "rule_id": "JAIMINI.2.4.7.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.4.7",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.348": {
        "rule_id": "JAIMINI.2.1.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.1.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=jaimini / score=0.790",
    },
    "SIG.MSR.349": {
        "rule_id": "JAIMINI.2.2.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.2.3",
        "match_confidence": 0.88,
        "match_rationale": "scope=dasha / school=jaimini / score=0.880",
    },
    "SIG.MSR.350": {
        "rule_id": "JAIMINI.2.3.20.STUB.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "2.3.20",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=jaimini / score=0.820",
    },
    "SIG.MSR.351": {
        "rule_id": "BPHS.83.20.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.20",
        "match_confidence": 0.85,
        "match_rationale": "scope=muhurta / school=parashari / score=0.850",
    },
    "SIG.MSR.352": {
        "rule_id": "BPHS.83.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.22",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.353": {
        "rule_id": "BPHS.83.10.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.10",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.354": {
        "rule_id": "BPHS.92.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "92.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=muhurta / school=parashari / score=0.760",
    },
    "SIG.MSR.355": {
        "rule_id": "BPHS.92.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "92.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.356": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.357": {
        "rule_id": "BPHS.83.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.25",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.358": {
        "rule_id": "BPHS.83.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.25",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.359": {
        "rule_id": "BPHS.5.85.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.85",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.360": {
        "rule_id": "BPHS.84.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "84.5",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.361": {
        "rule_id": "BPHS.5.85.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "5.85",
        "match_confidence": 0.85,
        "match_rationale": "scope=muhurta / school=parashari / score=0.850",
    },
    "SIG.MSR.362": {
        "rule_id": "BPHS.83.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.12",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.363": {
        "rule_id": "BPHS.83.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.12",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.364": {
        "rule_id": "BPHS.93.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "93.5",
        "match_confidence": 0.73,
        "match_rationale": "scope=muhurta / school=parashari / score=0.730",
    },
    "SIG.MSR.365": {
        "rule_id": "BPHS.83.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.25",
        "match_confidence": 0.85,
        "match_rationale": "scope=muhurta / school=parashari / score=0.850",
    },
    "SIG.MSR.366": {
        "rule_id": "BPHS.92.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "92.2",
        "match_confidence": 0.73,
        "match_rationale": "scope=muhurta / school=parashari / score=0.730",
    },
    "SIG.MSR.367": {
        "rule_id": "BPHS.83.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.25",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.368": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.369": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.69,
        "match_rationale": "scope=muhurta / school=parashari / score=0.690",
    },
    "SIG.MSR.370": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.371": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.372": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.373": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.374": {
        "rule_id": "BPHS.83.15.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.15",
        "match_confidence": 0.82,
        "match_rationale": "scope=muhurta / school=parashari / score=0.820",
    },
    "SIG.MSR.375": {
        "rule_id": "BPHS.83.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "83.25",
        "match_confidence": 0.79,
        "match_rationale": "scope=muhurta / school=parashari / score=0.790",
    },
    "SIG.MSR.376": {
        "rule_id": "TAJAKA.ch1.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch1.v1",
        "match_confidence": 0.68,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.680",
    },
    "SIG.MSR.377": {
        "rule_id": "BPHS.47.11.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "47.11",
        "match_confidence": 0.65,
        "match_rationale": "scope=dasha / school=parashari / score=0.650",
    },
    "SIG.MSR.378": {
        "rule_id": "TAJAKA.ch4.v11.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch4.v11",
        "match_confidence": 0.62,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.620",
    },
    "SIG.MSR.379": {
        "rule_id": "TAJAKA.ch5.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch5.v1",
        "match_confidence": 0.65,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.650",
    },
    "SIG.MSR.380": {
        "rule_id": "TAJAKA.ch3.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch3.v1",
        "match_confidence": 0.88,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.880",
    },
    "SIG.MSR.381": {
        "rule_id": "TAJAKA.ch14.v10.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch14.v10",
        "match_confidence": 0.88,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.880",
    },
    "SIG.MSR.382": {
        "rule_id": "TAJAKA.ch11.v4.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch11.v4",
        "match_confidence": 0.68,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.680",
    },
    "SIG.MSR.383": {
        "rule_id": "TAJAKA.ch11.v2.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch11.v2",
        "match_confidence": 0.85,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.850",
    },
    "SIG.MSR.384": {
        "rule_id": "TAJAKA.ch11.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch11.v1",
        "match_confidence": 0.71,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.710",
    },
    "SIG.MSR.385": {
        "rule_id": "TAJAKA.ch9.v5.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch9.v5",
        "match_confidence": 0.65,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.650",
    },
    "SIG.MSR.386": {
        "rule_id": "TAJAKA.ch3.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch3.v1",
        "match_confidence": 0.82,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.820",
    },
    "SIG.MSR.387": {
        "rule_id": "TAJAKA.ch19.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch19.v1",
        "match_confidence": 0.68,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.680",
    },
    "SIG.MSR.388": {
        "rule_id": "BPHS.70.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "70.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.389": {
        "rule_id": "BPHS.75.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.6",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.390": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=yoga / school=parashari / score=0.850",
    },
    "SIG.MSR.391": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.392": {
        "rule_id": "BPHS.37.32.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "37.32",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.393": {
        "rule_id": "BPHS.76.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "76.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.394": {
        "rule_id": "BPHS.34.21.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.21",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.395": {
        "rule_id": "STUB_BPHS.CH75.SUN_MAHAPURUSHA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.APPROX.1",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.396": {
        "rule_id": "BPHS.75.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "75.6",
        "match_confidence": 0.88,
        "match_rationale": "scope=yoga / school=parashari / score=0.880",
    },
    "SIG.MSR.397": {
        "rule_id": "JAIMINI.1.4.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "jaimini",
        "verse_citation": "1.4.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=jaimini / score=0.820",
    },
    "SIG.MSR.398": {
        "rule_id": "BPHS.21.4.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "21.4",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
    "SIG.MSR.399": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.76,
        "match_rationale": "scope=yoga / school=parashari / score=0.760",
    },
    "SIG.MSR.400": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.82,
        "match_rationale": "scope=yoga / school=parashari / score=0.820",
    },
    "SIG.MSR.401": {
        "rule_id": "BPHS.34.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.2",
        "match_confidence": 0.79,
        "match_rationale": "scope=yoga / school=parashari / score=0.790",
    },
}

BATCH_NUM = 4
SIGNAL_RANGE = ('SIG.MSR.302', 'SIG.MSR.401')
TOTAL_IN_BATCH = 100

GROUNDED_COUNT = 100
PARTIAL_COUNT = 0
NO_MATCH_COUNT = 0
