"""
brahmagyan.bodha.l2_grounded_batch_6 — BRAHMA-BO-2-1 (L2 Bodha Grounding)
======================================================================

WS-2 session l2-bodha-grounded: Batch 6
Signals grounded: SIG.MSR.505 – SIG.MSR.573 (69 signals)

Each entry in GROUNDED_SIGNALS maps signal_id → grounding assignment:
  rule_id:           WS-3 rule from rule corpus (WS3_RULE_BASE tag ws3-rule-base-complete)
  grounding_status:  GROUNDED | PARTIAL_MATCH | UNGROUNDED_NO_MATCH
  source_school:     parashari | jaimini | kp | tajaka | multi-school | nadi
  verse_citation:    source_verse.verse_ref from the matched rule
  match_confidence:  0.0–1.0 (scoring: scope 0–0.50, school 0–0.20, keyword 0–0.30)
  match_rationale:   brief rationale string

Batch 6 statistics:
  GROUNDED:            69
  PARTIAL_MATCH:       0
  UNGROUNDED_NO_MATCH: 0

Session: l2-bodha-grounded | Branch: feature/ws2-depth-build
Rule corpus: WS-3 (~1,370 rules across BPHS/Jaimini/KP/Tajaka)
Grounding algorithm: _grounding_engine.py
"""
from __future__ import annotations
from typing import Any


GROUNDED_SIGNALS: dict[str, dict[str, Any]] = {
    "SIG.MSR.505": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.506": {
        "rule_id": "BPHS.8.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.2",
        "match_confidence": 0.88,
        "match_rationale": "scope=divisional / school=parashari / score=0.880",
    },
    "SIG.MSR.507": {
        "rule_id": "BPHS.31.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.3",
        "match_confidence": 0.82,
        "match_rationale": "scope=divisional / school=parashari / score=0.820",
    },
    "SIG.MSR.508": {
        "rule_id": "BPHS.26.63.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.63",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.509": {
        "rule_id": "BPHS.32.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "32.12",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.510": {
        "rule_id": "BPHS.31.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.3",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.511": {
        "rule_id": "BPHS.31.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.5",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.512": {
        "rule_id": "BPHS.31.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "31.2",
        "match_confidence": 0.85,
        "match_rationale": "scope=divisional / school=parashari / score=0.850",
    },
    "SIG.MSR.513": {
        "rule_id": "BPHS.8.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.5",
        "match_confidence": 0.88,
        "match_rationale": "scope=divisional / school=parashari / score=0.880",
    },
    "SIG.MSR.514": {
        "rule_id": "BPHS.8.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "8.5",
        "match_confidence": 0.79,
        "match_rationale": "scope=divisional / school=parashari / score=0.790",
    },
    "SIG.MSR.515": {
        "rule_id": "BPHS.68.35.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.35",
        "match_confidence": 0.733,
        "match_rationale": "scope=transit / school=parashari / score=0.733",
    },
    "SIG.MSR.516": {
        "rule_id": "BPHS.26.48.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.48",
        "match_confidence": 0.72,
        "match_rationale": "scope=graha / school=parashari / score=0.720",
    },
    "SIG.MSR.517": {
        "rule_id": "BPHS.34.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.25",
        "match_confidence": 0.712,
        "match_rationale": "scope=bhava / school=parashari / score=0.712",
    },
    "SIG.MSR.518": {
        "rule_id": "BPHS.16.6.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "16.6",
        "match_confidence": 0.712,
        "match_rationale": "scope=bhava / school=parashari / score=0.712",
    },
    "SIG.MSR.519": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.72,
        "match_rationale": "scope=yoga / school=parashari / score=0.720",
    },
    "SIG.MSR.520": {
        "rule_id": "BPHS.3.55.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "3.55",
        "match_confidence": 0.66,
        "match_rationale": "scope=graha / school=parashari / score=0.660",
    },
    "SIG.MSR.521": {
        "rule_id": "BPHS.38.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "38.5",
        "match_confidence": 0.72,
        "match_rationale": "scope=yoga / school=parashari / score=0.720",
    },
    "SIG.MSR.522": {
        "rule_id": "STUB_BPHS.CH14.RAHU_LAGNA_EFFECTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "14.APPROX.8",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.523": {
        "rule_id": "BPHS.33.26.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "33.26",
        "match_confidence": 0.69,
        "match_rationale": "scope=bhava / school=parashari / score=0.690",
    },
    "SIG.MSR.524": {
        "rule_id": "BPHS.21.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "21.3",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.525": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.69,
        "match_rationale": "scope=yoga / school=parashari / score=0.690",
    },
    "SIG.MSR.526": {
        "rule_id": "BPHS.78.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.2",
        "match_confidence": 0.69,
        "match_rationale": "scope=transit / school=parashari / score=0.690",
    },
    "SIG.MSR.527": {
        "rule_id": "BPHS.78.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "78.3",
        "match_confidence": 0.66,
        "match_rationale": "scope=transit / school=parashari / score=0.660",
    },
    "SIG.MSR.528": {
        "rule_id": "STUB_BPHS.CH14.RAHU_LAGNA_EFFECTS",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "14.APPROX.8",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.529": {
        "rule_id": "BPHS.34.35.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "34.35",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.530": {
        "rule_id": "STUB_BPHS.CH49.RAHU_KETU_MOOLATRIKONA",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "49.APPROX.10",
        "match_confidence": 0.69,
        "match_rationale": "scope=graha / school=parashari / score=0.690",
    },
    "SIG.MSR.531": {
        "rule_id": "BPHS.26.17.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "26.17",
        "match_confidence": 0.69,
        "match_rationale": "scope=graha / school=parashari / score=0.690",
    },
    "SIG.MSR.532": {
        "rule_id": "BPHS.50.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "50.3",
        "match_confidence": 0.72,
        "match_rationale": "scope=dasha / school=parashari / score=0.720",
    },
    "SIG.MSR.533": {
        "rule_id": "BPHS.18.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "18.3",
        "match_confidence": 0.69,
        "match_rationale": "scope=bhava / school=parashari / score=0.690",
    },
    "SIG.MSR.534": {
        "rule_id": "BPHS.21.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "21.3",
        "match_confidence": 0.78,
        "match_rationale": "scope=bhava / school=parashari / score=0.780",
    },
    "SIG.MSR.535": {
        "rule_id": "BPHS.21.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "21.3",
        "match_confidence": 0.69,
        "match_rationale": "scope=bhava / school=parashari / score=0.690",
    },
    "SIG.MSR.536": {
        "rule_id": "BPHS.74.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "74.2",
        "match_confidence": 0.72,
        "match_rationale": "scope=yoga / school=parashari / score=0.720",
    },
    "SIG.MSR.537": {
        "rule_id": "BPHS.21.3.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "21.3",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.538": {
        "rule_id": "BPHS.39.2.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "39.2",
        "match_confidence": 0.69,
        "match_rationale": "scope=yoga / school=parashari / score=0.690",
    },
    "SIG.MSR.539": {
        "rule_id": "BPHS.36.42.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "36.42",
        "match_confidence": 0.75,
        "match_rationale": "scope=yoga / school=parashari / score=0.750",
    },
    "SIG.MSR.540": {
        "rule_id": "BPHS.68.22.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "68.22",
        "match_confidence": 0.75,
        "match_rationale": "scope=transit / school=parashari / score=0.750",
    },
    "SIG.MSR.541": {
        "rule_id": "BPHS.11.25.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "11.25",
        "match_confidence": 0.72,
        "match_rationale": "scope=bhava / school=parashari / score=0.720",
    },
    "SIG.MSR.542": {
        "rule_id": "BPHS.11.24.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "11.24",
        "match_confidence": 0.75,
        "match_rationale": "scope=bhava / school=parashari / score=0.750",
    },
    "SIG.MSR.543": {
        "rule_id": "BPHS.17.5.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "17.5",
        "match_confidence": 0.69,
        "match_rationale": "scope=bhava / school=parashari / score=0.690",
    },
    "SIG.MSR.544": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.545": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.546": {
        "rule_id": "BPHS.46.47.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.47",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.547": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.79,
        "match_rationale": "scope=dasha / school=parashari / score=0.790",
    },
    "SIG.MSR.548": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.549": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.550": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.551": {
        "rule_id": "BPHS.46.12.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.12",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.552": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.553": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.554": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.555": {
        "rule_id": "BPHS.46.18.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "46.18",
        "match_confidence": 0.85,
        "match_rationale": "scope=dasha / school=parashari / score=0.850",
    },
    "SIG.MSR.556": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.557": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.558": {
        "rule_id": "BPHS.53.16.1",
        "grounding_status": "GROUNDED",
        "source_school": "parashari",
        "verse_citation": "53.16",
        "match_confidence": 0.82,
        "match_rationale": "scope=dasha / school=parashari / score=0.820",
    },
    "SIG.MSR.559": {
        "rule_id": "TAJAKA.ch7.v2.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch7.v2",
        "match_confidence": 0.775,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.775",
    },
    "SIG.MSR.560": {
        "rule_id": "TAJAKA.ch5.v1.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch5.v1",
        "match_confidence": 0.65,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.650",
    },
    "SIG.MSR.561": {
        "rule_id": "TAJAKA.ch3.v2.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch3.v2",
        "match_confidence": 0.6,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.600",
    },
    "SIG.MSR.562": {
        "rule_id": "TAJAKA.ch12.v3.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch12.v3",
        "match_confidence": 0.613,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.613",
    },
    "SIG.MSR.563": {
        "rule_id": "TAJAKA.ch20.v6.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch20.v6",
        "match_confidence": 0.6,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.600",
    },
    "SIG.MSR.564": {
        "rule_id": "TAJAKA.ch2.v4.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch2.v4",
        "match_confidence": 0.59,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.590",
    },
    "SIG.MSR.565": {
        "rule_id": "TAJAKA.ch9.v2.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch9.v2",
        "match_confidence": 0.812,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.812",
    },
    "SIG.MSR.566": {
        "rule_id": "TAJAKA.ch16.v5.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch16.v5",
        "match_confidence": 0.56,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.560",
    },
    "SIG.MSR.567": {
        "rule_id": "TAJAKA.ch3.v10.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch3.v10",
        "match_confidence": 0.62,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.620",
    },
    "SIG.MSR.568": {
        "rule_id": "TAJAKA.ch5.v3.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch5.v3",
        "match_confidence": 0.671,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.671",
    },
    "SIG.MSR.569": {
        "rule_id": "TAJAKA.ch14.v4.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch14.v4",
        "match_confidence": 0.68,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.680",
    },
    "SIG.MSR.570": {
        "rule_id": "TAJAKA.ch9.v5.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch9.v5",
        "match_confidence": 0.59,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.590",
    },
    "SIG.MSR.571": {
        "rule_id": "TAJAKA.ch16.v3.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch16.v3",
        "match_confidence": 0.59,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.590",
    },
    "SIG.MSR.572": {
        "rule_id": "TAJAKA.ch1.v2.1",
        "grounding_status": "GROUNDED",
        "source_school": "tajaka",
        "verse_citation": "ch1.v2",
        "match_confidence": 0.82,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.820",
    },
    "SIG.MSR.573": {
        "rule_id": "TAJAKA.ch1.v2.1",
        "grounding_status": "GROUNDED",
        "source_school": "multi-school",
        "verse_citation": "ch1.v2",
        "match_confidence": 0.56,
        "match_rationale": "scope=varshaphal / school=tajaka / score=0.560",
    },
}

BATCH_NUM = 6
SIGNAL_RANGE = ('SIG.MSR.505', 'SIG.MSR.573')
TOTAL_IN_BATCH = 69

GROUNDED_COUNT = 69
PARTIAL_COUNT = 0
NO_MATCH_COUNT = 0
