"""Permanent fixtures for check_node_series_pin.py: the independent review's scratch cases (run.py/run2.py) plus the in-scope classes of the
revision. Each case is (name, lang, text, expect): `flag` = at least one UNPINNED read is reported; `clean` = reads (if any) are all pinned/exempt;
`blind` = a KNOWN BLIND SPOT: the lint misses it today (tests mark it xfail with the reason, so an improvement forces this file to be updated)."""

CASES = [("py '+' concat across 2 literals", 'py', 'q = "SELECT date, body " + "FROM ephemeris_daily WHERE date > %s"\n', 'blind'),
 ("py ' '.join list", 'py', 'q = " ".join(["SELECT date", "FROM ephemeris_daily", "WHERE date > 1"])\n', 'blind'),
 ('py "public"."ephemeris_daily"', 'py', 'q = \'SELECT date FROM "public"."ephemeris_daily" WHERE date > 1\'\n', 'flag'),
 ('py l0.ephemeris_daily', 'py', 'q = "SELECT date FROM l0.ephemeris_daily"\n', 'flag'),
 ('py comma join', 'py', 'q = "SELECT d.date FROM planets p, ephemeris_daily d WHERE p.x=d.body"\n', 'flag'),
 ('py SQL -- comment contains node_mode =',
  'py',
  'q = """SELECT date FROM ephemeris_daily\n -- TODO node_mode = true later\n"""\n',
  'flag'),
 ('sql /* node_mode = x */', 'sql', 'SELECT date FROM ephemeris_daily /* node_mode = true */ WHERE date > 1;\n', 'flag'),
 ('sql -- comment pin (should still flag)', 'sql', 'SELECT date FROM ephemeris_daily -- node_mode = true\n WHERE date > 1;\n', 'flag'),
 ('py pin on different table',
  'py',
  'q = "SELECT e.date FROM ephemeris_daily e JOIN other o ON o.node_mode = \'true\' AND o.d=e.date"\n',
  'flag'),
 ('py UNION one branch pinned',
  'py',
  'q = "SELECT date FROM ephemeris_daily WHERE node_mode = \'true\' UNION ALL SELECT date FROM ephemeris_daily"\n',
  'flag'),
 ('py CASE WHEN body=Sun', 'py', 'q = "SELECT CASE WHEN body = \'Sun\' THEN 1 ELSE 0 END FROM ephemeris_daily"\n', 'flag'),
 ("py body='Sun' OR date", 'py', 'q = "SELECT * FROM ephemeris_daily WHERE body = \'Sun\' OR date = %s"\n', 'flag'),
 ('py LIMIT 0 elsewhere', 'py', 'q = "WITH z AS (SELECT 1 LIMIT 0) SELECT * FROM ephemeris_daily"\n', 'flag'),
 ('py p.body = Sun other table',
  'py',
  'q = "SELECT e.date FROM ephemeris_daily e JOIN planets p ON p.id=e.pid WHERE p.body = \'Sun\'"\n',
  'flag'),
 ('py comment ending with colon above literal => docstring heuristics',
  'py',
  'def f(c):\n    c.execute(\n        # fetch rows:\n        "SELECT date FROM ephemeris_daily"\n    )\n',
  'flag'),
 ('ts supabase .from()', 'ts', 'const r = await sb.from("ephemeris_daily").select("*");\n', 'blind'),
 ('ts const T="public.ephemeris_daily"', 'ts', 'const T = "public.ephemeris_daily";\nconst q = `SELECT * FROM ${T}`;\n', 'flag'),
 ('py table via imported constant', 'py', 'from consts import EPH\nq = f"SELECT * FROM {EPH}"\n', 'blind'),
 ('ts conditional pin ${cond ? "AND node_mode = ..." : ""}',
  'ts',
  'const q = `SELECT * FROM ephemeris_daily WHERE d > 1 ${strict ? "AND node_mode = \'true\'" : ""}`;\n',
  'flag'),
 ('py f-string conditional NODE_SERIES_PREDICATE',
  'py',
  'q = f"SELECT * FROM ephemeris_daily WHERE {NODE_SERIES_PREDICATE if strict else \'TRUE\'}"\n',
  'flag'),
 ('py plain literal mention token', 'py', 'q = "SELECT * FROM ephemeris_daily -- NODE_SERIES_PREDICATE"\n', 'flag'),
 ('py marker belonging to previous function',
  'py',
  'def a(c):\n'
  '    # node-agnostic: this function reads only the Sun body column\n'
  '    return 1\n'
  'def b(c):\n'
  '    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('py vacuous marker',
  'py',
  'def b(c):\n    # node-agnostic: ok whatever dude\n    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('py marker says all nodes rows',
  'py',
  'def b(c):\n    # node-agnostic: returns every row including the nodes\n    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('sql INSERT..SELECT ON CONFLICT SET node_mode=',
  'sql',
  'INSERT INTO t(a,node_mode) SELECT a, node_mode FROM ephemeris_daily ON CONFLICT (a) DO UPDATE SET node_mode = EXCLUDED.node_mode;\n',
  'flag'),
 ('sql UPDATE .. FROM ephemeris_daily', 'sql', 'UPDATE t SET x = e.v FROM ephemeris_daily e WHERE e.date = t.date;\n', 'flag'),
 ('sql DELETE ... USING ephemeris_daily', 'sql', 'DELETE FROM t USING ephemeris_daily e WHERE e.date = t.date;\n', 'flag'),
 ('py FROM newline public.', 'py', 'q = "SELECT *\\nFROM\\n  public.ephemeris_daily"\n', 'flag'),
 ("py body NOT IN ('Rahu') only", 'py', 'q = "SELECT * FROM ephemeris_daily WHERE body NOT IN (\'Rahu\')"\n', 'flag'),
 ('py NOT IN nodes OR date', 'py', 'q = "SELECT * FROM ephemeris_daily WHERE body NOT IN (\'Rahu\',\'Ketu\') OR date > 1"\n', 'flag'),
 ('py semicolon in literal before FROM', 'py', 'q = "SELECT \';\' AS s FROM ephemeris_daily"\n', 'flag'),
 ('ts regex with quote before query', 'ts', "const re = /'/g;\nconst q = `SELECT * FROM ephemeris_daily`;\n", 'flag'),
 ('py sqlalchemy Table autoload',
  'py',
  'from sqlalchemy import Table\nt = Table("ephemeris_daily", md, autoload_with=e)\nr = conn.execute(t.select())\n',
  'blind'),
 ('py "{}".format("ephemeris_daily")', 'py', 'q = "SELECT * FROM {}".format("ephemeris_daily")\n', 'blind'),
 ('py psycopg2 sql.SQL + Identifier', 'py', 'q = sql.SQL("SELECT * FROM {}").format(sql.Identifier("ephemeris_daily"))\n', 'blind'),
 ('ts schema interpolated', 'ts', 'const q = `SELECT * FROM ${schema}.ephemeris_daily`;\n', 'flag'),
 ('sql view SELECT *', 'sql', 'CREATE VIEW v AS SELECT * FROM ephemeris_daily;\n', 'flag'),
 ('py quoted "ephemeris_daily" alone', 'py', 'q = \'SELECT * FROM "ephemeris_daily" e\'\n', 'flag'),
 ('py f-string {node_mode_clause} var name', 'py', 'q = f"SELECT * FROM ephemeris_daily WHERE x=1 AND node_mode = {mode}"\n', 'clean'),
 ('py newline FROM public.', 'py', 'q = """SELECT *\nFROM\n  public.ephemeris_daily"""\n', 'flag'),
 ('py newline between FROM and table (plain)', 'py', 'q = """SELECT *\nFROM\n  ephemeris_daily e"""\n', 'flag'),
 ('sql comment with ; between SELECT and FROM', 'sql', 'SELECT date, body -- the rows; all of them\n FROM ephemeris_daily;\n', 'flag'),
 ('sql plpgsql func body',
  'sql',
  'CREATE FUNCTION f() RETURNS SETOF date AS $$ BEGIN RETURN QUERY SELECT date FROM ephemeris_daily; END $$ LANGUAGE plpgsql;\n',
  'flag'),
 ('sql quoted schema', 'sql', 'CREATE VIEW v AS SELECT date FROM "public"."ephemeris_daily";\n', 'flag'),
 ('sql comma join', 'sql', 'SELECT t.x FROM t, ephemeris_daily e WHERE e.date=t.d;\n', 'flag'),
 ('sql CTE read', 'sql', 'WITH e AS (SELECT * FROM ephemeris_daily) SELECT * FROM e;\n', 'flag'),
 ('py CTE read', 'py', 'q = "WITH e AS (SELECT * FROM ephemeris_daily) SELECT * FROM e"\n', 'flag'),
 ('py JOIN alias form', 'py', 'q = "SELECT a.x FROM a JOIN ephemeris_daily AS e ON e.date=a.d"\n', 'flag'),
 ('py LEFT JOIN LATERAL',
  'py',
  'q = "SELECT a.x FROM a LEFT JOIN LATERAL (SELECT * FROM ephemeris_daily e WHERE e.date=a.d) z ON true"\n',
  'flag'),
 ("py body = 'Sun' AND in subselect pin of other table",
  'py',
  'q = "SELECT * FROM ephemeris_daily WHERE date IN (SELECT date FROM x WHERE node_mode=1)"\n',
  'flag'),
 ('ts template w/ ${NODE_SERIES_PREDICATE} wrongly named const',
  'ts',
  'const q = `SELECT * FROM ephemeris_daily WHERE ${NODE_SERIES_PREDICATE}`;\n',
  'clean'),
 ('ts /* marker */',
  'ts',
  'const q = `SELECT * FROM ephemeris_daily`; // node-agnostic: non_node_bodies_literal: seven grahas only here\n',
  'clean'),
 ('ts template pin in other template var',
  'ts',
  "const pin = `node_mode = 'true'`;\nconst q = `SELECT * FROM ephemeris_daily WHERE ${pin}`;\n",
  'flag'),
 ('py pin via variable',
  'py',
  'PIN = "(body NOT IN (\'Rahu\',\'Ketu\') OR node_mode = \'true\')"\nq = f"SELECT * FROM ephemeris_daily WHERE {PIN}"\n',
  'flag'),
 ('py doc-like: literal after if-colon on own line', 'py', 'def f(c):\n    if x:\n        """SELECT * FROM ephemeris_daily"""\n', 'flag'),
 ('py literal following a dict key colon on prev line', 'py', 'Q = {\n  "a":\n    """SELECT * FROM ephemeris_daily""",\n}\n', 'flag'),
 ('py literal first thing after a lambda/colon comment',
  'py',
  'rows = c.execute(\n    # all rows, not just the sun:\n    """SELECT * FROM ephemeris_daily"""\n)\n',
  'flag'),
 ('py f-string brace expr with quotes (py3.12)', 'py', 'q = f"SELECT {cols[\'a\']} FROM ephemeris_daily"\n', 'flag'),
 ('py string with # in it before', 'py', 'u="http://x#y"\nq = "SELECT * FROM ephemeris_daily"\n', 'flag'),
 ('py rb prefix / byte', 'py', 'q = b"SELECT * FROM ephemeris_daily"\n', 'flag'),
 ('ts supabase .from template', 'ts', 'const t="ephemeris_daily"; const r = db.from(t).select("*");\n', 'blind'),
 ('ts tagged sql`` read', 'ts', 'const r = await sql`select * from ephemeris_daily where date = ${d}`;\n', 'flag'),
 ('py lower-case from', 'py', 'q = "select * from ephemeris_daily"\n', 'flag'),
 ("py FROM only schema 'bg' prefix", 'py', 'q = "SELECT * FROM brahmagyan.ephemeris_daily"\n', 'flag'),
 ('py FROM with tab/odd whitespace + comment between', 'py', 'q = "SELECT *\\tFROM\\tephemeris_daily"\n', 'flag'),
 ('py FROM /* c */ ephemeris_daily', 'py', 'q = "SELECT * FROM /* c */ ephemeris_daily"\n', 'flag'),
 ('py FROM ONLY', 'py', 'q = "SELECT * FROM ONLY ephemeris_daily"\n', 'flag'),
 ('py psycopg2 named placeholder body=%(b)s', 'py', 'q = "SELECT * FROM ephemeris_daily WHERE body = %(b)s"\n', 'flag'),
 ('py body = ANY(%s) flagged', 'py', 'q = "SELECT * FROM ephemeris_daily WHERE body = ANY(%s)"\n', 'flag'),
 ('py body IN (%s, %s)', 'py', 'q = "SELECT * FROM ephemeris_daily WHERE body IN (%s, %s)"\n', 'flag'),
 ('py f-string body IN ({placeholders})', 'py', 'q = f"SELECT * FROM ephemeris_daily WHERE body IN ({ph})"\n', 'flag'),
 ("py f-string body = '{b}'", 'py', 'q = f"SELECT * FROM ephemeris_daily WHERE body = \'{b}\'"\n', 'flag'),
 ("ts body = '${b}'", 'ts', "const q = `SELECT * FROM ephemeris_daily WHERE body = '${b}'`;\n", 'flag'),
 ("py body IN ('Sun', ${list})", 'py', 'q = f"SELECT * FROM ephemeris_daily WHERE body IN (\'Sun\', {extra})"\n', 'flag'),
 ("py body NOT IN ('Rahu','Ketu') then body = x OR",
  'py',
  'q = "SELECT * FROM ephemeris_daily WHERE body NOT IN (\'Rahu\',\'Ketu\') OR body = %s"\n',
  'flag'),
 ('py valid marker above statement',
  'py',
  'def b(c):\n'
  '    # node-agnostic: count_only_table_level: floor check over the whole table\n'
  '    return c.execute("SELECT count(*) FROM ephemeris_daily")\n',
  'clean'),
 ('py valid marker one opener line above',
  'py',
  'def b(c):\n'
  '    # node-agnostic: count_only_table_level: floor check over the whole table\n'
  '    return c.execute(\n'
  '        "SELECT count(*) FROM ephemeris_daily")\n',
  'clean'),
 ('py marker with unknown reason code',
  'py',
  'def b(c):\n    # node-agnostic: because_i_said_so: this is fine really\n    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('py marker text too short',
  'py',
  'def b(c):\n    # node-agnostic: count_only_table_level: ok\n    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('py marker naming Rahu',
  'py',
  'def b(c):\n    # node-agnostic: non_node_bodies_literal: reads Rahu rows too\n    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('py marker separated by a blank line',
  'py',
  'def b(c):\n'
  '    # node-agnostic: count_only_table_level: floor check over the whole table\n'
  '\n'
  '    return c.execute("SELECT * FROM ephemeris_daily")\n',
  'flag'),
 ('sql marker inside the statement',
  'sql',
  'SELECT count(*) FROM ephemeris_daily -- node-agnostic: count_only_table_level: floor check over the table\n;\n',
  'clean'),
 ('sql marker scoped to ONE statement (second statement unpinned)',
  'sql',
  '-- node-agnostic: count_only_table_level: floor check over the table\n'
  'SELECT count(*) FROM ephemeris_daily;\n'
  'SELECT * FROM ephemeris_daily;\n',
  'flag'),
 ('sql block comment marker',
  'sql',
  'SELECT count(*) FROM ephemeris_daily /* node-agnostic: count_only_table_level: floor check over the table */;\n',
  'clean'),
 ('sql WHERE node_mode literal predicate', 'sql', "SELECT date FROM ephemeris_daily WHERE node_mode = 'true';\n", 'clean'),
 ('sql WHERE alias-qualified node_mode on a join',
  'sql',
  "SELECT e.date FROM ephemeris_daily e JOIN charts c ON c.d = e.date WHERE e.node_mode = 'true';\n",
  'clean'),
 ('sql unqualified node_mode on a join is not bound to this table',
  'sql',
  "SELECT e.date FROM ephemeris_daily e JOIN charts c ON c.d = e.date WHERE node_mode = 'true';\n",
  'flag'),
 ('sql ON-bound node_mode on the ephemeris join',
  'sql',
  "SELECT c.d FROM charts c JOIN ephemeris_daily e ON e.date = c.d AND e.node_mode = 'true';\n",
  'clean'),
 ('sql UNION where BOTH branches pinned',
  'sql',
  "SELECT date FROM ephemeris_daily WHERE node_mode = 'true' UNION ALL SELECT date FROM ephemeris_daily WHERE node_mode = 'mean';\n",
  'clean'),
 ('sql OR with unrelated predicate is not a pin',
  'sql',
  "SELECT date FROM ephemeris_daily WHERE node_mode = 'true' OR date > '2000-01-01';\n",
  'flag'),
 ('sql NULL-safe pin form',
  'sql',
  "SELECT date FROM ephemeris_daily WHERE (body NOT IN ('Rahu', 'Ketu') OR node_mode = 'true');\n",
  'clean'),
 ('sql literal non-node body IN list', 'sql', "SELECT date FROM ephemeris_daily WHERE body IN ('Sun', 'Moon');\n", 'clean'),
 ('sql node_mode in SELECT list only', 'sql', 'SELECT date, node_mode FROM ephemeris_daily;\n', 'flag'),
 ('py NODE_SERIES_PREDICATE bare in WHERE',
  'py',
  'q = f"SELECT * FROM ephemeris_daily WHERE x = 1 AND {NODE_SERIES_PREDICATE}"\n',
  'clean'),
 ('py NODE_SERIES_PREDICATE in the SELECT list is not a pin', 'py', 'q = f"SELECT {NODE_SERIES_PREDICATE} FROM ephemeris_daily"\n', 'flag'),
 ('py table through a same-file constant, pinned',
  'py',
  'T = "ephemeris_daily"\nq = f"SELECT * FROM {T} WHERE {NODE_SERIES_PREDICATE}"\n',
  'clean'),
 ('py table through a same-file constant, unpinned', 'py', 'T = "ephemeris_daily"\nq = f"SELECT * FROM {T} WHERE date > 1"\n', 'flag'),
 ('py count helper with the table name (v13_production_gate style)', 'py', 'c = count("ephemeris_daily")\n', 'flag'),
 ('py count helper with a valid marker',
  'py',
  '# node-agnostic: count_only_table_level: volume message only\nc = count("ephemeris_daily")\n',
  'clean'),
 ('py write is not a read',
  'py',
  'q = "INSERT INTO ephemeris_daily (a) VALUES (1) ON CONFLICT (a) DO NOTHING"\n'
  'q2 = "UPDATE ephemeris_daily SET a = 1"\n'
  'q3 = "DELETE FROM ephemeris_daily WHERE a = 1"\n',
  'clean'),
 ('py def docstring is not a read', 'py', 'def f():\n    """SELECT a FROM ephemeris_daily is prose"""\n    return 1\n', 'clean'),
 ('py module docstring is not a read', 'py', '"""SELECT a FROM ephemeris_daily is prose"""\nx = 1\n', 'clean'),
 ('py multi-line signature docstring is not a read',
  'py',
  'def f(\n    a: int,\n) -> int:\n    """SELECT a FROM ephemeris_daily is prose"""\n    return 1\n',
  'clean'),
 ('sql CTE: inner read unpinned even if the outer filters',
  'sql',
  "WITH e AS (SELECT * FROM ephemeris_daily) SELECT * FROM e WHERE node_mode = 'true';\n",
  'flag'),
 ('sql pin in a different SELECT of the same statement',
  'sql',
  "SELECT a.x FROM a WHERE a.node_mode = 'true' AND a.d IN (SELECT date FROM ephemeris_daily);\n",
  'flag'),
 ('sql EXTRACT(.. FROM date) is not a relation',
  'sql',
  "SELECT extract(year FROM date) FROM ephemeris_daily WHERE node_mode = 'true';\n",
  'clean'),
 ("sql reverse comparison '= node_mode'", 'sql', "SELECT date FROM ephemeris_daily WHERE 'true' = node_mode;\n", 'clean'),
 ('sql UNION where only the SECOND branch is pinned',
  'sql',
  "SELECT date FROM ephemeris_daily UNION ALL SELECT date FROM ephemeris_daily WHERE node_mode = 'true';\n",
  'flag'),
 ('sql COALESCE(node_mode) pin form', 'sql', "SELECT date FROM ephemeris_daily WHERE COALESCE(node_mode, 'true') = 'true';\n", 'clean'),
 ('sql node_mode IS NULL is a literal predicate', 'sql', 'SELECT date FROM ephemeris_daily WHERE node_mode IS NULL;\n', 'clean'),
 ('sql schema-qualified read with alias and AS',
  'sql',
  "SELECT e.date FROM public.ephemeris_daily AS e WHERE e.node_mode = 'true';\n",
  'clean'),
 ('sql comma join with the pin on the ephemeris alias',
  'sql',
  "SELECT t.x FROM t, ephemeris_daily e WHERE e.date = t.d AND e.node_mode = 'true';\n",
  'clean'),
 ('sql UPDATE ... FROM ephemeris_daily with a pin',
  'sql',
  "UPDATE t SET x = e.v FROM ephemeris_daily e WHERE e.date = t.date AND e.node_mode = 'true';\n",
  'clean'),
 ('sql DELETE ... USING ephemeris_daily with a pin',
  'sql',
  "DELETE FROM t USING ephemeris_daily e WHERE e.date = t.date AND e.node_mode = 'true';\n",
  'clean')]
