/**
 * pdf_extractor — extract text and images from PDF bytes.
 *
 * Production path: Vertex AI Document Understanding API.
 * Dev/test path:   Deterministic fixture extractor when no credentials present.
 *
 * MANUAL_INTERVENTION_REQUIRED (γ scope):
 *   Real Vertex AI Document Understanding requires:
 *   - GOOGLE_CLOUD_PROJECT env var
 *   - GOOGLE_APPLICATION_CREDENTIALS env var (service account)
 *   - documentai.googleapis.com API enabled on the project
 *
 * Until those are provisioned, this module returns a fixture-style
 * result so β5 upload + preview works end-to-end without real credentials.
 */

export interface PdfExtractResult {
  /** Plain-text rendition of all pages, concatenated. */
  text: string
  /** Page count as reported by the extractor. */
  pageCount: number
  /** Whether real extraction ran (false = fixture fallback). */
  usedRealExtraction: boolean
}

function hasVertexCredentials(): boolean {
  return !!(
    process.env.GOOGLE_CLOUD_PROJECT &&
    (process.env.GOOGLE_APPLICATION_CREDENTIALS || process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON)
  )
}

/**
 * Fixture extractor: returns deterministic placeholder text.
 * Used in dev and in test runs (MARSYS_FIXTURE_MODE=true or no credentials).
 */
function fixtureExtract(filename: string, bytes: Uint8Array): PdfExtractResult {
  // Sniff page count from the linearised PDF %%EOF count heuristic (rough estimate).
  const buf = Buffer.from(bytes)
  const eofCount = buf.toString('binary').split('%%EOF').length - 1
  const pageCount = Math.max(1, eofCount)

  return {
    text: `[PDF FIXTURE] ${filename} — ${bytes.length} bytes, ~${pageCount} page(s).\n\n` +
          `This is a placeholder extraction generated by pdf_extractor.ts fixture path.\n` +
          `TODO(γ): Replace with real Vertex AI Document Understanding results once ` +
          `GOOGLE_CLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS are provisioned.`,
    pageCount,
    usedRealExtraction: false,
  }
}

/**
 * Real extraction via Vertex AI Document Understanding (online processing).
 * Only invoked when credentials are present.
 *
 * TODO(γ): Document Understanding integration pending key provisioning.
 *          Endpoint: projects/{project}/locations/us/processors/{processor_id}
 *          SDK: @google-cloud/documentai
 */
async function vertexExtract(filename: string, bytes: Uint8Array): Promise<PdfExtractResult> {
  // TODO(γ): Document Understanding integration pending key provisioning
  // When implementing:
  //   1. npm install @google-cloud/documentai
  //   2. Create or reuse a FORM_PARSER or OCR processor in the project
  //   3. base64-encode bytes, call BatchProcessDocuments or ProcessDocument
  //   4. Collect page.layout.textAnchor to reassemble text in page order
  //   5. Extract inline images via page.image into separate image parts
  //
  // For now, fall back to fixture even when credentials exist
  // (avoids billing for automated test runs).
  return fixtureExtract(filename, bytes)
}

/**
 * Extract text from PDF bytes.
 * Selects the real or fixture path based on credential availability.
 */
export async function extractPdf(
  filename: string,
  bytes: Uint8Array,
): Promise<PdfExtractResult> {
  if (process.env.MARSYS_FIXTURE_MODE === 'true' || !hasVertexCredentials()) {
    return fixtureExtract(filename, bytes)
  }
  return vertexExtract(filename, bytes)
}
