-- M0-T26 RESTORE — asset_registry layer_index / layer_name
-- Captured 2026-08-23T06:42:43Z (UTC). Restores EXACTLY the pre-repair values of the two columns
-- this task writes, on all 128 rows. Touches no other column, no other table.
-- Aborts (RAISE EXCEPTION rolls back the whole transaction) unless exactly 128 rows update.
BEGIN;

DO $restore$
DECLARE
  n_updated integer;
BEGIN
  WITH snap(asset_id, layer_index, layer_name) AS (VALUES
  ('bg_class_lifetime_counts', 'L0', 'Brahmagyan'),
  ('bg_class_priors', 'L0', 'Brahmagyan'),
  ('bg_cohort', 'L0', 'Brahmagyan'),
  ('bg_compendium_index', 'L0', 'Brahmagyan'),
  ('bg_concordance', 'L0', 'Brahmagyan'),
  ('bg_dasha_systems', 'L0', 'Brahmagyan'),
  ('bg_dignity_reference', 'L0', 'Brahmagyan'),
  ('bg_doshas', 'L0', 'Brahmagyan'),
  ('bg_ephemeris', 'L0', 'Brahmagyan'),
  ('bg_ephemeris_engine', 'L0', 'Brahmagyan'),
  ('bg_formula_constants', 'L0', 'Brahmagyan'),
  ('bg_ghatana', 'L0', 'Brahmagyan'),
  ('bg_gochara_arcs', 'L0', 'Brahmagyan'),
  ('bg_gochara_citation_resolution', 'L0', 'Brahmagyan'),
  ('bg_kota_chakra_rings', 'L0', 'Brahmagyan'),
  ('bg_kp_sublord_division', 'L0', 'Brahmagyan'),
  ('bg_medical_mappings', 'L0', 'Brahmagyan'),
  ('bg_muhurta_lattice', 'L0', 'Brahmagyan'),
  ('bg_nakshatra', 'L0', 'Brahmagyan'),
  ('bg_nakshatra_medical', 'L0', 'Brahmagyan'),
  ('bg_ontology', 'L0', 'Brahmagyan'),
  ('bg_panchanga', 'L0', 'Brahmagyan'),
  ('bg_parihara_rules', 'L0', 'Brahmagyan'),
  ('bg_phaladeepika_latta', 'L0', 'Brahmagyan'),
  ('bg_prashna_rules', 'L0', 'Brahmagyan'),
  ('bg_reference', 'L0', 'Brahmagyan'),
  ('bg_remedies', 'L0', 'Brahmagyan'),
  ('bg_rules', 'L0', 'Brahmagyan'),
  ('bg_sarvatobhadra_grid', 'L0', 'Brahmagyan'),
  ('bg_sign_medical', '0', 'Brahmagyan'),
  ('bg_sky_calendar', 'L0', 'Brahmagyan'),
  ('bg_text_index', 'L0', 'Brahmagyan'),
  ('bg_texts', 'L0', 'Brahmagyan'),
  ('bg_transit_engine', 'L0', 'Brahmagyan'),
  ('bg_transit_rules', 'L0', 'Brahmagyan'),
  ('bg_vastu_directions', 'L0', 'Brahmagyan'),
  ('bg_vedha_malefic_scale', 'L0', 'Brahmagyan'),
  ('bg_vidhi_floors', NULL, NULL),
  ('bg_vidhi_primitives', NULL, NULL),
  ('bg_yogas', 'L0', 'Brahmagyan'),
  ('bo_anveshana', 'L2', 'Bodha'),
  ('bo_arudha', NULL, NULL),
  ('bo_bimba', 'L2', 'Bodha'),
  ('bo_cdlm_summary', NULL, NULL),
  ('bo_cgm_motifs', NULL, NULL),
  ('bo_cgm_paths', NULL, NULL),
  ('bo_chart_gestalt', NULL, NULL),
  ('bo_drishti', 'L2', 'Bodha'),
  ('bo_karanajala', 'L2', 'Bodha'),
  ('bo_laksana', 'L2', 'Bodha'),
  ('bo_laksana_rerank', NULL, NULL),
  ('bo_nakshatra_semantic', NULL, NULL),
  ('bo_pramana_mapa', 'L2', 'Bodha'),
  ('bo_pratijna', '2', 'Bodha'),
  ('bo_samskara', 'L2', 'Bodha'),
  ('bo_samvada', 'L2', 'Bodha'),
  ('bo_sangati', 'L2', 'Bodha'),
  ('bo_special_lagna', NULL, NULL),
  ('bo_sudarshana', NULL, NULL),
  ('bo_upaya', 'L2', 'Bodha'),
  ('bo_vargottama_dhana', NULL, NULL),
  ('bo_yantra_mechanism', NULL, NULL),
  ('ga_ayurdaya', '1', 'Ganita'),
  ('ga_condition', 'L1', 'Gaṇita'),
  ('ga_dashas', 'L1', 'Gaṇita'),
  ('ga_medical', 'L1', 'Gaṇita'),
  ('ga_nakshatra', 'L1', 'Gaṇita'),
  ('ga_panchanga', 'L1', 'Gaṇita'),
  ('ga_positions', 'L1', 'Gaṇita'),
  ('ga_prashna', 'L1', 'Gaṇita'),
  ('ga_sade_sati', 'L1', 'Gaṇita'),
  ('ga_sensitive', 'L1', 'Gaṇita'),
  ('ga_sensitive_degree', '1', 'Ganita'),
  ('ga_strength', 'L1', 'Gaṇita'),
  ('ga_structural', 'L1', 'Gaṇita'),
  ('ga_tajaka', 'L1', 'Gaṇita'),
  ('ga_transit_anchors', 'L1', 'Gaṇita'),
  ('ga_vargas', 'L1', 'Gaṇita'),
  ('ga_vastu', 'L1', 'Gaṇita'),
  ('ga_vichara', NULL, NULL),
  ('ga_yoga', 'L1', 'Gaṇita'),
  ('ka_avadhi', '3', 'Kala'),
  ('ka_bhavishya_lekha', 'L3', 'Kāla'),
  ('ka_dasha_kala', 'L3', 'Kāla'),
  ('ka_gochara', 'L3', 'Kāla'),
  ('ka_gochara_resonance', 'L3', 'Kāla'),
  ('ka_gochara_sweep', 'L3', 'Kāla'),
  ('ka_gochara_v3_century_materialize', 'L3', 'Kala'),
  ('ka_graha_sancara', 'L3', 'Kāla'),
  ('ka_jivana_parva', 'L3', 'Kāla'),
  ('ka_kala_darshana', 'L3', 'Kāla'),
  ('ka_kalasutra', 'L3', 'Kāla'),
  ('ka_kota_chakra', 'L3', 'Kāla'),
  ('ka_kshetra', 'L3', 'Kāla'),
  ('ka_moorti_nirnaya', 'L3', 'Kāla'),
  ('ka_muhurta_seva', 'L3', 'Kāla'),
  ('ka_sangam', 'L3', 'Kāla'),
  ('ka_sudarshana_varsha', 'L3', 'Kāla'),
  ('ka_taranga', '3', 'Kala'),
  ('ka_tithi_pravesha', 'L3', 'Kāla'),
  ('ka_tulana', 'L3', 'Kāla'),
  ('ka_vedha_gochara', 'L3', 'Kāla'),
  ('ka_vighnakara', 'L3', 'Kāla'),
  ('ka_yojaka', 'L3', 'Kāla'),
  ('lel_events', NULL, NULL),
  ('mi_abhilekha', 'L5', 'Mīmāṃsā'),
  ('mi_adhilepa', 'L5', 'Mīmāṃsā'),
  ('mi_bhara', 'L5', 'Mīmāṃsā'),
  ('mi_bhavisya', 'L5', 'Mīmāṃsā'),
  ('mi_darshana', 'L5', 'Mīmāṃsā'),
  ('mi_gunanaka', 'L5', 'Mīmāṃsā'),
  ('mi_jivanaghatana', 'L5', 'Mīmāṃsā'),
  ('mi_kula', 'L5', 'Mīmāṃsā'),
  ('mi_pariksha', 'L5', 'Mīmāṃsā'),
  ('mi_pramana', 'L5', 'Mīmāṃsā'),
  ('mi_sambandha', 'L5', 'Mīmāṃsā'),
  ('mi_sankalpa', 'L5', 'Mīmāṃsā'),
  ('mi_seva', 'L5', 'Mīmāṃsā'),
  ('mi_vistara', 'L5', 'Mīmāṃsā'),
  ('ph_muhurta', 'L4', 'Phala'),
  ('ph_nimitta', 'L4', 'Phala'),
  ('ph_phaladesa', 'L4', 'Phala'),
  ('ph_pramana', 'L4', 'Phala'),
  ('ph_pratikara', 'L4', 'Phala'),
  ('ph_rectification', 'L4', 'Phala'),
  ('ph_sankrama', 'L4', 'Phala'),
  ('ph_sodhana', 'L4', 'Phala'),
  ('ph_suddha_sodhana', 'L4', 'Phala')
  ), upd AS (
    UPDATE asset_registry a
       SET layer_index = s.layer_index,
           layer_name  = s.layer_name
      FROM snap s
     WHERE a.asset_id = s.asset_id
    RETURNING 1
  )
  SELECT count(*) INTO n_updated FROM upd;

  IF n_updated <> 128 THEN
    RAISE EXCEPTION 'M0-T26 restore aborted: updated % rows, expected 128', n_updated;
  END IF;
  RAISE NOTICE 'M0-T26 restore: % rows restored', n_updated;
END
$restore$;

COMMIT;
