import { z } from 'zod'

const nullableIso = z.string().datetime().nullable()

export const NirmanaElevationSnapshotSchema = z.object({
  schema_version: z.literal('1.0'),
  generation: z.string().regex(/^[a-f0-9]{64}$/),
  generated_at: z.string().datetime(),
  campaign: z.object({
    campaign_id: z.string(),
    definition_revision: z.string().nullable(),
    definition_status: z.enum(['reconciling', 'frozen', 'superseded']),
    campaign_status: z.enum(['takeover', 'foundation', 'running', 'blocked', 'paused', 'completed', 'unknown']),
    current_layer: z.string().nullable(),
    current_wave: z.number().int().nullable(),
  }),
  progress: z.object({
    denominator_status: z.enum(['reconciling', 'frozen']),
    assets_total: z.number().int().nonnegative().nullable(),
    assets_frozen: z.number().int().nonnegative(),
    layers_total: z.literal(6),
    layers_frozen: z.number().int().nonnegative(),
    buildable_assets_total: z.number().int().nonnegative().nullable(),
    accepted_rebuilds: z.number().int().nonnegative(),
  }),
  layers: z.array(z.object({
    layer_id: z.enum(['L0', 'L1', 'L2', 'L3', 'L4', 'L5']),
    order: z.number().int().min(0).max(5),
    state: z.enum(['locked', 'open', 'blocked', 'verifying', 'frozen', 'unknown']),
    assets_total: z.number().int().nonnegative().nullable(),
    optimization_reviewed: z.number().int().nonnegative(),
    rebuilt_or_dispositioned: z.number().int().nonnegative(),
    verified: z.number().int().nonnegative(),
    frozen: z.number().int().nonnegative(),
    waves: z.array(z.object({
      wave_index: z.number().int().nonnegative(),
      state: z.string(),
      asset_ids: z.array(z.string()),
      active_asset_ids: z.array(z.string()),
      blocked_asset_ids: z.array(z.string()),
    })),
  })),
  assets: z.array(z.object({
    asset_id: z.string(),
    display_name: z.string(),
    layer: z.string(),
    wave_index: z.number().int().nullable(),
    producer_id: z.string().nullable(),
    covered_asset_ids: z.array(z.string()),
    execution_obligation: z.enum(['build', 'probe', 'producer_covered', 'static_acceptance', 'source_acceptance', 'empty_acceptance', 'unresolved']),
    lifecycle_state: z.string(),
    readiness_state: z.string(),
    current_run_state: z.string().nullable(),
    progress_mode: z.enum(['determinate', 'indeterminate', 'not_applicable']),
    work_committed: z.number().int().nonnegative().nullable(),
    work_total: z.number().int().nonnegative().nullable(),
    current_unit_label: z.string().nullable(),
    baseline_duration_seconds: z.number().nonnegative().nullable(),
    final_duration_seconds: z.number().nonnegative().nullable(),
    improvement_percent: z.number().nullable(),
    blocker: z.string().nullable(),
    evidence_refs: z.array(z.string()),
  })),
  active_runs: z.array(z.object({
    run_id: z.string(),
    layer: z.string().nullable(),
    wave_index: z.number().int().nullable(),
    state: z.string(),
    active_asset_ids: z.array(z.string()),
    completed_assets: z.number().int().nonnegative(),
    planned_assets: z.number().int().nonnegative(),
    started_at: nullableIso,
    last_progress_at: nullableIso,
  })),
  release: z.object({
    main_sha: z.string().nullable(),
    deployed_sha: z.string().nullable(),
    deployed_revision: z.string().nullable(),
    production_in_sync: z.boolean().nullable(),
    observed_at: nullableIso,
  }),
  sources: z.array(z.object({
    source_id: z.string(),
    provenance: z.string(),
    state: z.enum(['fresh', 'stale', 'unavailable', 'unknown']),
    observed_at: nullableIso,
    age_seconds: z.number().int().nonnegative().nullable(),
    error: z.string().nullable(),
  })),
  data_quality: z.object({
    verdict: z.enum(['reliable', 'degraded', 'unknown']),
    gaps: z.array(z.string()),
    contradictions: z.array(z.string()),
  }),
})

export type NirmanaElevationSnapshot = z.infer<typeof NirmanaElevationSnapshotSchema>
