"""
_ga_condition_canonical_inputs.py -- shared test support for the Saturn / Sun condition-score goldens.

Not a test module (no test_ prefix; pytest does not collect it).

WHAT IS HERE. The INPUTS the real ga_condition compute path consumes for the canonical chart
482012f1-710e-4a25-994a-93821f5871aa, Saturn and Sun, on the five ayanamshas, plus the stored
intermediate and final values the path is expected to reproduce. Every number below was READ
(SELECT-only, as the read-only reader, 2026-10-02) from:

  chart_facts (graha_sign_attributes / graha_position, subjects SAT, SUN)
      -> sign, degree_in_sign, longitude_sidereal, retrograde_flag
  ga_condition_composite (build 7a6f34fb-d2ed-4b50-9c06-74613b3eb685; one row per ayanamsha x graha)
      -> varga_dignity_spread (the D1..D2700 dignity labels), and the stored outputs
         dignity_d1, avastha_baladi, avastha_deeptaadi, varga_dignity_composite, condition_score
  bg_combustion_orbs (Saturn) -> orb 15 / deep 12

Nothing is invented and nothing is derived by hand. The stored outputs are NOT fed to the band
function: `run_real_compute` runs the SAME helper functions `build_ga_condition_substep` calls, in the
same order, on the READ INPUTS, so the golden tests fail if any of them (dignity rules, the dignity /
deeptaadi / baladi score tables, the formula weights, the varga-composite weighting, the combustion
rule) changes the score or its band.

NOT COVERED. The database-bound halves of the writer cannot run in a unit test: `_load_graha_positions`,
`_load_varga_dignity_spread` (the chart_divisionals SELECT that produces the spread read here),
`_load_dignity_ref` / the bg_dignity_reference override (the golden uses the module constants, which the
writer falls back to when the table is unavailable; the stored dignities agree), and the orchestrator
transaction. A change in those shows only in an end-to-end rebuild, not here.
"""
from __future__ import annotations

from typing import Any

from ga_writers import ga_condition_bands as bands
from ga_writers import ga_condition_writer as cw
from ga_writers import ga_medical_writer as med
from ga_writers import ga_vastu_writer as vas

CANONICAL_CHART_ID = "482012f1-710e-4a25-994a-93821f5871aa"
AYANAMSHAS = (
    "lahiri_chitrapaksha",
    "krishnamurti",
    "raman",
    "surya_siddhanta_classical",
    "true_chitra",
)

#: bg_combustion_orbs, Saturn row (orb_degrees 15, deep_orb_degrees 12), as read.
COMBUSTION_ORBS = {"Saturn": {"orb": 15.0, "deep": 12.0}}

#: Pinned canonical scores (the values the lane's review pinned; equal to the stored
#: ga_condition_composite.condition_score read above), in AYANAMSHAS order.
SATURN_PINNED_SCORES = (0.683108, 0.691486, 0.697162, 0.68, 0.683108)
SUN_PINNED_SCORES = (0.303784, 0.302703, 0.317568, 0.286622, 0.303784)


def run_real_compute(graha: str, fx: dict[str, Any]) -> dict[str, Any]:
    """Run the writer's own helpers on one read-input fixture, in `build_ga_condition_substep`'s order.

    Returns every intermediate so a failing golden names the step that moved. The Sun is never combust
    (check_combustion returns (False, False) for it; the writer skips the arc for the Sun)."""
    dignity_d1 = cw.dignity_d1_from_sign(graha, fx["sign"], fx["degree_in_sign"])
    dignity_score = cw.DIGNITY_SCORES.get(dignity_d1)
    is_retrograde = fx["retro"] == "retrograde"

    is_combust = is_deeply_combust = False
    if graha != "Sun":
        arc = cw.compute_combustion_arc(fx["longitude"], fx["sun_longitude"])
        is_combust, is_deeply_combust = cw.check_combustion(
            graha, arc, COMBUSTION_ORBS, is_retrograde=is_retrograde
        )

    baladi = cw.avastha_baladi_from_degree(fx["degree_in_sign"])
    deeptaadi = cw.avastha_deeptaadi_from_dignity_and_state(dignity_d1, is_combust, is_retrograde)

    # the writer's spread shape is {varga: {"sign": ..., "dignity": ...}}; the composite reads only
    # the dignity label when no numeric score is stored (none is, in the chart_divisionals rows read)
    spread = {varga: {"dignity": label} for varga, label in fx["spread"].items()}
    varga_composite = cw._compute_varga_composite(spread)

    score, breakdown = cw.compute_condition_score_v1(
        dignity_score=dignity_score,
        deeptaadi=deeptaadi,
        baladi=baladi,
        is_combust=is_combust,
        is_deeply_combust=is_deeply_combust,
        is_retrograde=is_retrograde,
        varga_score=varga_composite,
    )
    return {
        "dignity_d1": dignity_d1,
        "dignity_score": dignity_score,
        "is_combust": is_combust,
        "is_deeply_combust": is_deeply_combust,
        "avastha_baladi": baladi,
        "avastha_deeptaadi": deeptaadi,
        "varga_dignity_composite": varga_composite,
        "condition_score": score,
        "breakdown": breakdown,
        "band": bands.score_band(score),
        "medical_label": med.indication_strength_from_score(score),
        "vastu_label": vas.compute_direction_impact(score),
    }


# ---- READ inputs and stored outputs -------------------------------------------------------------

SATURN_CANONICAL = {'lahiri_chitrapaksha': {'sign': 'Libra',
                         'degree_in_sign': 22.4319860591954,
                         'longitude': 202.431986059195,
                         'sun_longitude': 291.962617284992,
                         'retro': 'direct',
                         'spread': {'D1': 'Exalted',
                                    'D2': 'Neutral',
                                    'D3': 'Neutral',
                                    'D4': 'Neutral',
                                    'D5': 'Own',
                                    'D6': 'Neutral',
                                    'D7': 'Neutral',
                                    'D8': 'Neutral',
                                    'D9': 'Debilitated',
                                    'D10': 'Neutral',
                                    'D11': 'Neutral',
                                    'D12': 'Neutral',
                                    'D14': 'Own',
                                    'D15': 'Neutral',
                                    'D16': 'Neutral',
                                    'D20': 'Neutral',
                                    'D21': 'Own',
                                    'D24': 'Neutral',
                                    'D27': 'Neutral',
                                    'D30': 'Own',
                                    'D32': 'Neutral',
                                    'D33': 'Exalted',
                                    'D40': 'Neutral',
                                    'D45': 'Neutral',
                                    'D50': 'Neutral',
                                    'D54': 'Neutral',
                                    'D60': 'Neutral',
                                    'D108': 'Neutral',
                                    'D150': 'Neutral',
                                    'D2700': 'Neutral'},
                         'stored': {'dignity_d1': 'exalted',
                                    'avastha_baladi': 'vriddha',
                                    'avastha_deeptaadi': 'deepta',
                                    'is_combust': False,
                                    'is_deeply_combust': False,
                                    'varga_dignity_composite': 0.540541,
                                    'condition_score': 0.683108}},
 'krishnamurti': {'sign': 'Libra',
                  'degree_in_sign': 22.5288383925263,
                  'longitude': 202.528838392526,
                  'sun_longitude': 292.059469618322,
                  'retro': 'direct',
                  'spread': {'D1': 'Exalted',
                             'D2': 'Neutral',
                             'D3': 'Neutral',
                             'D4': 'Neutral',
                             'D5': 'Own',
                             'D6': 'Neutral',
                             'D7': 'Neutral',
                             'D8': 'Exalted',
                             'D9': 'Debilitated',
                             'D10': 'Neutral',
                             'D11': 'Neutral',
                             'D12': 'Own',
                             'D14': 'Own',
                             'D15': 'Neutral',
                             'D16': 'Debilitated',
                             'D20': 'Neutral',
                             'D21': 'Own',
                             'D24': 'Exalted',
                             'D27': 'Neutral',
                             'D30': 'Own',
                             'D32': 'Debilitated',
                             'D33': 'Exalted',
                             'D40': 'Exalted',
                             'D45': 'Neutral',
                             'D50': 'Neutral',
                             'D54': 'Neutral',
                             'D60': 'Own',
                             'D108': 'Own',
                             'D150': 'Neutral',
                             'D2700': 'Neutral'},
                  'stored': {'dignity_d1': 'exalted',
                             'avastha_baladi': 'vriddha',
                             'avastha_deeptaadi': 'deepta',
                             'is_combust': False,
                             'is_deeply_combust': False,
                             'varga_dignity_composite': 0.582432,
                             'condition_score': 0.691486}},
 'raman': {'sign': 'Libra',
           'degree_in_sign': 23.8782873925263,
           'longitude': 203.878287392526,
           'sun_longitude': 293.408918618322,
           'retro': 'direct',
           'spread': {'D1': 'Exalted',
                      'D2': 'Neutral',
                      'D3': 'Neutral',
                      'D4': 'Neutral',
                      'D5': 'Own',
                      'D6': 'Neutral',
                      'D7': 'Neutral',
                      'D8': 'Exalted',
                      'D9': 'Neutral',
                      'D10': 'Neutral',
                      'D11': 'Neutral',
                      'D12': 'Own',
                      'D14': 'Neutral',
                      'D15': 'Neutral',
                      'D16': 'Debilitated',
                      'D20': 'Neutral',
                      'D21': 'Own',
                      'D24': 'Neutral',
                      'D27': 'Neutral',
                      'D30': 'Neutral',
                      'D32': 'Neutral',
                      'D33': 'Neutral',
                      'D40': 'Neutral',
                      'D45': 'Neutral',
                      'D50': 'Neutral',
                      'D54': 'Exalted',
                      'D60': 'Neutral',
                      'D108': 'Neutral',
                      'D150': 'Neutral',
                      'D2700': 'Neutral'},
           'stored': {'dignity_d1': 'exalted',
                      'avastha_baladi': 'vriddha',
                      'avastha_deeptaadi': 'deepta',
                      'is_combust': False,
                      'is_deeply_combust': False,
                      'varga_dignity_composite': 0.610811,
                      'condition_score': 0.697162}},
 'surya_siddhanta_classical': {'sign': 'Libra',
                               'degree_in_sign': 25.3940188522237,
                               'longitude': 205.394018852224,
                               'sun_longitude': 294.92465007802,
                               'retro': 'direct',
                               'spread': {'D1': 'Exalted',
                                          'D2': 'Neutral',
                                          'D3': 'Neutral',
                                          'D4': 'Neutral',
                                          'D5': 'Own',
                                          'D6': 'Neutral',
                                          'D7': 'Neutral',
                                          'D8': 'Exalted',
                                          'D9': 'Neutral',
                                          'D10': 'Neutral',
                                          'D11': 'Neutral',
                                          'D12': 'Own',
                                          'D14': 'Neutral',
                                          'D15': 'Exalted',
                                          'D16': 'Neutral',
                                          'D20': 'Neutral',
                                          'D21': 'Neutral',
                                          'D24': 'Neutral',
                                          'D27': 'Neutral',
                                          'D30': 'Neutral',
                                          'D32': 'Neutral',
                                          'D33': 'Own',
                                          'D40': 'Own',
                                          'D45': 'Neutral',
                                          'D50': 'Exalted',
                                          'D54': 'Own',
                                          'D60': 'Neutral',
                                          'D108': 'Neutral',
                                          'D150': 'Exalted',
                                          'D2700': 'Neutral'},
                               'stored': {'dignity_d1': 'exalted',
                                          'avastha_baladi': 'mrita',
                                          'avastha_deeptaadi': 'deepta',
                                          'is_combust': False,
                                          'is_deeply_combust': False,
                                          'varga_dignity_composite': 0.65,
                                          'condition_score': 0.68}},
 'true_chitra': {'sign': 'Libra',
                 'degree_in_sign': 22.4475269942807,
                 'longitude': 202.447526994281,
                 'sun_longitude': 291.978158220077,
                 'retro': 'direct',
                 'spread': {'D1': 'Exalted',
                            'D2': 'Neutral',
                            'D3': 'Neutral',
                            'D4': 'Neutral',
                            'D5': 'Own',
                            'D6': 'Neutral',
                            'D7': 'Neutral',
                            'D8': 'Neutral',
                            'D9': 'Debilitated',
                            'D10': 'Neutral',
                            'D11': 'Neutral',
                            'D12': 'Neutral',
                            'D14': 'Own',
                            'D15': 'Neutral',
                            'D16': 'Neutral',
                            'D20': 'Neutral',
                            'D21': 'Own',
                            'D24': 'Neutral',
                            'D27': 'Neutral',
                            'D30': 'Own',
                            'D32': 'Neutral',
                            'D33': 'Exalted',
                            'D40': 'Neutral',
                            'D45': 'Neutral',
                            'D50': 'Neutral',
                            'D54': 'Neutral',
                            'D60': 'Neutral',
                            'D108': 'Neutral',
                            'D150': 'Neutral',
                            'D2700': 'Neutral'},
                 'stored': {'dignity_d1': 'exalted',
                            'avastha_baladi': 'vriddha',
                            'avastha_deeptaadi': 'deepta',
                            'is_combust': False,
                            'is_deeply_combust': False,
                            'varga_dignity_composite': 0.540541,
                            'condition_score': 0.683108}}}

SUN_CANONICAL = {'lahiri_chitrapaksha': {'sign': 'Capricorn',
                         'degree_in_sign': 21.9626172849916,
                         'longitude': 291.962617284992,
                         'sun_longitude': 291.962617284992,
                         'retro': 'direct',
                         'spread': {'D1': 'Neutral',
                                    'D2': 'Own',
                                    'D3': 'Neutral',
                                    'D4': 'Neutral',
                                    'D5': 'Exalted',
                                    'D6': 'Neutral',
                                    'D7': 'Neutral',
                                    'D8': 'Neutral',
                                    'D9': 'Neutral',
                                    'D10': 'Neutral',
                                    'D11': 'Neutral',
                                    'D12': 'Neutral',
                                    'D14': 'Own',
                                    'D15': 'Neutral',
                                    'D16': 'Neutral',
                                    'D20': 'Neutral',
                                    'D21': 'Exalted',
                                    'D24': 'Neutral',
                                    'D27': 'Neutral',
                                    'D30': 'Neutral',
                                    'D32': 'Neutral',
                                    'D33': 'Neutral',
                                    'D40': 'Neutral',
                                    'D45': 'Neutral',
                                    'D50': 'Debilitated',
                                    'D54': 'Neutral',
                                    'D60': 'Neutral',
                                    'D108': 'Neutral',
                                    'D150': 'Neutral',
                                    'D2700': 'Neutral'},
                         'stored': {'dignity_d1': 'enemy_sign',
                                    'avastha_baladi': 'vriddha',
                                    'avastha_deeptaadi': 'dina',
                                    'is_combust': False,
                                    'is_deeply_combust': False,
                                    'varga_dignity_composite': 0.518919,
                                    'condition_score': 0.303784}},
 'krishnamurti': {'sign': 'Capricorn',
                  'degree_in_sign': 22.0594696183224,
                  'longitude': 292.059469618322,
                  'sun_longitude': 292.059469618322,
                  'retro': 'direct',
                  'spread': {'D1': 'Neutral',
                             'D2': 'Own',
                             'D3': 'Neutral',
                             'D4': 'Neutral',
                             'D5': 'Exalted',
                             'D6': 'Neutral',
                             'D7': 'Neutral',
                             'D8': 'Neutral',
                             'D9': 'Neutral',
                             'D10': 'Neutral',
                             'D11': 'Neutral',
                             'D12': 'Neutral',
                             'D14': 'Own',
                             'D15': 'Neutral',
                             'D16': 'Neutral',
                             'D20': 'Neutral',
                             'D21': 'Exalted',
                             'D24': 'Neutral',
                             'D27': 'Neutral',
                             'D30': 'Own',
                             'D32': 'Neutral',
                             'D33': 'Neutral',
                             'D40': 'Neutral',
                             'D45': 'Debilitated',
                             'D50': 'Debilitated',
                             'D54': 'Neutral',
                             'D60': 'Neutral',
                             'D108': 'Neutral',
                             'D150': 'Neutral',
                             'D2700': 'Neutral'},
                  'stored': {'dignity_d1': 'enemy_sign',
                             'avastha_baladi': 'vriddha',
                             'avastha_deeptaadi': 'dina',
                             'is_combust': False,
                             'is_deeply_combust': False,
                             'varga_dignity_composite': 0.513514,
                             'condition_score': 0.302703}},
 'raman': {'sign': 'Capricorn',
           'degree_in_sign': 23.4089186183224,
           'longitude': 293.408918618322,
           'sun_longitude': 293.408918618322,
           'retro': 'direct',
           'spread': {'D1': 'Neutral',
                      'D2': 'Own',
                      'D3': 'Neutral',
                      'D4': 'Neutral',
                      'D5': 'Exalted',
                      'D6': 'Neutral',
                      'D7': 'Neutral',
                      'D8': 'Debilitated',
                      'D9': 'Own',
                      'D10': 'Neutral',
                      'D11': 'Neutral',
                      'D12': 'Neutral',
                      'D14': 'Own',
                      'D15': 'Neutral',
                      'D16': 'Exalted',
                      'D20': 'Neutral',
                      'D21': 'Neutral',
                      'D24': 'Debilitated',
                      'D27': 'Exalted',
                      'D30': 'Neutral',
                      'D32': 'Exalted',
                      'D33': 'Neutral',
                      'D40': 'Neutral',
                      'D45': 'Neutral',
                      'D50': 'Neutral',
                      'D54': 'Exalted',
                      'D60': 'Neutral',
                      'D108': 'Exalted',
                      'D150': 'Neutral',
                      'D2700': 'Debilitated'},
           'stored': {'dignity_d1': 'enemy_sign',
                      'avastha_baladi': 'vriddha',
                      'avastha_deeptaadi': 'dina',
                      'is_combust': False,
                      'is_deeply_combust': False,
                      'varga_dignity_composite': 0.587838,
                      'condition_score': 0.317568}},
 'surya_siddhanta_classical': {'sign': 'Capricorn',
                               'degree_in_sign': 24.9246500780199,
                               'longitude': 294.92465007802,
                               'sun_longitude': 294.92465007802,
                               'retro': 'direct',
                               'spread': {'D1': 'Neutral',
                                          'D2': 'Own',
                                          'D3': 'Neutral',
                                          'D4': 'Neutral',
                                          'D5': 'Neutral',
                                          'D6': 'Neutral',
                                          'D7': 'Neutral',
                                          'D8': 'Debilitated',
                                          'D9': 'Own',
                                          'D10': 'Neutral',
                                          'D11': 'Exalted',
                                          'D12': 'Neutral',
                                          'D14': 'Neutral',
                                          'D15': 'Neutral',
                                          'D16': 'Neutral',
                                          'D20': 'Own',
                                          'D21': 'Neutral',
                                          'D24': 'Neutral',
                                          'D27': 'Neutral',
                                          'D30': 'Debilitated',
                                          'D32': 'Neutral',
                                          'D33': 'Exalted',
                                          'D40': 'Neutral',
                                          'D45': 'Neutral',
                                          'D50': 'Neutral',
                                          'D54': 'Neutral',
                                          'D60': 'Neutral',
                                          'D108': 'Neutral',
                                          'D150': 'Neutral',
                                          'D2700': 'Neutral'},
                               'stored': {'dignity_d1': 'enemy_sign',
                                          'avastha_baladi': 'mrita',
                                          'avastha_deeptaadi': 'dina',
                                          'is_combust': False,
                                          'is_deeply_combust': False,
                                          'varga_dignity_composite': 0.558108,
                                          'condition_score': 0.286622}},
 'true_chitra': {'sign': 'Capricorn',
                 'degree_in_sign': 21.9781582200768,
                 'longitude': 291.978158220077,
                 'sun_longitude': 291.978158220077,
                 'retro': 'direct',
                 'spread': {'D1': 'Neutral',
                            'D2': 'Own',
                            'D3': 'Neutral',
                            'D4': 'Neutral',
                            'D5': 'Exalted',
                            'D6': 'Neutral',
                            'D7': 'Neutral',
                            'D8': 'Neutral',
                            'D9': 'Neutral',
                            'D10': 'Neutral',
                            'D11': 'Neutral',
                            'D12': 'Neutral',
                            'D14': 'Own',
                            'D15': 'Neutral',
                            'D16': 'Neutral',
                            'D20': 'Neutral',
                            'D21': 'Exalted',
                            'D24': 'Neutral',
                            'D27': 'Neutral',
                            'D30': 'Neutral',
                            'D32': 'Neutral',
                            'D33': 'Neutral',
                            'D40': 'Neutral',
                            'D45': 'Neutral',
                            'D50': 'Debilitated',
                            'D54': 'Neutral',
                            'D60': 'Neutral',
                            'D108': 'Neutral',
                            'D150': 'Neutral',
                            'D2700': 'Neutral'},
                 'stored': {'dignity_d1': 'enemy_sign',
                            'avastha_baladi': 'vriddha',
                            'avastha_deeptaadi': 'dina',
                            'is_combust': False,
                            'is_deeply_combust': False,
                            'varga_dignity_composite': 0.518919,
                            'condition_score': 0.303784}}}
