/**
 * L1 Gaṇita Retrieval Coverage Matrix
 * =====================================
 * Machine-readable map: fact_category → tool URI(s).
 * Used by the R3 CI gate to enforce coverage completeness.
 *
 * Phase R1 finding: 0 of 158 fact_categories were covered before this wave.
 * Phase R2 target: every category maps to ≥1 tool.
 *
 * Authored: Wave 3 Phase R1/R2 (2026-06-16)
 */

/** Every chart_facts.fact_category that exists for chart_id=native */
export const CHART_FACTS_CATEGORIES = [
  'anumukha_shani_period',
  'aprakasha_position',
  'ardha_ashtama_shani_period',
  'argala_natal_matrix',
  'arudha_pada',
  'ashtakavarga_anubindu',
  'ashtakavarga_bindu',
  'ashtakavarga_bindu_per_varga',
  'ashtakavarga_bindu_sign',
  'ashtakavarga_ekadhipathya_shodhana',
  'ashtakavarga_kakshya_boundary',
  'ashtakavarga_pinda_bhinna',
  'ashtakavarga_pinda_raasi',
  'ashtakavarga_pinda_sarva',
  'ashtakavarga_pinda_sarva_per_varga',
  'ashtakavarga_pinda_sodhita',
  'ashtakavarga_trikona_shodhana',
  'ashtama_shani_period',
  'aspect_jaimini',
  'aspect_jaimini_per_varga',
  'aspect_matrix_summary',
  'aspect_parashari_given',
  'aspect_parashari_per_varga',
  'aspect_parashari_received',
  'aspect_tajik',
  'bhadra_flag',
  'bhava_arudha',
  'bhava_bala_aspectual',
  'bhava_bala_directional',
  'bhava_bala_lord',
  'bhava_bala_occupant',
  'bhava_bala_positional',
  'bhava_bala_temporal',
  'bhava_bala_total_extended',
  'bhrigu_nadi_point',
  'chandra_bala_natal_baseline',
  'composite_dispositor_strength',
  'conjunction_per_varga',
  'conjunction_within_orb',
  'dhaiya_period',
  'dispositor_chain_per_varga',
  'dosha_fires',
  'dosha_label',
  'eclipse_proximity_natal',
  'esoteric_point_avayogi',
  'esoteric_point_bhrigu_bindu',
  'esoteric_point_brahma',
  'esoteric_point_chatushphuta',
  'esoteric_point_mrityu',
  'esoteric_point_panchasphuta',
  'esoteric_point_pranapada_sphuta',
  'esoteric_point_shiva',
  'esoteric_point_sri_yantra_position',
  'esoteric_point_trikona_dasha_sphuta',
  'esoteric_point_trisphuta',
  'esoteric_point_vishnu',
  'esoteric_point_yogi',
  'graha_avastha_baladi',
  'graha_avastha_deepta',
  'graha_avastha_jagrad',
  'graha_avastha_lajjitadi',
  'graha_avastha_lifetime_exposure_summary',
  'graha_avastha_sayanadi',
  'graha_composite_state_classification',
  'graha_dignity_per_varga',
  'graha_dispositor_chain',
  'graha_effective_dignity_modified_by_aspects',
  'graha_functional_class_per_ascendant',
  'graha_in_house_composite_strength',
  'graha_ishta_phala',
  'graha_kashta_phala',
  'graha_position',
  'graha_saptavargaja_bala_component',
  'graha_shadbala_cheshta',
  'graha_shadbala_dig',
  'graha_shadbala_drik',
  'graha_shadbala_kala',
  'graha_shadbala_naisargika',
  'graha_shadbala_sthana',
  'graha_shadbala_total',
  'graha_sign_attributes',
  'graha_special_state_rollup',
  'graha_tri_deva_role_strength',
  'graha_vargottama_amplification_factor',
  'graha_vimsopaka_dasavarga',
  'graha_vimsopaka_saptavarga',
  'graha_vimsopaka_shadvarga',
  'graha_vimsopaka_shodasavarga',
  'graha_yoga_karaka_flag',
  'house_bhava_bala_subscore',
  'house_bhava_bala_total',
  'house_strength_classification_rollup',
  'jaimini_tri_deva_role_per_graha',
  'janma_shani_period',
  'kala_sarpa_per_varga',
  'kantaka_shani_period',
  'karaka_bhava_concordance',
  'karaka_chara_position',
  'karaka_house_lord_overlap_flag',
  'karaka_web_per_varga',
  'karakamsa_position',
  'karakatva_strength_per_significance',
  'kp_cuspal_significators',
  'kp_ruling_planets_natal',
  'lal_kitab_special_point',
  'lord_aspects_lord_per_varga',
  'lord_in_house_per_varga',
  'maharsi_specific_point',
  'midpoint',
  'nakshatra_cross_ayanamsha',
  'nakshatra_pada_sensitive',
  'panchaka_flag',
  'panchanga_abhijit_muhurta',
  'panchanga_agni_vasa',
  'panchanga_brahma_muhurta',
  'panchanga_calendrical',
  'panchanga_choghadiya_birth',
  'panchanga_disha_shul',
  'panchanga_durmuhurta',
  'panchanga_godhuli_muhurta',
  'panchanga_gulika_kalam',
  'panchanga_hora_birth',
  'panchanga_karana',
  'panchanga_krakaca',
  'panchanga_madhyahna_sandhya',
  'panchanga_nakshatra_moon',
  'panchanga_nakshatra_shoonya_rashi',
  'panchanga_nishita_kala',
  'panchanga_panchaka_classification',
  'panchanga_pratah_sandhya',
  'panchanga_rahu_kalam',
  'panchanga_sashtighati',
  'panchanga_sayam_sandhya',
  'panchanga_solar_context',
  'panchanga_special_yoga_combinations',
  'panchanga_sun_moon_dynamics',
  'panchanga_tithi',
  'panchanga_tithi_shoonya_rashi',
  'panchanga_vara',
  'panchanga_varjyam',
  'panchanga_vijaya_muhurta',
  'panchanga_visha_ghati',
  'panchanga_yamaganda_kalam',
  'panchanga_yamakantaka',
  'panchanga_yoga',
  'parivartana_per_varga',
  'pranic_strength_per_graha',
  'sade_sati_cancellation_check',
  'sade_sati_concurrent_dasha_overlay',
  'sade_sati_cycle',
  'sade_sati_downstream_cross_reference',
  'sade_sati_modifier_overlay',
  'sade_sati_phase',
  'sade_sati_phase_quarter',
  'sade_sati_saturn_retrograde_subset',
  'saham_position',
  'saturn_derived_point',
  'swamsa_position',
  'tajik_hadda_lord',
  'tajik_triraashipathi',
  'tajik_vargottama_specific',
  'tara_bala_natal_baseline',
  'upagraha_position',
  'vargottama_per_varga',
  'vimsopaka_bala_per_graha',
  'virodha_argala_natal_matrix',
  'vishakha_shani_period',
  'yoga_fires',
  'yoga_label',
] as const

export type ChartFactsCategory = (typeof CHART_FACTS_CATEGORIES)[number]

/** Coverage map: category → covering tool URI(s) */
export const CATEGORY_TOOL_COVERAGE: Record<ChartFactsCategory, string[]> = {
  // ── Positions ──────────────────────────────────────────────────────────────
  graha_position:                       ['marsys://tool/L1/get_positions'],
  upagraha_position:                    ['marsys://tool/L1/get_positions'],
  aprakasha_position:                   ['marsys://tool/L1/get_positions'],
  karaka_chara_position:                ['marsys://tool/L1/get_karakas'],
  // W2 structural-close SC-5 (serving-side only, no writer change): real, computed,
  // previously-unserved category; opt-in via categories:["nakshatra_cross_ayanamsha"] on
  // get_positions (not on the default page — see get_positions.ts header comment).
  nakshatra_cross_ayanamsha:            ['marsys://tool/L1/get_positions'],

  // ── Strength / Shadbala ───────────────────────────────────────────────────
  graha_shadbala_cheshta:               ['marsys://tool/L1/get_strength'],
  graha_shadbala_dig:                   ['marsys://tool/L1/get_strength'],
  graha_shadbala_drik:                  ['marsys://tool/L1/get_strength'],
  graha_shadbala_kala:                  ['marsys://tool/L1/get_strength'],
  graha_shadbala_naisargika:            ['marsys://tool/L1/get_strength'],
  graha_shadbala_sthana:                ['marsys://tool/L1/get_strength'],
  graha_shadbala_total:                 ['marsys://tool/L1/get_strength'],
  graha_vimsopaka_dasavarga:            ['marsys://tool/L1/get_strength'],
  graha_vimsopaka_saptavarga:           ['marsys://tool/L1/get_strength'],
  graha_vimsopaka_shadvarga:            ['marsys://tool/L1/get_strength'],
  graha_vimsopaka_shodasavarga:         ['marsys://tool/L1/get_strength'],
  vimsopaka_bala_per_graha:             ['marsys://tool/L1/get_strength'],
  graha_saptavargaja_bala_component:    ['marsys://tool/L1/get_strength'],
  graha_ishta_phala:                    ['marsys://tool/L1/get_strength'],
  graha_kashta_phala:                   ['marsys://tool/L1/get_strength'],
  pranic_strength_per_graha:            ['marsys://tool/L1/get_strength'],
  graha_in_house_composite_strength:    ['marsys://tool/L1/get_strength'],
  graha_composite_state_classification: ['marsys://tool/L1/get_strength'],
  graha_special_state_rollup:           ['marsys://tool/L1/get_strength'],
  graha_yoga_karaka_flag:               ['marsys://tool/L1/get_strength'],
  graha_tri_deva_role_strength:         ['marsys://tool/L1/get_strength'],
  karakatva_strength_per_significance:  ['marsys://tool/L1/get_karakas'],

  // ── Dignity / Sign state ──────────────────────────────────────────────────
  graha_dignity_per_varga:                    ['marsys://tool/L1/get_dignity'],
  graha_effective_dignity_modified_by_aspects:['marsys://tool/L1/get_dignity'],
  graha_sign_attributes:                      ['marsys://tool/L1/get_dignity'],
  graha_vargottama_amplification_factor:      ['marsys://tool/L1/get_dignity'],
  vargottama_per_varga:                       ['marsys://tool/L1/get_dignity'],
  graha_functional_class_per_ascendant:       ['marsys://tool/L1/get_dignity'],

  // ── Ashtakavarga ─────────────────────────────────────────────────────────
  ashtakavarga_bindu:                 ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_anubindu:              ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_pinda_bhinna:          ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_pinda_sarva:           ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_pinda_sodhita:         ['marsys://tool/L1/get_ashtakavarga'],
  // W2 structural-close SC-4 (serving-side only, no writer change — see get_ashtakavarga.ts
  // header comment): these are real, computed, previously-unserved refinement categories.
  ashtakavarga_bindu_sign:            ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_pinda_raasi:           ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_trikona_shodhana:      ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_ekadhipathya_shodhana: ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_kakshya_boundary:      ['marsys://tool/L1/get_ashtakavarga'],
  // opt-in only (not on the default page — large per-varga row sets), reachable via an
  // explicit `categories` request; still genuinely served, per the coverage doctrine (§5.2).
  ashtakavarga_bindu_per_varga:       ['marsys://tool/L1/get_ashtakavarga'],
  ashtakavarga_pinda_sarva_per_varga: ['marsys://tool/L1/get_ashtakavarga'],

  // ── Bhava Bala / House Strength ───────────────────────────────────────────
  bhava_bala_aspectual:             ['marsys://tool/L1/get_bhava_bala'],
  bhava_bala_directional:           ['marsys://tool/L1/get_bhava_bala'],
  bhava_bala_lord:                  ['marsys://tool/L1/get_bhava_bala'],
  bhava_bala_occupant:              ['marsys://tool/L1/get_bhava_bala'],
  bhava_bala_positional:            ['marsys://tool/L1/get_bhava_bala'],
  bhava_bala_temporal:              ['marsys://tool/L1/get_bhava_bala'],
  bhava_bala_total_extended:        ['marsys://tool/L1/get_bhava_bala'],
  house_bhava_bala_subscore:        ['marsys://tool/L1/get_bhava_bala'],
  house_bhava_bala_total:           ['marsys://tool/L1/get_bhava_bala'],
  house_strength_classification_rollup: ['marsys://tool/L1/get_bhava_bala'],

  // ── Aspects ───────────────────────────────────────────────────────────────
  aspect_parashari_given:    ['marsys://tool/L1/get_aspects'],
  aspect_parashari_received: ['marsys://tool/L1/get_aspects'],
  aspect_parashari_per_varga:['marsys://tool/L1/get_aspects'],
  aspect_jaimini:            ['marsys://tool/L1/get_aspects'],
  aspect_jaimini_per_varga:  ['marsys://tool/L1/get_aspects'],
  aspect_matrix_summary:     ['marsys://tool/L1/get_aspects'],
  aspect_tajik:              ['marsys://tool/L1/get_aspects'],
  conjunction_within_orb:    ['marsys://tool/L1/get_aspects'],
  conjunction_per_varga:     ['marsys://tool/L1/get_aspects'],
  lord_aspects_lord_per_varga:['marsys://tool/L1/get_aspects'],
  lord_in_house_per_varga:   ['marsys://tool/L1/get_aspects'],

  // ── Yoga / Dosha ─────────────────────────────────────────────────────────
  yoga_fires:    ['marsys://tool/L1/get_yoga_dosha'],
  yoga_label:    ['marsys://tool/L1/get_yoga_dosha'],
  dosha_fires:   ['marsys://tool/L1/get_yoga_dosha'],
  dosha_label:   ['marsys://tool/L1/get_yoga_dosha'],
  bhadra_flag:   ['marsys://tool/L1/get_yoga_dosha'],
  panchaka_flag: ['marsys://tool/L1/get_yoga_dosha'],

  // ── Argala ────────────────────────────────────────────────────────────────
  argala_natal_matrix:         ['marsys://tool/L1/get_argala'],
  virodha_argala_natal_matrix: ['marsys://tool/L1/get_argala'],

  // ── Dispositors / Parivartana ─────────────────────────────────────────────
  graha_dispositor_chain:     ['marsys://tool/L1/get_dispositors'],
  dispositor_chain_per_varga: ['marsys://tool/L1/get_dispositors'],
  composite_dispositor_strength:['marsys://tool/L1/get_dispositors'],
  parivartana_per_varga:      ['marsys://tool/L1/get_dispositors'],
  kala_sarpa_per_varga:       ['marsys://tool/L1/get_dispositors'],

  // ── Sade Sati + Shani periods ─────────────────────────────────────────────
  sade_sati_cycle:                  ['marsys://tool/L1/get_sade_sati'],
  sade_sati_phase:                  ['marsys://tool/L1/get_sade_sati'],
  sade_sati_phase_quarter:          ['marsys://tool/L1/get_sade_sati'],
  sade_sati_modifier_overlay:       ['marsys://tool/L1/get_sade_sati'],
  sade_sati_cancellation_check:     ['marsys://tool/L1/get_sade_sati'],
  sade_sati_concurrent_dasha_overlay:['marsys://tool/L1/get_sade_sati'],
  sade_sati_downstream_cross_reference:['marsys://tool/L1/get_sade_sati'],
  sade_sati_saturn_retrograde_subset:['marsys://tool/L1/get_sade_sati'],
  janma_shani_period:               ['marsys://tool/L1/get_sade_sati'],
  anumukha_shani_period:            ['marsys://tool/L1/get_sade_sati'],
  ardha_ashtama_shani_period:       ['marsys://tool/L1/get_sade_sati'],
  ashtama_shani_period:             ['marsys://tool/L1/get_sade_sati'],
  dhaiya_period:                    ['marsys://tool/L1/get_sade_sati'],
  vishakha_shani_period:            ['marsys://tool/L1/get_sade_sati'],
  kantaka_shani_period:             ['marsys://tool/L1/get_sade_sati'],

  // ── Panchanga ─────────────────────────────────────────────────────────────
  panchanga_abhijit_muhurta:         ['marsys://tool/L1/get_panchanga'],
  panchanga_agni_vasa:               ['marsys://tool/L1/get_panchanga'],
  panchanga_brahma_muhurta:          ['marsys://tool/L1/get_panchanga'],
  panchanga_calendrical:             ['marsys://tool/L1/get_panchanga'],
  panchanga_choghadiya_birth:        ['marsys://tool/L1/get_panchanga'],
  panchanga_disha_shul:              ['marsys://tool/L1/get_panchanga'],
  panchanga_durmuhurta:              ['marsys://tool/L1/get_panchanga'],
  panchanga_godhuli_muhurta:         ['marsys://tool/L1/get_panchanga'],
  panchanga_gulika_kalam:            ['marsys://tool/L1/get_panchanga'],
  panchanga_hora_birth:              ['marsys://tool/L1/get_panchanga'],
  panchanga_karana:                  ['marsys://tool/L1/get_panchanga'],
  panchanga_krakaca:                 ['marsys://tool/L1/get_panchanga'],
  panchanga_madhyahna_sandhya:       ['marsys://tool/L1/get_panchanga'],
  panchanga_nakshatra_moon:          ['marsys://tool/L1/get_panchanga'],
  panchanga_nakshatra_shoonya_rashi: ['marsys://tool/L1/get_panchanga'],
  panchanga_nishita_kala:            ['marsys://tool/L1/get_panchanga'],
  panchanga_panchaka_classification: ['marsys://tool/L1/get_panchanga'],
  panchanga_pratah_sandhya:          ['marsys://tool/L1/get_panchanga'],
  panchanga_rahu_kalam:              ['marsys://tool/L1/get_panchanga'],
  panchanga_sashtighati:             ['marsys://tool/L1/get_panchanga'],
  panchanga_sayam_sandhya:           ['marsys://tool/L1/get_panchanga'],
  panchanga_solar_context:           ['marsys://tool/L1/get_panchanga'],
  panchanga_special_yoga_combinations:['marsys://tool/L1/get_panchanga'],
  panchanga_sun_moon_dynamics:       ['marsys://tool/L1/get_panchanga'],
  panchanga_tithi:                   ['marsys://tool/L1/get_panchanga'],
  panchanga_tithi_shoonya_rashi:     ['marsys://tool/L1/get_panchanga'],
  panchanga_vara:                    ['marsys://tool/L1/get_panchanga'],
  panchanga_varjyam:                 ['marsys://tool/L1/get_panchanga'],
  panchanga_vijaya_muhurta:          ['marsys://tool/L1/get_panchanga'],
  panchanga_visha_ghati:             ['marsys://tool/L1/get_panchanga'],
  panchanga_yamaganda_kalam:         ['marsys://tool/L1/get_panchanga'],
  panchanga_yamakantaka:             ['marsys://tool/L1/get_panchanga'],
  panchanga_yoga:                    ['marsys://tool/L1/get_panchanga'],

  // ── Sensitive / Esoteric Points ───────────────────────────────────────────
  esoteric_point_avayogi:            ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_bhrigu_bindu:       ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_brahma:             ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_chatushphuta:       ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_mrityu:             ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_panchasphuta:       ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_pranapada_sphuta:   ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_shiva:              ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_sri_yantra_position:['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_trikona_dasha_sphuta:['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_trisphuta:          ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_vishnu:             ['marsys://tool/L1/get_sensitive_points'],
  esoteric_point_yogi:               ['marsys://tool/L1/get_sensitive_points'],
  bhrigu_nadi_point:                 ['marsys://tool/L1/get_sensitive_points'],
  lal_kitab_special_point:           ['marsys://tool/L1/get_sensitive_points'],
  maharsi_specific_point:            ['marsys://tool/L1/get_sensitive_points'],
  midpoint:                          ['marsys://tool/L1/get_sensitive_points'],
  saham_position:                    ['marsys://tool/L1/get_sensitive_points'],
  saturn_derived_point:              ['marsys://tool/L1/get_sensitive_points'],
  nakshatra_pada_sensitive:          ['marsys://tool/L1/get_sensitive_points'],

  // ── Karakas / KP / Jaimini ───────────────────────────────────────────────
  arudha_pada:                   ['marsys://tool/L1/get_karakas'],
  // W2 structural-close S-3 (serving-side only, no writer change — see get_karakas.ts header
  // comment): computed by ga_sensitive_writer.py, previously zero serving route.
  bhava_arudha:                  ['marsys://tool/L1/get_karakas'],
  karakamsa_position:            ['marsys://tool/L1/get_karakas'],
  swamsa_position:               ['marsys://tool/L1/get_karakas'],
  karaka_house_lord_overlap_flag:['marsys://tool/L1/get_karakas'],
  // W2 structural-close SC-5 — opt-in only (large per-varga/per-house-pair row sets), reachable
  // via an explicit `categories` request; still genuinely served, per the coverage doctrine (§5.2).
  karaka_web_per_varga:          ['marsys://tool/L1/get_karakas'],
  karaka_bhava_concordance:      ['marsys://tool/L1/get_karakas'],
  kp_cuspal_significators:       ['marsys://tool/L1/get_karakas'],
  kp_ruling_planets_natal:       ['marsys://tool/L1/get_karakas'],
  jaimini_tri_deva_role_per_graha:['marsys://tool/L1/get_karakas'],

  // ── Avasthas ─────────────────────────────────────────────────────────────
  graha_avastha_baladi:                   ['marsys://tool/L1/get_avasthas'],
  graha_avastha_deepta:                   ['marsys://tool/L1/get_avasthas'],
  graha_avastha_jagrad:                   ['marsys://tool/L1/get_avasthas'],
  graha_avastha_lajjitadi:                ['marsys://tool/L1/get_avasthas'],
  graha_avastha_lifetime_exposure_summary:['marsys://tool/L1/get_avasthas'],
  graha_avastha_sayanadi:                 ['marsys://tool/L1/get_avasthas'],

  // ── Tajik ─────────────────────────────────────────────────────────────────
  tajik_hadda_lord:          ['marsys://tool/L1/get_tajik'],
  tajik_triraashipathi:      ['marsys://tool/L1/get_tajik'],
  tajik_vargottama_specific: ['marsys://tool/L1/get_tajik'],

  // ── Tara / Chandra Bala ───────────────────────────────────────────────────
  chandra_bala_natal_baseline: ['marsys://tool/L1/get_tara_chandra_bala'],
  tara_bala_natal_baseline:    ['marsys://tool/L1/get_tara_chandra_bala'],

  // ── Eclipse / Misc flags ──────────────────────────────────────────────────
  eclipse_proximity_natal: ['marsys://tool/L1/get_eclipse_flags'],
} as const

/** Additional non-chart_facts tables that need retrieval coverage */
export const NON_CHART_FACTS_COVERAGE: Record<string, string[]> = {
  // L1 separate tables
  chart_dashas:               ['marsys://tool/L1/get_dashas'],
  chart_divisionals:          ['marsys://tool/L1/get_divisionals'],
  l1_tajik_varsha_year_lords: ['marsys://tool/L1/get_tajik'],

  // L0 corpus tables
  brahma_yoga_catalog:     ['marsys://tool/L0/query_yoga_catalog'],
  brahma_dosha_catalog:    ['marsys://tool/L0/query_dosha_catalog'],
  brahma_remedy_corpus:    ['marsys://tool/L0/query_remedy_corpus'],
  // Drift fix (W2b Batch 2, TABLE_CONCEPT_DISPOSITIONS_v2_0.md): this previously pointed at
  // query_classical_texts, which queries classical_text_chunks — a DIFFERENT table. Corrected
  // to the new dedicated capability wired for brahma_compendium_index itself.
  brahma_compendium_index: ['marsys://tool/L0/query_compendium_index'],

  // L2 bodha tables (populated after Wave 4)
  bodha_signals:            ['marsys://tool/L2/get_msr_signals'],
  bodha_graph:              ['marsys://tool/L2/get_cgm_nodes'],
  bodha_graph_edges:        ['marsys://tool/L2/get_cgm_edges'],
  bodha_domain_links:       ['marsys://tool/L2/get_cdlm_cells'],
  bodha_remediation:        ['marsys://tool/L2/get_remediation'],
  bodha_resonance:          ['marsys://tool/L2/get_resonance'],
  bodha_signal_embeddings:  ['marsys://tool/L2/get_signal_embeddings'],
  synthesis_quality_scorecard: ['marsys://tool/L2/get_scorecard'],
}
