#!/usr/bin/env python3
"""Mechanically generate the POSITIVE privilege readback for the protected window (steward M20261003T135242-aad6 ruling 1).

Reads the FINAL bytes of the window files, extracts EVERY `GRANT` statement of 1206 §7 (data_plane_builder), 1235 (the three loader roles' EXECUTE on the evidence function) and 1240 §7 (data_plane_builder, gochara_verifier,
gochara_sealer), and writes a read-only SQL query that returns one row per grant that did NOT take (or whose role/object is missing). EXPECT ZERO ROWS; any row
= STOP in checklist row 9 (resolve before accepting the window). It uses has_table_privilege / has_column_privilege / has_function_privilege, so it sees direct,
PUBLIC and inherited paths. Usage:  python3 generate_window_privilege_readback.py <platform/migrations dir> > window_privilege_readback.sql
Self-test (disposable PostgreSQL): tests/test_window_privilege_readback_generator.py."""
import re
import sys
from pathlib import Path

FILES = ("1206_gochara_search_inventory_completeness.sql", "1235_ka_gochara_staged_candidate_evidence_function.sql", "1240_gochara_window_verification_gate.sql")


def strip_comments(sql: str) -> str:
    out, i, in_str = [], 0, False
    while i < len(sql):
        c = sql[i]
        if in_str:
            out.append(c)
            if c == "'":
                if sql[i + 1:i + 2] == "'":
                    out.append("'"); i += 1
                else:
                    in_str = False
        elif c == "'":
            in_str = True; out.append(c)
        elif c == "-" and sql[i + 1:i + 2] == "-":
            while i < len(sql) and sql[i] != "\n":
                i += 1
            continue
        else:
            out.append(c)
        i += 1
    return "".join(out)


def blank_strings(sql: str) -> str:
    """Replace the CONTENT of single-quoted literals with spaces (a `GRANT` inside a RAISE NOTICE message is not a statement)."""
    out, i, in_str = [], 0, False
    while i < len(sql):
        c = sql[i]
        if in_str:
            if c == "'":
                if sql[i + 1:i + 2] == "'":
                    out.append("  "); i += 2; continue
                in_str = False; out.append(c)
            else:
                out.append(" " if c != "\n" else "\n")
        else:
            if c == "'":
                in_str = True
            out.append(c)
        i += 1
    return "".join(out)


def split_top(s: str) -> list[str]:
    parts, depth, cur = [], 0, ""
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur.strip()); cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur.strip())
    return parts


def parse(sql: str) -> list[dict]:
    """Every GRANT as {kind: table|column|function, role, priv, obj, cols?}."""
    items = []
    for m in re.finditer(r"\bGRANT\s+(.+?)\s+ON\s+(FUNCTION\s+|TABLE\s+)?(.+?)\s+TO\s+([a-z_][a-z_0-9]*)\s*;", blank_strings(strip_comments(sql)), re.S | re.I):
        privs, kind, objs, role = m.group(1).strip(), (m.group(2) or "").strip().upper(), m.group(3).strip(), m.group(4)
        if kind == "FUNCTION":
            for sig in split_top(objs):
                items.append({"kind": "function", "role": role, "priv": "EXECUTE", "obj": re.sub(r"\s+", " ", sig)})
            continue
        for tbl in split_top(objs):
            for p in split_top(privs):
                cm = re.match(r"(SELECT|INSERT|UPDATE|REFERENCES)\s*\((.+)\)$", p, re.I)
                if cm:
                    for col in [c.strip() for c in cm.group(2).split(",")]:
                        items.append({"kind": "column", "role": role, "priv": cm.group(1).upper(), "obj": tbl, "col": col})
                else:
                    items.append({"kind": "table", "role": role, "priv": p.upper(), "obj": tbl})
    return items


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def render(items: list[dict]) -> str:
    rows = []
    for it in items:
        rows.append(f"({q(it['kind'])}, {q(it['role'])}, {q(it['priv'])}, {q(it['obj'])}, {q(it.get('col') or '')})")
    values = ",\n  ".join(rows)
    return f"""-- GENERATED by generate_window_privilege_readback.py from the final 1206 §7 and 1240 §7 bytes — {len(items)} grants. READ-ONLY. EXPECT ZERO ROWS (any row = STOP, checklist row 9).
WITH expected(kind, role, priv, obj, col) AS (VALUES
  {values}
), resolved AS (
  SELECT e.*, (SELECT count(*) FROM pg_roles r WHERE r.rolname = e.role) AS role_exists,
         CASE WHEN e.kind IN ('table', 'column') THEN to_regclass(e.obj)::oid END AS rel_oid,
         CASE WHEN e.kind = 'function' THEN to_regprocedure(e.obj)::oid END AS fn_oid
    FROM expected e
)
SELECT kind, role, priv, obj, col,
       CASE WHEN role_exists = 0 THEN 'ROLE MISSING'
            WHEN kind IN ('table', 'column') AND rel_oid IS NULL THEN 'OBJECT MISSING'
            WHEN kind = 'function' AND fn_oid IS NULL THEN 'OBJECT MISSING'
            ELSE 'PRIVILEGE NOT HELD' END AS problem
  FROM resolved
 WHERE role_exists = 0
    OR (kind IN ('table', 'column') AND rel_oid IS NULL)
    OR (kind = 'function' AND fn_oid IS NULL)
    OR (kind = 'table'    AND NOT has_table_privilege(role, rel_oid, priv))
    OR (kind = 'column'   AND NOT has_column_privilege(role, rel_oid, col, priv))
    OR (kind = 'function' AND NOT has_function_privilege(role, fn_oid, 'EXECUTE'))
 ORDER BY role, kind, obj, col;
"""


def main() -> int:
    d = Path(sys.argv[1])
    items = []
    for f in FILES:
        got = parse((d / f).read_text(encoding="utf-8"))
        items += got
    sys.stdout.write(render(items))
    return 0


if __name__ == "__main__":
    sys.exit(main())
