#!/usr/bin/env tsx
/**
 * l1_truth_index.ts — CLI runner for the L1 Truth Index Scorer
 *
 * ICR-S2 (2026-05-21): Reads MSR_v3_0.md, scores each signal for L1
 * (FORENSIC/LEL) grounding, and writes a coverage report.
 *
 * Usage:
 *   tsx platform/scripts/governance/l1_truth_index.ts
 *   npx ts-node --project platform/tsconfig.json platform/scripts/governance/l1_truth_index.ts
 *
 * Exit codes:
 *   0 — coverage ≥ 95% (PASS)
 *   1 — coverage < 95% (FAIL — CI gate)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { parseMsrFile, computeReport } from '../../src/lib/icr/l1_truth_index';

// ─────────────────────────────────────────────────────────────────────────────
// Paths (resolved from repo root — two levels up from scripts/governance/)
// ─────────────────────────────────────────────────────────────────────────────

const SCRIPT_DIR = dirname(new URL(import.meta.url).pathname);
const REPO_ROOT = resolve(SCRIPT_DIR, '..', '..', '..');

const MSR_PATH = resolve(REPO_ROOT, '025_HOLISTIC_SYNTHESIS', 'MSR_v3_0.md');
const REPORT_PATH = resolve(REPO_ROOT, '06_LEARNING_LAYER', 'L1_TRUTH_INDEX_REPORT_v1_0.md');

// ─────────────────────────────────────────────────────────────────────────────
// Run
// ─────────────────────────────────────────────────────────────────────────────

console.log(`[l1_truth_index] Reading MSR from: ${MSR_PATH}`);
const content = readFileSync(MSR_PATH, 'utf-8');

const signals = parseMsrFile(content);
const report = computeReport(signals);

console.log(`[l1_truth_index] Parsed ${report.total_signals} signals`);
console.log(`[l1_truth_index] Grounded: ${report.grounded_signals}`);
console.log(`[l1_truth_index] Ungrounded: ${report.ungrounded_signals}`);
console.log(`[l1_truth_index] Coverage: ${report.coverage_score}%`);
console.log(`[l1_truth_index] Gate (≥95%): ${report.passes_gate ? 'PASS' : 'FAIL'}`);

// ─────────────────────────────────────────────────────────────────────────────
// JSON summary to stdout
// ─────────────────────────────────────────────────────────────────────────────

console.log('\n--- JSON SUMMARY ---');
console.log(JSON.stringify({
  total_signals: report.total_signals,
  grounded_signals: report.grounded_signals,
  ungrounded_signals: report.ungrounded_signals,
  coverage_score: report.coverage_score,
  passes_gate: report.passes_gate,
}, null, 2));

// ─────────────────────────────────────────────────────────────────────────────
// Markdown report
// ─────────────────────────────────────────────────────────────────────────────

const ungroundedList = report.ungrounded_ids.length === 0
  ? '_None — all signals are L1-grounded._'
  : report.ungrounded_ids.map((id) => `- ${id}`).join('\n');

const passLabel = report.passes_gate ? 'PASS' : 'FAIL';

const reportMd = `---
artifact: L1_TRUTH_INDEX_REPORT_v1_0.md
version: "1.0"
status: CURRENT
authored_by: icr-s2-scorer
authored_at: 2026-05-21
---

# L1 Truth Index Report — ICR-S2

## Summary

| Metric | Value |
|---|---|
| total_signals | ${report.total_signals} |
| grounded_signals | ${report.grounded_signals} |
| ungrounded_signals | ${report.ungrounded_signals} |
| coverage_score | ${report.coverage_score}% |
| gate_threshold | 95% |
| gate_result | **${passLabel}** |

A signal is grounded if its block contains at least one citation to:
\`FORENSIC\`, \`FORENSIC_ASTROLOGICAL_DATA_v8_0\`, \`LIFE_EVENT_LOG\`, \`LEL\` (word-bounded),
a \`LEL.<CATEGORY>.<N>\` event ID, or an \`EVT.YYYY\` life-event log reference.

## Ungrounded Signal IDs (${report.ungrounded_ids.length})

${ungroundedList}

---

_Generated by \`platform/scripts/governance/l1_truth_index.ts\` on 2026-05-21 (ICR-S2)._
`;

mkdirSync(dirname(REPORT_PATH), { recursive: true });
writeFileSync(REPORT_PATH, reportMd, 'utf-8');
console.log(`\n[l1_truth_index] Report written to: ${REPORT_PATH}`);

// ─────────────────────────────────────────────────────────────────────────────
// Exit code
// ─────────────────────────────────────────────────────────────────────────────

process.exit(report.passes_gate ? 0 : 1);
