"""
tests/l3/ka_kshetra/golden_fixtures/__init__.py
Loads the frozen sampled-engine fixture snapshots for parity testing.

These fixtures were generated by generate_golden_fixtures.py and are the
FROZEN ground truth for the DHĀRĀ analytic-engine parity harness.
When the analytic DHĀRĀ engine is built, its outputs are compared against
the values in sampled_engine_v1_fixtures.json.

── KEY DESIGN PROPERTIES ────────────────────────────────────────────────────
• Engine: sampled (§5.2 log-linear segments + §5.5 circular-shift null)
• Engine version: 3
• Charts: native (482012f1-…) + abhinandan-1c826d5a
• Classes: career_change, marriage, relocation (+ edge cases)
• Decades: 0=[0,3650], 1=[3650,7300], 2=[7300,10950] days
• Edge cases captured:
    suppression_active — windows with active vedha at t_peak
    empty_class (rare_event) — ClassSkipped, skipped=True
    zero_weight_clocks — all w_s=0, zero_weight_clocks=True

── FIXTURE KEY FORMAT ────────────────────────────────────────────────────────
    '{chart_id}:{event_class}:{decade_index}'

Authority: SAMPŪRTI-Δ2 task brief; KALA_W2_FIELD_DESIGN_v1_0.md §5.1–§5.5.
"""
from __future__ import annotations

import json
from pathlib import Path

_FIXTURE_PATH = Path(__file__).parent / 'sampled_engine_v1_fixtures.json'


def load_golden_fixtures() -> dict:
    """Load the frozen sampled-engine output fixtures.

    Returns the full JSON object with keys:
        'meta'     — generation metadata (engine, version, generated_at, …)
        'fixtures' — dict keyed by '{chart_id}:{event_class}:{decade_index}'
    """
    with open(_FIXTURE_PATH, encoding='utf-8') as f:
        return json.load(f)


def get_fixture(chart_id: str, event_class: str, decade_index: int) -> dict:
    """Get a specific fixture by chart, class, and decade index (0-based).

    Raises KeyError when the combination is not in the fixture file — the
    honest signal that a fixture was not generated, not a silent None.
    """
    data = load_golden_fixtures()
    key = f'{chart_id}:{event_class}:{decade_index}'
    return data['fixtures'][key]


__all__ = ['load_golden_fixtures', 'get_fixture']
