-- =============================================================================
-- DRAFT_NEEDS_NUMBER_l0_bg_nakshatra_citation_curation.sql      (HELD DRAFT: NOT APPLIED, NOT A MIGRATION)
-- Lane: curation-lane (Exec Suvarna), branch suvarna/land/TI-curation-001, N-101 curation of bg_nakshatra.
-- SS allocates the migration number (block 1200-1299).  Citation TEXT only: 521 rows across 15 table(s);
-- no value, key or other column changes.  Every proposed citation is chunk-level (corpus chunk id + page + printed
-- sloka) and each row's FACT/INFERENCE class and supporting quote are in the ledger
-- (assets/bg_nakshatra_ledger.json); rows the held text CONTRADICTS are not touched (acharya batch).
-- GUARDS  per-table md5 fingerprint of every non-timestamp column must equal the pinned pre-state; every UPDATE
--         matches natural key AND exact old citation and must hit the exact expected row count; post-state
--         fingerprints are pinned; the stored integrity_check_sql is pinned by md5 and resealed (each sha256/md5 literal replaced by the value computed on the test replica after the UPDATEs); it must read true afterwards;
--         idempotent: a second apply is a NOTICE + no-op.
-- Seed parity (NOT patched here; follow-up after SS review and PR #2984): platform/python-sidecar/brahmagyan/l0_nakshatra.py (delete-then-insert of the three tables)
--         must carry the same citations or the next L0 rebuild reverts them; editing it also stales
--         nirmana-writer-digests.json (a #2984 file).
-- =============================================================================

DO $curation$
DECLARE
  n integer;
  ic text;
  ok boolean;
  fp_0 text;
  fp_1 text;
  fp_2 text;
BEGIN
  SELECT integrity_check_sql INTO ic FROM asset_registry WHERE asset_id = 'bg_nakshatra' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'curation refuses: asset_registry row bg_nakshatra not found'; END IF;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY nakshatra_id::text COLLATE "C"), '')) FROM reference_nakshatra t$q$ INTO fp_0;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY nakshatra_id::text COLLATE "C"), '')) FROM reference_nakshatra_pada t$q$ INTO fp_1;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY id::text COLLATE "C"), '')) FROM reference_nakshatra_matrix t$q$ INTO fp_2;
  IF fp_0 = '6fa93a906b8ccdcd06d7f327243ab223' AND fp_1 = 'b13cacb9ae130e03c5061d41b6f936fd' AND fp_2 = '94b383d5bebeca6900475bc6a3a4b18d' THEN
    IF NOT (position('bb322e6c4f72d395f4119e9a59bf3a4c13354d963a3682d15d73c3d410e43e95' IN ic) > 0 AND position('a24f56a803edcbd1c375e6a9169da0a4d8992fb524ab19adf28184d356f3a556' IN ic) > 0 AND position('63c18350a0b2375e0066d3886a54b1b997b7844956fc47b7d063678311d06fbc' IN ic) > 0) THEN RAISE EXCEPTION 'curation refuses: tables are at the curated content but the registry contract is not resealed'; END IF;
    RAISE NOTICE 'curation already applied: no-op';
    RETURN;
  END IF;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY nakshatra_id::text COLLATE "C"), '')) FROM reference_nakshatra t$q$ INTO fp_0;
  IF fp_0 IS DISTINCT FROM 'bc88d67b7f97022edbd3cdc33be9e6d8' THEN RAISE EXCEPTION 'curation refuses: reference_nakshatra is not the pinned pre-state (%)', fp_0; END IF;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY nakshatra_id::text COLLATE "C"), '')) FROM reference_nakshatra_pada t$q$ INTO fp_1;
  IF fp_1 IS DISTINCT FROM '7657a172a49be20a7276e4635d0645f3' THEN RAISE EXCEPTION 'curation refuses: reference_nakshatra_pada is not the pinned pre-state (%)', fp_1; END IF;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY id::text COLLATE "C"), '')) FROM reference_nakshatra_matrix t$q$ INTO fp_2;
  IF fp_2 IS DISTINCT FROM '751b9dbfe4316739d52815af08e3eb7e' THEN RAISE EXCEPTION 'curation refuses: reference_nakshatra_matrix is not the pinned pre-state (%)', fp_2; END IF;
  IF md5(ic) IS DISTINCT FROM '3a1bc82c78ed3f79aae62d18a4d29f0e' THEN RAISE EXCEPTION 'curation refuses: registry integrity_check_sql is not the pinned pre-state text (md5 mismatch)'; END IF;

  UPDATE reference_nakshatra t SET classical_source = v.new_c
    FROM (VALUES
      ($c$2$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$3$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$5$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$11$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$13$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$14$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$15$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$20$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$23$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$),
      ($c$25$c$, $c$bphs:ch92$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509-510 (nakshatra/rasi table; 13°20' per nakshatra) — bphs:PG501:C1, bphs:PG501:C2, bphs:PG502:C1 ; BPHS (Santhanam trans.), Ch.46 as printed, printed p.508 (Table of Dasas, nakshatra->Dasa lord) — bphs:PG500:C1; Brihat Jataka Ch.XVI (nakshatra rulers) — brihat_jataka:PG343:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Nakshatra-prakarana (Prakarana 2), Sloka 1 as printed — muhurta_chintamani:PG36:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Slokas 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG96:C2, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 2-8 as printed — muhurta_chintamani:PG37:C2, muhurta_chintamani:PG38:C1 (Mahidhara bhasha tika, Khemraj ed.) ; Muhurta-Cintamani, Prakarana 2, Slokas 59-60 as printed — muhurta_chintamani:PG54:C2, muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.) ; BPHS (Santhanam trans.), Gandanta chapter, Sloka 3 as printed — bphs:PG1018:C1; Muhurta-Cintamani, Vivaha-prakarana, Sloka 43 as printed — muhurta_chintamani:PG102:C1 ; Muhurta-Cintamani, Prakarana 2, Sloka 48 as printed (Moon in Pisces/Aquarius = panchaka) — muhurta_chintamani:PG51:C1$c$)
    ) AS v(nakshatra_id, old_c, new_c)
    WHERE t.nakshatra_id::text = v.nakshatra_id AND t.classical_source = v.old_c;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 10 THEN RAISE EXCEPTION 'curation expected 10 reference_nakshatra rows, updated %', n; END IF;
  UPDATE reference_nakshatra_pada t SET classical_source = v.new_c
    FROM (VALUES
      ($c$1$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$2$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$3$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$4$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$5$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$7$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$8$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$9$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.)$c$),
      ($c$10$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$11$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.)$c$),
      ($c$12$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$13$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$14$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$15$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$16$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$17$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$18$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$19$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.)$c$),
      ($c$20$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$21$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$23$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$24$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.) ; Muhurta-Cintamani, Prakarana 2, Nakshatra-chakra after Sloka 60 — muhurta_chintamani:PG55:C1 (Mahidhara bhasha tika, Khemraj ed.; OCR-damaged chart)$c$),
      ($c$25$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.)$c$),
      ($c$26$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.)$c$),
      ($c$27$c$, $c$bphs:ch92 + muhurta_chintamani:ch7$c$, $c$BPHS (Santhanam trans.), Ch.46 as printed, p.509 — bphs:PG501:C1 (4 padas of 3°20' each); BPHS navamsa-pada rule, Ch.46 as printed, p.537 — bphs:PG529:C1; BPHS Ch.6 (navamsa construction) — bphs:PG71:C1; Brihat Jataka Ch.I, Sloka 6 as printed — brihat_jataka:PG41:C1 (Sastri trans., 2nd ed.)$c$)
    ) AS v(nakshatra_id, old_c, new_c)
    WHERE t.nakshatra_id::text = v.nakshatra_id AND t.classical_source = v.old_c;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 100 THEN RAISE EXCEPTION 'curation expected 100 reference_nakshatra_pada rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 29-30 as printed — muhurta_chintamani:PG95:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='gana_kuta' and from_key=to_key) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 3 THEN RAISE EXCEPTION 'curation expected 3 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 34 as printed — muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='nadi_kuta' and from_key=to_key) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 3 THEN RAISE EXCEPTION 'curation expected 3 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 21, 34 as printed — muhurta_chintamani:PG93:C1, muhurta_chintamani:PG97:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='nadi_kuta' and from_key<>to_key) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 6 THEN RAISE EXCEPTION 'curation expected 6 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='yoni_kuta' and relation_value='same_yoni') AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 14 THEN RAISE EXCEPTION 'curation expected 14 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 25-26 as printed — muhurta_chintamani:PG94:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='yoni_kuta' and relation_value='enemy') AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 14 THEN RAISE EXCEPTION 'curation expected 14 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 24 (tika mark; verse-line OCR reads 27) as printed — muhurta_chintamani:PG93:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='tara_kuta' and substring(notes from 'pos=([0-9]+)')::int in (3,5,7)) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 243 THEN RAISE EXCEPTION 'curation expected 243 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 22 as printed — muhurta_chintamani:PG93:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='varna_kuta' and from_key in ('Brahmin','Kshatriya','Vaishya','Shudra') and to_key in ('Brahmin','Kshatriya','Vaishya','Shudra')) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 16 THEN RAISE EXCEPTION 'curation expected 16 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 27-28 as printed — muhurta_chintamani:PG94:C1, muhurta_chintamani:PG94:C2 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='graha_maitri_kuta' and from_key<>to_key and relation_value='friend_friend') AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 12 THEN RAISE EXCEPTION 'curation expected 12 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 27-28 as printed — muhurta_chintamani:PG94:C1, muhurta_chintamani:PG94:C2 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='graha_maitri_kuta' and from_key<>to_key and relation_value in ('friend_neutral','neutral_friend')) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 8 THEN RAISE EXCEPTION 'curation expected 8 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 27-28 as printed — muhurta_chintamani:PG94:C1, muhurta_chintamani:PG94:C2 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='graha_maitri_kuta' and from_key<>to_key and relation_value='neutral_neutral') AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 4 THEN RAISE EXCEPTION 'curation expected 4 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 27-28 as printed — muhurta_chintamani:PG94:C2 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='graha_maitri_kuta' and from_key<>to_key and relation_value='enemy_enemy') AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 4 THEN RAISE EXCEPTION 'curation expected 4 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 31 as printed — muhurta_chintamani:PG96:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='bhakoot_kuta' and ((relation_value='5/7' and from_key::int%2=0) or (relation_value='7/5' and from_key::int%2=1))) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 12 THEN RAISE EXCEPTION 'curation expected 12 reference_nakshatra_matrix rows, updated %', n; END IF;
  UPDATE reference_nakshatra_matrix t SET classical_source = $c$Muhurta-Cintamani, Vivaha-prakarana (Prakarana 6), Sloka 21, 31 as printed — muhurta_chintamani:PG93:C1, muhurta_chintamani:PG96:C1 (Mahidhara bhasha tika, Khemraj ed.)$c$
    WHERE t.id IN (select id from reference_nakshatra_matrix where matrix_type='bhakoot_kuta' and relation_value not in ('1/11','11/1','4/8','8/4','5/7','7/5')) AND t.classical_source = $c$bphs:ch73$c$;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 72 THEN RAISE EXCEPTION 'curation expected 72 reference_nakshatra_matrix rows, updated %', n; END IF;

  -- post-flight
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY nakshatra_id::text COLLATE "C"), '')) FROM reference_nakshatra t$q$ INTO fp_0;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY nakshatra_id::text COLLATE "C"), '')) FROM reference_nakshatra_pada t$q$ INTO fp_1;
  EXECUTE $q$SELECT md5(COALESCE(string_agg((to_jsonb(t) - ARRAY[$v$created_at$v$]::text[])::text, E'\n' ORDER BY id::text COLLATE "C"), '')) FROM reference_nakshatra_matrix t$q$ INTO fp_2;
  IF fp_0 IS DISTINCT FROM '6fa93a906b8ccdcd06d7f327243ab223' THEN RAISE EXCEPTION 'curation post-flight: reference_nakshatra content fingerprint mismatch (%)', fp_0; END IF;
  IF fp_1 IS DISTINCT FROM 'b13cacb9ae130e03c5061d41b6f936fd' THEN RAISE EXCEPTION 'curation post-flight: reference_nakshatra_pada content fingerprint mismatch (%)', fp_1; END IF;
  IF fp_2 IS DISTINCT FROM '94b383d5bebeca6900475bc6a3a4b18d' THEN RAISE EXCEPTION 'curation post-flight: reference_nakshatra_matrix content fingerprint mismatch (%)', fp_2; END IF;

  -- reseal the stored integrity contract (its sha256 covers the changed tables)
  UPDATE asset_registry SET integrity_check_sql = replace(replace(replace(integrity_check_sql, 'bbbf686205c208efe0a7f6dbd192b27e63931a9b37f442d194d8d17b72ee3fde', 'bb322e6c4f72d395f4119e9a59bf3a4c13354d963a3682d15d73c3d410e43e95'), '09eeb0e2027486201274b36427a17cee7eb1c60eceb3c3bf334c53b6fbc990a9', 'a24f56a803edcbd1c375e6a9169da0a4d8992fb524ab19adf28184d356f3a556'), '143ce4a335d0cc7fac4b7bb3137c713c238e7f6b06f2477d7ecf7aa14d88d9bb', '63c18350a0b2375e0066d3886a54b1b997b7844956fc47b7d063678311d06fbc') WHERE asset_id = 'bg_nakshatra';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'curation expected 1 registry row, updated %', n; END IF;
  SELECT integrity_check_sql INTO ic FROM asset_registry WHERE asset_id = 'bg_nakshatra';
  IF ic IS NOT NULL THEN
    EXECUTE ic INTO ok;
    IF ok IS NOT TRUE THEN RAISE EXCEPTION 'curation post-flight: bg_nakshatra stored integrity_check_sql reads false'; END IF;
  END IF;
END
$curation$;
