#!/usr/bin/env node
/**
 * generate_completeness_accounting.mjs - Elevation Campaign v2.1, Stream gamma (PURNA), Lane Omega-3.
 *
 * The Completeness Contract generator. Implements C7's `AccountingInvariantResult` type
 * (see ~/elev-v2-shared/contracts/C7_ACCOUNTING_INVARIANT_v1_0.md) exactly: for a given
 * (chart_id, domain) it computes the domain's TCI slice S, produces exactly one
 * `ConceptAccountingRow` per concept in S, assigns each to one of the five accounting states,
 * resolves real per-chart evidence PKs for served rows, and computes `pass` per C7's formula.
 *
 * INPUTS (upstream, read-only; both independently generated by Omega-1/Omega-2):
 *   - TOTAL_CONCEPT_INVENTORY_v1_0.json  (Omega-1, elev/gamma-Omega-tci)      - 14,073 concepts
 *   - DOMAIN_RELEVANCE_MAP_v1_0.json     (Omega-2, elev/gamma-Omega-relevance) - 14,073 rows
 * Paths default to the sibling worktrees but are overridable via env (TCI_PATH / RELEVANCE_PATH)
 * so the script keeps working once the branches merge and both artifacts land under this lane's
 * own capability_map/ directory.
 *
 * STATE ASSIGNMENT (per the Omega-3 brief + C7):
 *   row_count_per_canonical_chart[chart] > 0                              -> served
 *   row_count === 0 (or absent) AND computed_globally === true            -> empty_for_this_chart
 *   computed_globally === false                                          -> not_computed_globally
 *   superseded_by_aggregate  -> INTENTIONALLY UNUSED (see SUPERSEDED_NOTE below)
 *   excluded_by_named_rule   -> MUST NOT appear when auditing a slice S (C7 rule 2)
 *
 * EVIDENCE (C7 evidence table + rule 3):
 *   served               -> { tool, fact_ids }  fact_ids are REAL per-chart PKs resolved fresh
 *                           from the DB (chart_facts.fact_id or the owning L2+ table's PK), so
 *                           rule 3 ("fact_ids must resolve back to real ... values") holds by
 *                           construction. A served concept whose serving filter resolves to no
 *                           DB rows is recorded as an UNRESOLVED served row (fact_ids: []) and
 *                           counted honestly - it fails the evidence check and drops `pass`.
 *   empty_for_this_chart -> { fact_ids: [] }     query ran, zero rows for this chart (field present).
 *   not_computed_globally-> {}                   no evidence field required by C7.
 *
 * DB access: no local DATABASE_URL / pg module in this tree, so we shell out to `psql`
 * (the same 127.0.0.1:5433/amjis instance the postgres MCP uses). Connection comes from
 * env DATABASE_URL (required at run time; never hard-coded into this artifact).
 *
 * OUTPUTS (this lane's manifest scope, capability_map/**):
 *   COMPLETENESS_ACCOUNTING_<domain>_<chart8>_v1_0.json  (4 files, full AccountingInvariantResult)
 *   COMPLETENESS_ACCOUNTING_SUMMARY_v1_0.json            (the 4 headline results, no rows)
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '../../..');            // .../gamma-lane-omega-completeness
const WORKTREES = resolve(REPO, '..');                  // .../.worktrees

// ---- config -------------------------------------------------------------
const CHART_PRIMARY = '482012f1-710e-4a25-994a-93821f5871aa';
const CHART_SECOND  = '1c826d5a-41cb-4450-b4dc-59d440e5f75a';
const CHARTS = [CHART_PRIMARY, CHART_SECOND];
const DOMAINS = ['wealth', 'career'];
const GLOBAL = '__global__';

const CAP_MAP = join(REPO, '00_ARCHITECTURE/llm_consumption_audit/capability_map');

function firstExisting(cands) { return cands.find((p) => p && existsSync(p)); }
const TCI_PATH = process.env.TCI_PATH || firstExisting([
  join(CAP_MAP, 'TOTAL_CONCEPT_INVENTORY_v1_0.json'),
  join(WORKTREES, 'gamma-lane-omega-tci/00_ARCHITECTURE/llm_consumption_audit/capability_map/TOTAL_CONCEPT_INVENTORY_v1_0.json'),
]);
const RELEVANCE_PATH = process.env.RELEVANCE_PATH || firstExisting([
  join(CAP_MAP, 'DOMAIN_RELEVANCE_MAP_v1_0.json'),
  join(WORKTREES, 'gamma-lane-omega-relevance/00_ARCHITECTURE/llm_consumption_audit/capability_map/DOMAIN_RELEVANCE_MAP_v1_0.json'),
]);
const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) throw new Error('DATABASE_URL env is required (psql connection to the amjis DB)');

// ---- primary keys of every table a served concept can resolve against ----
// discovered via information_schema PRIMARY KEY constraints (Omega-3 setup step).
const PK = {
  chart_facts: 'fact_id',
  chart_dashas: 'dasha_row_id',
  chart_divisionals: 'id',
  asset_registry: 'asset_id',
  bodha_msr_signals: 'signal_id',
  bodha_mechanisms: 'mechanism_id',
  bodha_cgm_edges: 'edge_id',
  bodha_cgm_nodes: 'node_id',
  bodha_cgm_motifs: 'motif_id',
  bodha_cgm_paths: 'path_id',
  bodha_cgm_sub_graphs: 'subgraph_id',
  bodha_cdlm_pattern_clusters: 'pattern_id',
  bodha_cdlm_chart_summary: 'summary_id',
  bodha_convergence: 'convergence_id',
  bodha_discoveries: 'discovery_id',
  bodha_anomalies: 'anomaly_id',
  bodha_contradictions: 'contradiction_id',
  bodha_pratijna: 'pratijna_id',
  bodha_question_lenses: 'lens_id',
  bodha_rm_remedy_prescriptions: 'prescription_id',
  bodha_spine_bundles: 'id',
  kala_avadhi: 'avadhi_id',
  kala_activation: 'id',
  kala_bhavishya: 'id',
  kala_convergence: 'convergence_id',
  kala_gochara_windows: 'id',
  kala_jivana_parva: 'id',
  kala_obstruction: 'id',
  kala_taranga: 'taranga_id',
  phala_anchors: 'anchor_id',
  phala_muhurta: 'muhurta_id',
  phala_phaladesa: 'phaladesa_id',
  phala_pramana: 'pramana_id',
  phala_sankrama: 'sankrama_id',
  phala_sodhana: 'sodhana_id',
  mimamsa_insight_units: 'insight_id',
  mimamsa_predictions: 'prediction_id',
  mimamsa_signal_families: 'family_id',
  mimamsa_discoveries: 'discovery_id',
  mimamsa_calibration: 'match_id',
  mimamsa_attribution: 'match_id',
  mimamsa_manifestation_grammar: 'channel_id',
};

// ---- SUPERSEDED_NOTE ----------------------------------------------------
// C7's `superseded_by_aggregate` requires a concept whose information is *strictly* subsumed by
// another served concept that *cites* it (C7's own AV per-varga -> cross-varga-summary exemplar).
// The TCI does not carry the citation/subsumption edges needed to *prove* strict + cited
// subsumption; structural resemblance alone (e.g. per-varga divisional rows vs the ALL_VARGAS
// aggregate marker, or per-level dasha rows vs the whole-system concept) does NOT meet that bar -
// a summary marker does not strictly contain each detail row's full information, and none of these
// carry an explicit "subsumes + cites" edge in the inventory. Per the Omega-3 brief's guidance
// ("if you can't confidently identify genuine subsumption ... leave this category thin/empty rather
// than force matches, but DOCUMENT that choice"), this generator assigns ZERO rows to
// superseded_by_aggregate. Every candidate concept is instead accounted honestly by its own
// row_count (served / empty / not_computed). This never creates an unaccounted concept, so `pass`
// is unaffected by the choice.
const SUPERSEDED_NOTE =
  'superseded_by_aggregate intentionally empty: TCI lacks the citation/subsumption edges to prove ' +
  "C7's strict-and-cited subsumption bar; forcing structural matches would fabricate the state. " +
  'Candidates accounted honestly by their own row_count instead.';

// ---- helpers ------------------------------------------------------------
function log(...a) { process.stderr.write(a.join(' ') + '\n'); }

function psqlJson(sql) {
  const out = execFileSync('psql', [DB_URL, '-tAc', sql], {
    encoding: 'utf8', maxBuffer: 512 * 1024 * 1024,
  }).trim();
  if (!out) return [];
  return JSON.parse(out);
}

// canonicalise a filter value so JSON-encoded axis values (e.g. '{"domains": []}') match the DB's
// text rendering regardless of whitespace.
function canonVal(v) {
  if (v === null || v === undefined) return '\\u0000NULL';
  const s = String(v);
  try { return JSON.stringify(JSON.parse(s)); } catch { return s; }
}
const SEP = '\\u0001'; // U+0001 composite-key separator

// Map a concept to its resolution descriptor: { table, cols:[{name,val}], aggregate }.
// Returns null when the concept is not chart-resolvable (should not happen for served concepts).
function resolutionFor(entry) {
  const ax = entry.source_axis || '';
  const args = entry.serving_args || {};
  if (ax.startsWith('axis:')) {
    const body = ax.slice('axis:'.length);          // e.g. bodha_msr_signals.signal_type_id
    const dot = body.indexOf('.');
    const table = body.slice(0, dot);
    const col = body.slice(dot + 1);
    return { table, cols: [{ name: col, val: args[col] }] };
  }
  if (ax.startsWith('L1:chart_facts')) {
    // The DB COLUMN is `fact_category`; the live-tool PARAM (and thus the TCI serving_args key,
    // post Ω8-fixup) is `category`. Accept either serving_args key so this resolver keeps working
    // both before and after the Ω8 TCI serving_args rename (fact_category -> category).
    return { table: 'chart_facts', cols: [{ name: 'fact_category', val: args.category ?? args.fact_category }] };
  }
  if (ax.startsWith('meta:chart_facts')) {
    return { table: 'chart_facts', cols: [{ name: 'ayanamsha_id', val: args.ayanamsha_id }] };
  }
  if (ax.startsWith('L2:bodha_mechanisms')) {
    return { table: 'bodha_mechanisms', cols: [{ name: 'mechanism_class', val: args.mechanism_class }] };
  }
  if (ax.indexOf('chart_dashas(system') !== -1 && ax.indexOf('level') !== -1) {
    return { table: 'chart_dashas', cols: [
      { name: 'system_id', val: args.system_id }, { name: 'level_n', val: args.level_n },
    ] };
  }
  if (ax.startsWith('L3:chart_dashas')) {
    return { table: 'chart_dashas', cols: [{ name: 'system_id', val: args.system_id }], aggregate: true };
  }
  if (ax.startsWith('L1:chart_divisionals')) {
    return { table: 'chart_divisionals', cols: [{ name: 'varga', val: args.varga }] };
  }
  if (ax.startsWith('meta:asset_registry')) {
    return { table: 'asset_registry', cols: [{ name: 'asset_id', val: args.asset_id }] };
  }
  return null;
}

// stable key for a resolution SHAPE (table + grouping columns + aggregate flag) so that two
// different grouping shapes on the same table get separate indexes.
function shapeKey(r) { return `${r.table}|${r.cols.map((c) => c.name).join(',')}|${r.aggregate ? 'agg' : 'exact'}`; }

// ---- load inputs --------------------------------------------------------
log(`TCI:        ${TCI_PATH}`);
log(`RELEVANCE:  ${RELEVANCE_PATH}`);
if (!TCI_PATH || !RELEVANCE_PATH) throw new Error('Missing TCI or relevance-map input');

const tci = JSON.parse(readFileSync(TCI_PATH, 'utf8'));
const rel = JSON.parse(readFileSync(RELEVANCE_PATH, 'utf8'));
const tciById = new Map(tci.entries.map((e) => [e.concept_id, e]));
log(`loaded TCI entries=${tci.entries.length}  relevance entries=${rel.entries.length}`);

// slice rule: concept relevant to domain iff NOT domain_agnostic AND domain key present in domains.
const sliceCache = {};
function sliceFor(domain) {
  if (!sliceCache[domain]) {
    sliceCache[domain] = rel.entries
      .filter((e) => !e.domain_agnostic && e.domains && Object.prototype.hasOwnProperty.call(e.domains, domain))
      .map((e) => e.concept_id);
  }
  return sliceCache[domain];
}

function stateFor(entry, chart) {
  const rc = entry.row_count_per_canonical_chart || {};
  const n = rc[chart];
  if (typeof n === 'number' && n > 0) return 'served';
  if (entry.computed_globally === true) return 'empty_for_this_chart';
  return 'not_computed_globally';
}

// ---- gather every table we must query, from served concepts across all runs ----
const needTables = new Set();
const needShapes = new Map(); // shapeKey -> resolution descriptor
for (const domain of DOMAINS) {
  for (const cid of sliceFor(domain)) {
    const e = tciById.get(cid);
    if (!e) continue;
    let anyServed = false;
    for (const chart of CHARTS) { if (stateFor(e, chart) === 'served') anyServed = true; }
    if (!anyServed) continue;
    const r = resolutionFor(e);
    if (r) { needTables.add(r.table); needShapes.set(shapeKey(r), r); }
  }
}
log(`tables to resolve: ${[...needTables].sort().join(', ')}`);
log(`resolution shapes: ${needShapes.size}`);

// ---- discover which of the needed tables are chart-scoped ---------------
const hasChartId = {};
if (needTables.size) {
  const inList = [...needTables].map((t) => `'${t}'`).join(',');
  const rows = psqlJson(
    `SELECT COALESCE(json_agg(t), '[]') FROM (` +
    `SELECT table_name, bool_or(column_name='chart_id') AS has_chart ` +
    `FROM information_schema.columns WHERE table_name IN (${inList}) GROUP BY table_name) t`);
  for (const r of rows) hasChartId[r.table_name] = r.has_chart === true;
}
const chartScoped = (t) => hasChartId[t] === true;

// ---- build the per-(shape,chartKey) resolution index --------------------
// A single table can carry MULTIPLE grouping shapes (e.g. chart_dashas is grouped by
// system_id alone for whole-system concepts AND by (system_id, level_n) for per-level concepts),
// so the index is keyed by the shape (table + grouping columns), never by table alone.
// resolutionIndex[shapeKey][chartKey] = Map(canonKey -> pk[]); chartKey is a real chart_id for
// chart-scoped tables, GLOBAL for global reference tables (no chart_id column).
const resolutionIndex = {};
for (const [sk, r] of needShapes.entries()) {
  const table = r.table;
  const pk = PK[table];
  if (!pk) { log(`WARN no PK known for table ${table} - served rows on it cannot resolve`); continue; }
  const cols = r.cols.map((c) => c.name);
  resolutionIndex[sk] = {};
  const colSel = cols.map((c) => `${c}::text AS ${c}`).join(', ');
  const groupBy = cols.map((_, i) => i + 1).join(', ');
  const chartKeys = chartScoped(table) ? CHARTS : [GLOBAL];
  for (const chartKey of chartKeys) {
    const where = chartKey === GLOBAL ? '' : `WHERE chart_id = '${chartKey}'`;
    const sql =
      `SELECT ${colSel}, (array_agg(${pk}::text ORDER BY ${pk}))[1:3] AS pks ` +
      `FROM ${table} ${where} GROUP BY ${groupBy}`;
    const rows = psqlJson(`SELECT COALESCE(json_agg(t), '[]') FROM (${sql}) t`);
    const m = new Map();
    for (const row of rows) m.set(cols.map((c) => canonVal(row[c])).join(SEP), row.pks || []);
    resolutionIndex[sk][chartKey] = m;
  }
  log(`resolved ${sk} -> pk ${pk} scoped=${chartScoped(table)} agg=${!!r.aggregate} ` +
      `(groups ${chartKeys.map((k) => resolutionIndex[sk][k].size).join('/')})`);
}

// resolve a served concept -> { pks, reason }
function resolvePks(entry, chart) {
  const r = resolutionFor(entry);
  if (!r) return { pks: [], reason: 'no_resolution_mapping' };
  const idx = resolutionIndex[shapeKey(r)];
  if (!idx) return { pks: [], reason: `no_index_for_shape:${shapeKey(r)}` };
  const chartKey = chartScoped(r.table) ? chart : GLOBAL;
  const m = idx[chartKey];
  if (!m) return { pks: [], reason: `no_index_for_chart:${r.table}` };
  if (r.aggregate) {
    const head = canonVal(r.cols[0].val);
    const acc = [];
    for (const [k, v] of m.entries()) { if (k.split(SEP)[0] === head) acc.push(...v); }
    return { pks: acc.slice(0, 3), reason: acc.length ? null : 'aggregate_no_match' };
  }
  const key = r.cols.map((c) => canonVal(c.val)).join(SEP);
  const pks = m.get(key);
  if (pks && pks.length) return { pks, reason: null };
  return { pks: [], reason: 'value_not_found_in_db' };
}

// ---- per-(chart,domain) computation ------------------------------------
function compute(domain, chart) {
  const S = sliceFor(domain);
  const rows = [];
  const unaccounted = [];
  const stateCounts = { served: 0, empty_for_this_chart: 0, not_computed_globally: 0, superseded_by_aggregate: 0, excluded_by_named_rule: 0 };
  const unresolvedServed = [];

  for (const cid of S) {
    const e = tciById.get(cid);
    if (!e) { unaccounted.push(cid); continue; }
    const state = stateFor(e, chart);
    stateCounts[state]++;
    const evidence = {};
    if (state === 'served') {
      evidence.tool = e.serving_tool || null;
      const { pks, reason } = resolvePks(e, chart);
      evidence.fact_ids = pks;
      if (!pks.length) unresolvedServed.push({ concept_id: cid, source_axis: e.source_axis, reason });
    } else if (state === 'empty_for_this_chart') {
      evidence.fact_ids = []; // query ran, zero rows for this chart
    }
    rows.push({ concept_id: cid, chart_id: chart, domain, state, evidence });
  }

  // evidence-field validation per C7 evidence table + rule 3
  let evidenceOk = true;
  for (const row of rows) {
    if (row.state === 'served') {
      if (!row.evidence.tool || !Array.isArray(row.evidence.fact_ids) || row.evidence.fact_ids.length < 1) evidenceOk = false;
    } else if (row.state === 'empty_for_this_chart') {
      if (!Array.isArray(row.evidence.fact_ids)) evidenceOk = false;
    } else if (row.state === 'superseded_by_aggregate') {
      if (!row.evidence.superseded_by) evidenceOk = false;
    } else if (row.state === 'excluded_by_named_rule') {
      evidenceOk = false; // C7 rule 2: must never appear in a slice audit
    }
  }

  const unresolvedByAxis = {};
  const unresolvedByReason = {};
  for (const u of unresolvedServed) {
    unresolvedByAxis[u.source_axis] = (unresolvedByAxis[u.source_axis] || 0) + 1;
    unresolvedByReason[u.reason] = (unresolvedByReason[u.reason] || 0) + 1;
  }

  const slice_size = S.length;
  const pass = rows.length === slice_size && unaccounted.length === 0 && evidenceOk;

  return {
    result: { chart_id: chart, domain, slice_size, rows, unaccounted, pass },
    meta: {
      state_counts: stateCounts,
      unresolved_served_count: unresolvedServed.length,
      unresolved_by_axis: unresolvedByAxis,
      unresolved_by_reason: unresolvedByReason,
      unresolved_served_sample: unresolvedServed.slice(0, 40),
      evidence_ok: evidenceOk,
    },
  };
}

// ---- run all 4 ----------------------------------------------------------
const summary = {
  artifact: 'COMPLETENESS_ACCOUNTING_SUMMARY',
  version: '1.0',
  contract_id: 'C7',
  campaign: 'Elevation Campaign v2.1, Stream gamma (PURNA), Lane Omega-3 (Completeness Contract)',
  generator: 'platform/scripts/census/generate_completeness_accounting.mjs',
  generated_at: new Date().toISOString(),
  inputs: {
    tci: TCI_PATH,
    relevance_map: RELEVANCE_PATH,
    tci_version: tci.version,
    relevance_version: rel.version,
  },
  slice_rule: 'S(domain) = { concept : !domain_agnostic AND domain key present in domains } (matches DOMAIN_RELEVANCE_MAP method_note; verified: |S(wealth)|=13820, |S(career)|=13825 match the relevance-map summary).',
  superseded_note: SUPERSEDED_NOTE,
  results: [],
};

for (const domain of DOMAINS) {
  for (const chart of CHARTS) {
    const { result, meta } = compute(domain, chart);
    const chart8 = chart.slice(0, 8);
    const outPath = join(CAP_MAP, `COMPLETENESS_ACCOUNTING_${domain}_${chart8}_v1_0.json`);
    writeFileSync(outPath, JSON.stringify({
      artifact: 'COMPLETENESS_ACCOUNTING',
      version: '1.0',
      contract_id: 'C7',
      generated_at: summary.generated_at,
      generator: summary.generator,
      state_counts: meta.state_counts,
      unresolved_served_count: meta.unresolved_served_count,
      unresolved_by_axis: meta.unresolved_by_axis,
      unresolved_by_reason: meta.unresolved_by_reason,
      unresolved_served_sample: meta.unresolved_served_sample,
      superseded_note: SUPERSEDED_NOTE,
      ...result,
    }) + '\n');
    summary.results.push({
      domain, chart_id: chart, chart8,
      slice_size: result.slice_size,
      rows: result.rows.length,
      unaccounted: result.unaccounted.length,
      state_counts: meta.state_counts,
      unresolved_served_count: meta.unresolved_served_count,
      unresolved_by_axis: meta.unresolved_by_axis,
      unresolved_by_reason: meta.unresolved_by_reason,
      evidence_ok: meta.evidence_ok,
      pass: result.pass,
      out_file: `00_ARCHITECTURE/llm_consumption_audit/capability_map/COMPLETENESS_ACCOUNTING_${domain}_${chart8}_v1_0.json`,
    });
    log(`[${domain} | ${chart8}] |S|=${result.slice_size} rows=${result.rows.length} ` +
        `served=${meta.state_counts.served} empty=${meta.state_counts.empty_for_this_chart} ` +
        `not_computed=${meta.state_counts.not_computed_globally} unaccounted=${result.unaccounted.length} ` +
        `unresolved_served=${meta.unresolved_served_count} PASS=${result.pass}`);
  }
}

const sumPath = join(CAP_MAP, 'COMPLETENESS_ACCOUNTING_SUMMARY_v1_0.json');
writeFileSync(sumPath, JSON.stringify(summary, null, 2) + '\n');
log(`\nwrote summary -> ${sumPath}`);
log('DONE');
