import type { SemanticCapabilityDeclaration } from './types'

const common = {
  version: 1,
  scope: 'chart' as const,
  entitlement: 'native' as const,
  provenance_requirements: ['chart_id', 'build_id', 'formula_or_writer_version'],
  freshness_policy: 'Must match the active chart build; computed time surfaces also carry computed_at.',
  safety_notes: ['Retrieval evidence only; the planner must not interpret chart facts or write final synthesis.'],
}

export const MECHANISM_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    ...common,
    scu_id: 'scu.bodha.mechanism.network',
    label: 'Named causal mechanism network',
    description: 'Retrieve named, valenced Bodha mechanisms and their grounded member graph.',
    kind: 'mechanism',
    domains: ['all'],
    concepts: ['dispositor_chain', 'lordship_cycle', 'mutual_reception', 'affliction_mechanism'],
    intents: ['explain', 'assess', 'deep_inquiry'],
    horizons: ['natal'],
    inputs: ['chart_id', 'mechanism_class?', 'valence?', 'offset?', 'limit?', 'page_cursor?'],
    outputs: ['mechanisms', 'member_node_ids', 'member_edge_ids', 'facets', 'total_matching'],
    primary_binding_uri: 'marsys://tool/L2/query_mechanisms',
    primary_binding_details: {
      pagination: 'cursor',
      pagination_contract: {
        request_position_path: 'page_cursor', request_limit_path: 'limit', effective_maximum: 50,
        result_collection_path: 'content.rows', total_path: 'content.total_matching',
        more_available_path: 'content.more_available', next_path: 'content.next_page_cursor',
        deterministic_order: ['chain_circuit_class DESC', 'edge_strength_avg DESC', 'member_node_count DESC', 'mechanism_name ASC', 'mechanism_id ASC'],
      },
      execution_channels: ['platform_internal', 'mcp_full'],
      public_tool_name: 'bodha_mechanisms_get',
      route_evidence: 'platform-mcp/src/tools/register_p1_aliases.ts:1488',
    },
    edges: [
      { relation: 'requires', target_scu_id: 'scu.catalog.get_divisionals', rationale: 'Varga-specific claims require operative-varga evidence.' },
      { relation: 'related', target_scu_id: 'scu.kala.temporal_activation', rationale: 'Mechanisms become material through temporal activation.' },
      { relation: 'contradicts', target_scu_id: 'scu.yoga.firing_and_cancellation', rationale: 'Yoga cancellation can inhibit a promising mechanism.' },
    ],
    known_gaps: ['Mechanism graph is D1-only; cross-varga convergence must be assembled from separate evidence.'],
    producer_output_claims: [{
      asset_id: 'bo_yantra_mechanism', component: 'bodha_mechanisms rows',
      output_digest_spec_sha256: 'b867fc3bb5337bedb7e7c7fbf3f912b3ed888414c8cbb01f18776ba6294c2d0e',
      disposition: 'reviewed_output',
      evidence: 'platform/migrations/1009_nirmana_l2_bo_yantra_mechanism_output_digest_spec.sql:114',
    }],
    availability_contracts: [{
      binding_id: 'registry:marsys://tool/L2/query_mechanisms',
      requirements: [{
        kind: 'producer_output', asset_id: 'bo_yantra_mechanism',
        spec_sha256: 'b867fc3bb5337bedb7e7c7fbf3f912b3ed888414c8cbb01f18776ba6294c2d0e',
        scope: 'chart_build',
        source_ref: 'platform/migrations/1009_nirmana_l2_bo_yantra_mechanism_output_digest_spec.sql:114',
      }],
    }],
    editorial: true,
  },
]

export const TEMPORAL_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    ...common,
    scu_id: 'scu.kala.temporal_activation',
    label: 'Temporal activation windows',
    description: 'Retrieve signal activation windows, predicates, and temporal drill paths.',
    kind: 'temporal',
    domains: ['all'],
    concepts: ['dasha', 'transit', 'activation', 'convergence_window'],
    intents: ['timing', 'forecast', 'deep_inquiry'],
    horizons: ['current', 'multi_year'],
    inputs: ['chart_id', 'ayanamsha_id?', 'date_from?', 'date_to?', 'as_of?', 'signal_ids?', 'domain?', 'min_activation_strength?', 'top_k?'],
    outputs: ['activation_windows', 'predicates', 'signal_refs', 'total_matching', 'more_available', 'temporal_closure', 'drill_pointers'],
    primary_binding_uri: 'marsys://tool/L3/query_temporal_activation',
    primary_binding_details: {
      pagination: 'bounded_unverified',
      // The response now proves whether its exact filtered window was trimmed,
      // but it intentionally offers no continuation. A required inquiry must
      // therefore retain a frontier when that bounded window is incomplete.
      pagination_contract: {
        request_limit_path: 'top_k', effective_maximum: 500,
        result_collection_path: 'content.activations',
        total_path: 'content.total_matching',
        more_available_path: 'content.more_available',
        deterministic_order: [
          'dasha_activation_proximity_score DESC NULLS LAST',
          'orb_strength DESC NULLS LAST',
          'activation_start ASC',
          'id ASC',
        ],
      },
      execution_channels: ['platform_internal', 'mcp_full'],
      public_tool_name: 'kala_windows_get',
      route_evidence: 'platform-mcp/src/tools/register_p1_aliases.ts:1076',
    },
    edges: [
      { relation: 'requires', target_scu_id: 'scu.catalog.get_dashas', rationale: 'Dasha sequence is a temporal prerequisite.' },
      { relation: 'requires', target_scu_id: 'scu.catalog.query_planet_transit', rationale: 'Transit state completes current-time activation.' },
      { relation: 'enables', target_scu_id: 'scu.finance.prosperity_assessment', rationale: 'Times natal finance promise and inhibition.' },
    ],
    known_gaps: ['The route is an intentionally non-exhaustible top_k temporal-window read. Its source-reviewed closure receipt reports the exact filtered total and bounded-window state; a trimmed required result remains materially incomplete because no reviewed continuation exists.'],
    producer_output_claims: [
      { asset_id: 'ka_kalasutra', component: 'kala_activation rows', output_digest_spec_sha256: null, disposition: 'route_evidence_only', evidence: 'query_temporal_activation handler reads kala_activation', gap_reason: 'No reviewed output-digest component hash is joined to this SCU yet.' },
      { asset_id: 'ka_yojaka', component: 'kala_activation_predicates rows', output_digest_spec_sha256: '9f6bbfd1011ebf82aec647c3b80da57365e11a2fffbaf00f3a4df5bc77d307a5', disposition: 'reviewed_output', evidence: 'platform/migrations/1024_nirmana_l3_ka_yojaka_output_digest_spec.sql:80' },
      { asset_id: 'ka_bhavishya_lekha', component: 'kala_bhavishya forward windows', output_digest_spec_sha256: 'a66795f7fbf0a2713dbb860dd986128586b8b48830f3902f20bca0bcb12fccf2', disposition: 'reviewed_output', evidence: 'platform/migrations/974_nirmana_l3_ka_bhavishya_lekha_output_digest_spec.sql:232' },
    ],
    availability_dispositions: [{
      binding_id: 'registry:marsys://tool/L3/query_temporal_activation',
      status: 'deliberately_dark',
      reason: 'The handler reads kala_activation, but ka_kalasutra has only route evidence and no reviewed digest component for that relation. The reviewed predicate and forward-window receipts cannot substitute for the missing activation output receipt.',
      source_refs: [
        'platform/src/lib/retrieval/registry/layers/L3_kala/query_temporal_activation.ts',
        'platform/migrations/1024_nirmana_l3_ka_yojaka_output_digest_spec.sql:80',
        'platform/migrations/974_nirmana_l3_ka_bhavishya_lekha_output_digest_spec.sql:232',
      ],
    }],
    editorial: true,
  },
]

export const DIVISIONAL_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    ...common,
    scu_id: 'scu.catalog.get_divisionals',
    label: 'Operative divisional-chart evidence',
    description: 'Retrieve placements and derived house-from-varga-lagna across operative vargas.',
    kind: 'datum',
    domains: ['all'],
    concepts: ['varga', 'ratification', 'divisional_contradiction'],
    intents: ['assess', 'verify', 'deep_inquiry'],
    horizons: ['natal'],
    inputs: ['chart_id', 'varga?', 'graha?', 'offset?', 'limit?'],
    outputs: ['divisional_placements', 'house_from_varga_lagna', 'more_available', 'next_offset', 'vargottama'],
    primary_binding_uri: 'marsys://tool/L1/get_divisionals',
    primary_binding_details: {
      pagination: 'offset',
      pagination_contract: {
        request_position_path: 'offset', request_limit_path: 'limit', effective_maximum: 2000,
        result_collection_path: 'content.rows',
        next_path: 'content.next_offset',
        deterministic_order: ['varga', 'ayanamsha_id', 'graha', 'fact_category', 'fact_key'],
      },
      execution_channels: ['platform_internal'],
      route_evidence: 'platform/src/lib/retrieval/registry/layers/L1_ganita/get_divisionals.ts',
    },
    additional_bindings: [{
      binding_id: 'mcp:ganita_chart_facts_get:divisional_chart', kind: 'mcp_native', relation: 'provides',
      capability_uri: 'mcp://tool/ganita_chart_facts_get', public_tool_name: 'ganita_chart_facts_get',
      input_contract: { chart_id: 'string:required', divisional_chart: 'string:required', offset: 'number:optional', limit: 'number:optional' },
      output_contract: { divisional_facts: 'array' }, pagination: 'offset', pagination_verified: null,
      executable: true, execution_channels: ['mcp_full'],
      route_evidence: 'platform-mcp/src/tools/register_p1_aliases.ts:1528',
    }],
    edges: [
      { relation: 'provides', target_scu_id: 'scu.bodha.mechanism.network', rationale: 'Provides the varga evidence the D1-only mechanism surface does not compute.' },
      { relation: 'contradicts', target_scu_id: 'scu.finance.prosperity_assessment', rationale: 'An operative varga may fail to ratify a natal promise.' },
    ],
    known_gaps: ['Public MCP uses ganita_chart_facts_get with a required divisional_chart filter, not a same-name tool.'],
    producer_output_claims: [{
      asset_id: 'ga_vargas', component: 'chart_divisionals placements',
      output_digest_spec_sha256: '5f332a4889cb465f317fe7f2315bd59a7aee9d53df58e283b436040403a9bb51',
      disposition: 'reviewed_output', evidence: 'platform/migrations/883_nirmana_l1_ga_vargas_output_digest_spec.sql:28',
    }],
    availability_contracts: [{
      binding_id: 'registry:marsys://tool/L1/get_divisionals',
      requirements: [{
        kind: 'producer_output', asset_id: 'ga_vargas',
        spec_sha256: '5f332a4889cb465f317fe7f2315bd59a7aee9d53df58e283b436040403a9bb51',
        scope: 'chart_build',
        source_ref: 'platform/migrations/883_nirmana_l1_ga_vargas_output_digest_spec.sql:28',
      }],
    }],
    editorial: true,
  },
]

export const DASHA_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    version: 1,
    scu_id: 'scu.catalog.get_dashas',
    label: 'Get Dashas',
    description: 'Retrieve dated dasha period evidence from chart_dashas.',
    kind: 'temporal',
    domains: ['timing'],
    concepts: ['activation_timing', 'get_dashas', 'temporal_sequence', 'timing_window'],
    intents: ['sequence', 'time'],
    horizons: ['current', 'future', 'historical', 'multi_year'],
    scope: 'chart',
    inputs: ['all_levels', 'as_of_date', 'ayanamsha_id', 'chart_id', 'dasha_system', 'date_contains', 'date_from', 'fields', 'level', 'limit', 'lord_graha', 'offset', 'page_cursor', 'system', 'system_id', 'window_end', 'window_start'],
    outputs: ['evidence_references', 'temporal_sequence_evidence', 'timing_windows'],
    primary_binding_uri: 'marsys://tool/L1/get_dashas',
    primary_binding_details: {
      pagination: 'cursor',
      pagination_contract: {
        request_position_path: 'page_cursor',
        request_limit_path: 'limit',
        effective_maximum: 1000,
        result_collection_path: 'content.rows',
        next_path: 'content.next_page_cursor',
        more_available_path: 'content.more_available',
        deterministic_order: ['system_id ASC', 'ayanamsha_id ASC', 'start_date ASC', 'level_n ASC', 'start_iso ASC', 'dasha_row_id ASC'],
      },
      execution_channels: ['platform_internal'],
      route_evidence: 'platform/src/lib/retrieval/registry/layers/L1_ganita/get_dashas.ts',
    },
    provenance_requirements: ['chart_id_when_chart_scoped', 'build_id', 'formula_or_writer_version'],
    freshness_policy: 'Must resolve against the active compatible chart build.',
    entitlement: 'native',
    safety_notes: ['Read-only evidence surface; planner must not interpret returned chart facts.'],
    known_gaps: [],
    producer_output_claims: [{
      asset_id: 'ga_dashas',
      component: 'chart_dashas dasha periods',
      output_digest_spec_sha256: '573e8aa1a0298d6626784b5ff540c004fd4d2298b6b47d2980a447acdc193d14',
      disposition: 'reviewed_output',
      evidence: 'platform/migrations/881_nirmana_l1_ga_dashas_output_digest_spec.sql:56',
    }],
    availability_contracts: [{
      binding_id: 'registry:marsys://tool/L1/get_dashas',
      requirements: [{
        kind: 'producer_output',
        asset_id: 'ga_dashas',
        spec_sha256: '573e8aa1a0298d6626784b5ff540c004fd4d2298b6b47d2980a447acdc193d14',
        scope: 'chart_build',
        source_ref: 'platform/migrations/881_nirmana_l1_ga_dashas_output_digest_spec.sql:56',
      }],
    }],
    editorial: true,
  },
]

export const GESTALT_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    version: 1,
    scu_id: 'scu.catalog.query_chart_gestalt',
    label: 'Query Chart Gestalt',
    description: 'Retrieve the whole-chart gestalt digest from bodha_chart_gestalt.',
    kind: 'datum',
    domains: ['cross_domain'],
    concepts: ['domain_assessment', 'evidence_reconciliation', 'judgment_support', 'query_chart_gestalt'],
    intents: ['assess', 'reconcile'],
    horizons: ['current', 'natal'],
    scope: 'chart',
    inputs: ['ayanamsha_id', 'chart_id', 'limit'],
    outputs: ['assessment_findings', 'evidence_references', 'reconciled_evidence'],
    primary_binding_uri: 'marsys://tool/L2/query_chart_gestalt',
    provenance_requirements: ['chart_id_when_chart_scoped', 'build_id', 'formula_or_writer_version'],
    freshness_policy: 'Must resolve against the active compatible chart build.',
    entitlement: 'native',
    safety_notes: ['Read-only evidence surface; planner must not interpret returned chart facts.'],
    known_gaps: [],
    producer_output_claims: [{
      asset_id: 'bo_chart_gestalt',
      component: 'bodha_chart_gestalt rows',
      output_digest_spec_sha256: '2fae5316fbc9a445377a279716f4b1ea5834954b21a54e77f79fe3c6a2b3721e',
      disposition: 'reviewed_output',
      evidence: 'platform/migrations/984_nirmana_l2_bo_chart_gestalt_output_digest_spec.sql:125',
    }],
    availability_contracts: [{
      binding_id: 'registry:marsys://tool/L2/query_chart_gestalt',
      requirements: [{
        kind: 'producer_output',
        asset_id: 'bo_chart_gestalt',
        spec_sha256: '2fae5316fbc9a445377a279716f4b1ea5834954b21a54e77f79fe3c6a2b3721e',
        scope: 'chart_build',
        source_ref: 'platform/migrations/984_nirmana_l2_bo_chart_gestalt_output_digest_spec.sql:125',
      }],
    }],
    editorial: true,
  },
]

export const YOGA_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    ...common,
    scu_id: 'scu.yoga.firing_and_cancellation',
    label: 'Yoga firing, strength, and cancellation',
    description: 'Distinguish catalog membership from an actual firing and expose bhanga/cancellation.',
    kind: 'contradiction',
    domains: ['all'],
    concepts: ['yoga', 'firing', 'bhanga', 'cancellation', 'partial_formation'],
    intents: ['assess', 'verify', 'deep_inquiry'],
    horizons: ['natal', 'current'],
    inputs: ['chart_id', 'yoga_canonical_id?', 'fired?', 'bhanga_active?', 'offset?', 'limit?'],
    outputs: ['firings', 'strength', 'bhanga', 'activation_dasha_periods', 'grounds'],
    primary_binding_uri: 'marsys://tool/L1/get_yoga_firings',
    primary_binding_details: {
      pagination: 'offset',
      pagination_contract: {
        request_position_path: 'offset', request_limit_path: 'limit', effective_maximum: 50,
        result_collection_path: 'content.rows', total_path: 'content.total_matching',
        more_available_path: 'content.more_available',
        deterministic_order: ['strength DESC', 'yoga_canonical_id', 'ayanamsha_id', 'id'],
      },
      execution_channels: ['platform_internal', 'mcp_full'], public_tool_name: 'ganita_yoga_firings_get',
      route_evidence: 'platform-mcp/src/tools/register_p1_aliases.ts:970',
    },
    additional_bindings: [{
      binding_id: 'mcp:yoga_activation_by_dasha',
      kind: 'registry_capability',
      relation: 'provides',
      capability_uri: 'marsys://tool/L-TIMING/yoga_activation_by_dasha',
      input_contract: { chart_id: 'required', dasha_period: 'optional' },
      output_contract: { activated_yogas: 'array', signal_refs: 'array' },
      pagination: 'bounded_complete',
      pagination_verified: null,
      executable: true,
      execution_channels: ['platform_internal', 'mcp_full'],
      public_tool_name: 'kala_yoga_activation_get',
      route_evidence: 'platform-mcp/src/tools/register_p1_aliases.ts:1402',
    }],
    edges: [
      { relation: 'requires', target_scu_id: 'scu.catalog.get_dashas', rationale: 'Activation claims require the active dasha spine.' },
      { relation: 'related', target_scu_id: 'scu.kala.temporal_activation', rationale: 'Temporal window is the material activation context.' },
    ],
    known_gaps: [],
    producer_output_claims: [{
      asset_id: 'ga_yoga', component: 'ga_yoga_firings rows',
      output_digest_spec_sha256: 'fdd546e448c5b4ea4a8d2562e93b2883324ceac8e9c0644c9ec9aeaa2b4a3246',
      disposition: 'reviewed_output', evidence: 'platform/migrations/918_nirmana_l1_ga_yoga_output_digest_spec.sql:128',
    }],
    availability_contracts: [{
      binding_id: 'registry:marsys://tool/L1/get_yoga_firings',
      requirements: [{
        kind: 'producer_output', asset_id: 'ga_yoga',
        spec_sha256: 'fdd546e448c5b4ea4a8d2562e93b2883324ceac8e9c0644c9ec9aeaa2b4a3246',
        scope: 'chart_build',
        source_ref: 'platform/migrations/918_nirmana_l1_ga_yoga_output_digest_spec.sql:128',
      }],
    }],
    editorial: true,
  },
]

export const FINANCE_SCUS: readonly SemanticCapabilityDeclaration[] = [
  {
    ...common,
    scu_id: 'scu.finance.prosperity_assessment',
    label: 'Finance and prosperity assessment',
    description: 'Reconcile wealth houses, significators, operative vargas, mechanisms, contradictions, and timing.',
    kind: 'assessment',
    domains: ['wealth', 'finance', 'prosperity'],
    concepts: ['second_house', 'eleventh_house', 'jupiter', 'dhana_yoga', 'd2', 'd11', 'indu_lagna'],
    intents: ['wealth_deepdive', 'assess', 'deep_inquiry'],
    horizons: ['natal', 'current', 'multi_year'],
    inputs: ['chart_id', 'question'],
    outputs: ['convergences', 'tensions', 'signal_refs', 'judgment_flags'],
    primary_binding_uri: 'marsys://tool/L-DOMAIN/assess_wealth',
    primary_binding_details: {
      pagination: 'bounded_unverified', pagination_verified: null,
      execution_channels: ['platform_internal', 'mcp_full'], public_tool_name: 'assess_wealth',
      route_evidence: 'platform-mcp/src/tools/registry_bridge.ts:3504',
    },
    additional_bindings: [{
      binding_id: 'registry:finance-mechanisms',
      kind: 'registry_capability',
      relation: 'provides',
      capability_uri: 'marsys://tool/L2/query_mechanisms',
      input_contract: { chart_id: 'required', valence: 'optional' },
      output_contract: { mechanisms: 'array', facets: 'object' },
      pagination: 'offset',
      pagination_verified: null,
      pagination_contract: {
        request_position_path: 'offset', request_limit_path: 'limit', effective_maximum: 50,
        result_collection_path: 'content.rows', total_path: 'content.total_matching',
        more_available_path: 'content.more_available',
        deterministic_order: ['chain_circuit_class DESC', 'edge_strength_avg DESC', 'member_node_count DESC', 'mechanism_name ASC'],
      },
      executable: true,
      execution_channels: ['platform_internal', 'mcp_full'], public_tool_name: 'bodha_mechanisms_get',
      route_evidence: 'platform-mcp/src/tools/register_p1_aliases.ts:1488',
    }],
    edges: [
      { relation: 'requires', target_scu_id: 'scu.bodha.mechanism.network', rationale: 'Assessment must name supportive and inhibiting causal structures.' },
      { relation: 'requires', target_scu_id: 'scu.catalog.get_divisionals', rationale: 'D2/D11 and special-lagna evidence must ratify the natal promise.' },
      { relation: 'requires', target_scu_id: 'scu.yoga.firing_and_cancellation', rationale: 'Dhana yoga claims require firing and cancellation checks.' },
      { relation: 'requires', target_scu_id: 'scu.kala.temporal_activation', rationale: 'Current activation and convergence windows are material.' },
      { relation: 'related', target_scu_id: 'scu.catalog.query_classical_texts', rationale: 'Classical rule grounding supports interpretation downstream.' },
    ],
    known_gaps: ['Final interpretation remains the synthesis layer responsibility.'],
    producer_output_claims: [
      { asset_id: 'bo_cdlm_summary', component: 'wealth domain reconciled summary', output_digest_spec_sha256: 'f6520a32a0791a64083daed074bb45592b7da430a7d1912da4a3e0f240800497', disposition: 'reviewed_output', evidence: 'platform/migrations/986_nirmana_l2_bo_cdlm_summary_output_digest_spec.sql:137' },
      { asset_id: 'bo_vargottama_dhana', component: 'vargottama and dhana-axis signals', output_digest_spec_sha256: '8a94b6928bd78bde8434510517b7070c5d327149165afe10d269a62ad08cc1ec', disposition: 'reviewed_output', evidence: 'platform/migrations/907_nirmana_l2_bo_vargottama_dhana_output_digest_spec.sql:44' },
    ],
    availability_contracts: [{
      binding_id: 'registry:marsys://tool/L-DOMAIN/assess_wealth',
      requirements: [
        {
          kind: 'producer_output', asset_id: 'bo_cdlm_summary',
          spec_sha256: 'f6520a32a0791a64083daed074bb45592b7da430a7d1912da4a3e0f240800497',
          scope: 'chart_build',
          source_ref: 'platform/migrations/986_nirmana_l2_bo_cdlm_summary_output_digest_spec.sql:137',
        },
        {
          kind: 'producer_output', asset_id: 'bo_vargottama_dhana',
          spec_sha256: '8a94b6928bd78bde8434510517b7070c5d327149165afe10d269a62ad08cc1ec',
          scope: 'chart_build',
          source_ref: 'platform/migrations/907_nirmana_l2_bo_vargottama_dhana_output_digest_spec.sql:44',
        },
      ],
    }],
    editorial: true,
  },
]
