"""
gochara_intensity.permission — the PERMISSION term of lambda_e = PROMISE *
PERMISSION * exp(beta_e * X(t)) - suppression (BRIEF_D5 §1 G-3 row).

DR-14 (Timing-System Plurality) is this term's binding doctrine
(`00_ARCHITECTURE/llm_consumption_audit/briefs/doctrine_waves/DR_14_15_16_TEMPORAL_DOCTRINE_v1_0.md`):
activation windows are generated by a PLURALITY of independent timing
systems -- Vimśottarī (all levels) as the DEFAULT generator, never an
exclusive container; Jaimini rāśi-daśās (Chara, Nārāyaṇa); Tājaka/varṣaphala
year-lord + Mudda; Guru-Śani double-transit; aṣṭakavarga-threshold transits;
Saturn/Jupiter/nodal returns; Sāde Satī phases. "No system's window may be
served as exclusive." PERMISSION genuinely sums ACROSS these systems -- it
is never Vimśottarī-gated (the exact doctrinal violation DR-14 exists to
prevent, and this wave's verifier's specific acceptance bar per BRIEF_D5 §1
G-3 row).

This module evaluates 12 independent generators at a given instant t:

  1-8. 8 `chart_dashas` systems. IMPORTANT LIVE-DATA CORRECTION (found at
       G-3 build/verification time, 2026-07-19, live query against chart
       482012f1): G-2's `gochara_grammar.dasha_data.DASHA_SYSTEMS` tuple
       ("vimshottari","yogini","ashtottari","chara","naisargika","mudda",
       "kalachakra") does NOT match the live `chart_dashas.system_id`
       values for this chart, which are actually {ashtottari,
       chara_karaka, kalachakra, mudda, naisargika, narayana, vimshottari,
       vimshottari_kp, yogini} -- "chara" is stored as "chara_karaka", and
       a Nārāyaṇa daśā system (DR-14 names this explicitly: "Jaimini
       rāśi-daśās (Chara, Nārāyaṇa)") is ALSO live under "narayana",
       something G-2's own DASHA_SYSTEMS enumeration does not request.
       This module does NOT edit G-2's `dasha_data.py` (must_not_touch,
       read-only consumption) -- instead it calls
       `dasha_data.fetch_dasha_periods(..., systems=DASHA_SYSTEM_IDS)`,
       using `fetch_dasha_periods`'s own documented `systems` override
       parameter (built for exactly this: a caller requesting a specific
       system subset/superset) with the LIVE-VERIFIED id list below.
       `vimshottari_kp` (a KP-variant sub-period system) is deliberately
       EXCLUDED from `DASHA_SYSTEM_IDS` -- it is a finer subdivision of the
       same Vimśottarī family already counted once, not an independent
       generator; double-counting it would inflate PERMISSION's plurality
       count without adding a genuinely independent timing system.
  9. sade_sati_phase — reuses `gochara_grammar.primitives.sade_sati_phase`
     (itself reading `chart_facts` sade_sati_cycle/phase rows).
 10. guru_shani_double_transit — Jupiter+Saturn simultaneous drishti/degree
     contact on a resonance target, reusing `primitives.drishti_contact` /
     `primitives.degree_contact` restricted to those two grahas, composed
     via `composition.double_transit`'s own `is_guru_shani_double_transit`
     flag (the ONE double-transit pairing this codebase has a live cited
     `bg_transit_rules` row for).
 11. av_threshold_state — reuses `primitives.av_threshold_state`
     (aṣṭakavarga-threshold transit gates from `bg_transit_av_gates`).
 12. planetary_return — reuses `primitives.planetary_return`, restricted to
     Saturn/Jupiter/Rahu/Ketu targets (the "Saturn/Jupiter/nodal returns"
     DR-14 names explicitly).

NOT implemented (honest scope gap, documented rather than silently
skipped): a standalone Tājaka varṣaphala year-lord signal distinct from
`mudda` (mudda dasha IS the Tājaka annual sub-period system this codebase
stores; a dedicated year-lord computation is a further Tājaka sub-feature
this codebase's `ganita_tajaka_get` surface may expose but this module
does not additionally query it here, to keep the G-3 scope to REUSING
existing G-1/G-2 substrate per the task brief rather than adding new
astronomical computation classes, which BRIEF_D5 §7 explicitly excludes
from D-5 ["new ayanamsha/astronomy code beyond the sidecar's EXISTING
capabilities"]). 12 generators (8 dasha + 4 others) is comfortably >=
DR-14's "plurality" floor and >= the wave verifier's "sums across >= 2
independent systems" bar.

Every SYSTEM_WEIGHTS entry is a disclosed structural prior (not fitted --
BRIEF_D5 §7 explicitly reserves weight-fitting for D-4b). Vimśottarī keeps
the highest single weight, reflecting its role as DR-14's "DEFAULT
generator" -- but it is one of twelve summed terms, never a gate the
others must pass through, and PERMISSION is fully computable (and, per
this module's own test suite, DOES fire) with Vimśottarī's contribution
zeroed out entirely.
"""
from __future__ import annotations

import logging
from typing import Any, Optional

from services.gochara_grammar import dasha_data as DD
from services.gochara_grammar import primitives as P
from services.gochara_grammar import composition as CO
from services.gochara_grammar.models import ResonanceTarget
from pipeline.transit_search import _jd_to_ist_iso
from ._dbutil import savepoint_scope

logger = logging.getLogger(__name__)

# Disclosed structural-prior weights (calibration_state='structural_prior' --
# NEVER fitted in D-5, see module docstring). Sum = 1.0 so PERMISSION is
# naturally bounded to [0,1] as "fraction of DR-14 plurality confluence
# currently open", but the sum itself carries no doctrinal significance
# beyond normalization convenience -- an engineering choice, not a ruling.
SYSTEM_WEIGHTS: dict[str, float] = {
    "vimshottari": 0.16,           # DR-14 default generator -- highest single weight, not exclusive
    "chara_karaka": 0.10,           # Jaimini Chara Dasa (live system_id -- see docstring correction)
    "narayana": 0.08,               # Jaimini Narayana Dasa (live system_id -- see docstring correction)
    "mudda": 0.09,                  # Tajaka annual sub-period
    "yogini": 0.07,
    "ashtottari": 0.07,
    "naisargika": 0.05,
    "kalachakra": 0.05,
    "sade_sati": 0.10,              # whole-chart Saturn/Moon phase system
    "guru_shani_double_transit": 0.10,
    "av_threshold": 0.06,
    "planetary_return": 0.07,
}
assert abs(sum(SYSTEM_WEIGHTS.values()) - 1.0) < 1e-9

# LIVE-VERIFIED chart_dashas.system_id values (2026-07-19, chart 482012f1) --
# NOT G-2's DD.DASHA_SYSTEMS tuple, see module docstring's "IMPORTANT
# LIVE-DATA CORRECTION". Passed explicitly to
# `dasha_data.fetch_dasha_periods(..., systems=DASHA_SYSTEM_IDS)`.
DASHA_SYSTEM_IDS = ("vimshottari", "yogini", "ashtottari", "chara_karaka",
                     "naisargika", "mudda", "kalachakra", "narayana")


# Classical Yogini Dasa lord-to-graha correspondence (8 yoginis: Mangala,
# Pingala, Dhanya, Bhramari, Bhadrika, Ulka, Siddha, Sankata -> Moon, Sun,
# Jupiter, Mars, Mercury, Saturn, Venus, Rahu respectively) -- a standard
# Jyotish reference table, NOT a codebase-attested citation constant (no
# `gochara_grammar.citations` entry names it), so it is applied here as
# general classical-domain knowledge with this comment as its provenance,
# not dressed up as a `classical_citation` string. Needed because live
# `chart_dashas` stores yogini dasha lords by DEITY name (e.g. "Sankata"),
# not by graha name -- without this translation table, yogini's lord could
# never match `_relevant_grahas`'s graha-name vocabulary.
YOGINI_LORD_TO_GRAHA = {
    "mangala": "Moon", "pingala": "Sun", "dhanya": "Jupiter", "bhramari": "Mars",
    "bhadrika": "Mercury", "ulka": "Saturn", "siddha": "Venus", "sankata": "Rahu",
}


def _relevant_grahas(targets: list[ResonanceTarget]) -> set[str]:
    """Grahas a dasha LORD must match to count as a relevant "delivery"
    signal for this event_class -- the dvi-pramāṇa generalization DR-14
    names explicitly (promise x delivery: a dasha window is only doctrinally
    meaningful for an event_class if its lord actually relates to that
    class's resonance targets, not merely "some period from this system is
    running", which would be true of nearly every instant for every system
    since dasha periods tile the entire birth->birth+100y timeline)."""
    grahas: set[str] = set()
    for t in targets:
        if t.natal_planet:
            grahas.add(t.natal_planet)
        if t.target_type in ("karaka", "dasha_lord_portfolio") and t.target_ref:
            grahas.add(t.target_ref)
    return grahas


def _relevant_signs(targets: list[ResonanceTarget]) -> set[str]:
    """Signs a Jaimini rāśi-daśā (chara_karaka / narayana / this codebase's
    kalachakra rendering) LORD must match -- these systems store
    `lord_graha` as a RASHI name (e.g. "Taurus"), not a graha, per live-data
    verification at G-3 build time (see module docstring correction)."""
    return {t.target_sign for t in targets if t.target_sign}


def _lord_matches(sid: str, lord: str, relevant_grahas: set[str], relevant_signs: set[str]) -> bool:
    if lord is None:
        return False
    if lord in relevant_grahas:
        return True
    if lord in relevant_signs:
        return True
    translated = YOGINI_LORD_TO_GRAHA.get(str(lord).lower())
    return translated is not None and translated in relevant_grahas


def _dasha_contributions(
    dasha_periods: list[dict], t_iso: str, relevant_grahas: set[str], relevant_signs: set[str],
) -> dict[str, dict]:
    """Returns {system_id: {"active": bool, "detail": {...}}} for each of
    the 8 chart_dashas systems, independently checked.

    A system is "active" at t iff (a) it has a period covering t AND
    (b) that period's lord (graha, rasi, or yogini-deity-translated-to-
    graha, per `_lord_matches`) relates to this chart/event_class's
    resonance targets. When NEITHER `relevant_grahas` NOR `relevant_signs`
    is available (this chart/event_class's resonance-map rows carry no
    karaka/dasha_lord_portfolio/natal_planet/bhava-sign-resolved target),
    this degrades to the coarser "any period covering t" check, honestly
    noted in `detail['lord_relevance_check']` -- a system with NO way to be
    lord-checked should not be silently zeroed out."""
    out: dict[str, dict] = {sid: {"active": False, "detail": {}} for sid in DASHA_SYSTEM_IDS}
    lord_check_available = bool(relevant_grahas or relevant_signs)
    for period in dasha_periods:
        sid = period.get("system_id")
        if sid not in out or out[sid]["active"]:
            continue
        if not DD.period_contains(period, t_iso):
            continue
        lord = period.get("lord_graha")
        if lord_check_available and not _lord_matches(sid, lord, relevant_grahas, relevant_signs):
            continue
        out[sid] = {"active": True, "detail": {
            "lord_graha": lord,
            "start_iso": period.get("start_iso"),
            "end_iso": period.get("end_iso"),
            "lord_relevance_check": "matched_relevant_lord" if lord_check_available else "no_relevant_lord_vocabulary_resolved_any_period_counted",
        }}
    return out


def compute_permission(
    swe,
    conn,
    chart_id: str,
    event_class: str,
    targets: list[ResonanceTarget],
    t_jd: float,
    dasha_periods: Optional[list[dict]] = None,
    window_days: float = 15.0,
    ayanamsha_id: str = "lahiri_chitrapaksha",
) -> tuple[float, dict[str, Any]]:
    """Returns (permission, detail). `detail["systems_active"]` /
    `detail["systems_considered"]` are the lists the wave verifier's
    acceptance bar reads directly ("PERMISSION genuinely sums across >= 2
    independent timing systems"). `window_days` is the +/- search window
    used for the four point-primitive-sourced generators (sade_sati uses its
    own interval, dasha systems use exact period membership -- window_days
    does not affect those seven)."""
    t_iso = _jd_to_ist_iso(swe, t_jd)
    start_jd, end_jd = t_jd - window_days, t_jd + window_days

    systems: list[dict] = []

    # 1-8: chart_dashas systems (DR-14 plurality core -- Vimshottari is ONE
    # of these eight, never gating the rest). systems=DASHA_SYSTEM_IDS uses
    # the LIVE-VERIFIED system_id list (see module docstring correction),
    # not G-2's dasha_data.DASHA_SYSTEMS default.
    if dasha_periods is not None:
        periods = dasha_periods
    else:
        with savepoint_scope(conn, "dasha_periods"):
            periods = DD.fetch_dasha_periods(
                conn, chart_id, ayanamsha_id=ayanamsha_id, systems=list(DASHA_SYSTEM_IDS)
            )
    dasha_hits = _dasha_contributions(periods, t_iso, _relevant_grahas(targets), _relevant_signs(targets))
    for sid in DASHA_SYSTEM_IDS:
        hit = dasha_hits[sid]
        systems.append({
            "system_id": sid,
            "active": hit["active"],
            "weight": SYSTEM_WEIGHTS[sid],
            "detail": hit["detail"],
        })

    # 8: Sade Sati phase (whole-chart; needs one target only for event_class
    # context, not per-target geometry).
    sade_sati_active = False
    sade_sati_detail: dict = {}
    if targets:
        try:
            with savepoint_scope(conn, "sade_sati_permission"):
                sentences = P.sade_sati_phase(chart_id, targets[0], conn=conn)
                for s in sentences:
                    start_iso = s.detail.get("phase_start_iso")
                    end_iso = s.detail.get("phase_end_iso")
                    if not start_iso:
                        continue
                    pseudo_period = {"start_iso": start_iso, "end_iso": end_iso or "9999-12-31T00:00:00+00:00"}
                    if DD.period_contains(pseudo_period, t_iso):
                        sade_sati_active = True
                        sade_sati_detail = {"phase": s.detail.get("phase_name") or s.detail.get("subject"),
                                             "start_iso": start_iso, "end_iso": end_iso}
                        break
        except Exception as exc:  # noqa: BLE001 -- honest degrade, never crash PERMISSION
            logger.info("[permission] sade_sati_phase check failed: %s", exc)
    systems.append({"system_id": "sade_sati", "active": sade_sati_active,
                     "weight": SYSTEM_WEIGHTS["sade_sati"], "detail": sade_sati_detail})

    # 9: Guru-Sani double transit (Jupiter+Saturn only, per module docstring).
    gsdt_active = False
    gsdt_detail: dict = {}
    try:
        with savepoint_scope(conn, "guru_shani_double_transit"):
            contact_sentences = []
            for target in targets:
                if target.target_longitude_deg is None:
                    continue
                contact_sentences += P.drishti_contact(swe, chart_id, target, start_jd, end_jd, planets=["Jupiter", "Saturn"])
                contact_sentences += P.degree_contact(swe, chart_id, target, start_jd, end_jd, planets=["Jupiter", "Saturn"])
            comps = CO.double_transit(contact_sentences, window_days=window_days)
            for c in comps:
                if c.detail.get("is_guru_shani_double_transit"):
                    gsdt_active = True
                    gsdt_detail = {"target_ref": c.detail.get("target_ref"), "event_datetime_ist": c.event_datetime_ist}
                    break
    except Exception as exc:  # noqa: BLE001
        logger.info("[permission] guru_shani_double_transit check failed: %s", exc)
    systems.append({"system_id": "guru_shani_double_transit", "active": gsdt_active,
                     "weight": SYSTEM_WEIGHTS["guru_shani_double_transit"], "detail": gsdt_detail})

    # 10: AV-threshold transit gates (bhava targets only).
    av_active = False
    av_detail: dict = {}
    try:
        with savepoint_scope(conn, "av_threshold_permission"):
            for target in targets:
                if target.target_type != "bhava" or not target.target_sign:
                    continue
                events = P.av_threshold_state(swe, chart_id, target, start_jd, end_jd, conn=conn)
                if events:
                    av_active = True
                    av_detail = {"target_ref": target.target_ref, "count": len(events)}
                    break
    except Exception as exc:  # noqa: BLE001
        logger.info("[permission] av_threshold_state check failed: %s", exc)
    systems.append({"system_id": "av_threshold", "active": av_active,
                     "weight": SYSTEM_WEIGHTS["av_threshold"], "detail": av_detail})

    # 11: Saturn/Jupiter/nodal returns.
    return_active = False
    return_detail: dict = {}
    try:
        with savepoint_scope(conn, "planetary_return_permission"):
            for target in targets:
                if target.natal_planet not in ("Saturn", "Jupiter", "Rahu", "Ketu"):
                    continue
                if target.target_longitude_deg is None:
                    continue
                events = P.planetary_return(swe, chart_id, target, start_jd, end_jd)
                if events:
                    return_active = True
                    return_detail = {"natal_planet": target.natal_planet, "count": len(events)}
                    break
    except Exception as exc:  # noqa: BLE001
        logger.info("[permission] planetary_return check failed: %s", exc)
    systems.append({"system_id": "planetary_return", "active": return_active,
                     "weight": SYSTEM_WEIGHTS["planetary_return"], "detail": return_detail})

    active_weight = sum(s["weight"] for s in systems if s["active"])
    total_weight = sum(SYSTEM_WEIGHTS.values())
    permission = active_weight / total_weight if total_weight else 0.0

    systems_active = [s["system_id"] for s in systems if s["active"]]
    detail = {
        "systems": systems,
        "systems_active": systems_active,
        "systems_considered": [s["system_id"] for s in systems],
        "system_count_active": len(systems_active),
        "t_datetime_ist": t_iso,
        "window_days": window_days,
        "calibration_state": "structural_prior",
    }
    return permission, detail


__all__ = ["SYSTEM_WEIGHTS", "DASHA_SYSTEM_IDS", "compute_permission"]
