-- 1212_nirmana_l3_ka_vighnakara_output_digest_spec.sql
--
-- Suvarna Track I-4 (CANONICAL_CHART_REBUILD_PLAN_v1_0 blocker B-1). Transaction
-- ownership belongs to platform/scripts/migrate.ts. Data-only: one INSERT into
-- asset_output_digest_specs (amjis_app-owned); no table is altered. NOT applied by
-- this change -- the reviewer/operator applies it through the PR.
--
-- WHY `ka_vighnakara` could never be 'proven': provenance.build_receipt marks a
-- receipt 'unknown' when output_digest_spec_sha256 / output_digest are missing, and
-- the asset had no asset_output_digest_specs row (migration 1034 recorded it as a
-- blocked contract: "kala_obstruction has no stable, non-null unique key for both
-- convergence-anchored and dasha-anchored rows; BIGSERIAL id is execution history").
-- An 'unknown' receipt makes asset_freshness 'unknown', which asset_runner.
-- deps_unsatisfied (enforce mode) refuses for ka_kala_darshana, ka_bhavishya_lekha,
-- ph_muhurta, ph_pratikara and, transitively, the rest of Phala / mi_bhavisya.
--
-- Design (read from KaVighnakaraWriter, ka_vighnakara.py:172 DELETE / :285 INSERT):
--   * Table shape is migration 245's 11 columns (id, chart_id, convergence_id,
--     signal_id, obstruction_type, severity, severity_score, override_score,
--     obstruction_detail, source_citation, computed_at).
--   * HASHED (output content): chart_id (pinned), signal_id, obstruction_type,
--     severity, severity_score, override_score, obstruction_detail. obstruction_detail
--     carries peak_date, the detector facts and, for dasha-anchored rows,
--     anchor='dasha_timeline', so the two row populations stay distinguishable.
--   * EXCLUDED: id (BIGSERIAL, new on every delete-then-insert); computed_at (DEFAULT
--     now()); convergence_id (BIGSERIAL of kala_convergence, regenerated by every
--     ka_sangam rebuild, NULL for dasha-anchored rows); source_citation (embeds
--     'conv=<convergence_id>' on convergence rows). Hashing any of these would make
--     every identical rebuild look like changed output and stale all downstream.
--   * ORDERING: key_columns is every hashed column (chart_id aside: pinned constant).
--     The grammar needs keys that are non-NULL; it does not need them unique. Ordering
--     on the whole projection makes the row sequence total over what is hashed, so rows
--     that tie are byte-identical and heap/insert order cannot move the digest. The
--     reviewed-key NULL preflight is kept on purpose: a NULL signal_id (never emitted by
--     the writer; FK is ON DELETE CASCADE since migration 403) fails the build closed
--     instead of hashing in an unstable position.
--   * Chart scoping: the spec has no chart parameter, so (like 1018/1024) it is pinned
--     to the canonical chart via where_equals. Other charts' receipts for this asset
--     digest the canonical chart's rows until the contract gains a chart parameter.
--
-- KNOWN LIMITS (independent review of PR #2826, all accepted, none a blocker):
--   (a) Canonical-chart pin. The spec is pinned to chart 482012f1 via where_equals
--       (1018/1024 precedent). A rebuild of ANY OTHER chart now gets a 'proven' receipt
--       whose digest is the canonical chart's rows; before this migration it got
--       'unknown' (fail-closed). A known gap, now extended to a fifth asset; it closes
--       only when the digest contract gains a chart parameter.
--   (b) ka_vighnakara's depends_on includes ka_muhurta_seva (migration 730, header line 7). Its upstream digest
--       stays NULL, so its receipt stays 'unknown', until ka_muhurta_seva has rebuilt
--       under migration 1213 (and ka_dasha_kala too for ka_sangam). This spec alone does
--       not make ka_vighnakara 'proven'; the rebuild order does the rest.
--   (d) NULL signal_id. The reviewed-key NULL preflight raises, and in _run_data_writer
--       (asset_runner.py:1385-1425) that goes through mark_asset_error: the build ERRORS
--       rather than writing an 'unknown' receipt. The writer never emits NULL signal_id
--       (FK ON DELETE CASCADE since 403) but the column is nullable.
--   (e) Builder grants. No grant migration gives data_plane_builder SELECT on
--       kala_obstruction (646 grants nirmana_evidence_ingress_writer only). The digest
--       query reads it under the build role; ka_vighnakara already DELETEs/INSERTs there
--       so a grant likely exists live, but that is unverified here. Not in this PR.
--
-- Tests: platform/python-sidecar/tests/l3/test_i4_i5_output_digest_specs.py (static DDL/sha
-- checks always; real compute_output_digest on a disposable Postgres only when
-- I45_DIGEST_DSN is set: stable across identical rebuilds with
-- new ids / reversed order, moves on every hashed column, NULL-key negative).
--
-- Post-apply verification (CLAUDE.md N.4, never trust a silent no-op): expect 1 row
--   SELECT spec_sha256 FROM asset_output_digest_specs
--    WHERE asset_id = 'ka_vighnakara' AND retired_at IS NULL;  -- a731cb0c49546583b12dd24f1366389b99eb695aed4142f16560cea08b88f117

SET LOCAL lock_timeout = '5s';

INSERT INTO asset_output_digest_specs (asset_id, spec_sha256, spec)
VALUES (
  'ka_vighnakara',
  'a731cb0c49546583b12dd24f1366389b99eb695aed4142f16560cea08b88f117',
  '{"version":"nirmana-output-digest-spec-v1","components":[{"name":"kala_obstruction","relation":"kala_obstruction","key_columns":["signal_id","obstruction_type","severity_score","override_score","severity","obstruction_detail"],"where_equals":{"chart_id":"482012f1-710e-4a25-994a-93821f5871aa"},"value_columns":["chart_id","signal_id","obstruction_type","severity","severity_score","override_score","obstruction_detail"]}]}'::jsonb
)
ON CONFLICT (asset_id, spec_sha256) DO NOTHING;
