-- 979_nirmana_l2_bo_samskara_natural_key_partition.sql
--
-- NIRMANA v2.5 -- L2 (Bodha). Transaction ownership belongs to
-- platform/scripts/migrate.ts.
--
-- Sibling migration to 978 (bo_samskara output_digest_spec) -- see that
-- migration's header for the full verified account: sole-writer
-- co-writer investigation (the two operator CLI tools reuse the writer's
-- own helpers/INSERT verbatim, not distinct co-writers; the one genuine
-- other write site, brahmagyan/bodha/l2_embeddings.py, is dead,
-- unimported, scaffold-era dot-notation code targeting columns that do
-- not exist on the live schema), the signal_id-uniqueness check (live
-- UNIQUE constraint + FK to bodha_msr_signals's own PK), and the live
-- duplicate/NULL-key check (0 duplicate groups, 0 NULLs across 150,724
-- rows). Declared per the DEP-ASSERT precedent (880/908/909/910/927/930/
-- 939-940/941-942/943-944/946-947/948-949/950-951/952-953/954-955/
-- 956-957/958-959/960-961/962-963/964-965/968-969/970-971/972-973/
-- 974-975/976-977): natural_key_partition being NULL reads as
-- freshness_state='unknown' (reason 'partition_undeclared') regardless of
-- writer exclusivity or build success.

UPDATE asset_registry
   SET natural_key_partition = 'bodha_signal_embeddings (signal_id) -- BoSamskaraWriter is the confirmed sole live BUILD-TIME writer (grepped tree-wide for INSERT/DELETE/UPDATE INTO bodha_signal_embeddings: the writer''s own _INSERT is reused verbatim, same columns and same ON CONFLICT (signal_id) DO UPDATE clause, by two operator CLI tools -- run_bo_samskara_parallel.py and Conductor-ruled backfill_missing_signal_embeddings.py (#2434) -- neither introduces a distinct write path or column set. The one other file with a real INSERT, brahmagyan/bodha/l2_embeddings.py, is dead scaffold-era code (dot-notation asset id bodha.embeddings, retired per CLAUDE.md SS N.1), never imported by any reachable entrypoint, and its own INSERT column list (signal_id, embedding, model_name, embed_text) does not match the live schema at all -- would error on first execution if ever invoked). (signal_id) IS the table''s own live UNIQUE constraint (bodha_signal_embeddings_signal_id_key), reinforced by a FOREIGN KEY to bodha_msr_signals(signal_id) ON DELETE CASCADE (itself that table''s PRIMARY KEY) -- signal_id cannot duplicate across charts or ayanamshas by construction, so no chart_id/ayanamsha_id partition columns are needed. Live-verified 0 duplicate signal_id groups and 0 NULLs across all 150,724 live rows (50,678 canonical chart 482012f1 + 50,171 chart 1c826d5a + 49,875 chart cb73cd3d). Writer does a per-substep self-scoped delete-then-insert (CLAUDE.md SS N.3): each of the 5 ayanamsha SubSteps calls replace_prior_signal_embeddings(conn, chart_id, ayanamsha_id) (DELETE FROM bodha_signal_embeddings WHERE chart_id = %s AND ayanamsha_id = %s) immediately before its own INSERT batch, plus a perf-pre-D3 embedding-reuse optimization that reads prior rows BEFORE the delete to carry forward any embedding whose input text is byte-identical rather than re-calling Vertex AI. Surrogate/non-owned columns excluded from the digest value columns: embedding_id (surrogate PK, uuid4-generated by the writer) and build_id/computed_at (the standard build-run-identifier/wall-clock-write-time exclusion class used throughout this campaign, notwithstanding computed_at being a parameterized Python datetime.now() value here rather than a SQL NOW() literal).'
 WHERE asset_id = 'bo_samskara'
   AND natural_key_partition IS NULL;
