-- 983_nirmana_l2_bo_cgm_paths_natural_key_partition.sql
--
-- NIRMANA v2.5 -- L2 (Bodha). Transaction ownership belongs to
-- platform/scripts/migrate.ts.
--
-- Sibling migration to 982 (bo_cgm_paths output_digest_spec) -- see that
-- migration's header for the full verified account: sole-writer co-writer
-- investigation (bo_yantra_mechanism.py's reference is a prose comment
-- only, no read/write; bodha_writers/_idempotency.py's
-- replace_prior_cgm_paths() is defined but never imported/called anywhere
-- -- dead code), the max-pick-reduction non-determinism check (zero
-- multi-edge-per-from_node groups across all live dispositor-class edges
-- in bodha_cgm_edges, so the sort-and-pick-first pattern can never resolve
-- a tie), and the live duplicate/NULL-key check (0 duplicate groups, 0
-- NULLs across 135 rows). Declared per the DEP-ASSERT precedent
-- (880/908/909/910/927/930/939-940/941-942/943-944/946-947/948-949/
-- 950-951/952-953/954-955/956-957/958-959/960-961/962-963/964-965/
-- 968-969/970-971/972-973/974-975/978-979): natural_key_partition being
-- NULL reads as freshness_state='unknown' (reason 'partition_undeclared')
-- regardless of writer exclusivity or build success.

UPDATE asset_registry
   SET natural_key_partition = 'bodha_cgm_paths (chart_id, ayanamsha_id, snapshot_type, path_type, from_node_id, to_node_id) -- BoCgmPathsWriter (@register(''bo_cgm_paths'')) is the confirmed sole live BUILD-TIME writer (grepped tree-wide for INSERT/DELETE/UPDATE INTO bodha_cgm_paths across pipeline/orchestrator/writers/*.py, services/*.py, and bodha_writers/_idempotency.py: the writer''s own _PATH_INSERT is the sole live INSERT site; bo_yantra_mechanism.py''s reference is a prose comment only, no read or write of the table; bodha_writers/_idempotency.py defines a replace_prior_cgm_paths() DELETE-only helper that is never imported or called anywhere in the tree -- dead code, not a live co-writer). The key is the table''s own live UNIQUE constraint (chart_id, ayanamsha_id, build_id, snapshot_type, path_type, from_node_id, to_node_id) minus build_id (the writer''s own idempotent DELETE FROM bodha_cgm_paths WHERE chart_id = %s removes ALL prior build_ids for the chart before inserting, so at most one build_id''s data exists per chart at any time). The writer''s _build_dispositor_chains() reduces same-from_node_id dispositor-edge candidates via a sort-by-computed_strength-descending-then-pick-first pattern fed by a bodha_cgm_edges SELECT with no explicit ORDER BY -- live-verified via GROUP BY chart_id, ayanamsha_id, from_node_id HAVING COUNT(*) > 1 over all dispositor-class edges (all 3 charts, 40-45 edges each): ZERO groups, i.e. every graha node has exactly one dispositor edge (matches classical astrology -- a sign has exactly one ruling planet), so the max-pick sort is always over a single-element list and can never resolve a tie non-deterministically. Live-verified 0 duplicate-key groups and 0 NULLs across all 135 live rows (45 canonical chart 482012f1 + 45 chart 1c826d5a + 45 chart cb73cd3d). Surrogate/non-owned columns excluded from the digest value columns: path_id (surrogate PK, uuid4-generated by the writer) and build_id/computed_at (the standard build-run-identifier/wall-clock-write-time exclusion class used throughout this campaign, notwithstanding computed_at being a parameterized Python datetime.now(timezone.utc) value here rather than a SQL NOW() literal).'
 WHERE asset_id = 'bo_cgm_paths'
   AND natural_key_partition IS NULL;
