-- 985_nirmana_l2_bo_chart_gestalt_natural_key_partition.sql
--
-- NIRMANA v2.5 -- L2 (Bodha). Transaction ownership belongs to
-- platform/scripts/migrate.ts.
--
-- Sibling migration to 984 (bo_chart_gestalt output_digest_spec) -- see
-- that migration's header for the full verified account: sole-writer
-- co-writer investigation (the two test-file references import this
-- writer's own internal helpers verbatim, not distinct co-writers), the
-- two-defect-shape non-determinism check (every top-N/first-match SELECT
-- carries a deterministic tiebreak; the one ORDER-BY-less SELECT,
-- `final_disp_nodes`, is live-verified to return exactly one row per
-- chart x ayanamsha across ALL 3 charts and ALL 5 ayanamshas, so its
-- missing ORDER BY cannot produce an observable ordering difference), and
-- the live duplicate/NULL-key check (0 duplicate groups, 0 NULLs across
-- 15 rows). Declared per the DEP-ASSERT precedent
-- (880/908/909/910/927/930/939-940/941-942/943-944/946-947/948-949/
-- 950-951/952-953/954-955/956-957/958-959/960-961/962-963/964-965/
-- 968-969/970-971/972-973/974-975/978-979/982-983): natural_key_partition
-- being NULL reads as freshness_state='unknown' (reason
-- 'partition_undeclared') regardless of writer exclusivity or build
-- success.

UPDATE asset_registry
   SET natural_key_partition = 'bodha_chart_gestalt (chart_id, ayanamsha_id) -- BoChartGestaltWriter (@register(''bo_chart_gestalt'')) is the confirmed sole live BUILD-TIME writer (grepped tree-wide for INSERT/DELETE/UPDATE INTO bodha_chart_gestalt across pipeline/orchestrator/writers/*.py, services/*.py, and bodha_writers/_idempotency.py: the writer''s own run() is the sole live DELETE+INSERT site, and its own post-loop _patch_fragility() is the sole live UPDATE site, both on rows the same run just wrote; the only other tree references are two test files importing this writer''s own internal _write_aya helper verbatim, not distinct co-writers). The key is the table''s own live UNIQUE CONSTRAINT bodha_chart_gestalt_chart_id_ayanamsha_id_key (build_id is not part of this table''s unique key at all -- the writer''s own idempotent DELETE FROM bodha_chart_gestalt WHERE chart_id = %s removes ALL prior ayanamsha rows for the chart before inserting one row per ayanamsha, so exactly 5 rows exist per chart at any time). Non-determinism check covers BOTH defect shapes confirmed this campaign: every top-N/first-match SELECT in _write_aya (top_signals, strong_cells, top_nodes, malefic_signals, benefic_top, outlier_discoveries, contested, and the DISTINCT ON-based domain_signals) carries an explicit deterministic tiebreak in its ORDER BY; the one SELECT with no ORDER BY (final_disp_nodes, feeding the stored center_of_gravity_node_ids array and zoom_spine_jsonb.cgm_hub_node_ids -- the same byte-order-non-determinism shape flagged as a live defect in bo_yantra_mechanism this campaign) is live-verified via GROUP BY chart_id, ayanamsha_id HAVING count(DISTINCT to_node_id) > 1 over bodha_cgm_paths WHERE snapshot_type = ''static_natal'' AND is_final_dispositor = true across ALL 3 charts and ALL 5 ayanamshas: ZERO rows, i.e. every chart x ayanamsha combination has exactly one final-dispositor node, so a SELECT DISTINCT over a single-row result set is trivially order-invariant. _assess_fragility''s cross-ayanamsha comparison stores only sorted() domain lists and a boolean-derived fragility_class, order-independent by construction. Live-verified 0 duplicate-key groups and 0 NULLs across all 15 live rows (5 canonical chart 482012f1 + 5 chart 1c826d5a + 5 chart cb73cd3d). Surrogate/non-owned columns excluded from the digest value columns: gestalt_id (surrogate PK, uuid4-generated by the writer) and build_id/computed_at (the standard build-run-identifier/wall-clock-write-time exclusion class used throughout this campaign, notwithstanding computed_at being a parameterized Python datetime.now(timezone.utc) value here rather than a SQL NOW() literal).'
 WHERE asset_id = 'bo_chart_gestalt'
   AND natural_key_partition IS NULL;
