-- 987_nirmana_l2_bo_cdlm_summary_natural_key_partition.sql
--
-- NIRMANA v2.5 -- L2 (Bodha). Transaction ownership belongs to
-- platform/scripts/migrate.ts.
--
-- Sibling migration to 986 (bo_cdlm_summary output_digest_spec) -- see
-- that migration's header for the full verified account: sole-writer
-- co-writer investigation across all three tables this writer owns, the
-- deliberate SUBSET scope (only bodha_cdlm_chart_summary specced --
-- bodha_cdlm_domain_rollups and bodha_cdlm_pattern_clusters carry a real,
-- live-verified missing-tiebreak non-determinism defect, flagged on
-- #1770, not fixed here, per the #2502 subset-declaration ruling), the
-- live tie-check confirming bodha_cdlm_chart_summary's own dominant_3/
-- weakest_3 domain picks and strongest_pair max-pick have zero ties on
-- live data, and the live duplicate/NULL-key check (0 duplicate groups, 0
-- NULLs across 15 rows). Declared per the DEP-ASSERT precedent
-- (880/908/909/910/927/930/939-940/941-942/943-944/946-947/948-949/
-- 950-951/952-953/954-955/956-957/958-959/960-961/962-963/964-965/
-- 968-969/970-971/972-973/974-975/978-979/982-983/984-985):
-- natural_key_partition being NULL reads as freshness_state='unknown'
-- (reason 'partition_undeclared') regardless of writer exclusivity or
-- build success. This partition declaration covers the same single
-- component (bodha_cdlm_chart_summary) as migration 986's spec -- it does
-- NOT claim coverage of the two excluded sibling tables.

UPDATE asset_registry
   SET natural_key_partition = 'bodha_cdlm_chart_summary (chart_id, ayanamsha_id) -- BoCdlmSummaryWriter (@register(''bo_cdlm_summary'')) is the confirmed sole live BUILD-TIME writer of bodha_cdlm_chart_summary (grepped tree-wide for INSERT/UPDATE/DELETE INTO bodha_cdlm_chart_summary across pipeline/orchestrator/writers/*.py, services/*.py, and bodha_writers/_idempotency.py: the only hit outside this writer''s own file is the shared idempotency helper, not a distinct co-writer). The key is derived from the writer''s own idempotent DELETE FROM bodha_cdlm_chart_summary WHERE chart_id = %s (run before all three sibling tables'' insert loop) followed by exactly one INSERT per ayanamsha -- so exactly one row per (chart_id, ayanamsha_id) exists at any point in time, even though the table''s live UNIQUE CONSTRAINT also includes build_id and four always-NULL dynamic_*/tradition_view_id columns. Non-determinism check: sorted_domains (feeds dominant_3_domains_array/weakest_3_domains_array) sorts a per-domain SUM (order-independent regardless of unordered cell fetch) and a live tie-check across all 3 charts x 5 ayanamshas found zero duplicate total_strength values at any rank; strongest_pair (max-pick over computed_linkage_strength) live tie-check found zero ties across the same 15 rows -- the max is always unique. house_to_domain_strength_jsonb/karaka_to_domain_strength_jsonb are always the literal empty-object json.dumps({}); bridge_link_count/asymmetric_link_count are the same scalar COUNT; verification_pass_status/citation_ref/citation_human are fixed literals already asserted by migration 716''s integrity_check_sql. Live-verified 0 duplicate-key groups and 0 NULLs across all 15 live rows (5 canonical chart 482012f1 + 5 chart 1c826d5a + 5 chart cb73cd3d). Surrogate/non-owned columns excluded from the digest value columns: summary_id (surrogate PK, uuid4-generated by the writer) and build_id/computed_at (the standard build-run-identifier/wall-clock-write-time exclusion class used throughout this campaign). DELIBERATELY NOT COVERED by this partition declaration: bodha_cdlm_domain_rollups and bodha_cdlm_pattern_clusters, both sole-written by the same BoCdlmSummaryWriter but carrying a real, live-verified missing-tiebreak non-determinism defect (top_3_linked_domains_jsonb ties spanning the rank-3 cutoff on the canonical chart across all 5 ayanamshas for domains "residence" and "travel"; involved_cells_array fed by the same unordered SELECT, never sorted) -- flagged on #1770 for a future writer fix, not fabricated over here per SS N.8.'
 WHERE asset_id = 'bo_cdlm_summary'
   AND natural_key_partition IS NULL;
