-- Migration 430: bg_shashtiamsha_deities — canonical D60 (Shashtiamsha) reference table
-- (R6 1b-vargas, M-17)
--
-- Context: M-17 (MARSYS_DEFECT_GAP_REGISTER_v2_0.md) — ga_vargas_writer.py's D60 deity/quality
-- attribution was fabricated: D60_QUALITIES = ["Malefic","Neutral","Benefic"]*20 (a naive 3-cycle
-- repeating every 1.5 degrees within EACH sign, independent of amsa number or sign parity) and
-- D60_DEITIES ignored sign-parity entirely (_get_d60_deity only used degree-in-sign, never sign_idx,
-- despite classical Shashtiamsha requiring an odd/even-sign amsa-order reversal — see PyJHora's own
-- jhora.utils.get_amsa_ruler_from_planet_longitude, which reverses the 60-amsa index for even signs).
-- D60 carries the HIGHEST vimshopaka weight in serving (priors_config D60=0.95), so this fabricated
-- quality axis was the single highest-leverage falsification surface in the varga estate.
--
-- This migration replaces the fabricated per-degree cycling with the REAL classical kroora
-- (malefic)/soumya (benefic) Shashtiamsha split, cross-derived 1:1 from PyJHora's own reference
-- arrays (jhora.const.shashti_amsa_rulers_kroora / shashti_amsa_rulers_soumya, 0-based indices
-- converted to 1-based amsa_number here) — 23 kroora + 37 soumya = 60, verified disjoint and total.
-- This is real delegated classical data, not invented.
--
-- deity_name is intentionally NULL for all 60 rows: PyJHora ships only the kroora/soumya quality
-- split for Shashtiamsha (it does not materialize named deities either — evidently because named
-- attribution requires a primary BPHS Ch.7 verse-level citation this session could not verify against
-- a primary source). Per CLAUDE.md's canonical-or-floor rail ("canonical cited value OR floor NULL +
-- reason — NEVER a computable substitute"), a NULL + documented reason is correct here; a guessed
-- 60-name list (the prior D60_DEITIES array's failure mode) would be a B.10 fabrication regression,
-- not a fix. deity_name may be populated in a follow-up migration if/when a primary BPHS citation is
-- sourced — this table's shape already supports that (ADD is additive; no consumer depends on NULL).
--
-- ga_vargas_writer.py's D60 branch of _build_deity_rows now JOIN-reads this table by the correctly
-- sign-parity-reversed amsa_number (derived-by-JOIN at write time, never hand-copied — L1-authority
-- discipline, CLAUDE.md §N.5) instead of indexing the old fabricated Python lists.

BEGIN;

CREATE TABLE IF NOT EXISTS bg_shashtiamsha_deities (
    amsa_number         INTEGER     PRIMARY KEY
                        CHECK (amsa_number BETWEEN 1 AND 60),
    quality             TEXT        NOT NULL
                        CHECK (quality IN ('kroora', 'soumya')),
    deity_name          TEXT,
    classical_citation  TEXT        NOT NULL,
    rule_notes          TEXT
);

COMMENT ON TABLE bg_shashtiamsha_deities IS
  'M-17: canonical D60 (Shashtiamsha) amsa-quality reference — 60 amsas (0.5 deg each), '
  'kroora (malefic) / soumya (benefic) classification cross-derived from PyJHora '
  'jhora.const.shashti_amsa_rulers_kroora/soumya. deity_name floored NULL pending a primary '
  'BPHS Ch.7 verse-level citation (canonical-or-floor; never a guessed name). Consumed by '
  'ga_vargas_writer.py varga_deity_attribution rows for D60 via JOIN on the sign-parity-reversed '
  'amsa_number (PyJHora convention: amsa index reverses for even signs — see '
  'jhora.utils.get_amsa_ruler_from_planet_longitude).';

INSERT INTO bg_shashtiamsha_deities
    (amsa_number, quality, deity_name, classical_citation, rule_notes)
VALUES
(1, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 0); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(2, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 1); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(3, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 2); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(4, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 3); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(5, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 4); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(6, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 5); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(7, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 6); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(8, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 7); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(9, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 8); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(10, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 9); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(11, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 10); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(12, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 11); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(13, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 12); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(14, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 13); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(15, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 14); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(16, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 15); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(17, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 16); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(18, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 17); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(19, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 18); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(20, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 19); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(21, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 20); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(22, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 21); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(23, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 22); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(24, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 23); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(25, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 24); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(26, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 25); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(27, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 26); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(28, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 27); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(29, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 28); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(30, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 29); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(31, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 30); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(32, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 31); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(33, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 32); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(34, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 33); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(35, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 34); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(36, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 35); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(37, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 36); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(38, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 37); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(39, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 38); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(40, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 39); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(41, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 40); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(42, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 41); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(43, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 42); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(44, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 43); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(45, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 44); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(46, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 45); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(47, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 46); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(48, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 47); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(49, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 48); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(50, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 49); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(51, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 50); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(52, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 51); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(53, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 52); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(54, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 53); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(55, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 54); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(56, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 55); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(57, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 56); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(58, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 57); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(59, 'kroora', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_kroora (0-based idx 58); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.'),
(60, 'soumya', NULL, 'PyJHora jhora.const.shashti_amsa_rulers_soumya (0-based idx 59); BPHS Ch.7 Shashtiamsha kroora/soumya split', 'deity_name floored NULL: PyJHora ships only the kroora/soumya quality split for Shashtiamsha, not named deities; no primary BPHS Ch.7 verse-level deity-name source was available to verify a 60-name list -- canonical-or-floor requires NULL+reason over a guessed name.')
ON CONFLICT (amsa_number) DO UPDATE SET
    quality             = EXCLUDED.quality,
    deity_name          = EXCLUDED.deity_name,
    classical_citation  = EXCLUDED.classical_citation,
    rule_notes          = EXCLUDED.rule_notes;

-- Invariant check: exactly 23 kroora + 37 soumya = 60 rows (matches PyJHora's own arrays).
DO $$
DECLARE
    kroora_count INTEGER;
    soumya_count INTEGER;
    total_count INTEGER;
BEGIN
    SELECT count(*) INTO kroora_count FROM bg_shashtiamsha_deities WHERE quality = 'kroora';
    SELECT count(*) INTO soumya_count FROM bg_shashtiamsha_deities WHERE quality = 'soumya';
    SELECT count(*) INTO total_count FROM bg_shashtiamsha_deities;
    IF kroora_count != 23 OR soumya_count != 37 OR total_count != 60 THEN
        RAISE EXCEPTION 'bg_shashtiamsha_deities invariant violated: kroora=%, soumya=%, total=% (expected 23/37/60)',
            kroora_count, soumya_count, total_count;
    END IF;
END $$;

COMMIT;
