-- Migration 600: reviewed content-digest specifications for every L0 wave-0 writer.
-- 598 creates the append-only spec/receipt contract and seeds the first reviewed
-- specifications. 599 corrects the frozen L0 dependency graph. This migration
-- closes the remaining wave-0 digest gap before any production acceptance.
-- Transaction ownership belongs to platform/scripts/migrate.ts.

-- The component lists below were audited against each registered writer, its
-- seed implementation, the owning DDL, and the production relation metadata.
-- Co-writer tables are deliberately included. Execution-only surrogate IDs,
-- build IDs, and timestamps are deliberately excluded so identical semantic
-- output hashes identically across exact rebuilds.
INSERT INTO asset_output_digest_specs (asset_id, spec_sha256, spec)
VALUES
('bg_ephemeris','7b5c326b5acbdcb363b8adcb3c271f304f49d9e534a7aaf898f4e77aa00c2ff1','{"components":[{"key_columns":["date","body","ayanamsha_id"],"name":"ephemeris_daily","relation":"ephemeris_daily","value_columns":["date","body","ayanamsha_id","tropical_longitude","latitude","speed_dps","is_retrograde","sign_number","degree_in_sign","nakshatra_number","source_citation"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_reference','7f29bb1a2a6082096fd365bde66b817ca82c7cf2e56d40ee16e30ebdd4466fb3','{"components":[{"key_columns":["planet_id"],"name":"reference_planets","relation":"reference_planets","value_columns":["planet_id","canonical_name_en","canonical_name_sa","exaltation_sign","exaltation_degree","debilitation_sign","mooltrikona_sign","own_signs","natural_benefic","karak_domains","dasha_years","source_citation"]},{"key_columns":["nakshatra_id"],"name":"reference_nakshatras","relation":"reference_nakshatras","value_columns":["nakshatra_id","canonical_name_en","canonical_name_sa","lord","deity","nature","guna","start_degree","end_degree","pada_lords","body_part","source_citation"]},{"key_columns":["sign_id"],"name":"reference_signs","relation":"reference_signs","value_columns":["sign_id","canonical_name_en","canonical_name_sa","lord","element","modality","natural_house","is_odd","is_biped","significations","source_citation"]},{"key_columns":["planet_id","aspect_house"],"name":"reference_aspects","relation":"reference_aspects","value_columns":["planet_id","aspect_house","aspect_strength","strength_value","is_special","notes","source_citation"]},{"key_columns":["varga_id"],"name":"reference_vargas","relation":"reference_vargas","value_columns":["varga_id","varga_number","canonical_name_en","canonical_name_sa","division_count","primary_signification","secondary_signification","source_citation"]},{"key_columns":["house_num"],"name":"reference_houses","relation":"reference_houses","value_columns":["house_num","name_sa","name_en","category","natural_significations","karakas","classical_doctrine_jsonb","source_citation"]},{"key_columns":["strength_id"],"name":"reference_strength_systems","relation":"reference_strength_systems","value_columns":["strength_id","name_sa","name_en","category","formula_text","max_value","units","classical_interpretation","source_citation"]},{"key_columns":["karaka_id"],"name":"reference_karakas","relation":"reference_karakas","value_columns":["karaka_id","name_sa","name_en","karaka_type","applies_to","classical_significations","source_citation"]},{"key_columns":["upagraha_id"],"name":"reference_upagrahas","relation":"reference_upagrahas","value_columns":["upagraha_id","name_sa","name_en","parent_planet","computation_method","significations","source_citation"]},{"key_columns":["constant_id"],"name":"reference_constants","relation":"reference_constants","value_columns":["constant_id","name","value_numeric","value_text","unit","category","source_citation","classical_context"]},{"key_columns":["canonical_id"],"name":"reference_topic_tags","relation":"reference_topic_tags","value_columns":["canonical_id","name","category","description","example_chunks"]},{"key_columns":["term_id"],"name":"reference_glossary","relation":"reference_glossary","value_columns":["term_id","term_sa","term_en","definition","category","classical_citation","related_concepts"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_texts','c29c5ed004e16cf59f051882c805e458d0070619181829d4e989d6b213c80931','{"components":[{"key_columns":["text_id"],"name":"classical_texts","relation":"classical_texts","value_columns":["text_id","title_en","title_sa","author","school","tradition","tier","license","license_cleared","total_chapters","total_verses","source_edition"]},{"key_columns":["chunk_id"],"name":"classical_text_chunks","relation":"classical_text_chunks","value_columns":["text_id","chunk_id","verse_ref","chapter","verse_start","verse_end","content_sa","content_en","content_summary","topics","source_citation","translator","tradition_school","embedding","content_sha256","topic_tag","ocr_confidence_score","cleaned_translation_text","cleaned_devanagari_text","low_confidence_flag","ocr_review_note","ocr_cleanup_pass_version","translation_status","translation_provenance"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_ontology','f3243126c985a99bc1ec2100cb69be04184d357bbeeda9914818e2bd41ab3d0e','{"components":[{"key_columns":["entity_class","canonical_id"],"name":"brahma_ontology","relation":"brahma_ontology","value_columns":["entity_class","canonical_id","canonical_name_en","canonical_name_sa","synonyms","description","source_citation"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_remedies','4600275af578245d978777c9704adf67a6635ff76ff572c7c0dbbeacbf672f92','{"components":[{"key_columns":["remedy_id"],"name":"brahma_remedy_corpus","relation":"brahma_remedy_corpus","value_columns":["remedy_id","planet","domain","remedy_type","prescription_text","mantra_text","gemstone","charity_action","day_of_week","color_associated","confidence","source_canonical_id","source_citation","classical_ref","category","deity","mantra_sanskrit","mantra_transliteration","ingredients_jsonb","timing_rules_jsonb","cost_tier","contraindications","classical_attestation_text","scaffold_status"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_nakshatra','b9ebf94f5652dbb1ca00ea2c47927b698a13da2fa16723afa632c00b73f78dcb','{"components":[{"key_columns":["nakshatra_id"],"name":"reference_nakshatra","relation":"reference_nakshatra","value_columns":["nakshatra_id","name_sa_iast","name_sa_devanagari","name_en","alt_names","start_longitude","end_longitude","span_degrees","rashis_spanned","degree_in_rashi_ranges","vimshottari_lord","presiding_deity","secondary_deities","ruling_planet","gana","nadi","yoni_en","yoni_sa","yoni_sex","varna","tatva","guna","pakshi","nakshatra_gender","muhurta_type","disha","favorable_acts","prohibited_acts","symbol","shakti","basis_above","basis_below","net_result","motivation","body_part","paramayus","naisargika_maturity_age","deity_domain","is_gandanta","is_mula_sangya","is_panchaka","is_abhijit","tradition_scope","classical_source"]},{"key_columns":["nakshatra_id","pada_number"],"name":"reference_nakshatra_pada","relation":"reference_nakshatra_pada","value_columns":["pada_id","nakshatra_id","pada_number","absolute_pada","start_longitude","end_longitude","pada_navamsa_sign","pada_lord","pada_akshara","bija_sound","mantra_prefix","pada_deity_nuance","element_shading","dosha_shading","tradition_scope","classical_source"]},{"key_columns":["matrix_type","from_key","to_key"],"name":"reference_nakshatra_matrix","relation":"reference_nakshatra_matrix","value_columns":["matrix_type","from_key","to_key","relation_value","guna_points","max_points","notes","tradition_scope","classical_source"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_class_priors','ddab67f339af980fd4092270d6ed598189524d73b7d295a79e9f449fc64bd6c1','{"components":[{"key_columns":["prior_version","signal_type_class","fact_kind","source_subsystem","signal_tradition"],"name":"brahma_class_priors","relation":"brahma_class_priors","value_columns":["prior_version","signal_type_class","fact_kind","source_subsystem","signal_tradition","class_prior","varga_weights","contested","citation","ratified_by","prior_basis","source_ref"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_cohort','68e1528cb14abbabb36ebffbc3e0341cf814e7bfa9091698bcf6e0e4f277fd48','{"components":[{"key_columns":["synthetic_id"],"name":"bg_synthetic_cohort","relation":"bg_synthetic_cohort","value_columns":["synthetic_id","birth_datetime_utc","birth_lat","birth_lon","ayanamsha_key","positions","sampling_method","source_citation"]},{"key_columns":["synthetic_id","md_index"],"name":"bg_synthetic_cohort_md","relation":"bg_synthetic_cohort_md","value_columns":["synthetic_id","md_index","md_lord","start_age_years","end_age_years","md_full_years","is_partial","chain_version"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_class_lifetime_counts','ddab67f339af980fd4092270d6ed598189524d73b7d295a79e9f449fc64bd6c1','{"components":[{"key_columns":["prior_version","signal_type_class","fact_kind","source_subsystem","signal_tradition"],"name":"brahma_class_priors","relation":"brahma_class_priors","value_columns":["prior_version","signal_type_class","fact_kind","source_subsystem","signal_tradition","class_prior","varga_weights","contested","citation","ratified_by","prior_basis","source_ref"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_sky_calendar','d806c806b7d22231c1266ec8f0f11d84325daaeff03418d418dc460a4074c75c','{"components":[{"key_columns":["event_type","primary_body","secondary_body_key","event_jd"],"name":"bg_sky_calendar","relation":"bg_sky_calendar","value_columns":["event_type","primary_body","secondary_body","secondary_body_key","event_jd","event_datetime_utc","sign","nakshatra","longitude_deg","speed_dps","detail","ayanamsha_key","sampling_method","source_citation"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_prashna_rules','fbdb76f36bba1b45a527fcd807affe3e8d6837f11ed3ad586b5ebbc4001ffd4c','{"components":[{"key_columns":["method_id"],"name":"bg_prashna_lagna_methods","relation":"bg_prashna_lagna_methods","value_columns":["method_id","method_name","method_name_sa","derivation_rule","derivation_rule_jsonb","classical_citation","is_primary","tradition"]},{"key_columns":["yoga_id"],"name":"bg_prashna_tajik_yogas","relation":"bg_prashna_tajik_yogas","value_columns":["yoga_id","yoga_name","yoga_name_sa","judgment_meaning","formation_rule","formation_rule_jsonb","classical_citation","is_fructification_indicator"]},{"key_columns":["question_class"],"name":"bg_prashna_significators","relation":"bg_prashna_significators","value_columns":["question_class","querent_house","querent_planet","quesited_house","quesited_planet","significator_rule","classical_citation"]},{"key_columns":["rule_id"],"name":"bg_prashna_fructification_rules","relation":"bg_prashna_fructification_rules","value_columns":["rule_id","time_unit","degree_conversion_rule","applicable_when","classical_citation"]},{"key_columns":["technique_id"],"name":"bg_prashna_special_techniques","relation":"bg_prashna_special_techniques","value_columns":["technique_id","technique_name","technique_name_sa","application_rule","classical_citation"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_vastu_directions','567f0cf0ae5ce2061f5eb0a5d034733f7661f2a12101bf405b75f4b9a85bb881','{"components":[{"key_columns":["direction"],"name":"bg_vastu_directions","relation":"bg_vastu_directions","value_columns":["direction","direction_deg","ruling_graha","secondary_graha","favorable_color","element","classical_citation"]},{"key_columns":["direction","remedy_type"],"name":"bg_vastu_direction_remedials","relation":"bg_vastu_direction_remedials","value_columns":["direction","remedy_type","remedy_description","classical_citation"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_transit_rules','b704673aa5844f447190dfe9304de339930989a6197d1370f5ca88e997dd357c','{"components":[{"key_columns":["graha","rule_type","primary_house"],"name":"bg_transit_rules","relation":"bg_transit_rules","value_columns":["rule_type","graha","primary_house","vedha_house","phala","classical_citation","rule_notes"]},{"key_columns":["graha"],"name":"bg_transit_engine","relation":"bg_transit_engine","value_columns":["graha","avg_daily_motion_deg","zodiac_period_days","sign_residence_days","classical_citation"]},{"key_columns":["nakshatra_offset"],"name":"bg_transit_moorti","relation":"bg_transit_moorti","value_columns":["nakshatra_offset","moorti_name","quality_tier","phala_brief","classical_citation","rule_notes"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_medical_mappings','914a5a3a22053fdc15900cadd25242b777436ea8ef471006c376d8d5932c96da','{"components":[{"key_columns":["graha"],"name":"bg_medical_mappings","relation":"bg_medical_mappings","value_columns":["graha","dosha","dhatu","organ_systems","body_part","disease_tendency","classical_citation"]},{"key_columns":["nakshatra_name"],"name":"bg_nakshatra_medical","relation":"bg_nakshatra_medical","value_columns":["nakshatra_name","nakshatra_number","body_part","classical_citation","dosha"]},{"key_columns":["sign_number"],"name":"bg_sign_medical","relation":"bg_sign_medical","value_columns":["sign_number","sign_name","body_part","organ_systems","element","dosha","classical_citation"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_dignity_reference','59132811f3f4d26375541175b37e384137994f6be8f4c023ca49d2eade5af966','{"components":[{"key_columns":["graha"],"name":"bg_dignity_reference","relation":"bg_dignity_reference","value_columns":["graha","exaltation_sign","exaltation_degree","debilitation_sign","debilitation_degree","moolatrikona_sign","moolatrikona_from","moolatrikona_to","own_signs","classical_citation","notes","variant_traditions"]},{"key_columns":["scheme_name","state_name"],"name":"bg_avastha_schemes","relation":"bg_avastha_schemes","value_columns":["scheme_name","state_name","state_order","determination_rule","classical_citation","notes"]},{"key_columns":["graha"],"name":"bg_combustion_orbs","relation":"bg_combustion_orbs","value_columns":["graha","orb_degrees","deep_orb_degrees","retrograde_note","classical_citation"]},{"key_columns":["graha","other_graha"],"name":"bg_graha_naisargika_friendship","relation":"bg_graha_naisargika_friendship","value_columns":["graha","other_graha","relation","classical_citation"]},{"key_columns":["graha","motion_state"],"name":"bg_motion_state_thresholds","relation":"bg_motion_state_thresholds","value_columns":["graha","motion_state","speed_threshold_low","speed_threshold_high","threshold_type","typical_speed_dps","classical_citation","notes"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_vidhi_primitives','179ab2c22fad87f5f3c21475e3ddc5151eaf5fd88ea1c05cea0a6d73b845804f','{"components":[{"key_columns":["primitive_id"],"name":"vidhi_primitives","relation":"vidhi_primitives","value_columns":["primitive_id","version","definition","category","live_tool","tool_args","fallback_face","known_gap","mandatory_tags","cr27_prevents"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_muhurta_lattice','dd96913547048da000efbd94cfc106a9f90fe15b14b2def68aba9f45b4e4db98','{"components":[{"key_columns":["factor_family","factor_key","start_utc"],"name":"bg_muhurta_lattice","relation":"bg_muhurta_lattice","value_columns":["factor_family","factor_key","start_utc","end_utc","detail","reference_lat","reference_lon","reference_tz_offset_minutes","reference_location_key","ayanamsha_key","sampling_method","source_citation","corpus_status"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_kota_chakra_rings','d2f79f55eecc2ed93dd42690053bd1c3bd6c13dda635437a1f1d50b6b2f49dcf','{"components":[{"key_columns":["table_version","ring_position"],"name":"bg_kota_chakra_rings","relation":"bg_kota_chakra_rings","value_columns":["table_version","ring_position","ring_name","ring_index","dvara_assignment","citation","corpus_status","ratified_by"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_vedha_malefic_scale','16a4946da00360c29bd0e6f6b2dc4664c9a3510486d9ac25749c113288270163','{"components":[{"key_columns":["table_version","malefic_count"],"name":"bg_vedha_malefic_scale","relation":"bg_vedha_malefic_scale","value_columns":["table_version","malefic_count","effect_grade","effect_description","source_citation","verse_ref"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb),
('bg_phaladeepika_latta','327514850fdcf368051a1ed098ad07568da943955a886cc3205c166debcade16','{"components":[{"key_columns":["table_version","graha"],"name":"bg_phaladeepika_latta","relation":"bg_phaladeepika_latta","value_columns":["table_version","graha","count_from_graha","direction","effect_description","affliction_condition","source_citation","verse_ref"]}],"version":"nirmana-output-digest-spec-v1"}'::jsonb)
ON CONFLICT (asset_id, spec_sha256) DO NOTHING;

-- Forward reversal: retire these specifications only before any receipt refers
-- to them. Once referenced, preserve the append-only evidence chain.
