/** ELECT's web build cannot import the separately deployed MCP package.
 * Generate its data-only mirror from the canonical legacy vocabulary.
 * Run: npx tsx scripts/generate_muhurta_undertakings.ts [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { MUHURTA_UNDERTAKINGS } from '../../platform-mcp/src/lib/muhurta_undertakings'

const target = fileURLToPath(new URL('../src/lib/retrieval/registry/layers/L3_kala/muhurta_undertakings.generated.ts', import.meta.url))
const output = [
  '// Generated by platform/scripts/generate_muhurta_undertakings.ts; do not edit.',
  '// Source: platform-mcp/src/lib/muhurta_undertakings.ts (canonical legacy vocabulary).',
  `export const MUHURTA_UNDERTAKINGS = ${JSON.stringify(MUHURTA_UNDERTAKINGS, null, 2)} as const`,
  '',
].join('\n')

if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output) {
    throw new Error('Stale ELECT vocabulary mirror; run npx tsx scripts/generate_muhurta_undertakings.ts')
  }
} else {
  writeFileSync(target, output)
}
