/**
 * generate_vidhi_registry_mirror.ts — W2 R-1 item 5 codegen de-mirror (vidhi registry)
 * ========================================================================================
 * Design mandate: RETRIEVAL_3_0_FACETED_INSTRUMENTS_DESIGN_v1_0.md §19 ("SINGLE-SOURCE
 * CONTRACT GENERATION" — a contract is declared ONCE; every other process-boundary copy is
 * GENERATED, never hand-mirrored). Extends the proven `generate_envelope.ts` pattern
 * (`platform-mcp/scripts/generate_envelope.ts`) to the vidhi planning registry.
 *
 * PROBLEM THIS CLOSES (GT-56, W0 baseline probe): `platform/src/lib/vidhi/registry_data.ts`
 * (V-1's canonical source, D-2 Lane V-1) and `platform-mcp/src/resources/vidhi/registry_data.ts`
 * (D-2 Lane V-2's "vendored mirror", per that directory's own `index.ts` doc-comment — see
 * "the ONLY edit applied on copy is adding NodeNext-required `.js` import extensions") are two
 * HAND-SYNCED copies with NO codegen or parity gate enforcing the sync at the source-text
 * level. They had ALREADY DRIFTED by the time this lane opened: the type-import line read
 * `from './types'` on the canonical side and `from './types.js'` on the mirror side — the
 * exact drift the mirror's own doc-comment describes as its "ONLY edit", now caught actually
 * happening un-audited. (Content beyond that one line was still byte-identical at time of
 * writing — this generator exists so the NEXT drift, in either the import line or the data
 * itself, is caught mechanically instead of a second time by hand.)
 *
 * WHY THIS ISN'T generate_envelope.ts's ZERO-IMPORT CASE: `registry_data.ts` has exactly one
 * import — a TYPE-ONLY import of sibling types (`FloorItem`, `IntentFloor`, `VidhiPrimitive`
 * from `./types`). That's a real, load-bearing difference from `envelope.ts` (zero imports)
 * and from `generate_registry_shims.ts`'s case (platform-only runtime deps like
 * `@/lib/db/client` that platform-mcp cannot resolve at all). A same-directory *type-only*
 * sibling import is resolvable on BOTH sides of the process boundary — `platform-mcp/src/
 * resources/vidhi/types.ts` already exists as its own hand-mirror of `platform/src/lib/vidhi/
 * types.ts` (confirmed byte-identical at time of writing; NOT regenerated by this script —
 * out of this item's scope, see the "NOT COVERED" section below) — so instead of HALTING like
 * `generate_envelope.ts` does on any import, this generator REWRITES the one import it
 * recognizes (relative sibling import, type-only, no extension) to the NodeNext-required
 * `.js` extension platform-mcp's `moduleResolution: "NodeNext"` requires, and HALTS on
 * anything else (a non-relative import, a non-type-only import, more than the one expected
 * import) — the same "halt loudly rather than silently guess" discipline as its siblings.
 *
 * WHAT THIS SCRIPT ACTUALLY DOES (matches generate_envelope.ts's REAL implementation, not
 * just its docstring's printer-based framing — that script's own `generate()` does textual
 * transformation on the parsed-and-validated source, not a printer re-emit, and this one
 * follows that actual pattern for the same byte-determinism reason: a full AST printer
 * re-emit risks silently reformatting quote style / comment placement the mirror's own
 * committed history doesn't expect):
 *   1. Reads the canonical source file (platform/src/lib/vidhi/registry_data.ts).
 *   2. Parses it with the TypeScript compiler API (ts.createSourceFile) — validation only,
 *      never executed/imported.
 *   3. Walks the top-level ImportDeclarations. HALTS if there is not EXACTLY ONE, if it is
 *      not type-only, if its specifier is not a relative sibling path, or if it already
 *      carries a non-`.js`/`.json` extension this generator doesn't understand.
 *   4. Rewrites that one import's module-specifier text (`'./types'` → `'./types.js'`) via a
 *      direct string splice at the AST node's source position — the only substantive edit.
 *   5. Strips the canonical file's own leading `/** ... *\/` doc comment (which describes ITS
 *      identity as V-1's canonical source and the hand-sync this script replaces) and
 *      prepends a DO-NOT-HAND-EDIT banner + a content hash of the canonical source, so drift
 *      between the two files is mechanically detectable (see the parity test and `--check`).
 *
 * NOT COVERED (honest partial de-mirror — 2 of 3 known copies, not 3):
 *   - `platform-mcp/src/resources/vidhi/types.ts` — a THIRD hand-sync of the same shape
 *     (confirmed byte-identical to `platform/src/lib/vidhi/types.ts` right now, so not
 *     currently drifted, but nothing stops it drifting the same way registry_data.ts did).
 *     Left hand-maintained; a natural next-wave extension of this same script.
 *   - `platform/src/lib/vidhi/compiler.ts` mirrors the identical `'./types'` vs `'./types.js'`
 *     pattern against its own platform-mcp copy — found during this item's investigation,
 *     out of THIS item's scope (registry_data.ts only per the lane brief), flagged here so a
 *     future reader doesn't mistake the absence of a fix for an oversight.
 *   - **The DB-seed THIRD copy (migration 440, `platform/supabase/migrations/440_*.sql`,
 *     seeded by `bg_vidhi_primitives.py` / `bg_vidhi_floors.py` into `vidhi_primitives` /
 *     `vidhi_intent_floors` / `vidhi_floor_items`) is NOT regenerated or checked by this
 *     script.** Per `registry_data.ts`'s own "SOURCE-OF-TRUTH NOTE" header, the DB seed is
 *     meant to be content-identical to this TS registry but is populated by a separate Python
 *     writer path, not by this (or any) codegen step. Touching the migration itself is out of
 *     this item's scope (a live-data-affecting change, not a source-tree codegen concern; W2's
 *     `must_not_touch` also does not authorize modifying build/writer logic here). Keeping the
 *     DB seed in sync with this TS registry remains MANUAL until a future wave adds a real
 *     seed-regeneration step (e.g. a generator that reads this same canonical
 *     `registry_data.ts` and emits a `INSERT ... ON CONFLICT` seed migration, mirroring this
 *     script's AST-parse discipline). This is a genuine, flagged gap — this script closes 2 of
 *     the 3 known copies, not all 3.
 *
 * USAGE: npx tsx scripts/generate_vidhi_registry_mirror.ts [--check]   (run from platform/)
 *   (no flag)  regenerate platform-mcp/src/resources/vidhi/registry_data.ts from the
 *              canonical platform/src/lib/vidhi/registry_data.ts.
 *   --check    exit 1 if the committed generated file does not match what would be generated
 *              (CI drift gate — see the vidhi_codegen_parity.test.ts companion test).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import ts from 'typescript'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export const SOURCE_PATH = path.resolve(__dirname, '../src/lib/vidhi/registry_data.ts')
export const OUTPUT_PATH = path.resolve(__dirname, '../../platform-mcp/src/resources/vidhi/registry_data.ts')
const GENERATOR_REL_PATH = 'platform/scripts/generate_vidhi_registry_mirror.ts'
const SOURCE_REL_PATH = 'platform/src/lib/vidhi/registry_data.ts'
const OUTPUT_REL_PATH = 'platform-mcp/src/resources/vidhi/registry_data.ts'

function hashOf(text: string): string {
  return createHash('sha256').update(text).digest('hex').slice(0, 16)
}

/**
 * Validates the canonical source's import surface and returns the [start, end) text range
 * (relative to the FULL source string) of the single module-specifier string literal this
 * generator is authorized to rewrite. HALTS (throws) on anything it does not recognize —
 * mirrors generate_envelope.ts's assertNoImports discipline, widened to allow exactly the
 * one resolvable-on-both-sides shape (relative, type-only, sibling, no extension).
 */
function findRewritableTypeImportSpecifier(sourceFile: ts.SourceFile): { start: number; end: number; oldSpecifier: string } {
  const importDecls: ts.ImportDeclaration[] = []
  sourceFile.forEachChild(node => {
    if (ts.isImportDeclaration(node)) importDecls.push(node)
    if (ts.isImportEqualsDeclaration(node)) {
      throw new Error(
        `[generate_vidhi_registry_mirror] HALT: ${SOURCE_REL_PATH} contains an ` +
        `\`import = \` declaration this generator does not handle: ${node.getText(sourceFile)}`,
      )
    }
  })

  if (importDecls.length !== 1) {
    throw new Error(
      `[generate_vidhi_registry_mirror] HALT: expected exactly ONE import declaration in ` +
      `${SOURCE_REL_PATH}, found ${importDecls.length}. This generator only understands the ` +
      `single type-only sibling import documented in its header — raise with the native ` +
      `before hand-patching around a new import shape (a design-doc §19 judgment call).`,
    )
  }

  const decl = importDecls[0]!
  const isTypeOnly = decl.importClause?.isTypeOnly === true
  if (!isTypeOnly) {
    throw new Error(
      `[generate_vidhi_registry_mirror] HALT: ${SOURCE_REL_PATH}'s import is not \`import ` +
      `type { ... }\` (found: "${decl.getText(sourceFile)}"). This generator only rewrites ` +
      `TYPE-ONLY sibling imports — a runtime-value import would need a real cross-package ` +
      `resolution strategy (see generate_registry_shims.ts's docstring for that harder case), ` +
      `not a mechanical extension rewrite. Raise with the native.`,
    )
  }

  const specifierNode = decl.moduleSpecifier
  if (!ts.isStringLiteralLike(specifierNode)) {
    throw new Error(
      `[generate_vidhi_registry_mirror] HALT: non-literal module specifier in ` +
      `${SOURCE_REL_PATH}: ${decl.getText(sourceFile)}`,
    )
  }

  const specifierText = specifierNode.text // unquoted, e.g. './types'
  if (!specifierText.startsWith('./') && !specifierText.startsWith('../')) {
    throw new Error(
      `[generate_vidhi_registry_mirror] HALT: ${SOURCE_REL_PATH} imports a non-relative ` +
      `specifier ("${specifierText}") this generator cannot assume is resolvable inside ` +
      `platform-mcp's separate node_modules. Raise with the native before proceeding.`,
    )
  }
  if (specifierText.endsWith('.js') || specifierText.endsWith('.json')) {
    throw new Error(
      `[generate_vidhi_registry_mirror] HALT: ${SOURCE_REL_PATH}'s import specifier ` +
      `("${specifierText}") already carries an extension this generator expected to add — ` +
      `the canonical source's own convention may have changed; update this generator's ` +
      `assumption rather than silently double-appending ".js".`,
    )
  }

  return { start: specifierNode.getStart(sourceFile), end: specifierNode.getEnd(), oldSpecifier: specifierText }
}

function stripLeadingFileDocComment(sourceFile: ts.SourceFile, sourceText: string): string {
  // The canonical file's own leading /** ... */ doc-comment describes ITS identity as V-1's
  // canonical source (mentions the hand-sync this script replaces). The generated file gets
  // its own banner instead (below) — strip the source's leading block comment so the
  // generated output doesn't carry stale narrative about a hand-sync that is no longer how
  // this file is produced.
  const firstStatement = sourceFile.statements[0]
  if (!firstStatement) return sourceText
  const leadingRanges = ts.getLeadingCommentRanges(sourceText, firstStatement.getFullStart()) ?? []
  if (leadingRanges.length === 0) return sourceText
  const last = leadingRanges[leadingRanges.length - 1]!
  return sourceText.slice(last.end).replace(/^\s+/, '')
}

export function generate(): { generated: string; sourceHash: string } {
  const sourceText = readFileSync(SOURCE_PATH, 'utf8')
  const sourceFile = ts.createSourceFile(SOURCE_PATH, sourceText, ts.ScriptTarget.ES2022, true, ts.ScriptKind.TS)

  const { start, end, oldSpecifier } = findRewritableTypeImportSpecifier(sourceFile)
  const newSpecifier = `${oldSpecifier}.js`
  // Splice in the rewritten specifier, preserving the original quote character.
  const quoteChar = sourceText[start]
  const rewrittenSource = sourceText.slice(0, start) + `${quoteChar}${newSpecifier}${quoteChar}` + sourceText.slice(end)

  // Re-parse the rewritten text so stripLeadingFileDocComment walks correct positions.
  const rewrittenSourceFile = ts.createSourceFile(SOURCE_PATH, rewrittenSource, ts.ScriptTarget.ES2022, true, ts.ScriptKind.TS)
  const bodyOnly = stripLeadingFileDocComment(rewrittenSourceFile, rewrittenSource)
  const sourceHash = hashOf(sourceText)

  const banner = `/**
 * registry_data.ts — GENERATED, DO NOT HAND-EDIT.
 * ==================================================
 * Generated by \`${GENERATOR_REL_PATH}\` from \`${SOURCE_REL_PATH}\`
 * (source sha256:${sourceHash}). Run \`npm run codegen:vidhi\` in platform/ to regenerate
 * after any change to the canonical source; run \`npm run codegen:vidhi:check\` in CI to
 * detect drift.
 *
 * Design §19 (single-source contract generation): this file exists so the platform /
 * platform-mcp vidhi-registry process-boundary copy has exactly ONE authored copy (the
 * canonical file above) and this copy is mechanically derived. It previously stood as a
 * hand-synced "vendored mirror" (see this directory's index.ts doc-comment) — the two
 * copies had already drifted on this exact import line (GT-56, W0 baseline probe) with no
 * gate to catch it. This generated module, plus its companion parity test
 * (platform-mcp/src/__tests__/vidhi_codegen_parity.test.ts), closes that gap for
 * registry_data.ts specifically — see the generator's own header for the two OTHER known
 * hand-synced copies (types.ts here, compiler.ts, and the migration-440 DB seed) this pass
 * does NOT cover.
 *
 * The only substantive edit versus the canonical source is the NodeNext-required \`.js\`
 * extension on the sibling type-only import (platform-mcp's moduleResolution: "NodeNext"
 * requires it; platform's moduleResolution: "bundler" does not).
 */

`
  return { generated: banner + bodyOnly, sourceHash }
}

function main(): void {
  const checkMode = process.argv.includes('--check')
  const { generated } = generate()

  if (checkMode) {
    if (!existsSync(OUTPUT_PATH)) {
      console.error(`[generate_vidhi_registry_mirror --check] FAIL: ${OUTPUT_PATH} does not exist.`)
      process.exit(1)
    }
    const existing = readFileSync(OUTPUT_PATH, 'utf8')
    if (existing !== generated) {
      console.error(
        `[generate_vidhi_registry_mirror --check] FAIL: ${OUTPUT_REL_PATH} is STALE relative ` +
        `to ${SOURCE_REL_PATH}. Run \`npm run codegen:vidhi\` and commit the result.`,
      )
      process.exit(1)
    }
    console.log(`[generate_vidhi_registry_mirror --check] OK: ${OUTPUT_REL_PATH} is up to date.`)
    return
  }

  writeFileSync(OUTPUT_PATH, generated, 'utf8')
  console.log(`[generate_vidhi_registry_mirror] wrote ${OUTPUT_PATH}`)
}

// Only run main() when this module is the process entrypoint (`tsx
// scripts/generate_vidhi_registry_mirror.ts [--check]`) — NOT when imported by
// vidhi_codegen_parity.test.ts (platform-mcp), which imports `generate()` directly to assert
// byte-parity without triggering a file write or a check-mode `process.exit()` as a test
// side effect.
const isEntrypoint = (() => {
  try {
    return import.meta.url === `file://${process.argv[1]}` || import.meta.url === `file://${path.resolve(process.argv[1] ?? '')}`
  } catch {
    return false
  }
})()

if (isEntrypoint) {
  main()
}
