-- L0 reference table read by the ga_vargas writer (migration 430): 60 rows, quality as read live (suvarna_reader, 2026-10-02), deity_name
-- NULL on every row exactly as live (canonical-or-floor). Without it the writer's read fails INSIDE the build transaction and aborts it.
CREATE TABLE public.bg_shashtiamsha_deities (amsa_number integer PRIMARY KEY, quality text NOT NULL, deity_name text,
  classical_citation text NOT NULL, rule_notes text);
INSERT INTO public.bg_shashtiamsha_deities(amsa_number, quality, deity_name, classical_citation, rule_notes) VALUES
(1,'kroora',NULL,'fixture',''),
(2,'kroora',NULL,'fixture',''),
(3,'soumya',NULL,'fixture',''),
(4,'soumya',NULL,'fixture',''),
(5,'soumya',NULL,'fixture',''),
(6,'soumya',NULL,'fixture',''),
(7,'soumya',NULL,'fixture',''),
(8,'kroora',NULL,'fixture',''),
(9,'kroora',NULL,'fixture',''),
(10,'kroora',NULL,'fixture',''),
(11,'kroora',NULL,'fixture',''),
(12,'kroora',NULL,'fixture',''),
(13,'soumya',NULL,'fixture',''),
(14,'soumya',NULL,'fixture',''),
(15,'kroora',NULL,'fixture',''),
(16,'kroora',NULL,'fixture',''),
(17,'soumya',NULL,'fixture',''),
(18,'soumya',NULL,'fixture',''),
(19,'soumya',NULL,'fixture',''),
(20,'soumya',NULL,'fixture',''),
(21,'soumya',NULL,'fixture',''),
(22,'soumya',NULL,'fixture',''),
(23,'soumya',NULL,'fixture',''),
(24,'soumya',NULL,'fixture',''),
(25,'soumya',NULL,'fixture',''),
(26,'soumya',NULL,'fixture',''),
(27,'soumya',NULL,'fixture',''),
(28,'soumya',NULL,'fixture',''),
(29,'soumya',NULL,'fixture',''),
(30,'kroora',NULL,'fixture',''),
(31,'kroora',NULL,'fixture',''),
(32,'kroora',NULL,'fixture',''),
(33,'kroora',NULL,'fixture',''),
(34,'kroora',NULL,'fixture',''),
(35,'kroora',NULL,'fixture',''),
(36,'soumya',NULL,'fixture',''),
(37,'soumya',NULL,'fixture',''),
(38,'soumya',NULL,'fixture',''),
(39,'soumya',NULL,'fixture',''),
(40,'kroora',NULL,'fixture',''),
(41,'soumya',NULL,'fixture',''),
(42,'kroora',NULL,'fixture',''),
(43,'kroora',NULL,'fixture',''),
(44,'kroora',NULL,'fixture',''),
(45,'soumya',NULL,'fixture',''),
(46,'soumya',NULL,'fixture',''),
(47,'soumya',NULL,'fixture',''),
(48,'kroora',NULL,'fixture',''),
(49,'soumya',NULL,'fixture',''),
(50,'soumya',NULL,'fixture',''),
(51,'kroora',NULL,'fixture',''),
(52,'kroora',NULL,'fixture',''),
(53,'soumya',NULL,'fixture',''),
(54,'soumya',NULL,'fixture',''),
(55,'soumya',NULL,'fixture',''),
(56,'soumya',NULL,'fixture',''),
(57,'soumya',NULL,'fixture',''),
(58,'soumya',NULL,'fixture',''),
(59,'kroora',NULL,'fixture',''),
(60,'soumya',NULL,'fixture','');
ALTER TABLE public.bg_shashtiamsha_deities OWNER TO amjis_app;
-- ACL as read live (suvarna_reader, 2026-10-02): amjis_app owner plus role_* and suvarna_reader; NO grant to data_plane_builder
GRANT SELECT ON public.bg_shashtiamsha_deities TO role_web_serve, role_jobs, role_sidecar, rehearsal_reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bg_shashtiamsha_deities TO role_orchestrator;
